# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/max/Projects/Python/Workflow/0-MainUI/MainUI2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import UI_Icons

class Ui_MainUI(object):
    def setupUi(self, MainUI):
        
        MainUI.setObjectName("MainUI")
        MainUI.resize(1405, 823)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/image-sunset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainUI.setWindowIcon(icon)
        
        self.centralwidget = QtWidgets.QWidget(MainUI)
        self.centralwidget.setObjectName("centralwidget")
        
        self.ImageAreaTitlelabel = QtWidgets.QLabel(self.centralwidget)
        self.ImageAreaTitlelabel.setGeometry(QtCore.QRect(30, 0, 171, 20))
        self.ImageAreaTitlelabel.setObjectName("ImageAreaTitlelabel")
        
        self.OCRTextscrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.OCRTextscrollArea.setGeometry(QtCore.QRect(850, 20, 540, 700))
        self.OCRTextscrollArea.setAcceptDrops(False)
        self.OCRTextscrollArea.setWidgetResizable(True)
        self.OCRTextscrollArea.setObjectName("OCRTextscrollArea")
        self.OCRTextscrollAreaWidgetContents = QtWidgets.QWidget()
        self.OCRTextscrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 540, 1700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OCRTextscrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.OCRTextscrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.OCRTextscrollAreaWidgetContents.setMinimumSize(QtCore.QSize(540, 1700))
        self.OCRTextscrollAreaWidgetContents.setObjectName("OCRTextscrollAreaWidgetContents")
        self.OCRText = QtWidgets.QPlainTextEdit(self.OCRTextscrollAreaWidgetContents)
        self.OCRText.setGeometry(QtCore.QRect(0, 0, 540, 1702))
        self.OCRText.setMinimumSize(QtCore.QSize(540, 1702))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(20)
        self.OCRText.setFont(font)
        self.OCRText.setAutoFillBackground(False)
        self.OCRText.setObjectName("OCRText")
        self.OCRTextscrollArea.setWidget(self.OCRTextscrollAreaWidgetContents)
        self.OCRTextAreaTitlelabel = QtWidgets.QLabel(self.centralwidget)
        self.OCRTextAreaTitlelabel.setGeometry(QtCore.QRect(1050, 0, 141, 20))
        self.OCRTextAreaTitlelabel.setObjectName("OCRTextAreaTitlelabel")
        self.ImagescrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.ImagescrollArea.setGeometry(QtCore.QRect(20, 20, 520, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollArea.sizePolicy().hasHeightForWidth())
        self.ImagescrollArea.setSizePolicy(sizePolicy)
        self.ImagescrollArea.setMinimumSize(QtCore.QSize(501, 700))
        self.ImagescrollArea.setWidgetResizable(True)
        self.ImagescrollArea.setObjectName("ImagescrollArea")
        self.ImagescrollAreaWidgetContents = QtWidgets.QWidget()
        self.ImagescrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 501, 1800))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.ImagescrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.ImagescrollAreaWidgetContents.setMinimumSize(QtCore.QSize(501, 1800))
        self.ImagescrollAreaWidgetContents.setSizeIncrement(QtCore.QSize(0, 0))
        self.ImagescrollAreaWidgetContents.setBaseSize(QtCore.QSize(520, 700))
        self.ImagescrollAreaWidgetContents.setObjectName("ImagescrollAreaWidgetContents")
        self.Image = QtWidgets.QLabel(self.ImagescrollAreaWidgetContents)
        self.Image.setGeometry(QtCore.QRect(0, 0, 521, 1680))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Image.sizePolicy().hasHeightForWidth())
        self.Image.setSizePolicy(sizePolicy)
        self.Image.setMinimumSize(QtCore.QSize(500, 1680))
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("../../../../.designer/Images/Greek/jpg_desk_greek/greek_book_40_Matthew/greek1516_Page_012.jpg"))
        self.Image.setObjectName("Image")
        self.ImagescrollArea.setWidget(self.ImagescrollAreaWidgetContents)
        self.ChrRefTitlelabel = QtWidgets.QLabel(self.centralwidget)
        self.ChrRefTitlelabel.setGeometry(QtCore.QRect(580, 230, 141, 20))
        self.ChrRefTitlelabel.setObjectName("ChrRefTitlelabel")
        self.ChrRefscrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.ChrRefscrollArea.setGeometry(QtCore.QRect(550, 250, 291, 400))
        self.ChrRefscrollArea.setWidgetResizable(True)
        self.ChrRefscrollArea.setObjectName("ChrRefscrollArea")
        self.ChrRefcrollAreaWidgetContents = QtWidgets.QWidget()
        self.ChrRefcrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 200, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChrRefcrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.ChrRefcrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.ChrRefcrollAreaWidgetContents.setMinimumSize(QtCore.QSize(200, 500))
        self.ChrRefcrollAreaWidgetContents.setObjectName("ChrRefcrollAreaWidgetContents")
        self.ChrRefplainTextEdit = QtWidgets.QPlainTextEdit(self.ChrRefcrollAreaWidgetContents)
        self.ChrRefplainTextEdit.setGeometry(QtCore.QRect(0, 0, 275, 401))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(18)
        self.ChrRefplainTextEdit.setFont(font)
        self.ChrRefplainTextEdit.setObjectName("ChrRefplainTextEdit")
        self.ChrRefscrollArea.setWidget(self.ChrRefcrollAreaWidgetContents)
        MainUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1405, 22))
        self.menubar.setObjectName("menubar")
        self.menuPre_Process = QtWidgets.QMenu(self.menubar)
        self.menuPre_Process.setObjectName("menuPre_Process")
        self.menuExtract_pdf = QtWidgets.QMenu(self.menuPre_Process)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuExtract_pdf.setIcon(icon1)
        self.menuExtract_pdf.setObjectName("menuExtract_pdf")
        self.menuPrepare = QtWidgets.QMenu(self.menuPre_Process)
        self.menuPrepare.setObjectName("menuPrepare")
        self.menuGreekDR = QtWidgets.QMenu(self.menuPrepare)
        self.menuGreekDR.setObjectName("menuGreekDR")
        self.menuLatinDR = QtWidgets.QMenu(self.menuPrepare)
        self.menuLatinDR.setObjectName("menuLatinDR")
        self.menuTraining = QtWidgets.QMenu(self.menubar)
        self.menuTraining.setObjectName("menuTraining")
        self.menuGround_Truth = QtWidgets.QMenu(self.menuTraining)
        self.menuGround_Truth.setObjectName("menuGround_Truth")
        self.menuGreekGT = QtWidgets.QMenu(self.menuGround_Truth)
        self.menuGreekGT.setObjectName("menuGreekGT")
        self.menuGreek_Image_Lines = QtWidgets.QMenu(self.menuGreekGT)
        self.menuGreek_Image_Lines.setObjectName("menuGreek_Image_Lines")
        self.menuGreek_Text_Lines = QtWidgets.QMenu(self.menuGreekGT)
        self.menuGreek_Text_Lines.setObjectName("menuGreek_Text_Lines")
        self.menuLatinGT = QtWidgets.QMenu(self.menuGround_Truth)
        self.menuLatinGT.setObjectName("menuLatinGT")
        self.menuLatin_Image_Lines = QtWidgets.QMenu(self.menuLatinGT)
        self.menuLatin_Image_Lines.setObjectName("menuLatin_Image_Lines")
        self.menuLatin_Text_Lines = QtWidgets.QMenu(self.menuLatinGT)
        self.menuLatin_Text_Lines.setObjectName("menuLatin_Text_Lines")
        self.menuOCR = QtWidgets.QMenu(self.menubar)
        self.menuOCR.setObjectName("menuOCR")
        self.menuGreek_OCR = QtWidgets.QMenu(self.menuOCR)
        self.menuGreek_OCR.setObjectName("menuGreek_OCR")
        self.menuPost_Process = QtWidgets.QMenu(self.menubar)
        self.menuPost_Process.setObjectName("menuPost_Process")
        self.menuGreek_Post = QtWidgets.QMenu(self.menuPost_Process)
        self.menuGreek_Post.setObjectName("menuGreek_Post")
        MainUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainUI)
        self.statusbar.setObjectName("statusbar")
        MainUI.setStatusBar(self.statusbar)
        self.ToolBar = QtWidgets.QToolBar(MainUI)
        self.ToolBar.setObjectName("ToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.ToolBar)
        self.actionpdf_to_tiff = QtWidgets.QAction(MainUI)
        self.actionpdf_to_tiff.setObjectName("actionpdf_to_tiff")
        self.actionmove_pdf_for_tiff = QtWidgets.QAction(MainUI)
        self.actionmove_pdf_for_tiff.setObjectName("actionmove_pdf_for_tiff")
        self.actiontiff_to_mono = QtWidgets.QAction(MainUI)
        self.actiontiff_to_mono.setObjectName("actiontiff_to_mono")
        self.actionmono_to_png = QtWidgets.QAction(MainUI)
        self.actionmono_to_png.setObjectName("actionmono_to_png")
        self.actiontiff_to_png = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png.setObjectName("actiontiff_to_png")
        self.actionGreek = QtWidgets.QAction(MainUI)
        self.actionGreek.setObjectName("actionGreek")
        self.actiontiff_to_png_2 = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png_2.setObjectName("actiontiff_to_png_2")
        self.actionpdf_for_tiff = QtWidgets.QAction(MainUI)
        self.actionpdf_for_tiff.setObjectName("actionpdf_for_tiff")
        self.actionpdf_for_tiff_tb = QtWidgets.QAction(MainUI)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf4tiff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_for_tiff_tb.setIcon(icon2)
        self.actionpdf_for_tiff_tb.setObjectName("actionpdf_for_tiff_tb")
        self.actionpdf_to_tiff_tb = QtWidgets.QAction(MainUI)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf2tiff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_to_tiff_tb.setIcon(icon3)
        self.actionpdf_to_tiff_tb.setObjectName("actionpdf_to_tiff_tb")
        self.actiontiff_to_mono_tb = QtWidgets.QAction(MainUI)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiontiff_to_mono_tb.setIcon(icon4)
        self.actiontiff_to_mono_tb.setObjectName("actiontiff_to_mono_tb")
        self.actionmono_to_png_tb = QtWidgets.QAction(MainUI)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/png-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmono_to_png_tb.setIcon(icon5)
        self.actionmono_to_png_tb.setObjectName("actionmono_to_png_tb")
        self.actionLatin = QtWidgets.QAction(MainUI)
        self.actionLatin.setObjectName("actionLatin")
        self.actiontiff_to_png_3 = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png_3.setObjectName("actiontiff_to_png_3")
        self.actiontiff_to_png_4 = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png_4.setObjectName("actiontiff_to_png_4")
        self.actionDeskewGreek_tiff_tb = QtWidgets.QAction(MainUI)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeskewGreek_tiff_tb.setIcon(icon6)
        self.actionDeskewGreek_tiff_tb.setObjectName("actionDeskewGreek_tiff_tb")
        self.actiontiff_to_png_5 = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png_5.setObjectName("actiontiff_to_png_5")
        self.actionDeskewLatin_tiff_tb = QtWidgets.QAction(MainUI)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeskewLatin_tiff_tb.setIcon(icon7)
        self.actionDeskewLatin_tiff_tb.setObjectName("actionDeskewLatin_tiff_tb")
        self.actionResizeGreek_png_tb = QtWidgets.QAction(MainUI)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/resize-png-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResizeGreek_png_tb.setIcon(icon8)
        self.actionResizeGreek_png_tb.setObjectName("actionResizeGreek_png_tb")
        self.actionResizeLatin_png_tb = QtWidgets.QAction(MainUI)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Icons/resize-png-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResizeLatin_png_tb.setIcon(icon9)
        self.actionResizeLatin_png_tb.setObjectName("actionResizeLatin_png_tb")
        self.actionCrop_Languages_tb = QtWidgets.QAction(MainUI)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-langs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrop_Languages_tb.setIcon(icon10)
        self.actionCrop_Languages_tb.setObjectName("actionCrop_Languages_tb")
        self.actionextract_pdf_tb = QtWidgets.QAction(MainUI)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf-extract1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionextract_pdf_tb.setIcon(icon11)
        self.actionextract_pdf_tb.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionextract_pdf_tb.setObjectName("actionextract_pdf_tb")
        self.actiontiff_for_Ground_Truth = QtWidgets.QAction(MainUI)
        self.actiontiff_for_Ground_Truth.setObjectName("actiontiff_for_Ground_Truth")
        self.actionCrop = QtWidgets.QAction(MainUI)
        self.actionCrop.setObjectName("actionCrop")
        self.actiontiff_for_Ground_Truth_2 = QtWidgets.QAction(MainUI)
        self.actiontiff_for_Ground_Truth_2.setObjectName("actiontiff_for_Ground_Truth_2")
        self.actionSplit = QtWidgets.QAction(MainUI)
        self.actionSplit.setObjectName("actionSplit")
        self.actionRename_tiff_lines = QtWidgets.QAction(MainUI)
        self.actionRename_tiff_lines.setObjectName("actionRename_tiff_lines")
        self.actionRename_text_lines = QtWidgets.QAction(MainUI)
        self.actionRename_text_lines.setObjectName("actionRename_text_lines")
        self.actionReview_Ground_Truth = QtWidgets.QAction(MainUI)
        self.actionReview_Ground_Truth.setObjectName("actionReview_Ground_Truth")
        self.actionGreek_Wordlist_2 = QtWidgets.QAction(MainUI)
        self.actionGreek_Wordlist_2.setObjectName("actionGreek_Wordlist_2")
        self.actionLatin_Wordlist = QtWidgets.QAction(MainUI)
        self.actionLatin_Wordlist.setObjectName("actionLatin_Wordlist")
        self.actionImage_Lines = QtWidgets.QAction(MainUI)
        self.actionImage_Lines.setObjectName("actionImage_Lines")
        self.actionText_Lines = QtWidgets.QAction(MainUI)
        self.actionText_Lines.setObjectName("actionText_Lines")
        self.actionReview_Ground_Truth_2 = QtWidgets.QAction(MainUI)
        self.actionReview_Ground_Truth_2.setObjectName("actionReview_Ground_Truth_2")
        self.actionUpdate_Wordlist = QtWidgets.QAction(MainUI)
        self.actionUpdate_Wordlist.setObjectName("actionUpdate_Wordlist")
        self.actionUpdate_Wordlist_2 = QtWidgets.QAction(MainUI)
        self.actionUpdate_Wordlist_2.setObjectName("actionUpdate_Wordlist_2")
        self.actionCorrect_OCR_tb = QtWidgets.QAction(MainUI)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icons/Icons/ocr1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCorrect_OCR_tb.setIcon(icon12)
        self.actionCorrect_OCR_tb.setObjectName("actionCorrect_OCR_tb")
        self.actionVersify_Text = QtWidgets.QAction(MainUI)
        self.actionVersify_Text.setObjectName("actionVersify_Text")
        self.actionUpdate_Words = QtWidgets.QAction(MainUI)
        self.actionUpdate_Words.setObjectName("actionUpdate_Words")
        self.actionUpdate_Verses = QtWidgets.QAction(MainUI)
        self.actionUpdate_Verses.setObjectName("actionUpdate_Verses")
        self.actionUpdate_Words_Post = QtWidgets.QAction(MainUI)
        self.actionUpdate_Words_Post.setObjectName("actionUpdate_Words_Post")
        self.actionNormalize = QtWidgets.QAction(MainUI)
        self.actionNormalize.setObjectName("actionNormalize")
        self.actionLower_Case = QtWidgets.QAction(MainUI)
        self.actionLower_Case.setObjectName("actionLower_Case")
        self.actionRemove_Diacritics = QtWidgets.QAction(MainUI)
        self.actionRemove_Diacritics.setObjectName("actionRemove_Diacritics")
        self.actionAlign_Strongs = QtWidgets.QAction(MainUI)
        self.actionAlign_Strongs.setObjectName("actionAlign_Strongs")
        self.actionAlign_Lemmas = QtWidgets.QAction(MainUI)
        self.actionAlign_Lemmas.setObjectName("actionAlign_Lemmas")
        self.actionAlign_English = QtWidgets.QAction(MainUI)
        self.actionAlign_English.setObjectName("actionAlign_English")
        self.actionVariants = QtWidgets.QAction(MainUI)
        self.actionVariants.setObjectName("actionVariants")
        self.actionLatin_OCR = QtWidgets.QAction(MainUI)
        self.actionLatin_OCR.setObjectName("actionLatin_OCR")
        self.actionTrain_Tesseract_tb = QtWidgets.QAction(MainUI)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Icons/Icons/trainOCR1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTrain_Tesseract_tb.setIcon(icon13)
        self.actionTrain_Tesseract_tb.setObjectName("actionTrain_Tesseract_tb")
        self.actionReview_Ground_Truth_tb = QtWidgets.QAction(MainUI)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Icons/Icons/ground-truth1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReview_Ground_Truth_tb.setIcon(icon14)
        self.actionReview_Ground_Truth_tb.setObjectName("actionReview_Ground_Truth_tb")
        self.actionUpdate_Wordlist_tb = QtWidgets.QAction(MainUI)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Icons/Icons/update-greek-wordlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdate_Wordlist_tb.setIcon(icon15)
        self.actionUpdate_Wordlist_tb.setObjectName("actionUpdate_Wordlist_tb")
        self.actionCrop_Greek_to_tiff_Lines_tb = QtWidgets.QAction(MainUI)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrop_Greek_to_tiff_Lines_tb.setIcon(icon16)
        self.actionCrop_Greek_to_tiff_Lines_tb.setObjectName("actionCrop_Greek_to_tiff_Lines_tb")
        self.actionRename_Greek_tiff_Lines_tb = QtWidgets.QAction(MainUI)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Greek_tiff_Lines_tb.setIcon(icon17)
        self.actionRename_Greek_tiff_Lines_tb.setObjectName("actionRename_Greek_tiff_Lines_tb")
        self.actionMove_Greek_tiff_Lines_tb = QtWidgets.QAction(MainUI)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Icons/Icons/move-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_Greek_tiff_Lines_tb.setIcon(icon18)
        self.actionMove_Greek_tiff_Lines_tb.setObjectName("actionMove_Greek_tiff_Lines_tb")
        self.actionSplitGreek_text_lines_tb = QtWidgets.QAction(MainUI)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-textlines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSplitGreek_text_lines_tb.setIcon(icon19)
        self.actionSplitGreek_text_lines_tb.setObjectName("actionSplitGreek_text_lines_tb")
        self.actionRenameGreek_text_lines_tb = QtWidgets.QAction(MainUI)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename_textlines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRenameGreek_text_lines_tb.setIcon(icon20)
        self.actionRenameGreek_text_lines_tb.setObjectName("actionRenameGreek_text_lines_tb")
        self.actionImage_Lines_3 = QtWidgets.QAction(MainUI)
        self.actionImage_Lines_3.setObjectName("actionImage_Lines_3")
        self.actionReview_Ground_Truth_menu = QtWidgets.QAction(MainUI)
        self.actionReview_Ground_Truth_menu.setObjectName("actionReview_Ground_Truth_menu")
        self.actionUpdate_Wordlist_menu = QtWidgets.QAction(MainUI)
        self.actionUpdate_Wordlist_menu.setObjectName("actionUpdate_Wordlist_menu")
        self.actionCrop_Latin_To_tiff_Lines_tb = QtWidgets.QAction(MainUI)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrop_Latin_To_tiff_Lines_tb.setIcon(icon21)
        self.actionCrop_Latin_To_tiff_Lines_tb.setObjectName("actionCrop_Latin_To_tiff_Lines_tb")
        self.actionRename_Latin_tiff_Lines_tb = QtWidgets.QAction(MainUI)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Latin_tiff_Lines_tb.setIcon(icon22)
        self.actionRename_Latin_tiff_Lines_tb.setObjectName("actionRename_Latin_tiff_Lines_tb")
        self.actionMove_Latin_tiff_Lines_tb = QtWidgets.QAction(MainUI)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/Icons/Icons/move-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_Latin_tiff_Lines_tb.setIcon(icon23)
        self.actionMove_Latin_tiff_Lines_tb.setObjectName("actionMove_Latin_tiff_Lines_tb")
        self.actionSplit_Latin_Text_Lines_tb = QtWidgets.QAction(MainUI)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-textlines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSplit_Latin_Text_Lines_tb.setIcon(icon24)
        self.actionSplit_Latin_Text_Lines_tb.setObjectName("actionSplit_Latin_Text_Lines_tb")
        self.actionRename_Latin_Text_Lines_tb = QtWidgets.QAction(MainUI)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-textlines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Latin_Text_Lines_tb.setIcon(icon25)
        self.actionRename_Latin_Text_Lines_tb.setObjectName("actionRename_Latin_Text_Lines_tb")
        self.actiondeskew_mono = QtWidgets.QAction(MainUI)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-tiff-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondeskew_mono.setIcon(icon26)
        self.actiondeskew_mono.setObjectName("actiondeskew_mono")
        self.menuExtract_pdf.addAction(self.actionextract_pdf_tb)
        self.menuExtract_pdf.addSeparator()
        self.menuExtract_pdf.addAction(self.actionpdf_for_tiff_tb)
        self.menuExtract_pdf.addAction(self.actionpdf_to_tiff_tb)
        self.menuExtract_pdf.addAction(self.actiontiff_to_mono_tb)
        self.menuExtract_pdf.addAction(self.actiondeskew_mono)
        self.menuExtract_pdf.addAction(self.actionmono_to_png_tb)
        self.menuGreekDR.addAction(self.actionDeskewGreek_tiff_tb)
        self.menuGreekDR.addAction(self.actionResizeGreek_png_tb)
        self.menuLatinDR.addAction(self.actionDeskewLatin_tiff_tb)
        self.menuLatinDR.addAction(self.actionResizeLatin_png_tb)
        self.menuPrepare.addAction(self.menuGreekDR.menuAction())
        self.menuPrepare.addAction(self.menuLatinDR.menuAction())
        self.menuPre_Process.addSeparator()
        self.menuPre_Process.addAction(self.menuExtract_pdf.menuAction())
        self.menuPre_Process.addSeparator()
        self.menuPre_Process.addAction(self.actionCrop_Languages_tb)
        self.menuPre_Process.addSeparator()
        self.menuPre_Process.addAction(self.menuPrepare.menuAction())
        self.menuGreek_Image_Lines.addAction(self.actionCrop_Greek_to_tiff_Lines_tb)
        self.menuGreek_Image_Lines.addAction(self.actionRename_Greek_tiff_Lines_tb)
        self.menuGreek_Image_Lines.addAction(self.actionMove_Greek_tiff_Lines_tb)
        self.menuGreek_Text_Lines.addAction(self.actionSplitGreek_text_lines_tb)
        self.menuGreek_Text_Lines.addAction(self.actionRenameGreek_text_lines_tb)
        self.menuGreekGT.addAction(self.menuGreek_Image_Lines.menuAction())
        self.menuGreekGT.addAction(self.menuGreek_Text_Lines.menuAction())
        self.menuGreekGT.addAction(self.actionReview_Ground_Truth_tb)
        self.menuGreekGT.addAction(self.actionUpdate_Wordlist_tb)
        self.menuLatin_Image_Lines.addAction(self.actionCrop_Latin_To_tiff_Lines_tb)
        self.menuLatin_Image_Lines.addAction(self.actionRename_Latin_tiff_Lines_tb)
        self.menuLatin_Image_Lines.addAction(self.actionMove_Latin_tiff_Lines_tb)
        self.menuLatin_Text_Lines.addAction(self.actionSplit_Latin_Text_Lines_tb)
        self.menuLatin_Text_Lines.addAction(self.actionRename_Latin_Text_Lines_tb)
        self.menuLatinGT.addAction(self.menuLatin_Image_Lines.menuAction())
        self.menuLatinGT.addAction(self.menuLatin_Text_Lines.menuAction())
        self.menuLatinGT.addAction(self.actionReview_Ground_Truth_menu)
        self.menuLatinGT.addAction(self.actionUpdate_Wordlist_menu)
        self.menuGround_Truth.addAction(self.menuGreekGT.menuAction())
        self.menuGround_Truth.addAction(self.menuLatinGT.menuAction())
        self.menuTraining.addSeparator()
        self.menuTraining.addAction(self.menuGround_Truth.menuAction())
        self.menuTraining.addAction(self.actionTrain_Tesseract_tb)
        self.menuGreek_OCR.addAction(self.actionCorrect_OCR_tb)
        self.menuGreek_OCR.addAction(self.actionVersify_Text)
        self.menuOCR.addAction(self.menuGreek_OCR.menuAction())
        self.menuOCR.addAction(self.actionLatin_OCR)
        self.menuGreek_Post.addAction(self.actionUpdate_Verses)
        self.menuGreek_Post.addAction(self.actionUpdate_Words_Post)
        self.menuGreek_Post.addAction(self.actionNormalize)
        self.menuGreek_Post.addAction(self.actionLower_Case)
        self.menuGreek_Post.addAction(self.actionRemove_Diacritics)
        self.menuGreek_Post.addAction(self.actionAlign_Strongs)
        self.menuGreek_Post.addAction(self.actionAlign_Lemmas)
        self.menuGreek_Post.addAction(self.actionAlign_English)
        self.menuGreek_Post.addAction(self.actionVariants)
        self.menuPost_Process.addAction(self.menuGreek_Post.menuAction())
        self.menuPost_Process.addAction(self.actionUpdate_Words)
        self.menubar.addAction(self.menuPre_Process.menuAction())
        self.menubar.addAction(self.menuTraining.menuAction())
        self.menubar.addAction(self.menuOCR.menuAction())
        self.menubar.addAction(self.menuPost_Process.menuAction())
        self.ToolBar.addAction(self.actionextract_pdf_tb)
        self.ToolBar.addAction(self.actionpdf_for_tiff_tb)
        self.ToolBar.addAction(self.actionpdf_to_tiff_tb)
        self.ToolBar.addAction(self.actiontiff_to_mono_tb)
        self.ToolBar.addAction(self.actiondeskew_mono)
        self.ToolBar.addAction(self.actionmono_to_png_tb)
        self.ToolBar.addSeparator()
        self.ToolBar.addAction(self.actionCrop_Languages_tb)
        self.ToolBar.addAction(self.actionDeskewGreek_tiff_tb)
        self.ToolBar.addAction(self.actionResizeGreek_png_tb)
        self.ToolBar.addAction(self.actionDeskewLatin_tiff_tb)
        self.ToolBar.addAction(self.actionResizeLatin_png_tb)
        self.ToolBar.addSeparator()
        self.ToolBar.addAction(self.actionCrop_Greek_to_tiff_Lines_tb)
        self.ToolBar.addAction(self.actionRename_Greek_tiff_Lines_tb)
        self.ToolBar.addAction(self.actionMove_Greek_tiff_Lines_tb)
        self.ToolBar.addSeparator()
        self.ToolBar.addAction(self.actionCrop_Latin_To_tiff_Lines_tb)
        self.ToolBar.addAction(self.actionRename_Latin_tiff_Lines_tb)
        self.ToolBar.addAction(self.actionMove_Latin_tiff_Lines_tb)
        self.ToolBar.addSeparator()
        self.ToolBar.addAction(self.actionSplitGreek_text_lines_tb)
        self.ToolBar.addAction(self.actionRenameGreek_text_lines_tb)
        self.ToolBar.addSeparator()
        self.ToolBar.addAction(self.actionSplit_Latin_Text_Lines_tb)
        self.ToolBar.addAction(self.actionRename_Latin_Text_Lines_tb)
        self.ToolBar.addSeparator()
        self.ToolBar.addAction(self.actionReview_Ground_Truth_tb)
        self.ToolBar.addAction(self.actionUpdate_Wordlist_tb)
        self.ToolBar.addAction(self.actionTrain_Tesseract_tb)
        self.ToolBar.addAction(self.actionCorrect_OCR_tb)
        self.ToolBar.addSeparator()

        self.retranslateUi(MainUI)
        QtCore.QMetaObject.connectSlotsByName(MainUI)

    def retranslateUi(self, MainUI):
        _translate = QtCore.QCoreApplication.translate
        MainUI.setWindowTitle(_translate("MainUI", "Manuscript OCR"))
        self.ImageAreaTitlelabel.setText(_translate("MainUI", "Image to Recognize OCR"))
        self.OCRTextAreaTitlelabel.setText(_translate("MainUI", "OCR Text File to Edit"))
        self.ChrRefTitlelabel.setText(_translate("MainUI", "Character Reference"))
        self.menuPre_Process.setTitle(_translate("MainUI", "Pre-Process"))
        self.menuExtract_pdf.setTitle(_translate("MainUI", "Prepare Source"))
        self.menuPrepare.setTitle(_translate("MainUI", "Prepare Languages"))
        self.menuGreekDR.setTitle(_translate("MainUI", "Greek"))
        self.menuLatinDR.setTitle(_translate("MainUI", "Latin"))
        self.menuTraining.setTitle(_translate("MainUI", "Training"))
        self.menuGround_Truth.setTitle(_translate("MainUI", "Ground Truth"))
        self.menuGreekGT.setTitle(_translate("MainUI", "Greek"))
        self.menuGreek_Image_Lines.setTitle(_translate("MainUI", "Greek Image Lines"))
        self.menuGreek_Text_Lines.setTitle(_translate("MainUI", "Greek Text Lines"))
        self.menuLatinGT.setTitle(_translate("MainUI", "Latin"))
        self.menuLatin_Image_Lines.setTitle(_translate("MainUI", "Latin Image Lines"))
        self.menuLatin_Text_Lines.setTitle(_translate("MainUI", "Latin Text Lines"))
        self.menuOCR.setTitle(_translate("MainUI", "OCR"))
        self.menuGreek_OCR.setTitle(_translate("MainUI", "Greek"))
        self.menuPost_Process.setTitle(_translate("MainUI", "Post-Process"))
        self.menuGreek_Post.setTitle(_translate("MainUI", "Greek"))
        self.ToolBar.setWindowTitle(_translate("MainUI", "toolBar"))
        self.ToolBar.setToolTip(_translate("MainUI", "Extract pages from pdf source file"))
        self.ToolBar.setWhatsThis(_translate("MainUI", "pdf Page Extractor"))
        self.actionpdf_to_tiff.setText(_translate("MainUI", "pdf for tiff"))
        self.actionmove_pdf_for_tiff.setText(_translate("MainUI", "pdf to tiff"))
        self.actiontiff_to_mono.setText(_translate("MainUI", "tiff to mono"))
        self.actionmono_to_png.setText(_translate("MainUI", "mono to png"))
        self.actiontiff_to_png.setText(_translate("MainUI", "tiff to png"))
        self.actionGreek.setText(_translate("MainUI", "Greek"))
        self.actiontiff_to_png_2.setText(_translate("MainUI", "tiff to png"))
        self.actionpdf_for_tiff.setText(_translate("MainUI", "pdf for tiff"))
        self.actionpdf_for_tiff_tb.setText(_translate("MainUI", "pdf For tiff"))
        self.actionpdf_for_tiff_tb.setToolTip(_translate("MainUI", "Stage pdf pages FOR tiff conversion"))
        self.actionpdf_to_tiff_tb.setText(_translate("MainUI", "pdf To tiff"))
        self.actionpdf_to_tiff_tb.setToolTip(_translate("MainUI", "Convert pdf pages TO tiff files"))
        self.actiontiff_to_mono_tb.setText(_translate("MainUI", "tiff to mono"))
        self.actiontiff_to_mono_tb.setToolTip(_translate("MainUI", "Convert tiff files TO indexed monochrome"))
        self.actionmono_to_png_tb.setText(_translate("MainUI", "mono To png"))
        self.actionmono_to_png_tb.setToolTip(_translate("MainUI", "Convert deskewed monochrome tiff files TO png"))
        self.actionLatin.setText(_translate("MainUI", "Latin"))
        self.actiontiff_to_png_3.setText(_translate("MainUI", "tiff to png"))
        self.actiontiff_to_png_4.setText(_translate("MainUI", "tiff to png"))
        self.actionDeskewGreek_tiff_tb.setText(_translate("MainUI", "Deskew Greek tiff"))
        self.actiontiff_to_png_5.setText(_translate("MainUI", "tiff to png"))
        self.actionDeskewLatin_tiff_tb.setText(_translate("MainUI", "Deskew Latin tiff"))
        self.actionResizeGreek_png_tb.setText(_translate("MainUI", "Resize Greek png"))
        self.actionResizeLatin_png_tb.setText(_translate("MainUI", "Resize Latin png"))
        self.actionCrop_Languages_tb.setText(_translate("MainUI", "Crop Languages"))
        self.actionCrop_Languages_tb.setToolTip(_translate("MainUI", "Crop language sections into separate tiff files"))
        self.actionextract_pdf_tb.setText(_translate("MainUI", "Extract pdf"))
        self.actionextract_pdf_tb.setToolTip(_translate("MainUI", "Extract pages from pdf source document"))
        self.actiontiff_for_Ground_Truth.setText(_translate("MainUI", "tiff for Ground Truth"))
        self.actionCrop.setText(_translate("MainUI", "Crop to tiff lines"))
        self.actiontiff_for_Ground_Truth_2.setText(_translate("MainUI", "Move tiff lines"))
        self.actionSplit.setText(_translate("MainUI", "Split text lines"))
        self.actionRename_tiff_lines.setText(_translate("MainUI", "Rename tiff lines"))
        self.actionRename_text_lines.setText(_translate("MainUI", "Rename text lines"))
        self.actionReview_Ground_Truth.setText(_translate("MainUI", "Review Ground Truth"))
        self.actionGreek_Wordlist_2.setText(_translate("MainUI", "Greek Wordlist"))
        self.actionLatin_Wordlist.setText(_translate("MainUI", "Latin Wordlist"))
        self.actionImage_Lines.setText(_translate("MainUI", "Image Lines"))
        self.actionText_Lines.setText(_translate("MainUI", "Text Lines"))
        self.actionReview_Ground_Truth_2.setText(_translate("MainUI", "Review Ground Truth"))
        self.actionUpdate_Wordlist.setText(_translate("MainUI", "Update Wordlist"))
        self.actionUpdate_Wordlist_2.setText(_translate("MainUI", "Update Wordlist"))
        self.actionCorrect_OCR_tb.setText(_translate("MainUI", "Correct OCR"))
        self.actionVersify_Text.setText(_translate("MainUI", "Versify Text"))
        self.actionUpdate_Words.setText(_translate("MainUI", "Latin"))
        self.actionUpdate_Verses.setText(_translate("MainUI", "Update Verses"))
        self.actionUpdate_Words_Post.setText(_translate("MainUI", "Update Words"))
        self.actionNormalize.setText(_translate("MainUI", "Normalize"))
        self.actionLower_Case.setText(_translate("MainUI", "Lower Case"))
        self.actionRemove_Diacritics.setText(_translate("MainUI", "Remove Diacritics"))
        self.actionAlign_Strongs.setText(_translate("MainUI", "Align Strongs+RMAC"))
        self.actionAlign_Lemmas.setText(_translate("MainUI", "Align Lemmas"))
        self.actionAlign_English.setText(_translate("MainUI", "Align English"))
        self.actionVariants.setText(_translate("MainUI", "Variants"))
        self.actionLatin_OCR.setText(_translate("MainUI", "Latin"))
        self.actionTrain_Tesseract_tb.setText(_translate("MainUI", "Train Tesseract"))
        self.actionReview_Ground_Truth_tb.setText(_translate("MainUI", "Review Ground Truth"))
        self.actionUpdate_Wordlist_tb.setText(_translate("MainUI", "Update Greek Wordlist"))
        self.actionCrop_Greek_to_tiff_Lines_tb.setText(_translate("MainUI", "Crop Greek To tiff Lines"))
        self.actionRename_Greek_tiff_Lines_tb.setText(_translate("MainUI", "Rename Greek tiff Lines"))
        self.actionMove_Greek_tiff_Lines_tb.setText(_translate("MainUI", "Move Greek tiff Lines"))
        self.actionSplitGreek_text_lines_tb.setText(_translate("MainUI", "Split Greek Text Lines"))
        self.actionRenameGreek_text_lines_tb.setText(_translate("MainUI", "Rename Greek Text Lines"))
        self.actionImage_Lines_3.setText(_translate("MainUI", "Image Lines"))
        self.actionReview_Ground_Truth_menu.setText(_translate("MainUI", "Review Ground Truth"))
        self.actionUpdate_Wordlist_menu.setText(_translate("MainUI", "Update Wordlist"))
        self.actionCrop_Latin_To_tiff_Lines_tb.setText(_translate("MainUI", "Crop Latin To tiff Lines"))
        self.actionRename_Latin_tiff_Lines_tb.setText(_translate("MainUI", "Rename Latin tiff Lines"))
        self.actionMove_Latin_tiff_Lines_tb.setText(_translate("MainUI", "Move Greek tiff Lines"))
        self.actionSplit_Latin_Text_Lines_tb.setText(_translate("MainUI", "Split Latin Text Lines"))
        self.actionRename_Latin_Text_Lines_tb.setText(_translate("MainUI", "Rename Latin Text Lines"))
        self.actiondeskew_mono.setText(_translate("MainUI", "Deskew monochrome tiff files"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainUI = QtWidgets.QMainWindow()
    ui = Ui_MainUI()
    ui.setupUi(MainUI)
    MainUI.show()
    sys.exit(app.exec_())

