# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerUI/CropTif.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 801)
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/image-crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ImagescrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.ImagescrollArea.setGeometry(QtCore.QRect(0, 0, 550, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollArea.sizePolicy().hasHeightForWidth())
        self.ImagescrollArea.setSizePolicy(sizePolicy)
        self.ImagescrollArea.setMinimumSize(QtCore.QSize(500, 700))
        self.ImagescrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ImagescrollArea.setWidgetResizable(True)
        self.ImagescrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ImagescrollArea.setObjectName("ImagescrollArea")
        self.ImagescrollAreaWidgetContents = QtWidgets.QWidget()
        self.ImagescrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 550, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.ImagescrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.ImagescrollAreaWidgetContents.setMinimumSize(QtCore.QSize(550, 700))
        self.ImagescrollAreaWidgetContents.setSizeIncrement(QtCore.QSize(0, 0))
        self.ImagescrollAreaWidgetContents.setBaseSize(QtCore.QSize(960, 700))
        self.ImagescrollAreaWidgetContents.setObjectName("ImagescrollAreaWidgetContents")
        self.Image = QtWidgets.QLabel(self.ImagescrollAreaWidgetContents)
        self.Image.setGeometry(QtCore.QRect(0, 0, 550, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Image.sizePolicy().hasHeightForWidth())
        self.Image.setSizePolicy(sizePolicy)
        self.Image.setMinimumSize(QtCore.QSize(300, 700))
        self.Image.setBaseSize(QtCore.QSize(960, 700))
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../.designer/Images/Greek/jpg_desk_greek/greek_book_40_Matthew/greek1516_Page_012.jpg"))
        self.Image.setObjectName("Image")
        self.ImagescrollArea.setWidget(self.ImagescrollAreaWidgetContents)
        self.ImageLe = QtWidgets.QLineEdit(self.centralwidget)
        self.ImageLe.setGeometry(QtCore.QRect(30, 710, 481, 25))
        self.ImageLe.setObjectName("ImageLe")
        self.SaveCroppedImgbutton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveCroppedImgbutton.setGeometry(QtCore.QRect(420, 750, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveCroppedImgbutton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveCroppedImgbutton.setIcon(icon1)
        self.SaveCroppedImgbutton.setObjectName("SaveCroppedImgbutton")
        self.SaveCroppedImgAsbutton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveCroppedImgAsbutton.setGeometry(QtCore.QRect(310, 750, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveCroppedImgAsbutton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk-rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveCroppedImgAsbutton.setIcon(icon2)
        self.SaveCroppedImgAsbutton.setObjectName("SaveCroppedImgAsbutton")
        self.OpenImageFilebutton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenImageFilebutton.setGeometry(QtCore.QRect(30, 750, 91, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.OpenImageFilebutton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenImageFilebutton.setIcon(icon3)
        self.OpenImageFilebutton.setObjectName("OpenImageFilebutton")
        self.Cropbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Cropbutton.setGeometry(QtCore.QRect(140, 750, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.Cropbutton.setFont(font)
        self.Cropbutton.setIcon(icon)
        self.Cropbutton.setObjectName("Cropbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Crop Tif Image"))
        self.SaveCroppedImgbutton.setText(_translate("MainWindow", "Overwrite"))
        self.SaveCroppedImgAsbutton.setText(_translate("MainWindow", "Save As"))
        self.OpenImageFilebutton.setText(_translate("MainWindow", "Open Tif Image"))
        self.Cropbutton.setText(_translate("MainWindow", "Crop Selection"))

import UI_Icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

