services:
  - type: web
    name: biblion-website-static
    env: static
    rootDir: docs/website
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false