# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerUI/MyGrounderUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Grounder(object):
    def setupUi(self, Grounder):
        Grounder.setObjectName("Grounder")
        Grounder.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        Grounder.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionGrounder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Grounder.setWindowIcon(icon)
        Grounder.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        Grounder.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Grounder)
        self.centralwidget.setObjectName("centralwidget")
        self.ImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.ImageButton.setGeometry(QtCore.QRect(50, 10, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ImageButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ImageButton.setIcon(icon1)
        self.ImageButton.setObjectName("ImageButton")
        self.TextButton = QtWidgets.QPushButton(self.centralwidget)
        self.TextButton.setGeometry(QtCore.QRect(340, 10, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TextButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-document-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TextButton.setIcon(icon2)
        self.TextButton.setObjectName("TextButton")
        self.SaveImgButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveImgButton.setGeometry(QtCore.QRect(180, 10, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SaveImgButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk-rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveImgButton.setIcon(icon3)
        self.SaveImgButton.setObjectName("SaveImgButton")
        self.BothPrevButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothPrevButton.setGeometry(QtCore.QRect(530, 10, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BothPrevButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/ui-button-navigation-back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothPrevButton.setIcon(icon4)
        self.BothPrevButton.setObjectName("BothPrevButton")
        self.BothNextButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothNextButton.setGeometry(QtCore.QRect(660, 10, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BothNextButton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/ui-button-navigation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothNextButton.setIcon(icon5)
        self.BothNextButton.setObjectName("BothNextButton")
        self.Imagelabel = QtWidgets.QLabel(self.centralwidget)
        self.Imagelabel.setGeometry(QtCore.QRect(50, 80, 41, 17))
        self.Imagelabel.setObjectName("Imagelabel")
        self.ImageFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.ImageFileName.setGeometry(QtCore.QRect(100, 70, 471, 31))
        self.ImageFileName.setObjectName("ImageFileName")
        self.PrevImgButton = QtWidgets.QPushButton(self.centralwidget)
        self.PrevImgButton.setGeometry(QtCore.QRect(590, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PrevImgButton.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/back_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PrevImgButton.setIcon(icon6)
        self.PrevImgButton.setObjectName("PrevImgButton")
        self.NextImgButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextImgButton.setGeometry(QtCore.QRect(680, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.NextImgButton.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/forward_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextImgButton.setIcon(icon7)
        self.NextImgButton.setObjectName("NextImgButton")
        self.ImageView = QtWidgets.QLabel(self.centralwidget)
        self.ImageView.setGeometry(QtCore.QRect(50, 110, 701, 51))
        self.ImageView.setMinimumSize(QtCore.QSize(700, 50))
        self.ImageView.setText("")
        self.ImageView.setObjectName("ImageView")
        self.TextFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.TextFileName.setGeometry(QtCore.QRect(100, 180, 471, 31))
        self.TextFileName.setObjectName("TextFileName")
        self.Textlabel = QtWidgets.QLabel(self.centralwidget)
        self.Textlabel.setGeometry(QtCore.QRect(50, 190, 41, 17))
        self.Textlabel.setObjectName("Textlabel")
        self.NextTxtButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextTxtButton.setGeometry(QtCore.QRect(680, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.NextTxtButton.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/forward_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextTxtButton.setIcon(icon8)
        self.NextTxtButton.setObjectName("NextTxtButton")
        self.PrevTxtButton = QtWidgets.QPushButton(self.centralwidget)
        self.PrevTxtButton.setGeometry(QtCore.QRect(590, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PrevTxtButton.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Icons/back_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PrevTxtButton.setIcon(icon9)
        self.PrevTxtButton.setObjectName("PrevTxtButton")
        self.TextFileEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.TextFileEdit.setGeometry(QtCore.QRect(50, 220, 701, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.TextFileEdit.setFont(font)
        self.TextFileEdit.setObjectName("TextFileEdit")
        self.SaveAsButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveAsButton.setGeometry(QtCore.QRect(550, 280, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SaveAsButton.setFont(font)
        self.SaveAsButton.setIcon(icon3)
        self.SaveAsButton.setObjectName("SaveAsButton")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(660, 280, 89, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SaveButton.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveButton.setIcon(icon10)
        self.SaveButton.setObjectName("SaveButton")
        self.OCRButton = QtWidgets.QPushButton(self.centralwidget)
        self.OCRButton.setGeometry(QtCore.QRect(50, 290, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OCRButton.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/Icons/ocr3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OCRButton.setIcon(icon11)
        self.OCRButton.setObjectName("OCRButton")
        self.OCRTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.OCRTextEdit.setGeometry(QtCore.QRect(50, 320, 701, 51))
        self.OCRTextEdit.setObjectName("OCRTextEdit")
        self.ChrRefplainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ChrRefplainTextEdit.setGeometry(QtCore.QRect(50, 390, 700, 150))
        self.ChrRefplainTextEdit.setMinimumSize(QtCore.QSize(700, 150))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ChrRefplainTextEdit.setFont(font)
        self.ChrRefplainTextEdit.setObjectName("ChrRefplainTextEdit")
        Grounder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Grounder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        Grounder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Grounder)
        self.statusbar.setObjectName("statusbar")
        Grounder.setStatusBar(self.statusbar)

        self.retranslateUi(Grounder)
        QtCore.QMetaObject.connectSlotsByName(Grounder)

    def retranslateUi(self, Grounder):
        _translate = QtCore.QCoreApplication.translate
        Grounder.setWindowTitle(_translate("Grounder", "βϊϐλίον Grounder"))
        self.ImageButton.setText(_translate("Grounder", " Line Image"))
        self.TextButton.setText(_translate("Grounder", " Line Text"))
        self.SaveImgButton.setText(_translate("Grounder", "Save Image As"))
        self.BothPrevButton.setText(_translate("Grounder", " Both Prev"))
        self.BothNextButton.setText(_translate("Grounder", " Both Next"))
        self.Imagelabel.setText(_translate("Grounder", "Image:"))
        self.PrevImgButton.setText(_translate("Grounder", "  Prev"))
        self.NextImgButton.setText(_translate("Grounder", "  Next"))
        self.Textlabel.setText(_translate("Grounder", "Text:"))
        self.NextTxtButton.setText(_translate("Grounder", "  Next"))
        self.PrevTxtButton.setText(_translate("Grounder", "  Prev"))
        self.SaveAsButton.setText(_translate("Grounder", "Save Text As"))
        self.SaveButton.setText(_translate("Grounder", "Save Text"))
        self.OCRButton.setText(_translate("Grounder", "  OCR Line Image"))

import UI_Icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Grounder = QtWidgets.QMainWindow()
    ui = Ui_Grounder()
    ui.setupUi(Grounder)
    Grounder.show()
    sys.exit(app.exec_())

