# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerUI/MyResolverUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 881)
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionResolver.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PreservedCkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.PreservedCkBox.setGeometry(QtCore.QRect(170, 150, 111, 23))
        self.PreservedCkBox.setObjectName("PreservedCkBox")
        self.CorrectedCkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.CorrectedCkBox.setGeometry(QtCore.QRect(170, 180, 111, 23))
        self.CorrectedCkBox.setObjectName("CorrectedCkBox")
        self.FormLabel = QtWidgets.QLabel(self.centralwidget)
        self.FormLabel.setGeometry(QtCore.QRect(170, 130, 67, 17))
        self.FormLabel.setObjectName("FormLabel")
        self.TypeLabel = QtWidgets.QLabel(self.centralwidget)
        self.TypeLabel.setGeometry(QtCore.QRect(330, 130, 67, 17))
        self.TypeLabel.setObjectName("TypeLabel")
        self.ErrorCkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.ErrorCkBox.setGeometry(QtCore.QRect(330, 150, 92, 23))
        self.ErrorCkBox.setObjectName("ErrorCkBox")
        self.VarianceCkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.VarianceCkBox.setGeometry(QtCore.QRect(330, 180, 101, 23))
        self.VarianceCkBox.setObjectName("VarianceCkBox")
        self.ImpactLabel = QtWidgets.QLabel(self.centralwidget)
        self.ImpactLabel.setGeometry(QtCore.QRect(490, 130, 67, 17))
        self.ImpactLabel.setObjectName("ImpactLabel")
        self.ContextCkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.ContextCkBox.setGeometry(QtCore.QRect(490, 150, 92, 23))
        self.ContextCkBox.setObjectName("ContextCkBox")
        self.InflectionCkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.InflectionCkBox.setGeometry(QtCore.QRect(490, 180, 101, 23))
        self.InflectionCkBox.setObjectName("InflectionCkBox")
        self.ErrorCodeLabel = QtWidgets.QLabel(self.centralwidget)
        self.ErrorCodeLabel.setGeometry(QtCore.QRect(170, 240, 111, 17))
        self.ErrorCodeLabel.setObjectName("ErrorCodeLabel")
        self.ErrorCodeCombo = QtWidgets.QComboBox(self.centralwidget)
        self.ErrorCodeCombo.setGeometry(QtCore.QRect(170, 260, 111, 25))
        self.ErrorCodeCombo.setObjectName("ErrorCodeCombo")
        self.ErrorCodeCombo.addItem("")
        self.ErrorCodeCombo.addItem("")
        self.ErrorCodeCombo.addItem("")
        self.ErrorCodeCombo.addItem("")
        self.ErrorCodeCombo.addItem("")
        self.ErrorCodeCombo.addItem("")
        self.ErrorCodeCombo.addItem("")
        self.ErrorCodeCombo.addItem("")
        self.ErrorCodeCombo.addItem("")
        self.ErrorCodeCombo.addItem("")
        self.ErrorCodeCombo.addItem("")
        self.DescriptionTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.DescriptionTextEdit.setGeometry(QtCore.QRect(330, 260, 301, 81))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(12)
        self.DescriptionTextEdit.setFont(font)
        self.DescriptionTextEdit.setPlaceholderText("")
        self.DescriptionTextEdit.setObjectName("DescriptionTextEdit")
        self.StrongsLabel = QtWidgets.QLabel(self.centralwidget)
        self.StrongsLabel.setGeometry(QtCore.QRect(120, 370, 67, 17))
        self.StrongsLabel.setObjectName("StrongsLabel")
        self.LemmaLabel = QtWidgets.QLabel(self.centralwidget)
        self.LemmaLabel.setGeometry(QtCore.QRect(280, 370, 67, 17))
        self.LemmaLabel.setObjectName("LemmaLabel")
        self.RMACLabel = QtWidgets.QLabel(self.centralwidget)
        self.RMACLabel.setGeometry(QtCore.QRect(440, 370, 67, 17))
        self.RMACLabel.setObjectName("RMACLabel")
        self.VarianceCodeLabel = QtWidgets.QLabel(self.centralwidget)
        self.VarianceCodeLabel.setGeometry(QtCore.QRect(170, 300, 101, 17))
        self.VarianceCodeLabel.setObjectName("VarianceCodeLabel")
        self.DescriptionLabel = QtWidgets.QLabel(self.centralwidget)
        self.DescriptionLabel.setGeometry(QtCore.QRect(330, 240, 81, 17))
        self.DescriptionLabel.setObjectName("DescriptionLabel")
        self.VarianceCodeLE = QtWidgets.QLineEdit(self.centralwidget)
        self.VarianceCodeLE.setGeometry(QtCore.QRect(170, 320, 113, 25))
        self.VarianceCodeLE.setReadOnly(True)
        self.VarianceCodeLE.setObjectName("VarianceCodeLE")
        self.VarWordSelLabel = QtWidgets.QLabel(self.centralwidget)
        self.VarWordSelLabel.setGeometry(QtCore.QRect(540, 70, 181, 17))
        self.VarWordSelLabel.setObjectName("VarWordSelLabel")
        self.VarWordSelCombo = QtWidgets.QComboBox(self.centralwidget)
        self.VarWordSelCombo.setGeometry(QtCore.QRect(540, 90, 200, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(12)
        self.VarWordSelCombo.setFont(font)
        self.VarWordSelCombo.setEditable(True)
        self.VarWordSelCombo.setCurrentText("")
        self.VarWordSelCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.VarWordSelCombo.setModelColumn(0)
        self.VarWordSelCombo.setObjectName("VarWordSelCombo")
        self.StrongsLE = QtWidgets.QLineEdit(self.centralwidget)
        self.StrongsLE.setGeometry(QtCore.QRect(120, 390, 113, 25))
        self.StrongsLE.setText("")
        self.StrongsLE.setReadOnly(False)
        self.StrongsLE.setObjectName("StrongsLE")
        self.LemmaLE = QtWidgets.QLineEdit(self.centralwidget)
        self.LemmaLE.setGeometry(QtCore.QRect(280, 390, 113, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(12)
        self.LemmaLE.setFont(font)
        self.LemmaLE.setReadOnly(False)
        self.LemmaLE.setObjectName("LemmaLE")
        self.RMACLE = QtWidgets.QLineEdit(self.centralwidget)
        self.RMACLE.setGeometry(QtCore.QRect(440, 390, 113, 25))
        self.RMACLE.setReadOnly(False)
        self.RMACLE.setObjectName("RMACLE")
        self.WordLE = QtWidgets.QLineEdit(self.centralwidget)
        self.WordLE.setGeometry(QtCore.QRect(50, 90, 200, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(12)
        self.WordLE.setFont(font)
        self.WordLE.setReadOnly(False)
        self.WordLE.setObjectName("WordLE")
        self.NoDiaWordLE = QtWidgets.QLineEdit(self.centralwidget)
        self.NoDiaWordLE.setGeometry(QtCore.QRect(290, 90, 200, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(12)
        self.NoDiaWordLE.setFont(font)
        self.NoDiaWordLE.setReadOnly(True)
        self.NoDiaWordLE.setObjectName("NoDiaWordLE")
        self.WordLabel = QtWidgets.QLabel(self.centralwidget)
        self.WordLabel.setGeometry(QtCore.QRect(50, 70, 67, 17))
        self.WordLabel.setObjectName("WordLabel")
        self.NoDiaWordLabel = QtWidgets.QLabel(self.centralwidget)
        self.NoDiaWordLabel.setGeometry(QtCore.QRect(290, 70, 121, 17))
        self.NoDiaWordLabel.setObjectName("NoDiaWordLabel")
        self.UpdateButton = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateButton.setGeometry(QtCore.QRect(120, 450, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.UpdateButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/up_alt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UpdateButton.setIcon(icon1)
        self.UpdateButton.setObjectName("UpdateButton")
        self.UpdateBibleButton = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateBibleButton.setGeometry(QtCore.QRect(600, 450, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.UpdateBibleButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/drive-upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UpdateBibleButton.setIcon(icon2)
        self.UpdateBibleButton.setObjectName("UpdateBibleButton")
        self.BookLabel = QtWidgets.QLabel(self.centralwidget)
        self.BookLabel.setGeometry(QtCore.QRect(170, 10, 67, 17))
        self.BookLabel.setObjectName("BookLabel")
        self.ChapterLabel = QtWidgets.QLabel(self.centralwidget)
        self.ChapterLabel.setGeometry(QtCore.QRect(330, 10, 67, 17))
        self.ChapterLabel.setObjectName("ChapterLabel")
        self.VerseLable = QtWidgets.QLabel(self.centralwidget)
        self.VerseLable.setGeometry(QtCore.QRect(490, 10, 67, 17))
        self.VerseLable.setObjectName("VerseLable")
        self.BookLE = QtWidgets.QLineEdit(self.centralwidget)
        self.BookLE.setGeometry(QtCore.QRect(170, 30, 113, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(12)
        self.BookLE.setFont(font)
        self.BookLE.setReadOnly(True)
        self.BookLE.setObjectName("BookLE")
        self.ChapterLE = QtWidgets.QLineEdit(self.centralwidget)
        self.ChapterLE.setGeometry(QtCore.QRect(330, 30, 113, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(12)
        self.ChapterLE.setFont(font)
        self.ChapterLE.setReadOnly(True)
        self.ChapterLE.setObjectName("ChapterLE")
        self.VerseLE = QtWidgets.QLineEdit(self.centralwidget)
        self.VerseLE.setGeometry(QtCore.QRect(490, 30, 113, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(12)
        self.VerseLE.setFont(font)
        self.VerseLE.setReadOnly(True)
        self.VerseLE.setObjectName("VerseLE")
        self.PreviousButton = QtWidgets.QPushButton(self.centralwidget)
        self.PreviousButton.setGeometry(QtCore.QRect(50, 200, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.PreviousButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/back_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PreviousButton.setIcon(icon3)
        self.PreviousButton.setObjectName("PreviousButton")
        self.NextButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextButton.setGeometry(QtCore.QRect(650, 200, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.NextButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/forward_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextButton.setIcon(icon4)
        self.NextButton.setObjectName("NextButton")
        self.VarianceTable = QtWidgets.QTableWidget(self.centralwidget)
        self.VarianceTable.setGeometry(QtCore.QRect(50, 510, 701, 331))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(12)
        self.VarianceTable.setFont(font)
        self.VarianceTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.VarianceTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.VarianceTable.setObjectName("VarianceTable")
        self.VarianceTable.setColumnCount(22)
        self.VarianceTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.VarianceTable.setHorizontalHeaderItem(21, item)
        self.LineLE = QtWidgets.QLineEdit(self.centralwidget)
        self.LineLE.setGeometry(QtCore.QRect(50, 30, 71, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(12)
        self.LineLE.setFont(font)
        self.LineLE.setReadOnly(True)
        self.LineLE.setObjectName("LineLE")
        self.LineLabel = QtWidgets.QLabel(self.centralwidget)
        self.LineLabel.setGeometry(QtCore.QRect(50, 10, 67, 17))
        self.LineLabel.setObjectName("LineLabel")
        self.WordNumLE = QtWidgets.QLineEdit(self.centralwidget)
        self.WordNumLE.setGeometry(QtCore.QRect(650, 30, 91, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(12)
        self.WordNumLE.setFont(font)
        self.WordNumLE.setReadOnly(True)
        self.WordNumLE.setObjectName("WordNumLE")
        self.WordNumLabel = QtWidgets.QLabel(self.centralwidget)
        self.WordNumLabel.setGeometry(QtCore.QRect(650, 10, 71, 17))
        self.WordNumLabel.setObjectName("WordNumLabel")
        self.UpdateSimButton = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateSimButton.setGeometry(QtCore.QRect(280, 450, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.UpdateSimButton.setFont(font)
        self.UpdateSimButton.setIcon(icon1)
        self.UpdateSimButton.setObjectName("UpdateSimButton")
        self.ResolvedCkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.ResolvedCkBox.setGeometry(QtCore.QRect(600, 390, 92, 23))
        self.ResolvedCkBox.setObjectName("ResolvedCkBox")
        self.ResolveButton = QtWidgets.QPushButton(self.centralwidget)
        self.ResolveButton.setGeometry(QtCore.QRect(440, 450, 101, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.ResolveButton.setFont(font)
        self.ResolveButton.setIcon(icon2)
        self.ResolveButton.setObjectName("ResolveButton")
        self.allRadButton = QtWidgets.QRadioButton(self.centralwidget)
        self.allRadButton.setGeometry(QtCore.QRect(390, 490, 71, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allRadButton.sizePolicy().hasHeightForWidth())
        self.allRadButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.allRadButton.setFont(font)
        self.allRadButton.setChecked(True)
        self.allRadButton.setObjectName("allRadButton")
        self.presRadButton = QtWidgets.QRadioButton(self.centralwidget)
        self.presRadButton.setGeometry(QtCore.QRect(170, 490, 111, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.presRadButton.sizePolicy().hasHeightForWidth())
        self.presRadButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.presRadButton.setFont(font)
        self.presRadButton.setObjectName("presRadButton")
        self.unresRadButton = QtWidgets.QRadioButton(self.centralwidget)
        self.unresRadButton.setGeometry(QtCore.QRect(50, 490, 111, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unresRadButton.sizePolicy().hasHeightForWidth())
        self.unresRadButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.unresRadButton.setFont(font)
        self.unresRadButton.setChecked(False)
        self.unresRadButton.setObjectName("unresRadButton")
        self.corrRadButton = QtWidgets.QRadioButton(self.centralwidget)
        self.corrRadButton.setGeometry(QtCore.QRect(280, 490, 111, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.corrRadButton.sizePolicy().hasHeightForWidth())
        self.corrRadButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.corrRadButton.setFont(font)
        self.corrRadButton.setChecked(False)
        self.corrRadButton.setObjectName("corrRadButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "βϊϐλίον Resolver"))
        self.PreservedCkBox.setText(_translate("MainWindow", "Preserved(P)"))
        self.CorrectedCkBox.setText(_translate("MainWindow", "Corrected(C)"))
        self.FormLabel.setText(_translate("MainWindow", "Form"))
        self.TypeLabel.setText(_translate("MainWindow", "Type"))
        self.ErrorCkBox.setText(_translate("MainWindow", "Error(E)"))
        self.VarianceCkBox.setText(_translate("MainWindow", "Variance(V)"))
        self.ImpactLabel.setText(_translate("MainWindow", "Impact"))
        self.ContextCkBox.setText(_translate("MainWindow", "Context(C)"))
        self.InflectionCkBox.setText(_translate("MainWindow", "Inflection(I)"))
        self.ErrorCodeLabel.setText(_translate("MainWindow", "* Key Selection"))
        self.ErrorCodeCombo.setItemText(0, _translate("MainWindow", "None"))
        self.ErrorCodeCombo.setItemText(1, _translate("MainWindow", "Addition-A"))
        self.ErrorCodeCombo.setItemText(2, _translate("MainWindow", "Diacritic-D"))
        self.ErrorCodeCombo.setItemText(3, _translate("MainWindow", "RMAC-M"))
        self.ErrorCodeCombo.setItemText(4, _translate("MainWindow", "Omission-O"))
        self.ErrorCodeCombo.setItemText(5, _translate("MainWindow", "Punctuation-P"))
        self.ErrorCodeCombo.setItemText(6, _translate("MainWindow", "Strong\'s-S"))
        self.ErrorCodeCombo.setItemText(7, _translate("MainWindow", "Spelling-X"))
        self.ErrorCodeCombo.setItemText(8, _translate("MainWindow", "Spacing-Y"))
        self.ErrorCodeCombo.setItemText(9, _translate("MainWindow", "Printing-Z"))
        self.ErrorCodeCombo.setItemText(10, _translate("MainWindow", "Translation-T"))
        self.StrongsLabel.setText(_translate("MainWindow", "Strong\'s"))
        self.LemmaLabel.setText(_translate("MainWindow", "Lemma"))
        self.RMACLabel.setText(_translate("MainWindow", "RMAC"))
        self.VarianceCodeLabel.setText(_translate("MainWindow", "Variance Code"))
        self.DescriptionLabel.setText(_translate("MainWindow", "Description"))
        self.VarianceCodeLE.setPlaceholderText(_translate("MainWindow", "Variance Code"))
        self.VarWordSelLabel.setText(_translate("MainWindow", "* Variant  Word Selection"))
        self.StrongsLE.setPlaceholderText(_translate("MainWindow", "Strong\'s Ref"))
        self.LemmaLE.setPlaceholderText(_translate("MainWindow", "Lemma"))
        self.RMACLE.setPlaceholderText(_translate("MainWindow", "RMAC"))
        self.WordLE.setPlaceholderText(_translate("MainWindow", "Word"))
        self.NoDiaWordLE.setPlaceholderText(_translate("MainWindow", "Normalized Word"))
        self.WordLabel.setText(_translate("MainWindow", "Word"))
        self.NoDiaWordLabel.setText(_translate("MainWindow", "Normalized Word"))
        self.UpdateButton.setText(_translate("MainWindow", "Update Variant"))
        self.UpdateBibleButton.setText(_translate("MainWindow", "Update Bible"))
        self.BookLabel.setText(_translate("MainWindow", "Book"))
        self.ChapterLabel.setText(_translate("MainWindow", "Chapter"))
        self.VerseLable.setText(_translate("MainWindow", "Verse"))
        self.BookLE.setPlaceholderText(_translate("MainWindow", "Book"))
        self.ChapterLE.setPlaceholderText(_translate("MainWindow", "Chapter"))
        self.VerseLE.setPlaceholderText(_translate("MainWindow", "Verse"))
        self.PreviousButton.setText(_translate("MainWindow", "Previous"))
        self.NextButton.setText(_translate("MainWindow", "Next"))
        item = self.VarianceTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.VarianceTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Line"))
        item = self.VarianceTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Book"))
        item = self.VarianceTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Chapter"))
        item = self.VarianceTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Verse"))
        item = self.VarianceTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "WordNum"))
        item = self.VarianceTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Word"))
        item = self.VarianceTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "NoDiaWord"))
        item = self.VarianceTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "VarWord"))
        item = self.VarianceTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Strong"))
        item = self.VarianceTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "RMAC"))
        item = self.VarianceTable.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Lemma"))
        item = self.VarianceTable.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "ErrorCode"))
        item = self.VarianceTable.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "VarCode"))
        item = self.VarianceTable.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Description"))
        item = self.VarianceTable.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Preserved"))
        item = self.VarianceTable.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Corrected"))
        item = self.VarianceTable.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "Error"))
        item = self.VarianceTable.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "Variance"))
        item = self.VarianceTable.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "Context"))
        item = self.VarianceTable.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "Inflection"))
        item = self.VarianceTable.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "Resolved"))
        self.LineLE.setPlaceholderText(_translate("MainWindow", "Line Num"))
        self.LineLabel.setText(_translate("MainWindow", "Line"))
        self.WordNumLE.setPlaceholderText(_translate("MainWindow", "Word Num"))
        self.WordNumLabel.setText(_translate("MainWindow", "WordNum"))
        self.UpdateSimButton.setText(_translate("MainWindow", "Update Similar"))
        self.ResolvedCkBox.setText(_translate("MainWindow", "Resolved"))
        self.ResolveButton.setText(_translate("MainWindow", "Update Resolved"))
        self.allRadButton.setText(_translate("MainWindow", "Show All"))
        self.presRadButton.setText(_translate("MainWindow", "Show Preserved"))
        self.unresRadButton.setText(_translate("MainWindow", "Show Unresolved"))
        self.corrRadButton.setText(_translate("MainWindow", "Show Corrected"))

import UI_Icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

