# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerUI/MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainUI(object):
    def setupUi(self, MainUI):
        MainUI.setObjectName("MainUI")
        MainUI.setEnabled(True)
        MainUI.resize(1301, 958)
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainUI.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/bibocr3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainUI.setWindowIcon(icon)
        MainUI.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainUI)
        self.centralwidget.setObjectName("centralwidget")
        self.ImagescrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.ImagescrollArea.setGeometry(QtCore.QRect(10, 30, 551, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollArea.sizePolicy().hasHeightForWidth())
        self.ImagescrollArea.setSizePolicy(sizePolicy)
        self.ImagescrollArea.setMinimumSize(QtCore.QSize(501, 600))
        self.ImagescrollArea.setWidgetResizable(True)
        self.ImagescrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ImagescrollArea.setObjectName("ImagescrollArea")
        self.ImagescrollAreaWidgetContents = QtWidgets.QWidget()
        self.ImagescrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 540, 1740))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.ImagescrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.ImagescrollAreaWidgetContents.setMinimumSize(QtCore.QSize(540, 1740))
        self.ImagescrollAreaWidgetContents.setSizeIncrement(QtCore.QSize(0, 0))
        self.ImagescrollAreaWidgetContents.setBaseSize(QtCore.QSize(520, 700))
        self.ImagescrollAreaWidgetContents.setObjectName("ImagescrollAreaWidgetContents")
        self.Image = QtWidgets.QLabel(self.ImagescrollAreaWidgetContents)
        self.Image.setGeometry(QtCore.QRect(0, 0, 540, 1743))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Image.sizePolicy().hasHeightForWidth())
        self.Image.setSizePolicy(sizePolicy)
        self.Image.setMinimumSize(QtCore.QSize(540, 1740))
        self.Image.setBaseSize(QtCore.QSize(520, 700))
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../.designer/Images/Greek/jpg_desk_greek/greek_book_40_Matthew/greek1516_Page_012.jpg"))
        self.Image.setObjectName("Image")
        self.ImagescrollArea.setWidget(self.ImagescrollAreaWidgetContents)
        self.OpenImageFilebutton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenImageFilebutton.setGeometry(QtCore.QRect(10, 0, 71, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.OpenImageFilebutton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenImageFilebutton.setIcon(icon1)
        self.OpenImageFilebutton.setObjectName("OpenImageFilebutton")
        self.ImageLe = QtWidgets.QLineEdit(self.centralwidget)
        self.ImageLe.setGeometry(QtCore.QRect(320, 0, 241, 25))
        self.ImageLe.setObjectName("ImageLe")
        self.OCRbutton = QtWidgets.QPushButton(self.centralwidget)
        self.OCRbutton.setGeometry(QtCore.QRect(600, 0, 81, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.OCRbutton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/ocr3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OCRbutton.setIcon(icon2)
        self.OCRbutton.setObjectName("OCRbutton")
        self.LHDialogtbutton = QtWidgets.QPushButton(self.centralwidget)
        self.LHDialogtbutton.setEnabled(True)
        self.LHDialogtbutton.setGeometry(QtCore.QRect(600, 200, 31, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.LHDialogtbutton.setFont(font)
        self.LHDialogtbutton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-line-spacing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LHDialogtbutton.setIcon(icon3)
        self.LHDialogtbutton.setObjectName("LHDialogtbutton")
        self.TextLE = QtWidgets.QLineEdit(self.centralwidget)
        self.TextLE.setGeometry(QtCore.QRect(720, 0, 241, 25))
        self.TextLE.setObjectName("TextLE")
        self.EditCorrectedTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.EditCorrectedTextbutton.setGeometry(QtCore.QRect(970, 0, 71, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.EditCorrectedTextbutton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-document-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EditCorrectedTextbutton.setIcon(icon4)
        self.EditCorrectedTextbutton.setObjectName("EditCorrectedTextbutton")
        self.SaveAsOCRCorrTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveAsOCRCorrTextbutton.setGeometry(QtCore.QRect(1170, 0, 61, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveAsOCRCorrTextbutton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk-rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveAsOCRCorrTextbutton.setIcon(icon5)
        self.SaveAsOCRCorrTextbutton.setObjectName("SaveAsOCRCorrTextbutton")
        self.SaveOCRCorrTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveOCRCorrTextbutton.setGeometry(QtCore.QRect(1250, 0, 41, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveOCRCorrTextbutton.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveOCRCorrTextbutton.setIcon(icon6)
        self.SaveOCRCorrTextbutton.setObjectName("SaveOCRCorrTextbutton")
        self.OCRText = QtWidgets.QTextEdit(self.centralwidget)
        self.OCRText.setGeometry(QtCore.QRect(720, 30, 570, 601))
        self.OCRText.setMinimumSize(QtCore.QSize(540, 600))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OCRText.setFont(font)
        self.OCRText.setObjectName("OCRText")
        self.LHlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.LHlineEdit.setGeometry(QtCore.QRect(630, 200, 51, 25))
        self.LHlineEdit.setMaxLength(32767)
        self.LHlineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.LHlineEdit.setClearButtonEnabled(False)
        self.LHlineEdit.setObjectName("LHlineEdit")
        self.LHslider = QtWidgets.QSlider(self.centralwidget)
        self.LHslider.setEnabled(False)
        self.LHslider.setGeometry(QtCore.QRect(630, 230, 16, 160))
        self.LHslider.setMinimum(100)
        self.LHslider.setMaximum(200)
        self.LHslider.setSingleStep(2)
        self.LHslider.setPageStep(10)
        self.LHslider.setProperty("value", 144)
        self.LHslider.setSliderPosition(144)
        self.LHslider.setOrientation(QtCore.Qt.Vertical)
        self.LHslider.setInvertedAppearance(True)
        self.LHslider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.LHslider.setObjectName("LHslider")
        self.LHlabel = QtWidgets.QLabel(self.centralwidget)
        self.LHlabel.setGeometry(QtCore.QRect(610, 180, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LHlabel.setFont(font)
        self.LHlabel.setObjectName("LHlabel")
        self.Cropbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Cropbutton.setGeometry(QtCore.QRect(230, 0, 41, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Cropbutton.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/image-crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cropbutton.setIcon(icon7)
        self.Cropbutton.setObjectName("Cropbutton")
        self.Zoombutton = QtWidgets.QPushButton(self.centralwidget)
        self.Zoombutton.setGeometry(QtCore.QRect(100, 0, 41, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Zoombutton.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Magnifying Glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Zoombutton.setIcon(icon8)
        self.Zoombutton.setObjectName("Zoombutton")
        self.ZoomComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ZoomComboBox.setGeometry(QtCore.QRect(140, 0, 71, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZoomComboBox.sizePolicy().hasHeightForWidth())
        self.ZoomComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ZoomComboBox.setFont(font)
        self.ZoomComboBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ZoomComboBox.setEditable(True)
        self.ZoomComboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.ZoomComboBox.setObjectName("ZoomComboBox")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.fontComboBox = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox.setGeometry(QtCore.QRect(570, 100, 141, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fontComboBox.setFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.fontSizeBox = QtWidgets.QSpinBox(self.centralwidget)
        self.fontSizeBox.setGeometry(QtCore.QRect(617, 150, 51, 26))
        self.fontSizeBox.setAlignment(QtCore.Qt.AlignCenter)
        self.fontSizeBox.setMinimum(6)
        self.fontSizeBox.setMaximum(30)
        self.fontSizeBox.setProperty("value", 20)
        self.fontSizeBox.setObjectName("fontSizeBox")
        self.fontSizelabel = QtWidgets.QLabel(self.centralwidget)
        self.fontSizelabel.setGeometry(QtCore.QRect(620, 130, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fontSizelabel.setFont(font)
        self.fontSizelabel.setObjectName("fontSizelabel")
        self.langComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.langComboBox.setGeometry(QtCore.QRect(570, 50, 141, 25))
        self.langComboBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.langComboBox.setEditable(False)
        self.langComboBox.setObjectName("langComboBox")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langComboBox.addItem("")
        self.langlabel = QtWidgets.QLabel(self.centralwidget)
        self.langlabel.setGeometry(QtCore.QRect(600, 30, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.langlabel.setFont(font)
        self.langlabel.setObjectName("langlabel")
        self.fontlabel = QtWidgets.QLabel(self.centralwidget)
        self.fontlabel.setGeometry(QtCore.QRect(630, 80, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fontlabel.setFont(font)
        self.fontlabel.setObjectName("fontlabel")
        self.Writerbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Writerbutton.setGeometry(QtCore.QRect(1070, 0, 21, 25))
        self.Writerbutton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Icons/libreoffice-writer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Writerbutton.setIcon(icon9)
        self.Writerbutton.setObjectName("Writerbutton")
        self.Calcbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Calcbutton.setGeometry(QtCore.QRect(1120, 0, 21, 25))
        self.Calcbutton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/Icons/libreoffice-calc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Calcbutton.setIcon(icon10)
        self.Calcbutton.setObjectName("Calcbutton")
        self.Gimpbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Gimpbutton.setGeometry(QtCore.QRect(290, 0, 21, 25))
        self.Gimpbutton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/Icons/gimp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Gimpbutton.setIcon(icon11)
        self.Gimpbutton.setObjectName("Gimpbutton")
        self.reloadTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.reloadTextbutton.setGeometry(QtCore.QRect(700, 0, 21, 25))
        self.reloadTextbutton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icons/reload_page.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadTextbutton.setIcon(icon12)
        self.reloadTextbutton.setObjectName("reloadTextbutton")
        self.reloadImagebutton = QtWidgets.QPushButton(self.centralwidget)
        self.reloadImagebutton.setGeometry(QtCore.QRect(560, 0, 21, 25))
        self.reloadImagebutton.setText("")
        self.reloadImagebutton.setIcon(icon12)
        self.reloadImagebutton.setObjectName("reloadImagebutton")
        MainUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1301, 20))
        self.menubar.setObjectName("menubar")
        self.menuPre_Process = QtWidgets.QMenu(self.menubar)
        self.menuPre_Process.setObjectName("menuPre_Process")
        self.menuExtract_pdf = QtWidgets.QMenu(self.menuPre_Process)
        self.menuExtract_pdf.setIcon(icon1)
        self.menuExtract_pdf.setObjectName("menuExtract_pdf")
        self.menuPrepare = QtWidgets.QMenu(self.menuPre_Process)
        self.menuPrepare.setObjectName("menuPrepare")
        self.menuGreekDR = QtWidgets.QMenu(self.menuPrepare)
        self.menuGreekDR.setObjectName("menuGreekDR")
        self.menuLatinDR = QtWidgets.QMenu(self.menuPrepare)
        self.menuLatinDR.setObjectName("menuLatinDR")
        self.menuTraining = QtWidgets.QMenu(self.menubar)
        self.menuTraining.setObjectName("menuTraining")
        self.menuGround_Truth = QtWidgets.QMenu(self.menuTraining)
        self.menuGround_Truth.setObjectName("menuGround_Truth")
        self.menuGreekGT = QtWidgets.QMenu(self.menuGround_Truth)
        self.menuGreekGT.setObjectName("menuGreekGT")
        self.menuGreek_Image_Lines = QtWidgets.QMenu(self.menuGreekGT)
        self.menuGreek_Image_Lines.setObjectName("menuGreek_Image_Lines")
        self.menuGreek_Text_Lines = QtWidgets.QMenu(self.menuGreekGT)
        self.menuGreek_Text_Lines.setObjectName("menuGreek_Text_Lines")
        self.menuLatinGT = QtWidgets.QMenu(self.menuGround_Truth)
        self.menuLatinGT.setObjectName("menuLatinGT")
        self.menuLatin_Image_Lines = QtWidgets.QMenu(self.menuLatinGT)
        self.menuLatin_Image_Lines.setObjectName("menuLatin_Image_Lines")
        self.menuLatin_Text_Lines = QtWidgets.QMenu(self.menuLatinGT)
        self.menuLatin_Text_Lines.setObjectName("menuLatin_Text_Lines")
        self.menuOCR = QtWidgets.QMenu(self.menubar)
        self.menuOCR.setObjectName("menuOCR")
        self.menuSelect_Language = QtWidgets.QMenu(self.menuOCR)
        self.menuSelect_Language.setObjectName("menuSelect_Language")
        self.menuPost_Process = QtWidgets.QMenu(self.menubar)
        self.menuPost_Process.setObjectName("menuPost_Process")
        self.menuGreek_Post = QtWidgets.QMenu(self.menuPost_Process)
        self.menuGreek_Post.setObjectName("menuGreek_Post")
        self.menuPrepare_Text = QtWidgets.QMenu(self.menuPost_Process)
        self.menuPrepare_Text.setObjectName("menuPrepare_Text")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuGlyphs = QtWidgets.QMenu(self.menubar)
        self.menuGlyphs.setObjectName("menuGlyphs")
        self.menuIndex_Images = QtWidgets.QMenu(self.menuGlyphs)
        self.menuIndex_Images.setObjectName("menuIndex_Images")
        self.menuGround_Truth_2 = QtWidgets.QMenu(self.menubar)
        self.menuGround_Truth_2.setObjectName("menuGround_Truth_2")
        self.menuUpdate_Wordlists = QtWidgets.QMenu(self.menuGround_Truth_2)
        self.menuUpdate_Wordlists.setObjectName("menuUpdate_Wordlists")
        self.menuSetup_Training = QtWidgets.QMenu(self.menuGround_Truth_2)
        self.menuSetup_Training.setObjectName("menuSetup_Training")
        MainUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainUI)
        self.statusbar.setObjectName("statusbar")
        MainUI.setStatusBar(self.statusbar)
        self.PreProcessToolBar = QtWidgets.QToolBar(MainUI)
        self.PreProcessToolBar.setObjectName("PreProcessToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.PreProcessToolBar)
        self.TrainingToolBar = QtWidgets.QToolBar(MainUI)
        self.TrainingToolBar.setObjectName("TrainingToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.TrainingToolBar)
        self.dockOutput = QtWidgets.QDockWidget(MainUI)
        self.dockOutput.setEnabled(True)
        self.dockOutput.setMinimumSize(QtCore.QSize(560, 200))
        self.dockOutput.setBaseSize(QtCore.QSize(520, 200))
        self.dockOutput.setAccessibleName("")
        self.dockOutput.setAccessibleDescription("")
        self.dockOutput.setFloating(False)
        self.dockOutput.setObjectName("dockOutput")
        self.dockOutputContents = QtWidgets.QWidget()
        self.dockOutputContents.setObjectName("dockOutputContents")
        self.OutputText = QtWidgets.QTextEdit(self.dockOutputContents)
        self.OutputText.setGeometry(QtCore.QRect(10, 0, 550, 200))
        self.OutputText.setMinimumSize(QtCore.QSize(520, 200))
        self.OutputText.setObjectName("OutputText")
        self.dockOutput.setWidget(self.dockOutputContents)
        MainUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockOutput)
        self.dockChrRef = QtWidgets.QDockWidget(MainUI)
        self.dockChrRef.setMinimumSize(QtCore.QSize(650, 220))
        self.dockChrRef.setBaseSize(QtCore.QSize(640, 200))
        self.dockChrRef.setObjectName("dockChrRef")
        self.dockChrRefContents = QtWidgets.QWidget()
        self.dockChrRefContents.setMinimumSize(QtCore.QSize(650, 200))
        self.dockChrRefContents.setObjectName("dockChrRefContents")
        self.ChrRefplainTextEdit = QtWidgets.QPlainTextEdit(self.dockChrRefContents)
        self.ChrRefplainTextEdit.setGeometry(QtCore.QRect(110, 0, 570, 200))
        self.ChrRefplainTextEdit.setMinimumSize(QtCore.QSize(570, 200))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(18)
        self.ChrRefplainTextEdit.setFont(font)
        self.ChrRefplainTextEdit.setObjectName("ChrRefplainTextEdit")
        self.dockChrRef.setWidget(self.dockChrRefContents)
        MainUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockChrRef)
        self.toolBar = QtWidgets.QToolBar(MainUI)
        self.toolBar.setObjectName("toolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionpdf_to_tiff = QtWidgets.QAction(MainUI)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Icons/Icons/ocr2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_to_tiff.setIcon(icon13)
        self.actionpdf_to_tiff.setObjectName("actionpdf_to_tiff")
        self.actionmove_pdf_for_tiff = QtWidgets.QAction(MainUI)
        self.actionmove_pdf_for_tiff.setObjectName("actionmove_pdf_for_tiff")
        self.actiontiff_to_mono = QtWidgets.QAction(MainUI)
        self.actiontiff_to_mono.setObjectName("actiontiff_to_mono")
        self.actionmono_to_png = QtWidgets.QAction(MainUI)
        self.actionmono_to_png.setObjectName("actionmono_to_png")
        self.actiontiff_to_png = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png.setObjectName("actiontiff_to_png")
        self.actionGreek = QtWidgets.QAction(MainUI)
        self.actionGreek.setObjectName("actionGreek")
        self.actiontiff_to_png_2 = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png_2.setObjectName("actiontiff_to_png_2")
        self.actionpdf_for_tiff = QtWidgets.QAction(MainUI)
        self.actionpdf_for_tiff.setObjectName("actionpdf_for_tiff")
        self.actionpdf_for_tiff_tb = QtWidgets.QAction(MainUI)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf4tiff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_for_tiff_tb.setIcon(icon14)
        self.actionpdf_for_tiff_tb.setObjectName("actionpdf_for_tiff_tb")
        self.actionpdf_to_tiff_tb = QtWidgets.QAction(MainUI)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf2tiff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_to_tiff_tb.setIcon(icon15)
        self.actionpdf_to_tiff_tb.setObjectName("actionpdf_to_tiff_tb")
        self.actiontiff_to_mono_tb = QtWidgets.QAction(MainUI)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiontiff_to_mono_tb.setIcon(icon16)
        self.actiontiff_to_mono_tb.setObjectName("actiontiff_to_mono_tb")
        self.actionmono_to_png_tb = QtWidgets.QAction(MainUI)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Icons/Icons/png-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmono_to_png_tb.setIcon(icon17)
        self.actionmono_to_png_tb.setObjectName("actionmono_to_png_tb")
        self.actionLatin = QtWidgets.QAction(MainUI)
        self.actionLatin.setObjectName("actionLatin")
        self.actiontiff_to_png_3 = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png_3.setObjectName("actiontiff_to_png_3")
        self.actiontiff_to_png_4 = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png_4.setObjectName("actiontiff_to_png_4")
        self.actionDeskewGreek_tiff_tb = QtWidgets.QAction(MainUI)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeskewGreek_tiff_tb.setIcon(icon18)
        self.actionDeskewGreek_tiff_tb.setObjectName("actionDeskewGreek_tiff_tb")
        self.actiontiff_to_png_5 = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png_5.setObjectName("actiontiff_to_png_5")
        self.actionDeskewLatin_tiff_tb = QtWidgets.QAction(MainUI)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeskewLatin_tiff_tb.setIcon(icon19)
        self.actionDeskewLatin_tiff_tb.setObjectName("actionDeskewLatin_tiff_tb")
        self.actionResizeGreek_png_tb = QtWidgets.QAction(MainUI)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/Icons/Icons/resize-png-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResizeGreek_png_tb.setIcon(icon20)
        self.actionResizeGreek_png_tb.setObjectName("actionResizeGreek_png_tb")
        self.actionResizeLatin_png_tb = QtWidgets.QAction(MainUI)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/Icons/Icons/resize-png-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResizeLatin_png_tb.setIcon(icon21)
        self.actionResizeLatin_png_tb.setObjectName("actionResizeLatin_png_tb")
        self.actionCrop_Languages_tb = QtWidgets.QAction(MainUI)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-langs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrop_Languages_tb.setIcon(icon22)
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        self.actionCrop_Languages_tb.setFont(font)
        self.actionCrop_Languages_tb.setObjectName("actionCrop_Languages_tb")
        self.actionextract_pdf_tb = QtWidgets.QAction(MainUI)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf-extract1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionextract_pdf_tb.setIcon(icon23)
        self.actionextract_pdf_tb.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionextract_pdf_tb.setObjectName("actionextract_pdf_tb")
        self.actiontiff_for_Ground_Truth = QtWidgets.QAction(MainUI)
        self.actiontiff_for_Ground_Truth.setObjectName("actiontiff_for_Ground_Truth")
        self.actionCrop = QtWidgets.QAction(MainUI)
        self.actionCrop.setObjectName("actionCrop")
        self.actiontiff_for_Ground_Truth_2 = QtWidgets.QAction(MainUI)
        self.actiontiff_for_Ground_Truth_2.setObjectName("actiontiff_for_Ground_Truth_2")
        self.actionSplit = QtWidgets.QAction(MainUI)
        self.actionSplit.setObjectName("actionSplit")
        self.actionRename_tiff_lines = QtWidgets.QAction(MainUI)
        self.actionRename_tiff_lines.setObjectName("actionRename_tiff_lines")
        self.actionRename_text_lines = QtWidgets.QAction(MainUI)
        self.actionRename_text_lines.setObjectName("actionRename_text_lines")
        self.actionReview_Ground_Truth = QtWidgets.QAction(MainUI)
        self.actionReview_Ground_Truth.setObjectName("actionReview_Ground_Truth")
        self.actionGreek_Wordlist_2 = QtWidgets.QAction(MainUI)
        self.actionGreek_Wordlist_2.setObjectName("actionGreek_Wordlist_2")
        self.actionLatin_Wordlist = QtWidgets.QAction(MainUI)
        self.actionLatin_Wordlist.setObjectName("actionLatin_Wordlist")
        self.actionImage_Lines = QtWidgets.QAction(MainUI)
        self.actionImage_Lines.setObjectName("actionImage_Lines")
        self.actionText_Lines = QtWidgets.QAction(MainUI)
        self.actionText_Lines.setObjectName("actionText_Lines")
        self.actionReview_Ground_Truth_2 = QtWidgets.QAction(MainUI)
        self.actionReview_Ground_Truth_2.setObjectName("actionReview_Ground_Truth_2")
        self.actionUpdate_Wordlist = QtWidgets.QAction(MainUI)
        self.actionUpdate_Wordlist.setObjectName("actionUpdate_Wordlist")
        self.actionUpdate_Wordlist_2 = QtWidgets.QAction(MainUI)
        self.actionUpdate_Wordlist_2.setObjectName("actionUpdate_Wordlist_2")
        self.actionCorrect_OCR_tb = QtWidgets.QAction(MainUI)
        self.actionCorrect_OCR_tb.setIcon(icon2)
        self.actionCorrect_OCR_tb.setObjectName("actionCorrect_OCR_tb")
        self.actionVersify_Text = QtWidgets.QAction(MainUI)
        self.actionVersify_Text.setObjectName("actionVersify_Text")
        self.actionUpdate_Words = QtWidgets.QAction(MainUI)
        self.actionUpdate_Words.setObjectName("actionUpdate_Words")
        self.actionUpdate_Verses = QtWidgets.QAction(MainUI)
        self.actionUpdate_Verses.setObjectName("actionUpdate_Verses")
        self.actionUpdate_Words_Post = QtWidgets.QAction(MainUI)
        self.actionUpdate_Words_Post.setObjectName("actionUpdate_Words_Post")
        self.actionNormalize = QtWidgets.QAction(MainUI)
        self.actionNormalize.setObjectName("actionNormalize")
        self.actionLower_Case = QtWidgets.QAction(MainUI)
        self.actionLower_Case.setObjectName("actionLower_Case")
        self.actionRemove_Diacritics = QtWidgets.QAction(MainUI)
        self.actionRemove_Diacritics.setObjectName("actionRemove_Diacritics")
        self.actionAlign_Strongs = QtWidgets.QAction(MainUI)
        self.actionAlign_Strongs.setObjectName("actionAlign_Strongs")
        self.actionAlign_Lemmas = QtWidgets.QAction(MainUI)
        self.actionAlign_Lemmas.setObjectName("actionAlign_Lemmas")
        self.actionAlign_English = QtWidgets.QAction(MainUI)
        self.actionAlign_English.setObjectName("actionAlign_English")
        self.actionVariants = QtWidgets.QAction(MainUI)
        self.actionVariants.setObjectName("actionVariants")
        self.actionTrain_Tesseract_tb = QtWidgets.QAction(MainUI)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/Icons/Icons/trainOCR1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTrain_Tesseract_tb.setIcon(icon24)
        self.actionTrain_Tesseract_tb.setObjectName("actionTrain_Tesseract_tb")
        self.actionReview_Ground_Truth_tb = QtWidgets.QAction(MainUI)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/Icons/Icons/ground-truth1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReview_Ground_Truth_tb.setIcon(icon25)
        self.actionReview_Ground_Truth_tb.setObjectName("actionReview_Ground_Truth_tb")
        self.actionUpdate_Wordlist_tb = QtWidgets.QAction(MainUI)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/Icons/Icons/update-greek-wordlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdate_Wordlist_tb.setIcon(icon26)
        self.actionUpdate_Wordlist_tb.setObjectName("actionUpdate_Wordlist_tb")
        self.actionCrop_Greek_to_tiff_Lines_tb = QtWidgets.QAction(MainUI)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrop_Greek_to_tiff_Lines_tb.setIcon(icon27)
        self.actionCrop_Greek_to_tiff_Lines_tb.setObjectName("actionCrop_Greek_to_tiff_Lines_tb")
        self.actionRename_Greek_tiff_Lines_tb = QtWidgets.QAction(MainUI)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Greek_tiff_Lines_tb.setIcon(icon28)
        self.actionRename_Greek_tiff_Lines_tb.setObjectName("actionRename_Greek_tiff_Lines_tb")
        self.actionMove_Greek_tiff_Lines_tb = QtWidgets.QAction(MainUI)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/Icons/Icons/move-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_Greek_tiff_Lines_tb.setIcon(icon29)
        self.actionMove_Greek_tiff_Lines_tb.setObjectName("actionMove_Greek_tiff_Lines_tb")
        self.actionSplitGreek_text_lines_tb = QtWidgets.QAction(MainUI)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-textlines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSplitGreek_text_lines_tb.setIcon(icon30)
        self.actionSplitGreek_text_lines_tb.setObjectName("actionSplitGreek_text_lines_tb")
        self.actionRenameGreek_text_lines_tb = QtWidgets.QAction(MainUI)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename_textlines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRenameGreek_text_lines_tb.setIcon(icon31)
        self.actionRenameGreek_text_lines_tb.setObjectName("actionRenameGreek_text_lines_tb")
        self.actionImage_Lines_3 = QtWidgets.QAction(MainUI)
        self.actionImage_Lines_3.setObjectName("actionImage_Lines_3")
        self.actionReview_Ground_Truth_menu = QtWidgets.QAction(MainUI)
        self.actionReview_Ground_Truth_menu.setObjectName("actionReview_Ground_Truth_menu")
        self.actionUpdate_Wordlist_menu = QtWidgets.QAction(MainUI)
        self.actionUpdate_Wordlist_menu.setObjectName("actionUpdate_Wordlist_menu")
        self.actionCrop_Latin_To_tiff_Lines_tb = QtWidgets.QAction(MainUI)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrop_Latin_To_tiff_Lines_tb.setIcon(icon32)
        self.actionCrop_Latin_To_tiff_Lines_tb.setObjectName("actionCrop_Latin_To_tiff_Lines_tb")
        self.actionRename_Latin_tiff_Lines_tb = QtWidgets.QAction(MainUI)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Latin_tiff_Lines_tb.setIcon(icon33)
        self.actionRename_Latin_tiff_Lines_tb.setObjectName("actionRename_Latin_tiff_Lines_tb")
        self.actionMove_Latin_tiff_Lines_tb = QtWidgets.QAction(MainUI)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/Icons/Icons/move-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_Latin_tiff_Lines_tb.setIcon(icon34)
        self.actionMove_Latin_tiff_Lines_tb.setObjectName("actionMove_Latin_tiff_Lines_tb")
        self.actionSplit_Latin_Text_Lines_tb = QtWidgets.QAction(MainUI)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-textlines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSplit_Latin_Text_Lines_tb.setIcon(icon35)
        self.actionSplit_Latin_Text_Lines_tb.setObjectName("actionSplit_Latin_Text_Lines_tb")
        self.actionRename_Latin_Text_Lines_tb = QtWidgets.QAction(MainUI)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-textlines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Latin_Text_Lines_tb.setIcon(icon36)
        self.actionRename_Latin_Text_Lines_tb.setObjectName("actionRename_Latin_Text_Lines_tb")
        self.actiondeskew_mono = QtWidgets.QAction(MainUI)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-tiff-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondeskew_mono.setIcon(icon37)
        self.actiondeskew_mono.setObjectName("actiondeskew_mono")
        self.actionOpen_Image = QtWidgets.QAction(MainUI)
        self.actionOpen_Image.setIcon(icon1)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionVerse_Correction = QtWidgets.QAction(MainUI)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/Icons/Icons/versify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVerse_Correction.setIcon(icon38)
        self.actionVerse_Correction.setObjectName("actionVerse_Correction")
        self.actionConvert_Greek_tiff_To_png = QtWidgets.QAction(MainUI)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff2png-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConvert_Greek_tiff_To_png.setIcon(icon39)
        self.actionConvert_Greek_tiff_To_png.setObjectName("actionConvert_Greek_tiff_To_png")
        self.actionConvert_Latin_tiff_To_png = QtWidgets.QAction(MainUI)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff2png-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConvert_Latin_tiff_To_png.setIcon(icon40)
        self.actionConvert_Latin_tiff_To_png.setObjectName("actionConvert_Latin_tiff_To_png")
        self.actionExtract_Glyphs = QtWidgets.QAction(MainUI)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/Icons/Icons/epsilon-trace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExtract_Glyphs.setIcon(icon41)
        self.actionExtract_Glyphs.setObjectName("actionExtract_Glyphs")
        self.actionLine_tif_to_bmp = QtWidgets.QAction(MainUI)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff2bmp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLine_tif_to_bmp.setIcon(icon42)
        self.actionLine_tif_to_bmp.setObjectName("actionLine_tif_to_bmp")
        self.actionFontForge = QtWidgets.QAction(MainUI)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(":/Icons/Icons/FontForge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFontForge.setIcon(icon43)
        self.actionFontForge.setObjectName("actionFontForge")
        self.actionPrefernces = QtWidgets.QAction(MainUI)
        self.actionPrefernces.setObjectName("actionPrefernces")
        self.actionOpen_Text = QtWidgets.QAction(MainUI)
        self.actionOpen_Text.setObjectName("actionOpen_Text")
        self.actionSave_Image = QtWidgets.QAction(MainUI)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionSave_As_Image = QtWidgets.QAction(MainUI)
        self.actionSave_As_Image.setObjectName("actionSave_As_Image")
        self.actionSave_Text = QtWidgets.QAction(MainUI)
        self.actionSave_Text.setObjectName("actionSave_Text")
        self.actionSave_As_Text = QtWidgets.QAction(MainUI)
        self.actionSave_As_Text.setObjectName("actionSave_As_Text")
        self.actionConvert_Image_s = QtWidgets.QAction(MainUI)
        self.actionConvert_Image_s.setObjectName("actionConvert_Image_s")
        self.actionReview_Ground_Truth_3 = QtWidgets.QAction(MainUI)
        self.actionReview_Ground_Truth_3.setObjectName("actionReview_Ground_Truth_3")
        self.actionHebrew = QtWidgets.QAction(MainUI)
        self.actionHebrew.setObjectName("actionHebrew")
        self.actionHebrew_2 = QtWidgets.QAction(MainUI)
        self.actionHebrew_2.setObjectName("actionHebrew_2")
        self.actionUpdate_Hebrew_Wordlist = QtWidgets.QAction(MainUI)
        self.actionUpdate_Hebrew_Wordlist.setObjectName("actionUpdate_Hebrew_Wordlist")
        self.actionHebrew_3 = QtWidgets.QAction(MainUI)
        self.actionHebrew_3.setObjectName("actionHebrew_3")
        self.actionOCR_Image = QtWidgets.QAction(MainUI)
        self.actionOCR_Image.setObjectName("actionOCR_Image")
        self.actionSelect_Image = QtWidgets.QAction(MainUI)
        self.actionSelect_Image.setObjectName("actionSelect_Image")
        self.actionGreek_2 = QtWidgets.QAction(MainUI)
        self.actionGreek_2.setObjectName("actionGreek_2")
        self.actionHebrew_4 = QtWidgets.QAction(MainUI)
        self.actionHebrew_4.setObjectName("actionHebrew_4")
        self.actionLatin_2 = QtWidgets.QAction(MainUI)
        self.actionLatin_2.setObjectName("actionLatin_2")
        self.actionSelect_Language_Model = QtWidgets.QAction(MainUI)
        self.actionSelect_Language_Model.setObjectName("actionSelect_Language_Model")
        self.actionSelect_Fonts = QtWidgets.QAction(MainUI)
        self.actionSelect_Fonts.setObjectName("actionSelect_Fonts")
        self.actionany = QtWidgets.QAction(MainUI)
        self.actionany.setObjectName("actionany")
        self.actionAny = QtWidgets.QAction(MainUI)
        self.actionAny.setObjectName("actionAny")
        self.actionStage_Ground_Truth = QtWidgets.QAction(MainUI)
        self.actionStage_Ground_Truth.setObjectName("actionStage_Ground_Truth")
        self.actionCreate_e_Sword_Bible_Module = QtWidgets.QAction(MainUI)
        self.actionCreate_e_Sword_Bible_Module.setObjectName("actionCreate_e_Sword_Bible_Module")
        self.actionCreate_theWord_Bible_Module = QtWidgets.QAction(MainUI)
        self.actionCreate_theWord_Bible_Module.setObjectName("actionCreate_theWord_Bible_Module")
        self.actionEnglish = QtWidgets.QAction(MainUI)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionEnglishh = QtWidgets.QAction(MainUI)
        self.actionEnglishh.setObjectName("actionEnglishh")
        self.actionEnglish_2 = QtWidgets.QAction(MainUI)
        self.actionEnglish_2.setObjectName("actionEnglish_2")
        self.actionEnglish_3 = QtWidgets.QAction(MainUI)
        self.actionEnglish_3.setObjectName("actionEnglish_3")
        self.actionOnline = QtWidgets.QAction(MainUI)
        self.actionOnline.setObjectName("actionOnline")
        self.actionManual_Crop_Image_tb = QtWidgets.QAction(MainUI)
        self.actionManual_Crop_Image_tb.setIcon(icon7)
        self.actionManual_Crop_Image_tb.setObjectName("actionManual_Crop_Image_tb")
        self.actionEdit_Image_tb = QtWidgets.QAction(MainUI)
        self.actionEdit_Image_tb.setIcon(icon11)
        self.actionEdit_Image_tb.setObjectName("actionEdit_Image_tb")
        self.actionLibreOffice_Writer = QtWidgets.QAction(MainUI)
        self.actionLibreOffice_Writer.setIcon(icon9)
        self.actionLibreOffice_Writer.setObjectName("actionLibreOffice_Writer")
        self.actionLibreOffice_Calc = QtWidgets.QAction(MainUI)
        self.actionLibreOffice_Calc.setIcon(icon10)
        self.actionLibreOffice_Calc.setObjectName("actionLibreOffice_Calc")
        self.menuExtract_pdf.addAction(self.actionextract_pdf_tb)
        self.menuExtract_pdf.addSeparator()
        self.menuExtract_pdf.addAction(self.actionpdf_for_tiff_tb)
        self.menuExtract_pdf.addAction(self.actionpdf_to_tiff_tb)
        self.menuExtract_pdf.addAction(self.actiontiff_to_mono_tb)
        self.menuExtract_pdf.addAction(self.actionmono_to_png_tb)
        self.menuExtract_pdf.addAction(self.actiondeskew_mono)
        self.menuGreekDR.addAction(self.actionConvert_Greek_tiff_To_png)
        self.menuGreekDR.addAction(self.actionDeskewGreek_tiff_tb)
        self.menuGreekDR.addAction(self.actionResizeGreek_png_tb)
        self.menuLatinDR.addAction(self.actionConvert_Latin_tiff_To_png)
        self.menuLatinDR.addAction(self.actionDeskewLatin_tiff_tb)
        self.menuLatinDR.addAction(self.actionResizeLatin_png_tb)
        self.menuPrepare.addSeparator()
        self.menuPrepare.addAction(self.actionCrop_Languages_tb)
        self.menuPrepare.addAction(self.actionManual_Crop_Image_tb)
        self.menuPrepare.addAction(self.actionHebrew)
        self.menuPrepare.addAction(self.menuGreekDR.menuAction())
        self.menuPrepare.addAction(self.menuLatinDR.menuAction())
        self.menuPrepare.addAction(self.actionEnglishh)
        self.menuPre_Process.addSeparator()
        self.menuPre_Process.addAction(self.menuExtract_pdf.menuAction())
        self.menuPre_Process.addSeparator()
        self.menuPre_Process.addSeparator()
        self.menuPre_Process.addAction(self.menuPrepare.menuAction())
        self.menuGreek_Image_Lines.addAction(self.actionCrop_Greek_to_tiff_Lines_tb)
        self.menuGreek_Image_Lines.addAction(self.actionRename_Greek_tiff_Lines_tb)
        self.menuGreek_Image_Lines.addAction(self.actionMove_Greek_tiff_Lines_tb)
        self.menuGreek_Text_Lines.addAction(self.actionSplitGreek_text_lines_tb)
        self.menuGreek_Text_Lines.addAction(self.actionRenameGreek_text_lines_tb)
        self.menuGreekGT.addAction(self.menuGreek_Image_Lines.menuAction())
        self.menuGreekGT.addAction(self.menuGreek_Text_Lines.menuAction())
        self.menuLatin_Image_Lines.addAction(self.actionCrop_Latin_To_tiff_Lines_tb)
        self.menuLatin_Image_Lines.addAction(self.actionRename_Latin_tiff_Lines_tb)
        self.menuLatin_Image_Lines.addAction(self.actionMove_Latin_tiff_Lines_tb)
        self.menuLatin_Text_Lines.addAction(self.actionSplit_Latin_Text_Lines_tb)
        self.menuLatin_Text_Lines.addAction(self.actionRename_Latin_Text_Lines_tb)
        self.menuLatinGT.addAction(self.menuLatin_Image_Lines.menuAction())
        self.menuLatinGT.addAction(self.menuLatin_Text_Lines.menuAction())
        self.menuGround_Truth.addAction(self.actionHebrew_2)
        self.menuGround_Truth.addAction(self.menuGreekGT.menuAction())
        self.menuGround_Truth.addAction(self.menuLatinGT.menuAction())
        self.menuGround_Truth.addAction(self.actionEnglish_3)
        self.menuTraining.addSeparator()
        self.menuTraining.addAction(self.menuGround_Truth.menuAction())
        self.menuTraining.addAction(self.actionReview_Ground_Truth_tb)
        self.menuTraining.addAction(self.actionStage_Ground_Truth)
        self.menuSelect_Language.addAction(self.actionGreek_2)
        self.menuSelect_Language.addAction(self.actionHebrew_4)
        self.menuSelect_Language.addAction(self.actionLatin_2)
        self.menuSelect_Language.addAction(self.actionEnglish_2)
        self.menuOCR.addAction(self.menuSelect_Language.menuAction())
        self.menuOCR.addAction(self.actionSelect_Image)
        self.menuOCR.addAction(self.actionCorrect_OCR_tb)
        self.menuGreek_Post.addAction(self.actionUpdate_Verses)
        self.menuGreek_Post.addAction(self.actionUpdate_Words_Post)
        self.menuGreek_Post.addAction(self.actionNormalize)
        self.menuGreek_Post.addAction(self.actionLower_Case)
        self.menuGreek_Post.addAction(self.actionRemove_Diacritics)
        self.menuGreek_Post.addAction(self.actionAlign_Strongs)
        self.menuGreek_Post.addAction(self.actionAlign_English)
        self.menuGreek_Post.addAction(self.actionVariants)
        self.menuPost_Process.addAction(self.menuPrepare_Text.menuAction())
        self.menuPost_Process.addAction(self.actionHebrew_3)
        self.menuPost_Process.addAction(self.menuGreek_Post.menuAction())
        self.menuPost_Process.addAction(self.actionUpdate_Words)
        self.menuPost_Process.addAction(self.actionEnglish)
        self.menuPost_Process.addAction(self.actionCreate_e_Sword_Bible_Module)
        self.menuPost_Process.addAction(self.actionCreate_theWord_Bible_Module)
        self.menuFile.addAction(self.actionOpen_Image)
        self.menuFile.addAction(self.actionOpen_Text)
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addAction(self.actionSave_As_Image)
        self.menuFile.addAction(self.actionSave_Text)
        self.menuFile.addAction(self.actionSave_As_Text)
        self.menuEdit.addAction(self.actionEdit_Image_tb)
        self.menuEdit.addAction(self.actionPrefernces)
        self.menuTools.addAction(self.actionConvert_Image_s)
        self.menuTools.addAction(self.actionVerse_Correction)
        self.menuTools.addAction(self.actionOnline)
        self.menuTools.addAction(self.actionLibreOffice_Writer)
        self.menuTools.addAction(self.actionLibreOffice_Calc)
        self.menuIndex_Images.addAction(self.actionLine_tif_to_bmp)
        self.menuGlyphs.addAction(self.menuIndex_Images.menuAction())
        self.menuGlyphs.addAction(self.actionExtract_Glyphs)
        self.menuGlyphs.addAction(self.actionFontForge)
        self.menuUpdate_Wordlists.addAction(self.actionUpdate_Hebrew_Wordlist)
        self.menuUpdate_Wordlists.addAction(self.actionUpdate_Wordlist_tb)
        self.menuUpdate_Wordlists.addAction(self.actionUpdate_Wordlist_menu)
        self.menuSetup_Training.addAction(self.actionSelect_Language_Model)
        self.menuSetup_Training.addAction(self.actionSelect_Fonts)
        self.menuGround_Truth_2.addAction(self.menuUpdate_Wordlists.menuAction())
        self.menuGround_Truth_2.addAction(self.menuSetup_Training.menuAction())
        self.menuGround_Truth_2.addAction(self.actionTrain_Tesseract_tb)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPre_Process.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuOCR.menuAction())
        self.menubar.addAction(self.menuTraining.menuAction())
        self.menubar.addAction(self.menuGlyphs.menuAction())
        self.menubar.addAction(self.menuGround_Truth_2.menuAction())
        self.menubar.addAction(self.menuPost_Process.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.PreProcessToolBar.addAction(self.actionextract_pdf_tb)
        self.PreProcessToolBar.addAction(self.actionpdf_for_tiff_tb)
        self.PreProcessToolBar.addAction(self.actionpdf_to_tiff_tb)
        self.PreProcessToolBar.addAction(self.actiontiff_to_mono_tb)
        self.PreProcessToolBar.addAction(self.actionmono_to_png_tb)
        self.PreProcessToolBar.addAction(self.actiondeskew_mono)
        self.PreProcessToolBar.addSeparator()
        self.PreProcessToolBar.addAction(self.actionCrop_Languages_tb)
        self.PreProcessToolBar.addAction(self.actionConvert_Greek_tiff_To_png)
        self.PreProcessToolBar.addAction(self.actionDeskewGreek_tiff_tb)
        self.PreProcessToolBar.addAction(self.actionResizeGreek_png_tb)
        self.PreProcessToolBar.addAction(self.actionConvert_Latin_tiff_To_png)
        self.PreProcessToolBar.addAction(self.actionDeskewLatin_tiff_tb)
        self.PreProcessToolBar.addAction(self.actionResizeLatin_png_tb)
        self.PreProcessToolBar.addSeparator()
        self.PreProcessToolBar.addAction(self.actionManual_Crop_Image_tb)
        self.PreProcessToolBar.addAction(self.actionEdit_Image_tb)
        self.PreProcessToolBar.addAction(self.actionCorrect_OCR_tb)
        self.PreProcessToolBar.addSeparator()
        self.TrainingToolBar.addAction(self.actionCrop_Greek_to_tiff_Lines_tb)
        self.TrainingToolBar.addAction(self.actionCrop_Latin_To_tiff_Lines_tb)
        self.TrainingToolBar.addAction(self.actionRename_Greek_tiff_Lines_tb)
        self.TrainingToolBar.addAction(self.actionMove_Greek_tiff_Lines_tb)
        self.TrainingToolBar.addAction(self.actionRename_Latin_tiff_Lines_tb)
        self.TrainingToolBar.addAction(self.actionMove_Latin_tiff_Lines_tb)
        self.TrainingToolBar.addSeparator()
        self.TrainingToolBar.addAction(self.actionLine_tif_to_bmp)
        self.TrainingToolBar.addAction(self.actionExtract_Glyphs)
        self.TrainingToolBar.addAction(self.actionFontForge)
        self.TrainingToolBar.addAction(self.actionLibreOffice_Calc)
        self.TrainingToolBar.addAction(self.actionLibreOffice_Writer)
        self.TrainingToolBar.addSeparator()
        self.TrainingToolBar.addAction(self.actionSplitGreek_text_lines_tb)
        self.TrainingToolBar.addAction(self.actionRenameGreek_text_lines_tb)
        self.TrainingToolBar.addAction(self.actionSplit_Latin_Text_Lines_tb)
        self.TrainingToolBar.addAction(self.actionRename_Latin_Text_Lines_tb)
        self.TrainingToolBar.addSeparator()
        self.TrainingToolBar.addAction(self.actionReview_Ground_Truth_tb)
        self.TrainingToolBar.addAction(self.actionVerse_Correction)
        self.TrainingToolBar.addAction(self.actionUpdate_Wordlist_tb)
        self.TrainingToolBar.addAction(self.actionTrain_Tesseract_tb)
        self.TrainingToolBar.addSeparator()

        self.retranslateUi(MainUI)
        QtCore.QMetaObject.connectSlotsByName(MainUI)

    def retranslateUi(self, MainUI):
        _translate = QtCore.QCoreApplication.translate
        MainUI.setWindowTitle(_translate("MainUI", "Biblical OCR"))
        self.OpenImageFilebutton.setText(_translate("MainUI", "Open Image"))
        self.OCRbutton.setText(_translate("MainUI", "OCR Raw"))
        self.EditCorrectedTextbutton.setText(_translate("MainUI", "Open Text"))
        self.SaveAsOCRCorrTextbutton.setText(_translate("MainUI", "Save As"))
        self.SaveOCRCorrTextbutton.setText(_translate("MainUI", "Save"))
        self.LHlineEdit.setText(_translate("MainUI", "150"))
        self.LHlineEdit.setPlaceholderText(_translate("MainUI", "150"))
        self.LHslider.setToolTip(_translate("MainUI", "Set text line spacing."))
        self.LHlabel.setText(_translate("MainUI", " Line Spacing"))
        self.Cropbutton.setText(_translate("MainUI", "Crop"))
        self.Zoombutton.setText(_translate("MainUI", "Zoom"))
        self.ZoomComboBox.setCurrentText(_translate("MainUI", "Best_Fit"))
        self.ZoomComboBox.setItemText(0, _translate("MainUI", "Best_Fit"))
        self.ZoomComboBox.setItemText(1, _translate("MainUI", "10 %"))
        self.ZoomComboBox.setItemText(2, _translate("MainUI", "25 %"))
        self.ZoomComboBox.setItemText(3, _translate("MainUI", "50 %"))
        self.ZoomComboBox.setItemText(4, _translate("MainUI", "100 %"))
        self.ZoomComboBox.setItemText(5, _translate("MainUI", "200 %"))
        self.fontSizelabel.setText(_translate("MainUI", "Font Size"))
        self.langComboBox.setItemText(0, _translate("MainUI", "feg"))
        self.langComboBox.setItemText(1, _translate("MainUI", "Ancient Greek"))
        self.langComboBox.setItemText(2, _translate("MainUI", "Modern Greek"))
        self.langComboBox.setItemText(3, _translate("MainUI", "feh"))
        self.langComboBox.setItemText(4, _translate("MainUI", "Hebrew"))
        self.langComboBox.setItemText(5, _translate("MainUI", "fel"))
        self.langComboBox.setItemText(6, _translate("MainUI", "Latin"))
        self.langlabel.setText(_translate("MainUI", " OCR Language"))
        self.fontlabel.setText(_translate("MainUI", "Font"))
        self.reloadTextbutton.setToolTip(_translate("MainUI", "Reload text file"))
        self.reloadImagebutton.setToolTip(_translate("MainUI", "Reload image"))
        self.menuPre_Process.setTitle(_translate("MainUI", "Language"))
        self.menuExtract_pdf.setTitle(_translate("MainUI", "Source"))
        self.menuPrepare.setTitle(_translate("MainUI", "Languages"))
        self.menuGreekDR.setTitle(_translate("MainUI", "Greek"))
        self.menuLatinDR.setTitle(_translate("MainUI", "Latin"))
        self.menuTraining.setTitle(_translate("MainUI", "Ground-Truth"))
        self.menuGround_Truth.setTitle(_translate("MainUI", "Establish Truth"))
        self.menuGreekGT.setTitle(_translate("MainUI", "Greek"))
        self.menuGreek_Image_Lines.setTitle(_translate("MainUI", "Greek Image Lines"))
        self.menuGreek_Text_Lines.setTitle(_translate("MainUI", "Greek Text Lines"))
        self.menuLatinGT.setTitle(_translate("MainUI", "Latin"))
        self.menuLatin_Image_Lines.setTitle(_translate("MainUI", "Latin Image Lines"))
        self.menuLatin_Text_Lines.setTitle(_translate("MainUI", "Latin Text Lines"))
        self.menuOCR.setTitle(_translate("MainUI", "OCR"))
        self.menuSelect_Language.setTitle(_translate("MainUI", "Select Language"))
        self.menuPost_Process.setTitle(_translate("MainUI", "Modules"))
        self.menuGreek_Post.setTitle(_translate("MainUI", "Greek"))
        self.menuPrepare_Text.setTitle(_translate("MainUI", "Prepare Text"))
        self.menuFile.setTitle(_translate("MainUI", "File"))
        self.menuEdit.setTitle(_translate("MainUI", "Edit"))
        self.menuView.setTitle(_translate("MainUI", "View"))
        self.menuTools.setTitle(_translate("MainUI", "Tools"))
        self.menuHelp.setTitle(_translate("MainUI", "Help"))
        self.menuGlyphs.setTitle(_translate("MainUI", "FontForge"))
        self.menuIndex_Images.setTitle(_translate("MainUI", "Bitmap Images"))
        self.menuGround_Truth_2.setTitle(_translate("MainUI", "Training"))
        self.menuUpdate_Wordlists.setTitle(_translate("MainUI", "Update Wordlists"))
        self.menuSetup_Training.setTitle(_translate("MainUI", "Setup Training"))
        self.PreProcessToolBar.setWindowTitle(_translate("MainUI", "toolBar"))
        self.PreProcessToolBar.setToolTip(_translate("MainUI", "Extract pages from pdf source file"))
        self.PreProcessToolBar.setWhatsThis(_translate("MainUI", "pdf Page Extractor"))
        self.TrainingToolBar.setWindowTitle(_translate("MainUI", "toolBar"))
        self.dockOutput.setWindowTitle(_translate("MainUI", " Output"))
        self.dockChrRef.setWindowTitle(_translate("MainUI", "                    Character Reference"))
        self.ChrRefplainTextEdit.setDocumentTitle(_translate("MainUI", "Character Reference"))
        self.toolBar.setWindowTitle(_translate("MainUI", "toolBar"))
        self.actionpdf_to_tiff.setText(_translate("MainUI", "pdf for tiff"))
        self.actionmove_pdf_for_tiff.setText(_translate("MainUI", "pdf to tiff"))
        self.actiontiff_to_mono.setText(_translate("MainUI", "tiff to mono"))
        self.actionmono_to_png.setText(_translate("MainUI", "mono to png"))
        self.actiontiff_to_png.setText(_translate("MainUI", "tiff to png"))
        self.actionGreek.setText(_translate("MainUI", "Greek"))
        self.actiontiff_to_png_2.setText(_translate("MainUI", "tiff to png"))
        self.actionpdf_for_tiff.setText(_translate("MainUI", "pdf for tiff"))
        self.actionpdf_for_tiff_tb.setText(_translate("MainUI", "pdf For tiff"))
        self.actionpdf_for_tiff_tb.setToolTip(_translate("MainUI", "Stage pdf pages FOR tiff conversion"))
        self.actionpdf_to_tiff_tb.setText(_translate("MainUI", "pdf To tiff"))
        self.actionpdf_to_tiff_tb.setToolTip(_translate("MainUI", "Convert pdf pages TO tiff files"))
        self.actiontiff_to_mono_tb.setText(_translate("MainUI", "tiff indexed"))
        self.actiontiff_to_mono_tb.setToolTip(_translate("MainUI", "Convert tiff files TO indexed monochrome"))
        self.actionmono_to_png_tb.setText(_translate("MainUI", "png indexed"))
        self.actionmono_to_png_tb.setToolTip(_translate("MainUI", "Convert deskewed monochrome tiff files TO png"))
        self.actionLatin.setText(_translate("MainUI", "Latin"))
        self.actiontiff_to_png_3.setText(_translate("MainUI", "tiff to png"))
        self.actiontiff_to_png_4.setText(_translate("MainUI", "tiff to png"))
        self.actionDeskewGreek_tiff_tb.setText(_translate("MainUI", "Deskew Greek tiff"))
        self.actiontiff_to_png_5.setText(_translate("MainUI", "tiff to png"))
        self.actionDeskewLatin_tiff_tb.setText(_translate("MainUI", "Deskew Latin tiff"))
        self.actionResizeGreek_png_tb.setText(_translate("MainUI", "Resize Greek png"))
        self.actionResizeLatin_png_tb.setText(_translate("MainUI", "Resize Latin png"))
        self.actionCrop_Languages_tb.setText(_translate("MainUI", "Auto Crop Languages"))
        self.actionCrop_Languages_tb.setToolTip(_translate("MainUI", "Crop language sections into separate tiff files"))
        self.actionextract_pdf_tb.setText(_translate("MainUI", "Extract pdf"))
        self.actionextract_pdf_tb.setToolTip(_translate("MainUI", "Extract pages from pdf source document"))
        self.actiontiff_for_Ground_Truth.setText(_translate("MainUI", "tiff for Ground Truth"))
        self.actionCrop.setText(_translate("MainUI", "Crop to tiff lines"))
        self.actiontiff_for_Ground_Truth_2.setText(_translate("MainUI", "Move tiff lines"))
        self.actionSplit.setText(_translate("MainUI", "Split text lines"))
        self.actionRename_tiff_lines.setText(_translate("MainUI", "Rename tiff lines"))
        self.actionRename_text_lines.setText(_translate("MainUI", "Rename text lines"))
        self.actionReview_Ground_Truth.setText(_translate("MainUI", "Review Ground Truth"))
        self.actionGreek_Wordlist_2.setText(_translate("MainUI", "Greek Wordlist"))
        self.actionLatin_Wordlist.setText(_translate("MainUI", "Latin Wordlist"))
        self.actionImage_Lines.setText(_translate("MainUI", "Image Lines"))
        self.actionText_Lines.setText(_translate("MainUI", "Text Lines"))
        self.actionReview_Ground_Truth_2.setText(_translate("MainUI", "Review Ground Truth"))
        self.actionUpdate_Wordlist.setText(_translate("MainUI", "Update Wordlist"))
        self.actionUpdate_Wordlist_2.setText(_translate("MainUI", "Update Wordlist"))
        self.actionCorrect_OCR_tb.setText(_translate("MainUI", "OCR Image"))
        self.actionVersify_Text.setText(_translate("MainUI", "Versify Text"))
        self.actionUpdate_Words.setText(_translate("MainUI", "Latin"))
        self.actionUpdate_Verses.setText(_translate("MainUI", "Update Verses"))
        self.actionUpdate_Words_Post.setText(_translate("MainUI", "Update Words"))
        self.actionNormalize.setText(_translate("MainUI", "Normalize"))
        self.actionLower_Case.setText(_translate("MainUI", "Lower Case"))
        self.actionRemove_Diacritics.setText(_translate("MainUI", "Remove Diacritics"))
        self.actionAlign_Strongs.setText(_translate("MainUI", "Align Strongs+RMAC"))
        self.actionAlign_Lemmas.setText(_translate("MainUI", "Align Lemmas"))
        self.actionAlign_English.setText(_translate("MainUI", "Align English"))
        self.actionVariants.setText(_translate("MainUI", "Variants"))
        self.actionTrain_Tesseract_tb.setText(_translate("MainUI", "Train Tesseract"))
        self.actionReview_Ground_Truth_tb.setText(_translate("MainUI", "Review Ground Truth"))
        self.actionUpdate_Wordlist_tb.setText(_translate("MainUI", "Update Greek Wordlist"))
        self.actionCrop_Greek_to_tiff_Lines_tb.setText(_translate("MainUI", "Crop Greek To tiff Lines"))
        self.actionRename_Greek_tiff_Lines_tb.setText(_translate("MainUI", "Rename Greek tiff Lines"))
        self.actionMove_Greek_tiff_Lines_tb.setText(_translate("MainUI", "Move Greek tiff Lines"))
        self.actionSplitGreek_text_lines_tb.setText(_translate("MainUI", "Split Greek Text Lines"))
        self.actionRenameGreek_text_lines_tb.setText(_translate("MainUI", "Rename Greek Text Lines"))
        self.actionImage_Lines_3.setText(_translate("MainUI", "Image Lines"))
        self.actionReview_Ground_Truth_menu.setText(_translate("MainUI", "Review Ground Truth"))
        self.actionUpdate_Wordlist_menu.setText(_translate("MainUI", "Update Latin Wordlist"))
        self.actionCrop_Latin_To_tiff_Lines_tb.setText(_translate("MainUI", "Crop Latin To tiff Lines"))
        self.actionRename_Latin_tiff_Lines_tb.setText(_translate("MainUI", "Rename Latin tiff Lines"))
        self.actionMove_Latin_tiff_Lines_tb.setText(_translate("MainUI", "Move Greek tiff Lines"))
        self.actionSplit_Latin_Text_Lines_tb.setText(_translate("MainUI", "Split Latin Text Lines"))
        self.actionRename_Latin_Text_Lines_tb.setText(_translate("MainUI", "Rename Latin Text Lines"))
        self.actiondeskew_mono.setText(_translate("MainUI", "Deskew indexed"))
        self.actionOpen_Image.setText(_translate("MainUI", "Open Image"))
        self.actionVerse_Correction.setText(_translate("MainUI", "Verse Correction"))
        self.actionConvert_Greek_tiff_To_png.setText(_translate("MainUI", "Convert Greek tiff To png"))
        self.actionConvert_Latin_tiff_To_png.setText(_translate("MainUI", "Convert Latin tiff To png"))
        self.actionExtract_Glyphs.setText(_translate("MainUI", "GlyphTracer"))
        self.actionLine_tif_to_bmp.setText(_translate("MainUI", "Line tif to bmp"))
        self.actionFontForge.setText(_translate("MainUI", "FontForge"))
        self.actionPrefernces.setText(_translate("MainUI", "Preferences"))
        self.actionOpen_Text.setText(_translate("MainUI", "Open Text"))
        self.actionSave_Image.setText(_translate("MainUI", "Save Image"))
        self.actionSave_As_Image.setText(_translate("MainUI", "Save As Image"))
        self.actionSave_Text.setText(_translate("MainUI", "Save Text"))
        self.actionSave_As_Text.setText(_translate("MainUI", "Save As Text"))
        self.actionConvert_Image_s.setText(_translate("MainUI", "Convert Image(s)"))
        self.actionReview_Ground_Truth_3.setText(_translate("MainUI", "Review Ground Truth"))
        self.actionHebrew.setText(_translate("MainUI", "Hebrew"))
        self.actionHebrew_2.setText(_translate("MainUI", "Hebrew"))
        self.actionUpdate_Hebrew_Wordlist.setText(_translate("MainUI", "Update Hebrew Wordlist"))
        self.actionHebrew_3.setText(_translate("MainUI", "Hebrew"))
        self.actionOCR_Image.setText(_translate("MainUI", "OCR Image"))
        self.actionSelect_Image.setText(_translate("MainUI", "Select Image"))
        self.actionGreek_2.setText(_translate("MainUI", "Greek"))
        self.actionHebrew_4.setText(_translate("MainUI", "Hebrew"))
        self.actionLatin_2.setText(_translate("MainUI", "Latin"))
        self.actionSelect_Language_Model.setText(_translate("MainUI", "Select Language Model"))
        self.actionSelect_Fonts.setText(_translate("MainUI", "Select Fonts"))
        self.actionany.setText(_translate("MainUI", "any"))
        self.actionAny.setText(_translate("MainUI", "Any"))
        self.actionStage_Ground_Truth.setText(_translate("MainUI", "Stage Ground Truth"))
        self.actionCreate_e_Sword_Bible_Module.setText(_translate("MainUI", "e-Sword Bible Module"))
        self.actionCreate_theWord_Bible_Module.setText(_translate("MainUI", "theWord Bible Module"))
        self.actionEnglish.setText(_translate("MainUI", "English"))
        self.actionEnglishh.setText(_translate("MainUI", "English"))
        self.actionEnglish_2.setText(_translate("MainUI", "English"))
        self.actionEnglish_3.setText(_translate("MainUI", "English"))
        self.actionOnline.setText(_translate("MainUI", "Online"))
        self.actionManual_Crop_Image_tb.setText(_translate("MainUI", "Manual Crop"))
        self.actionManual_Crop_Image_tb.setToolTip(_translate("MainUI", "Manually crop tif image"))
        self.actionEdit_Image_tb.setText(_translate("MainUI", "Gimp Image Editor"))
        self.actionLibreOffice_Writer.setText(_translate("MainUI", "LibreOffice Writer"))
        self.actionLibreOffice_Calc.setText(_translate("MainUI", "LibreOffice Calc"))

import UI_Icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainUI = QtWidgets.QMainWindow()
    ui = Ui_MainUI()
    ui.setupUi(MainUI)
    MainUI.show()
    sys.exit(app.exec_())

