# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerUI/ImageEditUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1580, 1028)
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/image-crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setObjectName("centralwidget")
        self.ImagescrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.ImagescrollArea.setGeometry(QtCore.QRect(200, 0, 1241, 921))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollArea.sizePolicy().hasHeightForWidth())
        self.ImagescrollArea.setSizePolicy(sizePolicy)
        self.ImagescrollArea.setMinimumSize(QtCore.QSize(500, 700))
        self.ImagescrollArea.setMouseTracking(True)
        self.ImagescrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ImagescrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ImagescrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.ImagescrollArea.setWidgetResizable(True)
        self.ImagescrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ImagescrollArea.setObjectName("ImagescrollArea")
        self.ImagescrollAreaWidgetContents = QtWidgets.QWidget()
        self.ImagescrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 6400, 9600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.ImagescrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.ImagescrollAreaWidgetContents.setMinimumSize(QtCore.QSize(6400, 9600))
        self.ImagescrollAreaWidgetContents.setSizeIncrement(QtCore.QSize(0, 0))
        self.ImagescrollAreaWidgetContents.setBaseSize(QtCore.QSize(6800, 2200))
        self.ImagescrollAreaWidgetContents.setMouseTracking(False)
        self.ImagescrollAreaWidgetContents.setObjectName("ImagescrollAreaWidgetContents")
        self.Image = QtWidgets.QLabel(self.ImagescrollAreaWidgetContents)
        self.Image.setGeometry(QtCore.QRect(460, 810, 6800, 9600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Image.sizePolicy().hasHeightForWidth())
        self.Image.setSizePolicy(sizePolicy)
        self.Image.setMinimumSize(QtCore.QSize(6400, 9600))
        self.Image.setBaseSize(QtCore.QSize(6800, 2200))
        self.Image.setMouseTracking(False)
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../../../../../.designer/Images/Greek/jpg_desk_greek/greek_book_40_Matthew/greek1516_Page_012.jpg"))
        self.Image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Image.setObjectName("Image")
        self.Cropped = QtWidgets.QLabel(self.ImagescrollAreaWidgetContents)
        self.Cropped.setGeometry(QtCore.QRect(130, 60, 3200, 4800))
        self.Cropped.setMinimumSize(QtCore.QSize(3200, 4800))
        self.Cropped.setMouseTracking(False)
        self.Cropped.setObjectName("Cropped")
        self.ImagescrollArea.setWidget(self.ImagescrollAreaWidgetContents)
        self.ImageLe = QtWidgets.QLineEdit(self.centralwidget)
        self.ImageLe.setGeometry(QtCore.QRect(330, 940, 481, 25))
        self.ImageLe.setMouseTracking(False)
        self.ImageLe.setObjectName("ImageLe")
        self.OpenImageFilebutton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenImageFilebutton.setGeometry(QtCore.QRect(830, 940, 91, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.OpenImageFilebutton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenImageFilebutton.setIcon(icon1)
        self.OpenImageFilebutton.setObjectName("OpenImageFilebutton")
        self.Cropbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Cropbutton.setGeometry(QtCore.QRect(1060, 940, 51, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.Cropbutton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/image-crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cropbutton.setIcon(icon2)
        self.Cropbutton.setObjectName("Cropbutton")
        self.ZoomComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ZoomComboBox.setGeometry(QtCore.QRect(990, 940, 51, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZoomComboBox.sizePolicy().hasHeightForWidth())
        self.ZoomComboBox.setSizePolicy(sizePolicy)
        self.ZoomComboBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ZoomComboBox.setEditable(True)
        self.ZoomComboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.ZoomComboBox.setObjectName("ZoomComboBox")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.Zoombutton = QtWidgets.QPushButton(self.centralwidget)
        self.Zoombutton.setGeometry(QtCore.QRect(940, 940, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Zoombutton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/image-resize1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Zoombutton.setIcon(icon3)
        self.Zoombutton.setObjectName("Zoombutton")
        self.Deskewbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Deskewbutton.setGeometry(QtCore.QRect(1130, 940, 51, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.Deskewbutton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew_clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Deskewbutton.setIcon(icon4)
        self.Deskewbutton.setObjectName("Deskewbutton")
        self.Rotatebutton = QtWidgets.QPushButton(self.centralwidget)
        self.Rotatebutton.setGeometry(QtCore.QRect(1200, 940, 51, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.Rotatebutton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/rotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Rotatebutton.setIcon(icon5)
        self.Rotatebutton.setObjectName("Rotatebutton")
        self.Flipbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Flipbutton.setGeometry(QtCore.QRect(1270, 940, 51, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.Flipbutton.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/hflip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Flipbutton.setIcon(icon6)
        self.Flipbutton.setObjectName("Flipbutton")
        self.CroppedscrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.CroppedscrollArea.setGeometry(QtCore.QRect(-380, 0, 575, 921))
        self.CroppedscrollArea.setMinimumSize(QtCore.QSize(500, 700))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CroppedscrollArea.setFont(font)
        self.CroppedscrollArea.setMouseTracking(True)
        self.CroppedscrollArea.setWidgetResizable(True)
        self.CroppedscrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.CroppedscrollArea.setObjectName("CroppedscrollArea")
        self.CroppedscrollAreaWidgetContents = QtWidgets.QWidget()
        self.CroppedscrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 3200, 4800))
        self.CroppedscrollAreaWidgetContents.setMinimumSize(QtCore.QSize(3200, 4800))
        self.CroppedscrollAreaWidgetContents.setMouseTracking(False)
        self.CroppedscrollAreaWidgetContents.setObjectName("CroppedscrollAreaWidgetContents")
        self.CroppedWidget = QtWidgets.QDockWidget(self.CroppedscrollAreaWidgetContents)
        self.CroppedWidget.setGeometry(QtCore.QRect(-20, 10, 581, 1006))
        self.CroppedWidget.setMinimumSize(QtCore.QSize(581, 1006))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CroppedWidget.setFont(font)
        self.CroppedWidget.setMouseTracking(True)
        self.CroppedWidget.setFloating(True)
        self.CroppedWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.CroppedWidget.setWindowTitle("")
        self.CroppedWidget.setObjectName("CroppedWidget")
        self.CroppedWidgetContents = QtWidgets.QWidget()
        self.CroppedWidgetContents.setMinimumSize(QtCore.QSize(580, 984))
        self.CroppedWidgetContents.setMouseTracking(True)
        self.CroppedWidgetContents.setObjectName("CroppedWidgetContents")
        self.SaveCroppedImgAsbutton = QtWidgets.QPushButton(self.CroppedWidgetContents)
        self.SaveCroppedImgAsbutton.setGeometry(QtCore.QRect(500, 940, 61, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveCroppedImgAsbutton.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk-rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveCroppedImgAsbutton.setIcon(icon7)
        self.SaveCroppedImgAsbutton.setObjectName("SaveCroppedImgAsbutton")
        self.SaveCroppedImgbutton = QtWidgets.QPushButton(self.CroppedWidgetContents)
        self.SaveCroppedImgbutton.setGeometry(QtCore.QRect(410, 940, 71, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveCroppedImgbutton.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveCroppedImgbutton.setIcon(icon8)
        self.SaveCroppedImgbutton.setObjectName("SaveCroppedImgbutton")
        self.CroppedLe = QtWidgets.QLineEdit(self.CroppedWidgetContents)
        self.CroppedLe.setGeometry(QtCore.QRect(10, 940, 381, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CroppedLe.setFont(font)
        self.CroppedLe.setMouseTracking(False)
        self.CroppedLe.setObjectName("CroppedLe")
        self.CroppedWidget.setWidget(self.CroppedWidgetContents)
        self.CroppedscrollArea.setWidget(self.CroppedscrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Crop Tif Image"))
        self.Cropped.setText(_translate("MainWindow", "TextLabel"))
        self.OpenImageFilebutton.setText(_translate("MainWindow", "Open Image"))
        self.Cropbutton.setText(_translate("MainWindow", "Crop"))
        self.ZoomComboBox.setCurrentText(_translate("MainWindow", "5 %"))
        self.ZoomComboBox.setItemText(0, _translate("MainWindow", "5 %"))
        self.ZoomComboBox.setItemText(1, _translate("MainWindow", "10 %"))
        self.ZoomComboBox.setItemText(2, _translate("MainWindow", "25 %"))
        self.ZoomComboBox.setItemText(3, _translate("MainWindow", "50 %"))
        self.ZoomComboBox.setItemText(4, _translate("MainWindow", "100 %"))
        self.ZoomComboBox.setItemText(5, _translate("MainWindow", "200 %"))
        self.Zoombutton.setText(_translate("MainWindow", "Zoom"))
        self.Deskewbutton.setText(_translate("MainWindow", "Deskew"))
        self.Rotatebutton.setText(_translate("MainWindow", "Rotate"))
        self.Flipbutton.setText(_translate("MainWindow", "Flip"))
        self.SaveCroppedImgAsbutton.setText(_translate("MainWindow", "Save As"))
        self.SaveCroppedImgbutton.setText(_translate("MainWindow", "Overwrite"))

import UI_Icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

