# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerUI/MyFixerUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Fixer(object):
    def setupUi(self, Fixer):
        Fixer.setObjectName("Fixer")
        Fixer.setEnabled(True)
        Fixer.resize(1319, 933)
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        Fixer.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/grail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Fixer.setWindowIcon(icon)
        Fixer.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(Fixer)
        self.centralwidget.setObjectName("centralwidget")
        self.SaveAsVerseTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveAsVerseTextbutton.setGeometry(QtCore.QRect(1240, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveAsVerseTextbutton.setFont(font)
        self.SaveAsVerseTextbutton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk-rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveAsVerseTextbutton.setIcon(icon1)
        self.SaveAsVerseTextbutton.setObjectName("SaveAsVerseTextbutton")
        self.SaveVerseTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveVerseTextbutton.setGeometry(QtCore.QRect(1270, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveVerseTextbutton.setFont(font)
        self.SaveVerseTextbutton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveVerseTextbutton.setIcon(icon2)
        self.SaveVerseTextbutton.setObjectName("SaveVerseTextbutton")
        self.BothNextChapterButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothNextChapterButton.setGeometry(QtCore.QRect(690, 0, 21, 25))
        self.BothNextChapterButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/ui-button-navigation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothNextChapterButton.setIcon(icon3)
        self.BothNextChapterButton.setObjectName("BothNextChapterButton")
        self.BothPrevChapterButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothPrevChapterButton.setGeometry(QtCore.QRect(610, 0, 21, 25))
        self.BothPrevChapterButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/ui-button-navigation-back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothPrevChapterButton.setIcon(icon4)
        self.BothPrevChapterButton.setObjectName("BothPrevChapterButton")
        self.BothLoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothLoadButton.setEnabled(True)
        self.BothLoadButton.setGeometry(QtCore.QRect(650, 0, 21, 25))
        self.BothLoadButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/synchronize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothLoadButton.setIcon(icon5)
        self.BothLoadButton.setObjectName("BothLoadButton")
        self.OCRgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.OCRgroupBox.setGeometry(QtCore.QRect(580, 80, 161, 131))
        self.OCRgroupBox.setTitle("")
        self.OCRgroupBox.setObjectName("OCRgroupBox")
        self.OCRlangComboBox = QtWidgets.QComboBox(self.OCRgroupBox)
        self.OCRlangComboBox.setGeometry(QtCore.QRect(20, 50, 121, 25))
        self.OCRlangComboBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OCRlangComboBox.setEditable(False)
        self.OCRlangComboBox.setObjectName("OCRlangComboBox")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlanglabel = QtWidgets.QLabel(self.OCRgroupBox)
        self.OCRlanglabel.setGeometry(QtCore.QRect(40, 30, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OCRlanglabel.setFont(font)
        self.OCRlanglabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OCRlanglabel.setObjectName("OCRlanglabel")
        self.OCRModellabel = QtWidgets.QLabel(self.OCRgroupBox)
        self.OCRModellabel.setGeometry(QtCore.QRect(30, 80, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OCRModellabel.setFont(font)
        self.OCRModellabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OCRModellabel.setObjectName("OCRModellabel")
        self.OCRModelComboBox = QtWidgets.QComboBox(self.OCRgroupBox)
        self.OCRModelComboBox.setGeometry(QtCore.QRect(50, 100, 61, 25))
        self.OCRModelComboBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OCRModelComboBox.setEditable(False)
        self.OCRModelComboBox.setObjectName("OCRModelComboBox")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.ImageLE = QtWidgets.QLineEdit(self.centralwidget)
        self.ImageLE.setGeometry(QtCore.QRect(740, 0, 241, 25))
        self.ImageLE.setObjectName("ImageLE")
        self.SessiongroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.SessiongroupBox.setGeometry(QtCore.QRect(580, 30, 161, 71))
        self.SessiongroupBox.setTitle("")
        self.SessiongroupBox.setObjectName("SessiongroupBox")
        self.booklabel = QtWidgets.QLabel(self.SessiongroupBox)
        self.booklabel.setGeometry(QtCore.QRect(60, 0, 41, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.booklabel.setFont(font)
        self.booklabel.setAlignment(QtCore.Qt.AlignCenter)
        self.booklabel.setObjectName("booklabel")
        self.bookComboBox = QtWidgets.QComboBox(self.SessiongroupBox)
        self.bookComboBox.setGeometry(QtCore.QRect(50, 20, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bookComboBox.setFont(font)
        self.bookComboBox.setEditable(True)
        self.bookComboBox.setObjectName("bookComboBox")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.reloadRefImgbutton = QtWidgets.QPushButton(self.centralwidget)
        self.reloadRefImgbutton.setGeometry(QtCore.QRect(580, 0, 21, 25))
        self.reloadRefImgbutton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadRefImgbutton.setIcon(icon6)
        self.reloadRefImgbutton.setObjectName("reloadRefImgbutton")
        self.PrevRefImgbutton = QtWidgets.QPushButton(self.centralwidget)
        self.PrevRefImgbutton.setGeometry(QtCore.QRect(280, 0, 21, 25))
        self.PrevRefImgbutton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/back_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PrevRefImgbutton.setIcon(icon7)
        self.PrevRefImgbutton.setObjectName("PrevRefImgbutton")
        self.RefImgLE = QtWidgets.QLineEdit(self.centralwidget)
        self.RefImgLE.setGeometry(QtCore.QRect(340, 0, 241, 25))
        self.RefImgLE.setObjectName("RefImgLE")
        self.RefImgZoombutton = QtWidgets.QPushButton(self.centralwidget)
        self.RefImgZoombutton.setEnabled(True)
        self.RefImgZoombutton.setGeometry(QtCore.QRect(160, 0, 21, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RefImgZoombutton.setFont(font)
        self.RefImgZoombutton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/image-resize1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RefImgZoombutton.setIcon(icon8)
        self.RefImgZoombutton.setObjectName("RefImgZoombutton")
        self.NextRefImgbutton = QtWidgets.QPushButton(self.centralwidget)
        self.NextRefImgbutton.setGeometry(QtCore.QRect(310, 0, 21, 25))
        self.NextRefImgbutton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Icons/forward_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextRefImgbutton.setIcon(icon9)
        self.NextRefImgbutton.setObjectName("NextRefImgbutton")
        self.OpenImagebutton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenImagebutton.setGeometry(QtCore.QRect(30, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.OpenImagebutton.setFont(font)
        self.OpenImagebutton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenImagebutton.setIcon(icon10)
        self.OpenImagebutton.setObjectName("OpenImagebutton")
        self.RefImgZoomComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.RefImgZoomComboBox.setGeometry(QtCore.QRect(180, 0, 61, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RefImgZoomComboBox.sizePolicy().hasHeightForWidth())
        self.RefImgZoomComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RefImgZoomComboBox.setFont(font)
        self.RefImgZoomComboBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.RefImgZoomComboBox.setEditable(True)
        self.RefImgZoomComboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.RefImgZoomComboBox.setObjectName("RefImgZoomComboBox")
        self.RefImgZoomComboBox.addItem("")
        self.RefImgZoomComboBox.addItem("")
        self.RefImgZoomComboBox.addItem("")
        self.RefImgZoomComboBox.addItem("")
        self.RefImgZoomComboBox.addItem("")
        self.RefImgScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.RefImgScrollArea.setGeometry(QtCore.QRect(30, 30, 551, 600))
        self.RefImgScrollArea.setWidgetResizable(True)
        self.RefImgScrollArea.setObjectName("RefImgScrollArea")
        self.RefScrollAreaWidgetContents = QtWidgets.QWidget()
        self.RefScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 549, 598))
        self.RefScrollAreaWidgetContents.setObjectName("RefScrollAreaWidgetContents")
        self.RefImg = QtWidgets.QLabel(self.RefScrollAreaWidgetContents)
        self.RefImg.setGeometry(QtCore.QRect(0, 0, 6800, 9600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RefImg.sizePolicy().hasHeightForWidth())
        self.RefImg.setSizePolicy(sizePolicy)
        self.RefImg.setMinimumSize(QtCore.QSize(3400, 4800))
        self.RefImg.setBaseSize(QtCore.QSize(520, 700))
        self.RefImg.setText("")
        self.RefImg.setScaledContents(False)
        self.RefImg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.RefImg.setObjectName("RefImg")
        self.RefImgZoomslider = QtWidgets.QSlider(self.RefScrollAreaWidgetContents)
        self.RefImgZoomslider.setEnabled(False)
        self.RefImgZoomslider.setGeometry(QtCore.QRect(160, 0, 21, 161))
        self.RefImgZoomslider.setMinimum(10)
        self.RefImgZoomslider.setMaximum(100)
        self.RefImgZoomslider.setSingleStep(1)
        self.RefImgZoomslider.setPageStep(20)
        self.RefImgZoomslider.setProperty("value", 25)
        self.RefImgZoomslider.setSliderPosition(25)
        self.RefImgZoomslider.setOrientation(QtCore.Qt.Vertical)
        self.RefImgZoomslider.setInvertedAppearance(True)
        self.RefImgZoomslider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.RefImgZoomslider.setObjectName("RefImgZoomslider")
        self.RefImgScrollArea.setWidget(self.RefScrollAreaWidgetContents)
        self.PrevImagebutton = QtWidgets.QPushButton(self.centralwidget)
        self.PrevImagebutton.setGeometry(QtCore.QRect(990, 0, 21, 25))
        self.PrevImagebutton.setText("")
        self.PrevImagebutton.setIcon(icon7)
        self.PrevImagebutton.setObjectName("PrevImagebutton")
        self.NextImagebutton = QtWidgets.QPushButton(self.centralwidget)
        self.NextImagebutton.setGeometry(QtCore.QRect(1020, 0, 21, 25))
        self.NextImagebutton.setText("")
        self.NextImagebutton.setIcon(icon9)
        self.NextImagebutton.setObjectName("NextImagebutton")
        self.ImageZoombutton = QtWidgets.QPushButton(self.centralwidget)
        self.ImageZoombutton.setEnabled(True)
        self.ImageZoombutton.setGeometry(QtCore.QRect(1080, 0, 21, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ImageZoombutton.setFont(font)
        self.ImageZoombutton.setText("")
        self.ImageZoombutton.setIcon(icon8)
        self.ImageZoombutton.setObjectName("ImageZoombutton")
        self.ImageZoomComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ImageZoomComboBox.setGeometry(QtCore.QRect(1100, 0, 61, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageZoomComboBox.sizePolicy().hasHeightForWidth())
        self.ImageZoomComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ImageZoomComboBox.setFont(font)
        self.ImageZoomComboBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ImageZoomComboBox.setEditable(True)
        self.ImageZoomComboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.ImageZoomComboBox.setObjectName("ImageZoomComboBox")
        self.ImageZoomComboBox.addItem("")
        self.ImageZoomComboBox.addItem("")
        self.ImageZoomComboBox.addItem("")
        self.ImageZoomComboBox.addItem("")
        self.ImageZoomComboBox.addItem("")
        self.reloadImagebutton = QtWidgets.QPushButton(self.centralwidget)
        self.reloadImagebutton.setGeometry(QtCore.QRect(720, 0, 21, 25))
        self.reloadImagebutton.setText("")
        self.reloadImagebutton.setIcon(icon6)
        self.reloadImagebutton.setObjectName("reloadImagebutton")
        self.ImportRefImgFilebutton = QtWidgets.QPushButton(self.centralwidget)
        self.ImportRefImgFilebutton.setGeometry(QtCore.QRect(70, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.ImportRefImgFilebutton.setFont(font)
        self.ImportRefImgFilebutton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/image-import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ImportRefImgFilebutton.setIcon(icon11)
        self.ImportRefImgFilebutton.setObjectName("ImportRefImgFilebutton")
        self.ExportImageFilebutton = QtWidgets.QPushButton(self.centralwidget)
        self.ExportImageFilebutton.setGeometry(QtCore.QRect(1200, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.ExportImageFilebutton.setFont(font)
        self.ExportImageFilebutton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icons/image-export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExportImageFilebutton.setIcon(icon12)
        self.ExportImageFilebutton.setObjectName("ExportImageFilebutton")
        self.ImageScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.ImageScrollArea.setGeometry(QtCore.QRect(740, 30, 551, 600))
        self.ImageScrollArea.setWidgetResizable(True)
        self.ImageScrollArea.setObjectName("ImageScrollArea")
        self.ImageScrollAreaWidgetContents = QtWidgets.QWidget()
        self.ImageScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 549, 598))
        self.ImageScrollAreaWidgetContents.setObjectName("ImageScrollAreaWidgetContents")
        self.Image = QtWidgets.QLabel(self.ImageScrollAreaWidgetContents)
        self.Image.setEnabled(False)
        self.Image.setGeometry(QtCore.QRect(0, 0, 3400, 4800))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Image.sizePolicy().hasHeightForWidth())
        self.Image.setSizePolicy(sizePolicy)
        self.Image.setMinimumSize(QtCore.QSize(3400, 4800))
        self.Image.setBaseSize(QtCore.QSize(520, 700))
        self.Image.setText("")
        self.Image.setScaledContents(False)
        self.Image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Image.setObjectName("Image")
        self.ImageZoomslider = QtWidgets.QSlider(self.ImageScrollAreaWidgetContents)
        self.ImageZoomslider.setEnabled(False)
        self.ImageZoomslider.setGeometry(QtCore.QRect(370, 0, 21, 161))
        self.ImageZoomslider.setMinimum(10)
        self.ImageZoomslider.setMaximum(100)
        self.ImageZoomslider.setSingleStep(1)
        self.ImageZoomslider.setPageStep(20)
        self.ImageZoomslider.setProperty("value", 25)
        self.ImageZoomslider.setSliderPosition(25)
        self.ImageZoomslider.setOrientation(QtCore.Qt.Vertical)
        self.ImageZoomslider.setInvertedAppearance(True)
        self.ImageZoomslider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.ImageZoomslider.setObjectName("ImageZoomslider")
        self.ImageScrollArea.setWidget(self.ImageScrollAreaWidgetContents)
        Fixer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Fixer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1319, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuMorphology = QtWidgets.QMenu(self.menuEdit)
        self.menuMorphology.setObjectName("menuMorphology")
        self.menuFill = QtWidgets.QMenu(self.menuEdit)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Icons/Icons/paint-can.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuFill.setIcon(icon13)
        self.menuFill.setObjectName("menuFill")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuPrepare = QtWidgets.QMenu(self.menubar)
        self.menuPrepare.setObjectName("menuPrepare")
        Fixer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Fixer)
        self.statusbar.setObjectName("statusbar")
        Fixer.setStatusBar(self.statusbar)
        self.dockOutput = QtWidgets.QDockWidget(Fixer)
        self.dockOutput.setEnabled(True)
        self.dockOutput.setMinimumSize(QtCore.QSize(581, 200))
        self.dockOutput.setBaseSize(QtCore.QSize(560, 200))
        self.dockOutput.setAccessibleName("")
        self.dockOutput.setAccessibleDescription("")
        self.dockOutput.setFloating(False)
        self.dockOutput.setObjectName("dockOutput")
        self.dockOutputContents = QtWidgets.QWidget()
        self.dockOutputContents.setObjectName("dockOutputContents")
        self.OutputText = QtWidgets.QTextEdit(self.dockOutputContents)
        self.OutputText.setGeometry(QtCore.QRect(29, 0, 550, 200))
        self.OutputText.setMinimumSize(QtCore.QSize(520, 200))
        self.OutputText.setObjectName("OutputText")
        self.dockOutput.setWidget(self.dockOutputContents)
        Fixer.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockOutput)
        self.EditToolBar = QtWidgets.QToolBar(Fixer)
        self.EditToolBar.setObjectName("EditToolBar")
        Fixer.addToolBar(QtCore.Qt.TopToolBarArea, self.EditToolBar)
        self.dockNothing = QtWidgets.QDockWidget(Fixer)
        self.dockNothing.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockNothing.sizePolicy().hasHeightForWidth())
        self.dockNothing.setSizePolicy(sizePolicy)
        self.dockNothing.setMinimumSize(QtCore.QSize(145, 220))
        self.dockNothing.setBaseSize(QtCore.QSize(150, 200))
        self.dockNothing.setWindowTitle("")
        self.dockNothing.setObjectName("dockNothing")
        self.dockNothingContents = QtWidgets.QWidget()
        self.dockNothingContents.setMinimumSize(QtCore.QSize(150, 200))
        self.dockNothingContents.setObjectName("dockNothingContents")
        self.Nothing = QtWidgets.QLabel(self.dockNothingContents)
        self.Nothing.setEnabled(False)
        self.Nothing.setGeometry(QtCore.QRect(0, 0, 140, 200))
        self.Nothing.setMinimumSize(QtCore.QSize(140, 200))
        self.Nothing.setText("")
        self.Nothing.setObjectName("Nothing")
        self.dockNothing.setWidget(self.dockNothingContents)
        Fixer.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockNothing)
        self.dockGlyphRef = QtWidgets.QDockWidget(Fixer)
        self.dockGlyphRef.setMinimumSize(QtCore.QSize(550, 200))
        self.dockGlyphRef.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockGlyphRef.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.dockGlyphRef.setObjectName("dockGlyphRef")
        self.dockGlyphRefContents = QtWidgets.QWidget()
        self.dockGlyphRefContents.setMinimumSize(QtCore.QSize(550, 200))
        self.dockGlyphRefContents.setObjectName("dockGlyphRefContents")
        self.GlyphRef = QtWidgets.QLabel(self.dockGlyphRefContents)
        self.GlyphRef.setGeometry(QtCore.QRect(9, 0, 545, 200))
        self.GlyphRef.setMinimumSize(QtCore.QSize(545, 200))
        self.GlyphRef.setText("")
        self.GlyphRef.setObjectName("GlyphRef")
        self.dockGlyphRef.setWidget(self.dockGlyphRefContents)
        Fixer.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockGlyphRef)
        self.actionOpen_Image = QtWidgets.QAction(Fixer)
        self.actionOpen_Image.setIcon(icon10)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionExtract_Glyphs = QtWidgets.QAction(Fixer)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Icons/Icons/trace1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExtract_Glyphs.setIcon(icon14)
        self.actionExtract_Glyphs.setObjectName("actionExtract_Glyphs")
        self.actionFontForge = QtWidgets.QAction(Fixer)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Icons/Icons/FontForge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFontForge.setIcon(icon15)
        self.actionFontForge.setObjectName("actionFontForge")
        self.actionPreferences = QtWidgets.QAction(Fixer)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionOpen_Image_2 = QtWidgets.QAction(Fixer)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-document-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Image_2.setIcon(icon16)
        self.actionOpen_Image_2.setObjectName("actionOpen_Image_2")
        self.actionSave_Image = QtWidgets.QAction(Fixer)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionSave_As_Image = QtWidgets.QAction(Fixer)
        self.actionSave_As_Image.setObjectName("actionSave_As_Image")
        self.actionSave_Text = QtWidgets.QAction(Fixer)
        self.actionSave_Text.setIcon(icon2)
        self.actionSave_Text.setObjectName("actionSave_Text")
        self.actionSave_As_Text = QtWidgets.QAction(Fixer)
        self.actionSave_As_Text.setIcon(icon1)
        self.actionSave_As_Text.setObjectName("actionSave_As_Text")
        self.actionSelect_Image = QtWidgets.QAction(Fixer)
        self.actionSelect_Image.setObjectName("actionSelect_Image")
        self.actionSelect_Language_Model = QtWidgets.QAction(Fixer)
        self.actionSelect_Language_Model.setObjectName("actionSelect_Language_Model")
        self.actionSelect_Fonts = QtWidgets.QAction(Fixer)
        self.actionSelect_Fonts.setObjectName("actionSelect_Fonts")
        self.actionany = QtWidgets.QAction(Fixer)
        self.actionany.setObjectName("actionany")
        self.actionAny = QtWidgets.QAction(Fixer)
        self.actionAny.setObjectName("actionAny")
        self.actionCreate_e_Sword_Bible_Module = QtWidgets.QAction(Fixer)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Icons/Icons/esword.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_e_Sword_Bible_Module.setIcon(icon17)
        self.actionCreate_e_Sword_Bible_Module.setObjectName("actionCreate_e_Sword_Bible_Module")
        self.actionCreate_theWord_Bible_Module = QtWidgets.QAction(Fixer)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Icons/Icons/theword.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_theWord_Bible_Module.setIcon(icon18)
        self.actionCreate_theWord_Bible_Module.setObjectName("actionCreate_theWord_Bible_Module")
        self.actionManual_Crop_Image_tb = QtWidgets.QAction(Fixer)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/Icons/Icons/image-crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionManual_Crop_Image_tb.setIcon(icon19)
        self.actionManual_Crop_Image_tb.setObjectName("actionManual_Crop_Image_tb")
        self.actionEdit_Image_tb = QtWidgets.QAction(Fixer)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/Icons/Icons/gimp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_Image_tb.setIcon(icon20)
        self.actionEdit_Image_tb.setObjectName("actionEdit_Image_tb")
        self.actionGimp = QtWidgets.QAction(Fixer)
        self.actionGimp.setIcon(icon20)
        self.actionGimp.setObjectName("actionGimp")
        self.actionOpen_Reference_Image = QtWidgets.QAction(Fixer)
        self.actionOpen_Reference_Image.setIcon(icon16)
        self.actionOpen_Reference_Image.setObjectName("actionOpen_Reference_Image")
        self.actionRotateRefImg_CW = QtWidgets.QAction(Fixer)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/Icons/Icons/layer-rotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRotateRefImg_CW.setIcon(icon21)
        self.actionRotateRefImg_CW.setObjectName("actionRotateRefImg_CW")
        self.actionDeskewRefImg = QtWidgets.QAction(Fixer)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew_clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeskewRefImg.setIcon(icon22)
        self.actionDeskewRefImg.setObjectName("actionDeskewRefImg")
        self.actionDespeckleRefImg = QtWidgets.QAction(Fixer)
        self.actionDespeckleRefImg.setObjectName("actionDespeckleRefImg")
        self.actionFlipRefImg = QtWidgets.QAction(Fixer)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/Icons/Icons/layer-flip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFlipRefImg.setIcon(icon23)
        self.actionFlipRefImg.setObjectName("actionFlipRefImg")
        self.actionConvert = QtWidgets.QAction(Fixer)
        self.actionConvert.setObjectName("actionConvert")
        self.actionImport_Current_Image = QtWidgets.QAction(Fixer)
        self.actionImport_Current_Image.setIcon(icon11)
        self.actionImport_Current_Image.setObjectName("actionImport_Current_Image")
        self.actionExport_Image = QtWidgets.QAction(Fixer)
        self.actionExport_Image.setIcon(icon12)
        self.actionExport_Image.setObjectName("actionExport_Image")
        self.actionThreshold = QtWidgets.QAction(Fixer)
        self.actionThreshold.setObjectName("actionThreshold")
        self.actionOperator = QtWidgets.QAction(Fixer)
        self.actionOperator.setObjectName("actionOperator")
        self.actionSE = QtWidgets.QAction(Fixer)
        self.actionSE.setObjectName("actionSE")
        self.actionkernal_x = QtWidgets.QAction(Fixer)
        self.actionkernal_x.setObjectName("actionkernal_x")
        self.actionkernel_y = QtWidgets.QAction(Fixer)
        self.actionkernel_y.setObjectName("actionkernel_y")
        self.actionIterations = QtWidgets.QAction(Fixer)
        self.actionIterations.setObjectName("actionIterations")
        self.actionBoxes = QtWidgets.QAction(Fixer)
        self.actionBoxes.setObjectName("actionBoxes")
        self.actionGlyph_Tracer = QtWidgets.QAction(Fixer)
        self.actionGlyph_Tracer.setIcon(icon14)
        self.actionGlyph_Tracer.setObjectName("actionGlyph_Tracer")
        self.actionPage_Segmentation = QtWidgets.QAction(Fixer)
        self.actionPage_Segmentation.setObjectName("actionPage_Segmentation")
        self.actionLanguage_Segmentation = QtWidgets.QAction(Fixer)
        self.actionLanguage_Segmentation.setObjectName("actionLanguage_Segmentation")
        self.actionLine_Segmentation = QtWidgets.QAction(Fixer)
        self.actionLine_Segmentation.setObjectName("actionLine_Segmentation")
        self.actionGlyph_Production = QtWidgets.QAction(Fixer)
        self.actionGlyph_Production.setObjectName("actionGlyph_Production")
        self.actionFont_Production = QtWidgets.QAction(Fixer)
        self.actionFont_Production.setObjectName("actionFont_Production")
        self.actionCropRefImg = QtWidgets.QAction(Fixer)
        self.actionCropRefImg.setIcon(icon19)
        self.actionCropRefImg.setObjectName("actionCropRefImg")
        self.actionBox_Production = QtWidgets.QAction(Fixer)
        self.actionBox_Production.setObjectName("actionBox_Production")
        self.actionErase = QtWidgets.QAction(Fixer)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/Icons/Icons/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionErase.setIcon(icon24)
        self.actionErase.setObjectName("actionErase")
        self.actionFillBackground = QtWidgets.QAction(Fixer)
        self.actionFillBackground.setObjectName("actionFillBackground")
        self.actionFillForeground = QtWidgets.QAction(Fixer)
        self.actionFillForeground.setObjectName("actionFillForeground")
        self.actionFillTransparent = QtWidgets.QAction(Fixer)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/Icons/Icons/table-paint-can.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFillTransparent.setIcon(icon25)
        self.actionFillTransparent.setObjectName("actionFillTransparent")
        self.actionFillSelection = QtWidgets.QAction(Fixer)
        self.actionFillSelection.setObjectName("actionFillSelection")
        self.actionRotateRefImg_CCW = QtWidgets.QAction(Fixer)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/Icons/Icons/layer-rotate-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRotateRefImg_CCW.setIcon(icon26)
        self.actionRotateRefImg_CCW.setObjectName("actionRotateRefImg_CCW")
        self.actionDenoise = QtWidgets.QAction(Fixer)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/Icons/Icons/denoise.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDenoise.setIcon(icon27)
        self.actionDenoise.setObjectName("actionDenoise")
        self.menuFile.addAction(self.actionOpen_Reference_Image)
        self.menuFile.addAction(self.actionOpen_Image_2)
        self.menuFile.addAction(self.actionSave_Text)
        self.menuFile.addAction(self.actionSave_As_Text)
        self.menuFile.addAction(self.actionImport_Current_Image)
        self.menuFile.addAction(self.actionExport_Image)
        self.menuMorphology.addAction(self.actionThreshold)
        self.menuMorphology.addAction(self.actionOperator)
        self.menuMorphology.addAction(self.actionSE)
        self.menuMorphology.addAction(self.actionkernal_x)
        self.menuMorphology.addAction(self.actionkernel_y)
        self.menuMorphology.addAction(self.actionIterations)
        self.menuFill.addSeparator()
        self.menuFill.addAction(self.actionFillTransparent)
        self.menuFill.addAction(self.actionFillSelection)
        self.menuFill.addAction(self.actionFillBackground)
        self.menuFill.addAction(self.actionFillForeground)
        self.menuEdit.addAction(self.actionDenoise)
        self.menuEdit.addAction(self.actionErase)
        self.menuEdit.addAction(self.actionCropRefImg)
        self.menuEdit.addAction(self.menuFill.menuAction())
        self.menuEdit.addAction(self.actionFlipRefImg)
        self.menuEdit.addAction(self.actionRotateRefImg_CW)
        self.menuEdit.addAction(self.actionRotateRefImg_CCW)
        self.menuEdit.addAction(self.actionDeskewRefImg)
        self.menuEdit.addAction(self.menuMorphology.menuAction())
        self.menuEdit.addAction(self.actionBoxes)
        self.menuPrepare.addAction(self.actionLanguage_Segmentation)
        self.menuPrepare.addAction(self.actionBox_Production)
        self.menuPrepare.addAction(self.actionLine_Segmentation)
        self.menuPrepare.addAction(self.actionGlyph_Production)
        self.menuPrepare.addAction(self.actionFont_Production)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPrepare.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.EditToolBar.addAction(self.actionDenoise)
        self.EditToolBar.addAction(self.actionErase)
        self.EditToolBar.addAction(self.actionFlipRefImg)
        self.EditToolBar.addAction(self.actionRotateRefImg_CW)
        self.EditToolBar.addAction(self.actionRotateRefImg_CCW)
        self.EditToolBar.addAction(self.actionCropRefImg)
        self.EditToolBar.addAction(self.actionFillTransparent)
        self.EditToolBar.addAction(self.actionDeskewRefImg)

        self.retranslateUi(Fixer)
        QtCore.QMetaObject.connectSlotsByName(Fixer)

    def retranslateUi(self, Fixer):
        _translate = QtCore.QCoreApplication.translate
        Fixer.setWindowTitle(_translate("Fixer", "Fixer"))
        self.SaveAsVerseTextbutton.setToolTip(_translate("Fixer", "Save image as..."))
        self.SaveVerseTextbutton.setToolTip(_translate("Fixer", "Overwrite reference image"))
        self.BothNextChapterButton.setToolTip(_translate("Fixer", "Next image pair"))
        self.BothPrevChapterButton.setToolTip(_translate("Fixer", "Previous  image pair"))
        self.BothLoadButton.setToolTip(_translate("Fixer", "Synch image pair"))
        self.OCRlangComboBox.setToolTip(_translate("Fixer", "Select OCR language"))
        self.OCRlangComboBox.setItemText(0, _translate("Fixer", "Ancient Greek"))
        self.OCRlangComboBox.setItemText(1, _translate("Fixer", "Middle Greek"))
        self.OCRlangComboBox.setItemText(2, _translate("Fixer", "Modern Greek"))
        self.OCRlangComboBox.setItemText(3, _translate("Fixer", "Hebrew"))
        self.OCRlangComboBox.setItemText(4, _translate("Fixer", "Latin"))
        self.OCRlanglabel.setText(_translate("Fixer", " OCR Language"))
        self.OCRModellabel.setToolTip(_translate("Fixer", "Select OCR LSTM model"))
        self.OCRModellabel.setText(_translate("Fixer", " OCR LSTM Model"))
        self.OCRModelComboBox.setToolTip(_translate("Fixer", "Select OCR language model"))
        self.OCRModelComboBox.setItemText(0, _translate("Fixer", "ell"))
        self.OCRModelComboBox.setItemText(1, _translate("Fixer", "grc"))
        self.OCRModelComboBox.setItemText(2, _translate("Fixer", "feg"))
        self.OCRModelComboBox.setItemText(3, _translate("Fixer", "heb"))
        self.OCRModelComboBox.setItemText(4, _translate("Fixer", "feh"))
        self.OCRModelComboBox.setItemText(5, _translate("Fixer", "lat"))
        self.OCRModelComboBox.setItemText(6, _translate("Fixer", "fel"))
        self.ImageLE.setToolTip(_translate("Fixer", "Image name"))
        self.booklabel.setText(_translate("Fixer", "Book"))
        self.bookComboBox.setToolTip(_translate("Fixer", "Bible book current image|text directory"))
        self.bookComboBox.setItemText(0, _translate("Fixer", "Mat"))
        self.bookComboBox.setItemText(1, _translate("Fixer", "Mar"))
        self.bookComboBox.setItemText(2, _translate("Fixer", "Luk"))
        self.bookComboBox.setItemText(3, _translate("Fixer", "Joh"))
        self.bookComboBox.setItemText(4, _translate("Fixer", "Act"))
        self.bookComboBox.setItemText(5, _translate("Fixer", "Rom"))
        self.bookComboBox.setItemText(6, _translate("Fixer", "1Co"))
        self.bookComboBox.setItemText(7, _translate("Fixer", "2Co"))
        self.bookComboBox.setItemText(8, _translate("Fixer", "Gal"))
        self.bookComboBox.setItemText(9, _translate("Fixer", "Eph"))
        self.bookComboBox.setItemText(10, _translate("Fixer", "Php"))
        self.bookComboBox.setItemText(11, _translate("Fixer", "Col"))
        self.bookComboBox.setItemText(12, _translate("Fixer", "1Th"))
        self.bookComboBox.setItemText(13, _translate("Fixer", "2Th"))
        self.bookComboBox.setItemText(14, _translate("Fixer", "1Ti"))
        self.bookComboBox.setItemText(15, _translate("Fixer", "2Ti"))
        self.bookComboBox.setItemText(16, _translate("Fixer", "Tit"))
        self.bookComboBox.setItemText(17, _translate("Fixer", "Phm"))
        self.bookComboBox.setItemText(18, _translate("Fixer", "Heb"))
        self.bookComboBox.setItemText(19, _translate("Fixer", "Jas"))
        self.bookComboBox.setItemText(20, _translate("Fixer", "1Pe"))
        self.bookComboBox.setItemText(21, _translate("Fixer", "2Pe"))
        self.bookComboBox.setItemText(22, _translate("Fixer", "1Jn"))
        self.bookComboBox.setItemText(23, _translate("Fixer", "2Jn"))
        self.bookComboBox.setItemText(24, _translate("Fixer", "3Jn"))
        self.bookComboBox.setItemText(25, _translate("Fixer", "Jud"))
        self.bookComboBox.setItemText(26, _translate("Fixer", "Rev"))
        self.reloadRefImgbutton.setToolTip(_translate("Fixer", "Reload reference image"))
        self.PrevRefImgbutton.setToolTip(_translate("Fixer", "Previous Reference Image"))
        self.RefImgLE.setToolTip(_translate("Fixer", "Reference image name"))
        self.RefImgZoombutton.setToolTip(_translate("Fixer", "Enable reference zoom slider"))
        self.NextRefImgbutton.setToolTip(_translate("Fixer", "Next Reference Image"))
        self.OpenImagebutton.setToolTip(_translate("Fixer", "Open image"))
        self.RefImgZoomComboBox.setToolTip(_translate("Fixer", "Select reference image zoom"))
        self.RefImgZoomComboBox.setCurrentText(_translate("Fixer", "10 %"))
        self.RefImgZoomComboBox.setItemText(0, _translate("Fixer", "10 %"))
        self.RefImgZoomComboBox.setItemText(1, _translate("Fixer", "25 %"))
        self.RefImgZoomComboBox.setItemText(2, _translate("Fixer", "50 %"))
        self.RefImgZoomComboBox.setItemText(3, _translate("Fixer", "100 %"))
        self.RefImgZoomComboBox.setItemText(4, _translate("Fixer", "200 %"))
        self.RefImgZoomslider.setToolTip(_translate("Fixer", "Zoom reference image"))
        self.PrevImagebutton.setToolTip(_translate("Fixer", "Previous Image"))
        self.NextImagebutton.setToolTip(_translate("Fixer", "Next Image"))
        self.ImageZoombutton.setToolTip(_translate("Fixer", "Enable zoom slider"))
        self.ImageZoomComboBox.setToolTip(_translate("Fixer", "Select current image zoom"))
        self.ImageZoomComboBox.setCurrentText(_translate("Fixer", "10 %"))
        self.ImageZoomComboBox.setItemText(0, _translate("Fixer", "10 %"))
        self.ImageZoomComboBox.setItemText(1, _translate("Fixer", "25 %"))
        self.ImageZoomComboBox.setItemText(2, _translate("Fixer", "50 %"))
        self.ImageZoomComboBox.setItemText(3, _translate("Fixer", "100 %"))
        self.ImageZoomComboBox.setItemText(4, _translate("Fixer", "200 %"))
        self.reloadImagebutton.setToolTip(_translate("Fixer", "Reload image"))
        self.ImportRefImgFilebutton.setToolTip(_translate("Fixer", "Import image from main window"))
        self.ExportImageFilebutton.setToolTip(_translate("Fixer", "Export image as..."))
        self.Image.setToolTip(_translate("Fixer", "Preview modified image"))
        self.ImageZoomslider.setToolTip(_translate("Fixer", "Zoom image"))
        self.menuFile.setTitle(_translate("Fixer", "File"))
        self.menuEdit.setTitle(_translate("Fixer", "Edit"))
        self.menuMorphology.setTitle(_translate("Fixer", "Morphology"))
        self.menuFill.setTitle(_translate("Fixer", "Fill"))
        self.menuView.setTitle(_translate("Fixer", "View"))
        self.menuHelp.setTitle(_translate("Fixer", "Help"))
        self.menuPrepare.setTitle(_translate("Fixer", "Prepflow"))
        self.dockOutput.setWindowTitle(_translate("Fixer", "     Output"))
        self.EditToolBar.setWindowTitle(_translate("Fixer", "Versify Text Tool Bar"))
        self.EditToolBar.setToolTip(_translate("Fixer", "Versify Text Tool Bar"))
        self.dockGlyphRef.setWindowTitle(_translate("Fixer", "Glyph Reference"))
        self.actionOpen_Image.setText(_translate("Fixer", "Open Image"))
        self.actionExtract_Glyphs.setText(_translate("Fixer", "GlyphTracer"))
        self.actionExtract_Glyphs.setToolTip(_translate("Fixer", "Extract and trace bitmap glyphs with GlyphTracer"))
        self.actionExtract_Glyphs.setStatusTip(_translate("Fixer", "Extracting and trace bitmap glyphs with GlyphTracer..."))
        self.actionFontForge.setText(_translate("Fixer", "FontForge"))
        self.actionFontForge.setToolTip(_translate("Fixer", "Edit current GlyphTracer sfd file in FontForge"))
        self.actionFontForge.setStatusTip(_translate("Fixer", "Editing current GlyphTracer sfd file in FontForge..."))
        self.actionPreferences.setText(_translate("Fixer", "Preferences"))
        self.actionOpen_Image_2.setText(_translate("Fixer", "Open Text"))
        self.actionSave_Image.setText(_translate("Fixer", "Save Image"))
        self.actionSave_As_Image.setText(_translate("Fixer", "Save As Image"))
        self.actionSave_Text.setText(_translate("Fixer", "Save Image"))
        self.actionSave_As_Text.setText(_translate("Fixer", "Save As Image"))
        self.actionSelect_Image.setText(_translate("Fixer", "Select Image"))
        self.actionSelect_Language_Model.setText(_translate("Fixer", "Select Language Model"))
        self.actionSelect_Fonts.setText(_translate("Fixer", "Select Fonts"))
        self.actionany.setText(_translate("Fixer", "any"))
        self.actionAny.setText(_translate("Fixer", "Any"))
        self.actionCreate_e_Sword_Bible_Module.setText(_translate("Fixer", "e-Sword Bible Module"))
        self.actionCreate_theWord_Bible_Module.setText(_translate("Fixer", "theWord Bible Module"))
        self.actionManual_Crop_Image_tb.setText(_translate("Fixer", "Manual Crop"))
        self.actionManual_Crop_Image_tb.setToolTip(_translate("Fixer", "Manually crop current tif image"))
        self.actionManual_Crop_Image_tb.setStatusTip(_translate("Fixer", "Manually cropping current tif image..."))
        self.actionEdit_Image_tb.setText(_translate("Fixer", "Gimp Image Editor"))
        self.actionEdit_Image_tb.setStatusTip(_translate("Fixer", "Editing image in Gimp..."))
        self.actionGimp.setText(_translate("Fixer", "Gimp"))
        self.actionOpen_Reference_Image.setText(_translate("Fixer", "Open Reference Text"))
        self.actionRotateRefImg_CW.setText(_translate("Fixer", "Rotate CW"))
        self.actionDeskewRefImg.setText(_translate("Fixer", "Deskew"))
        self.actionDespeckleRefImg.setText(_translate("Fixer", "Despeckle"))
        self.actionFlipRefImg.setText(_translate("Fixer", "Flip"))
        self.actionConvert.setText(_translate("Fixer", "Convert"))
        self.actionImport_Current_Image.setText(_translate("Fixer", "Import Reference Image"))
        self.actionExport_Image.setText(_translate("Fixer", "Export Image As"))
        self.actionThreshold.setText(_translate("Fixer", "Threshold"))
        self.actionOperator.setText(_translate("Fixer", "Operator"))
        self.actionSE.setText(_translate("Fixer", "SE"))
        self.actionkernal_x.setText(_translate("Fixer", "kernal(x)"))
        self.actionkernel_y.setText(_translate("Fixer", "kernel(y)"))
        self.actionIterations.setText(_translate("Fixer", "Iterations"))
        self.actionBoxes.setText(_translate("Fixer", "Boxer"))
        self.actionGlyph_Tracer.setText(_translate("Fixer", "Glyph Tracer"))
        self.actionPage_Segmentation.setText(_translate("Fixer", "Page Segmentation"))
        self.actionLanguage_Segmentation.setText(_translate("Fixer", "Language Segmentation"))
        self.actionLine_Segmentation.setText(_translate("Fixer", "Line Segmentation"))
        self.actionGlyph_Production.setText(_translate("Fixer", "Glyph Production"))
        self.actionFont_Production.setText(_translate("Fixer", "Font Production"))
        self.actionCropRefImg.setText(_translate("Fixer", "Crop"))
        self.actionBox_Production.setText(_translate("Fixer", "Box Production"))
        self.actionErase.setText(_translate("Fixer", "Erase"))
        self.actionFillBackground.setText(_translate("Fixer", "Background"))
        self.actionFillForeground.setText(_translate("Fixer", "Foreground"))
        self.actionFillTransparent.setText(_translate("Fixer", "Fill Transparent Areas"))
        self.actionFillSelection.setText(_translate("Fixer", "Selection"))
        self.actionRotateRefImg_CCW.setText(_translate("Fixer", "Rotate CCW"))
        self.actionDenoise.setText(_translate("Fixer", "Denoise"))
        self.actionDenoise.setToolTip(_translate("Fixer", "Denoise"))

import UI_Icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fixer = QtWidgets.QMainWindow()
    ui = Ui_Fixer()
    ui.setupUi(Fixer)
    Fixer.show()
    sys.exit(app.exec_())

