# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerUI/VariantRecorderDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RecorderDialog(object):
    def setupUi(self, RecorderDialog):
        RecorderDialog.setObjectName("RecorderDialog")
        RecorderDialog.setWindowModality(QtCore.Qt.NonModal)
        RecorderDialog.resize(562, 391)
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        RecorderDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RecorderDialog.setWindowIcon(icon)
        RecorderDialog.setSizeGripEnabled(True)
        RecorderDialog.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(RecorderDialog)
        self.buttonBox.setGeometry(QtCore.QRect(340, 350, 151, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Abort|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.VarWordSelCombo = QtWidgets.QComboBox(RecorderDialog)
        self.VarWordSelCombo.setGeometry(QtCore.QRect(20, 220, 231, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(11)
        self.VarWordSelCombo.setFont(font)
        self.VarWordSelCombo.setEditable(True)
        self.VarWordSelCombo.setCurrentText("")
        self.VarWordSelCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.VarWordSelCombo.setModelColumn(0)
        self.VarWordSelCombo.setObjectName("VarWordSelCombo")
        self.ReplaceWordlabel = QtWidgets.QLabel(RecorderDialog)
        self.ReplaceWordlabel.setGeometry(QtCore.QRect(310, 200, 231, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.ReplaceWordlabel.setFont(font)
        self.ReplaceWordlabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.ReplaceWordlabel.setObjectName("ReplaceWordlabel")
        self.VarWordlabel = QtWidgets.QLabel(RecorderDialog)
        self.VarWordlabel.setGeometry(QtCore.QRect(20, 200, 231, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.VarWordlabel.setFont(font)
        self.VarWordlabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.VarWordlabel.setObjectName("VarWordlabel")
        self.VariantCodeCombo = QtWidgets.QComboBox(RecorderDialog)
        self.VariantCodeCombo.setGeometry(QtCore.QRect(230, 270, 101, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.VariantCodeCombo.setFont(font)
        self.VariantCodeCombo.setObjectName("VariantCodeCombo")
        self.VariantCodeCombo.addItem("")
        self.VariantCodeCombo.addItem("")
        self.VariantCodeCombo.addItem("")
        self.VariantCodeCombo.addItem("")
        self.VariantCodeCombo.addItem("")
        self.VariantCodeCombo.addItem("")
        self.VariantCodeCombo.addItem("")
        self.VariantCodeCombo.addItem("")
        self.VariantCodeCombo.addItem("")
        self.VariantCodeCombo.addItem("")
        self.VariantCodeCombo.addItem("")
        self.Preservedlabel = QtWidgets.QLabel(RecorderDialog)
        self.Preservedlabel.setGeometry(QtCore.QRect(160, 250, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Preservedlabel.setFont(font)
        self.Preservedlabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.Preservedlabel.setObjectName("Preservedlabel")
        self.ReplaceWordSelCombo = QtWidgets.QComboBox(RecorderDialog)
        self.ReplaceWordSelCombo.setGeometry(QtCore.QRect(310, 220, 231, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(11)
        self.ReplaceWordSelCombo.setFont(font)
        self.ReplaceWordSelCombo.setEditable(True)
        self.ReplaceWordSelCombo.setCurrentText("")
        self.ReplaceWordSelCombo.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.ReplaceWordSelCombo.setModelColumn(0)
        self.ReplaceWordSelCombo.setObjectName("ReplaceWordSelCombo")
        self.VariantCodeLabel = QtWidgets.QLabel(RecorderDialog)
        self.VariantCodeLabel.setGeometry(QtCore.QRect(230, 250, 101, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.VariantCodeLabel.setFont(font)
        self.VariantCodeLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.VariantCodeLabel.setObjectName("VariantCodeLabel")
        self.RefNormWordlineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.RefNormWordlineEdit.setGeometry(QtCore.QRect(20, 170, 231, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.RefNormWordlineEdit.setFont(font)
        self.RefNormWordlineEdit.setObjectName("RefNormWordlineEdit")
        self.VerseNormWordlineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.VerseNormWordlineEdit.setGeometry(QtCore.QRect(310, 170, 231, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.VerseNormWordlineEdit.setFont(font)
        self.VerseNormWordlineEdit.setObjectName("VerseNormWordlineEdit")
        self.VerseNormWordlabel = QtWidgets.QLabel(RecorderDialog)
        self.VerseNormWordlabel.setGeometry(QtCore.QRect(310, 150, 231, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.VerseNormWordlabel.setFont(font)
        self.VerseNormWordlabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.VerseNormWordlabel.setObjectName("VerseNormWordlabel")
        self.RefNormWordlabel = QtWidgets.QLabel(RecorderDialog)
        self.RefNormWordlabel.setGeometry(QtCore.QRect(20, 150, 231, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.RefNormWordlabel.setFont(font)
        self.RefNormWordlabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.RefNormWordlabel.setObjectName("RefNormWordlabel")
        self.RefTextlabel = QtWidgets.QLabel(RecorderDialog)
        self.RefTextlabel.setGeometry(QtCore.QRect(10, 30, 241, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(12)
        self.RefTextlabel.setFont(font)
        self.RefTextlabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.RefTextlabel.setObjectName("RefTextlabel")
        self.RefWordNumlineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.RefWordNumlineEdit.setGeometry(QtCore.QRect(220, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.RefWordNumlineEdit.setFont(font)
        self.RefWordNumlineEdit.setObjectName("RefWordNumlineEdit")
        self.VerseWordNumlineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.VerseWordNumlineEdit.setGeometry(QtCore.QRect(510, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.VerseWordNumlineEdit.setFont(font)
        self.VerseWordNumlineEdit.setObjectName("VerseWordNumlineEdit")
        self.RefWordNumlabel = QtWidgets.QLabel(RecorderDialog)
        self.RefWordNumlabel.setGeometry(QtCore.QRect(220, 60, 31, 16))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.RefWordNumlabel.setFont(font)
        self.RefWordNumlabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.RefWordNumlabel.setObjectName("RefWordNumlabel")
        self.VerseTextlabel = QtWidgets.QLabel(RecorderDialog)
        self.VerseTextlabel.setGeometry(QtCore.QRect(310, 30, 231, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(12)
        self.VerseTextlabel.setFont(font)
        self.VerseTextlabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.VerseTextlabel.setObjectName("VerseTextlabel")
        self.Refcolon = QtWidgets.QLabel(RecorderDialog)
        self.Refcolon.setGeometry(QtCore.QRect(150, 70, 20, 31))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Refcolon.setFont(font)
        self.Refcolon.setAlignment(QtCore.Qt.AlignCenter)
        self.Refcolon.setObjectName("Refcolon")
        self.RefBooklineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.RefBooklineEdit.setGeometry(QtCore.QRect(70, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.RefBooklineEdit.setFont(font)
        self.RefBooklineEdit.setObjectName("RefBooklineEdit")
        self.RefChapterlineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.RefChapterlineEdit.setGeometry(QtCore.QRect(120, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.RefChapterlineEdit.setFont(font)
        self.RefChapterlineEdit.setObjectName("RefChapterlineEdit")
        self.RefVerselineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.RefVerselineEdit.setGeometry(QtCore.QRect(170, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.RefVerselineEdit.setFont(font)
        self.RefVerselineEdit.setObjectName("RefVerselineEdit")
        self.RefLinelineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.RefLinelineEdit.setGeometry(QtCore.QRect(20, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.RefLinelineEdit.setFont(font)
        self.RefLinelineEdit.setObjectName("RefLinelineEdit")
        self.RefLinelabel = QtWidgets.QLabel(RecorderDialog)
        self.RefLinelabel.setGeometry(QtCore.QRect(20, 60, 31, 16))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.RefLinelabel.setFont(font)
        self.RefLinelabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.RefLinelabel.setObjectName("RefLinelabel")
        self.RefVerselabel = QtWidgets.QLabel(RecorderDialog)
        self.RefVerselabel.setGeometry(QtCore.QRect(170, 60, 31, 16))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.RefVerselabel.setFont(font)
        self.RefVerselabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.RefVerselabel.setObjectName("RefVerselabel")
        self.RefBooklabel = QtWidgets.QLabel(RecorderDialog)
        self.RefBooklabel.setGeometry(QtCore.QRect(70, 60, 31, 16))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.RefBooklabel.setFont(font)
        self.RefBooklabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.RefBooklabel.setObjectName("RefBooklabel")
        self.RefChapterlabel = QtWidgets.QLabel(RecorderDialog)
        self.RefChapterlabel.setGeometry(QtCore.QRect(110, 60, 51, 16))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.RefChapterlabel.setFont(font)
        self.RefChapterlabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.RefChapterlabel.setObjectName("RefChapterlabel")
        self.VerseChapterlineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.VerseChapterlineEdit.setGeometry(QtCore.QRect(410, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.VerseChapterlineEdit.setFont(font)
        self.VerseChapterlineEdit.setObjectName("VerseChapterlineEdit")
        self.VerseBooklabel = QtWidgets.QLabel(RecorderDialog)
        self.VerseBooklabel.setGeometry(QtCore.QRect(360, 60, 31, 16))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.VerseBooklabel.setFont(font)
        self.VerseBooklabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.VerseBooklabel.setObjectName("VerseBooklabel")
        self.VerseLinelineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.VerseLinelineEdit.setGeometry(QtCore.QRect(310, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.VerseLinelineEdit.setFont(font)
        self.VerseLinelineEdit.setObjectName("VerseLinelineEdit")
        self.VerseVerselineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.VerseVerselineEdit.setGeometry(QtCore.QRect(460, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.VerseVerselineEdit.setFont(font)
        self.VerseVerselineEdit.setObjectName("VerseVerselineEdit")
        self.VerseBooklineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.VerseBooklineEdit.setGeometry(QtCore.QRect(360, 80, 31, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.VerseBooklineEdit.setFont(font)
        self.VerseBooklineEdit.setObjectName("VerseBooklineEdit")
        self.VersChapterlabel = QtWidgets.QLabel(RecorderDialog)
        self.VersChapterlabel.setGeometry(QtCore.QRect(400, 60, 51, 16))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.VersChapterlabel.setFont(font)
        self.VersChapterlabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.VersChapterlabel.setObjectName("VersChapterlabel")
        self.VerseVerselabel = QtWidgets.QLabel(RecorderDialog)
        self.VerseVerselabel.setGeometry(QtCore.QRect(460, 60, 31, 16))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.VerseVerselabel.setFont(font)
        self.VerseVerselabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.VerseVerselabel.setObjectName("VerseVerselabel")
        self.Versecolon = QtWidgets.QLabel(RecorderDialog)
        self.Versecolon.setGeometry(QtCore.QRect(440, 70, 20, 31))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Versecolon.setFont(font)
        self.Versecolon.setAlignment(QtCore.Qt.AlignCenter)
        self.Versecolon.setObjectName("Versecolon")
        self.VerseLinelabel = QtWidgets.QLabel(RecorderDialog)
        self.VerseLinelabel.setGeometry(QtCore.QRect(310, 60, 31, 16))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.VerseLinelabel.setFont(font)
        self.VerseLinelabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.VerseLinelabel.setObjectName("VerseLinelabel")
        self.VerseWordNumlabel = QtWidgets.QLabel(RecorderDialog)
        self.VerseWordNumlabel.setGeometry(QtCore.QRect(510, 60, 31, 16))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.VerseWordNumlabel.setFont(font)
        self.VerseWordNumlabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.VerseWordNumlabel.setObjectName("VerseWordNumlabel")
        self.Correctedlabel = QtWidgets.QLabel(RecorderDialog)
        self.Correctedlabel.setGeometry(QtCore.QRect(350, 250, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Correctedlabel.setFont(font)
        self.Correctedlabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.Correctedlabel.setObjectName("Correctedlabel")
        self.RefWordlineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.RefWordlineEdit.setGeometry(QtCore.QRect(20, 120, 231, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.RefWordlineEdit.setFont(font)
        self.RefWordlineEdit.setObjectName("RefWordlineEdit")
        self.VerseWordlineEdit = QtWidgets.QLineEdit(RecorderDialog)
        self.VerseWordlineEdit.setGeometry(QtCore.QRect(310, 120, 231, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.VerseWordlineEdit.setFont(font)
        self.VerseWordlineEdit.setObjectName("VerseWordlineEdit")
        self.VerseWordlabel = QtWidgets.QLabel(RecorderDialog)
        self.VerseWordlabel.setGeometry(QtCore.QRect(310, 100, 231, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.VerseWordlabel.setFont(font)
        self.VerseWordlabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.VerseWordlabel.setObjectName("VerseWordlabel")
        self.RefWordlabel = QtWidgets.QLabel(RecorderDialog)
        self.RefWordlabel.setGeometry(QtCore.QRect(20, 100, 231, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.RefWordlabel.setFont(font)
        self.RefWordlabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.RefWordlabel.setObjectName("RefWordlabel")
        self.PreservedcheckBox = QtWidgets.QCheckBox(RecorderDialog)
        self.PreservedcheckBox.setGeometry(QtCore.QRect(180, 270, 16, 21))
        self.PreservedcheckBox.setText("")
        self.PreservedcheckBox.setObjectName("PreservedcheckBox")
        self.CorrectedcheckBox = QtWidgets.QCheckBox(RecorderDialog)
        self.CorrectedcheckBox.setGeometry(QtCore.QRect(370, 270, 16, 21))
        self.CorrectedcheckBox.setText("")
        self.CorrectedcheckBox.setObjectName("CorrectedcheckBox")
        self.ExistingradioButton = QtWidgets.QRadioButton(RecorderDialog)
        self.ExistingradioButton.setGeometry(QtCore.QRect(190, 350, 71, 23))
        self.ExistingradioButton.setChecked(True)
        self.ExistingradioButton.setObjectName("ExistingradioButton")
        self.NewradioButton = QtWidgets.QRadioButton(RecorderDialog)
        self.NewradioButton.setGeometry(QtCore.QRect(270, 350, 51, 23))
        self.NewradioButton.setChecked(False)
        self.NewradioButton.setObjectName("NewradioButton")
        self.ClosepushButton = QtWidgets.QPushButton(RecorderDialog)
        self.ClosepushButton.setGeometry(QtCore.QRect(80, 350, 89, 20))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ClosepushButton.setIcon(icon1)
        self.ClosepushButton.setObjectName("ClosepushButton")

        self.retranslateUi(RecorderDialog)
        self.buttonBox.accepted.connect(RecorderDialog.accept)
        self.buttonBox.rejected.connect(RecorderDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(RecorderDialog)

    def retranslateUi(self, RecorderDialog):
        _translate = QtCore.QCoreApplication.translate
        RecorderDialog.setWindowTitle(_translate("RecorderDialog", "Variant Recorder"))
        self.VarWordSelCombo.setToolTip(_translate("RecorderDialog", "Select variant word"))
        self.ReplaceWordlabel.setToolTip(_translate("RecorderDialog", "Select OCR LSTM model"))
        self.ReplaceWordlabel.setText(_translate("RecorderDialog", "Replace Verse Word With"))
        self.VarWordlabel.setToolTip(_translate("RecorderDialog", "Variant word"))
        self.VarWordlabel.setText(_translate("RecorderDialog", "Variant Word"))
        self.VariantCodeCombo.setToolTip(_translate("RecorderDialog", "Select variant code"))
        self.VariantCodeCombo.setItemText(0, _translate("RecorderDialog", "None"))
        self.VariantCodeCombo.setItemText(1, _translate("RecorderDialog", "Addition-A"))
        self.VariantCodeCombo.setItemText(2, _translate("RecorderDialog", "Diacritic-D"))
        self.VariantCodeCombo.setItemText(3, _translate("RecorderDialog", "RMAC-M"))
        self.VariantCodeCombo.setItemText(4, _translate("RecorderDialog", "Omission-O"))
        self.VariantCodeCombo.setItemText(5, _translate("RecorderDialog", "Punctuation-P"))
        self.VariantCodeCombo.setItemText(6, _translate("RecorderDialog", "Strong\'s-S"))
        self.VariantCodeCombo.setItemText(7, _translate("RecorderDialog", "Spelling-X"))
        self.VariantCodeCombo.setItemText(8, _translate("RecorderDialog", "Spacing-Y"))
        self.VariantCodeCombo.setItemText(9, _translate("RecorderDialog", "Printing-Z"))
        self.VariantCodeCombo.setItemText(10, _translate("RecorderDialog", "Translation-T"))
        self.Preservedlabel.setToolTip(_translate("RecorderDialog", "Preserved"))
        self.Preservedlabel.setText(_translate("RecorderDialog", "Preserved"))
        self.ReplaceWordSelCombo.setToolTip(_translate("RecorderDialog", "Select replacement word"))
        self.VariantCodeLabel.setText(_translate("RecorderDialog", "Variance Key"))
        self.VerseNormWordlabel.setToolTip(_translate("RecorderDialog", "Select OCR LSTM model"))
        self.VerseNormWordlabel.setText(_translate("RecorderDialog", "Verse Normalized Word"))
        self.RefNormWordlabel.setToolTip(_translate("RecorderDialog", "Select OCR LSTM model"))
        self.RefNormWordlabel.setText(_translate("RecorderDialog", "Reference Normalized Word"))
        self.RefTextlabel.setToolTip(_translate("RecorderDialog", "Select OCR LSTM model"))
        self.RefTextlabel.setText(_translate("RecorderDialog", "Reference Text"))
        self.RefWordNumlabel.setToolTip(_translate("RecorderDialog", "Select OCR LSTM model"))
        self.RefWordNumlabel.setText(_translate("RecorderDialog", "Word"))
        self.VerseTextlabel.setToolTip(_translate("RecorderDialog", "Select OCR LSTM model"))
        self.VerseTextlabel.setText(_translate("RecorderDialog", "Verse Text"))
        self.Refcolon.setText(_translate("RecorderDialog", ":"))
        self.RefLinelabel.setText(_translate("RecorderDialog", "Line"))
        self.RefVerselabel.setText(_translate("RecorderDialog", "Verse"))
        self.RefBooklabel.setText(_translate("RecorderDialog", "Book"))
        self.RefChapterlabel.setText(_translate("RecorderDialog", "Chapter"))
        self.VerseBooklabel.setText(_translate("RecorderDialog", "Book"))
        self.VersChapterlabel.setText(_translate("RecorderDialog", "Chapter"))
        self.VerseVerselabel.setText(_translate("RecorderDialog", "Verse"))
        self.Versecolon.setText(_translate("RecorderDialog", ":"))
        self.VerseLinelabel.setText(_translate("RecorderDialog", "Line"))
        self.VerseWordNumlabel.setToolTip(_translate("RecorderDialog", "Select OCR LSTM model"))
        self.VerseWordNumlabel.setText(_translate("RecorderDialog", "Word"))
        self.Correctedlabel.setToolTip(_translate("RecorderDialog", "Preserved"))
        self.Correctedlabel.setText(_translate("RecorderDialog", "Corrected"))
        self.VerseWordlabel.setToolTip(_translate("RecorderDialog", "Select OCR LSTM model"))
        self.VerseWordlabel.setText(_translate("RecorderDialog", "Verse Word"))
        self.RefWordlabel.setToolTip(_translate("RecorderDialog", "Select OCR LSTM model"))
        self.RefWordlabel.setText(_translate("RecorderDialog", "Reference Word"))
        self.ExistingradioButton.setText(_translate("RecorderDialog", "Existing"))
        self.NewradioButton.setText(_translate("RecorderDialog", "New"))
        self.ClosepushButton.setText(_translate("RecorderDialog", "Close"))

import UI_Icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RecorderDialog = QtWidgets.QDialog()
    ui = Ui_RecorderDialog()
    ui.setupUi(RecorderDialog)
    RecorderDialog.show()
    sys.exit(app.exec_())

