# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/max/Projects/BiblionOCR/ViewController/Application/0-MainUI/QtDesignerUI/MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainUI(object):
    def setupUi(self, MainUI):
        MainUI.setObjectName("MainUI")
        MainUI.setEnabled(True)
        MainUI.resize(1319, 950)
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainUI.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionReader2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainUI.setWindowIcon(icon)
        MainUI.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainUI)
        self.centralwidget.setObjectName("centralwidget")
        self.ImagescrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.ImagescrollArea.setGeometry(QtCore.QRect(20, 30, 551, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollArea.sizePolicy().hasHeightForWidth())
        self.ImagescrollArea.setSizePolicy(sizePolicy)
        self.ImagescrollArea.setMinimumSize(QtCore.QSize(501, 600))
        self.ImagescrollArea.setWidgetResizable(True)
        self.ImagescrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ImagescrollArea.setObjectName("ImagescrollArea")
        self.ImagescrollAreaWidgetContents = QtWidgets.QWidget()
        self.ImagescrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 3200, 4800))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.ImagescrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.ImagescrollAreaWidgetContents.setMinimumSize(QtCore.QSize(3200, 4800))
        self.ImagescrollAreaWidgetContents.setSizeIncrement(QtCore.QSize(0, 0))
        self.ImagescrollAreaWidgetContents.setBaseSize(QtCore.QSize(520, 700))
        self.ImagescrollAreaWidgetContents.setObjectName("ImagescrollAreaWidgetContents")
        self.Image = QtWidgets.QLabel(self.ImagescrollAreaWidgetContents)
        self.Image.setGeometry(QtCore.QRect(0, 2, 6800, 9600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Image.sizePolicy().hasHeightForWidth())
        self.Image.setSizePolicy(sizePolicy)
        self.Image.setMinimumSize(QtCore.QSize(3400, 4800))
        self.Image.setBaseSize(QtCore.QSize(520, 700))
        self.Image.setText("")
        self.Image.setScaledContents(False)
        self.Image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Image.setObjectName("Image")
        self.ImagescrollArea.setWidget(self.ImagescrollAreaWidgetContents)
        self.OpenImageFilebutton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenImageFilebutton.setGeometry(QtCore.QRect(20, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.OpenImageFilebutton.setFont(font)
        self.OpenImageFilebutton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenImageFilebutton.setIcon(icon1)
        self.OpenImageFilebutton.setObjectName("OpenImageFilebutton")
        self.ImageLe = QtWidgets.QLineEdit(self.centralwidget)
        self.ImageLe.setGeometry(QtCore.QRect(330, 0, 241, 25))
        self.ImageLe.setObjectName("ImageLe")
        self.EditCorrectedTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.EditCorrectedTextbutton.setGeometry(QtCore.QRect(980, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.EditCorrectedTextbutton.setFont(font)
        self.EditCorrectedTextbutton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-document-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EditCorrectedTextbutton.setIcon(icon2)
        self.EditCorrectedTextbutton.setObjectName("EditCorrectedTextbutton")
        self.SaveAsOCRCorrTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveAsOCRCorrTextbutton.setGeometry(QtCore.QRect(1250, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveAsOCRCorrTextbutton.setFont(font)
        self.SaveAsOCRCorrTextbutton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk-rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveAsOCRCorrTextbutton.setIcon(icon3)
        self.SaveAsOCRCorrTextbutton.setObjectName("SaveAsOCRCorrTextbutton")
        self.SaveOCRCorrTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveOCRCorrTextbutton.setGeometry(QtCore.QRect(1280, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveOCRCorrTextbutton.setFont(font)
        self.SaveOCRCorrTextbutton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveOCRCorrTextbutton.setIcon(icon4)
        self.SaveOCRCorrTextbutton.setObjectName("SaveOCRCorrTextbutton")
        self.OCRText = QtWidgets.QTextEdit(self.centralwidget)
        self.OCRText.setGeometry(QtCore.QRect(730, 30, 570, 601))
        self.OCRText.setMinimumSize(QtCore.QSize(540, 600))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OCRText.setFont(font)
        self.OCRText.setObjectName("OCRText")
        self.Writerbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Writerbutton.setGeometry(QtCore.QRect(1180, 0, 21, 25))
        self.Writerbutton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/libreoffice-writer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Writerbutton.setIcon(icon5)
        self.Writerbutton.setObjectName("Writerbutton")
        self.Calcbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Calcbutton.setGeometry(QtCore.QRect(1210, 0, 21, 25))
        self.Calcbutton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/libreoffice-calc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Calcbutton.setIcon(icon6)
        self.Calcbutton.setObjectName("Calcbutton")
        self.reloadTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.reloadTextbutton.setGeometry(QtCore.QRect(710, 0, 21, 25))
        self.reloadTextbutton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/reload-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadTextbutton.setIcon(icon7)
        self.reloadTextbutton.setObjectName("reloadTextbutton")
        self.reloadImagebutton = QtWidgets.QPushButton(self.centralwidget)
        self.reloadImagebutton.setGeometry(QtCore.QRect(570, 0, 21, 25))
        self.reloadImagebutton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadImagebutton.setIcon(icon8)
        self.reloadImagebutton.setObjectName("reloadImagebutton")
        self.MyPixlerbutton = QtWidgets.QPushButton(self.centralwidget)
        self.MyPixlerbutton.setGeometry(QtCore.QRect(60, 0, 21, 25))
        self.MyPixlerbutton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Icons/preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MyPixlerbutton.setIcon(icon9)
        self.MyPixlerbutton.setObjectName("MyPixlerbutton")
        self.Deskewbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Deskewbutton.setGeometry(QtCore.QRect(90, 0, 21, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Deskewbutton.setFont(font)
        self.Deskewbutton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew_clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Deskewbutton.setIcon(icon10)
        self.Deskewbutton.setObjectName("Deskewbutton")
        self.PrevImgButton = QtWidgets.QPushButton(self.centralwidget)
        self.PrevImgButton.setGeometry(QtCore.QRect(270, 0, 21, 25))
        self.PrevImgButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/Icons/back_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PrevImgButton.setIcon(icon11)
        self.PrevImgButton.setObjectName("PrevImgButton")
        self.NextImgButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextImgButton.setGeometry(QtCore.QRect(300, 0, 21, 25))
        self.NextImgButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icons/Icons/forward_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextImgButton.setIcon(icon12)
        self.NextImgButton.setObjectName("NextImgButton")
        self.PrevTxtButton = QtWidgets.QPushButton(self.centralwidget)
        self.PrevTxtButton.setGeometry(QtCore.QRect(1010, 0, 21, 25))
        self.PrevTxtButton.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Icons/Icons/back_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PrevTxtButton.setIcon(icon13)
        self.PrevTxtButton.setObjectName("PrevTxtButton")
        self.NextTxtButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextTxtButton.setGeometry(QtCore.QRect(1040, 0, 21, 25))
        self.NextTxtButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Icons/Icons/forward_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextTxtButton.setIcon(icon14)
        self.NextTxtButton.setObjectName("NextTxtButton")
        self.BothNextButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothNextButton.setGeometry(QtCore.QRect(680, 0, 21, 25))
        self.BothNextButton.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Icons/Icons/ui-button-navigation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothNextButton.setIcon(icon15)
        self.BothNextButton.setObjectName("BothNextButton")
        self.BothPrevButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothPrevButton.setGeometry(QtCore.QRect(600, 0, 21, 25))
        self.BothPrevButton.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Icons/Icons/ui-button-navigation-back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothPrevButton.setIcon(icon16)
        self.BothPrevButton.setObjectName("BothPrevButton")
        self.BothLoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothLoadButton.setEnabled(True)
        self.BothLoadButton.setGeometry(QtCore.QRect(640, 0, 21, 25))
        self.BothLoadButton.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Icons/Icons/documents1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothLoadButton.setIcon(icon17)
        self.BothLoadButton.setObjectName("BothLoadButton")
        self.OCRgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.OCRgroupBox.setGeometry(QtCore.QRect(570, 20, 161, 161))
        self.OCRgroupBox.setTitle("")
        self.OCRgroupBox.setObjectName("OCRgroupBox")
        self.OCRlangComboBox = QtWidgets.QComboBox(self.OCRgroupBox)
        self.OCRlangComboBox.setGeometry(QtCore.QRect(20, 80, 121, 25))
        self.OCRlangComboBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OCRlangComboBox.setEditable(False)
        self.OCRlangComboBox.setObjectName("OCRlangComboBox")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlanglabel = QtWidgets.QLabel(self.OCRgroupBox)
        self.OCRlanglabel.setGeometry(QtCore.QRect(40, 60, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OCRlanglabel.setFont(font)
        self.OCRlanglabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OCRlanglabel.setObjectName("OCRlanglabel")
        self.OCRModellabel = QtWidgets.QLabel(self.OCRgroupBox)
        self.OCRModellabel.setGeometry(QtCore.QRect(30, 110, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OCRModellabel.setFont(font)
        self.OCRModellabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OCRModellabel.setObjectName("OCRModellabel")
        self.OCRModelComboBox = QtWidgets.QComboBox(self.OCRgroupBox)
        self.OCRModelComboBox.setGeometry(QtCore.QRect(50, 130, 61, 25))
        self.OCRModelComboBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OCRModelComboBox.setEditable(False)
        self.OCRModelComboBox.setObjectName("OCRModelComboBox")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRbutton = QtWidgets.QPushButton(self.OCRgroupBox)
        self.OCRbutton.setGeometry(QtCore.QRect(50, 20, 61, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.OCRbutton.setFont(font)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Icons/Icons/ocr3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OCRbutton.setIcon(icon18)
        self.OCRbutton.setObjectName("OCRbutton")
        self.TextLE = QtWidgets.QLineEdit(self.centralwidget)
        self.TextLE.setGeometry(QtCore.QRect(730, 0, 241, 25))
        self.TextLE.setObjectName("TextLE")
        self.SessiongroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.SessiongroupBox.setGeometry(QtCore.QRect(570, 180, 161, 51))
        self.SessiongroupBox.setTitle("")
        self.SessiongroupBox.setObjectName("SessiongroupBox")
        self.booklabel = QtWidgets.QLabel(self.SessiongroupBox)
        self.booklabel.setGeometry(QtCore.QRect(50, 0, 61, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.booklabel.setFont(font)
        self.booklabel.setAlignment(QtCore.Qt.AlignCenter)
        self.booklabel.setObjectName("booklabel")
        self.bookComboBox = QtWidgets.QComboBox(self.SessiongroupBox)
        self.bookComboBox.setGeometry(QtCore.QRect(50, 20, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bookComboBox.setFont(font)
        self.bookComboBox.setEditable(True)
        self.bookComboBox.setObjectName("bookComboBox")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.TextgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.TextgroupBox.setGeometry(QtCore.QRect(570, 230, 161, 101))
        self.TextgroupBox.setTitle("")
        self.TextgroupBox.setObjectName("TextgroupBox")
        self.fontlabel = QtWidgets.QLabel(self.TextgroupBox)
        self.fontlabel.setGeometry(QtCore.QRect(70, 0, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fontlabel.setFont(font)
        self.fontlabel.setObjectName("fontlabel")
        self.fontSizelabel = QtWidgets.QLabel(self.TextgroupBox)
        self.fontSizelabel.setGeometry(QtCore.QRect(60, 50, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fontSizelabel.setFont(font)
        self.fontSizelabel.setObjectName("fontSizelabel")
        self.fontSizeBox = QtWidgets.QSpinBox(self.TextgroupBox)
        self.fontSizeBox.setGeometry(QtCore.QRect(57, 70, 51, 26))
        self.fontSizeBox.setAlignment(QtCore.Qt.AlignCenter)
        self.fontSizeBox.setMinimum(6)
        self.fontSizeBox.setMaximum(30)
        self.fontSizeBox.setProperty("value", 20)
        self.fontSizeBox.setObjectName("fontSizeBox")
        self.fontComboBox = QtWidgets.QFontComboBox(self.TextgroupBox)
        self.fontComboBox.setGeometry(QtCore.QRect(10, 20, 141, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fontComboBox.setFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.ZoomComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ZoomComboBox.setGeometry(QtCore.QRect(170, 0, 81, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZoomComboBox.sizePolicy().hasHeightForWidth())
        self.ZoomComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ZoomComboBox.setFont(font)
        self.ZoomComboBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ZoomComboBox.setEditable(True)
        self.ZoomComboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.ZoomComboBox.setObjectName("ZoomComboBox")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.Zoombutton = QtWidgets.QPushButton(self.centralwidget)
        self.Zoombutton.setEnabled(True)
        self.Zoombutton.setGeometry(QtCore.QRect(150, 0, 21, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Zoombutton.setFont(font)
        self.Zoombutton.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/Icons/Icons/image-resize1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Zoombutton.setIcon(icon19)
        self.Zoombutton.setObjectName("Zoombutton")
        self.Cropbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Cropbutton.setGeometry(QtCore.QRect(120, 0, 21, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Cropbutton.setFont(font)
        self.Cropbutton.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/Icons/Icons/image-grey-crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cropbutton.setIcon(icon20)
        self.Cropbutton.setObjectName("Cropbutton")
        self.LHslider = QtWidgets.QSlider(self.centralwidget)
        self.LHslider.setEnabled(False)
        self.LHslider.setGeometry(QtCore.QRect(1090, 30, 21, 161))
        self.LHslider.setMinimum(100)
        self.LHslider.setMaximum(200)
        self.LHslider.setSingleStep(2)
        self.LHslider.setPageStep(10)
        self.LHslider.setProperty("value", 144)
        self.LHslider.setSliderPosition(144)
        self.LHslider.setOrientation(QtCore.Qt.Vertical)
        self.LHslider.setInvertedAppearance(True)
        self.LHslider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.LHslider.setObjectName("LHslider")
        self.LHlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.LHlineEdit.setGeometry(QtCore.QRect(1100, 0, 31, 25))
        self.LHlineEdit.setMaxLength(32767)
        self.LHlineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.LHlineEdit.setClearButtonEnabled(False)
        self.LHlineEdit.setObjectName("LHlineEdit")
        self.LHDialogtbutton = QtWidgets.QPushButton(self.centralwidget)
        self.LHDialogtbutton.setEnabled(True)
        self.LHDialogtbutton.setGeometry(QtCore.QRect(1070, 0, 31, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.LHDialogtbutton.setFont(font)
        self.LHDialogtbutton.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-line-spacing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LHDialogtbutton.setIcon(icon21)
        self.LHDialogtbutton.setObjectName("LHDialogtbutton")
        self.Zoomslider = QtWidgets.QSlider(self.centralwidget)
        self.Zoomslider.setEnabled(False)
        self.Zoomslider.setGeometry(QtCore.QRect(190, 30, 21, 161))
        self.Zoomslider.setMinimum(10)
        self.Zoomslider.setMaximum(100)
        self.Zoomslider.setSingleStep(1)
        self.Zoomslider.setPageStep(20)
        self.Zoomslider.setProperty("value", 25)
        self.Zoomslider.setSliderPosition(25)
        self.Zoomslider.setOrientation(QtCore.Qt.Vertical)
        self.Zoomslider.setInvertedAppearance(True)
        self.Zoomslider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Zoomslider.setObjectName("Zoomslider")
        self.MyWriterbutton = QtWidgets.QPushButton(self.centralwidget)
        self.MyWriterbutton.setGeometry(QtCore.QRect(1150, 0, 21, 25))
        self.MyWriterbutton.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/Icons/Icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MyWriterbutton.setIcon(icon22)
        self.MyWriterbutton.setObjectName("MyWriterbutton")
        self.FindReplacebutton = QtWidgets.QPushButton(self.centralwidget)
        self.FindReplacebutton.setGeometry(QtCore.QRect(590, 340, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.FindReplacebutton.setFont(font)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/Icons/Icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FindReplacebutton.setIcon(icon23)
        self.FindReplacebutton.setObjectName("FindReplacebutton")
        MainUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1319, 20))
        self.menubar.setObjectName("menubar")
        self.menuPre_Process = QtWidgets.QMenu(self.menubar)
        self.menuPre_Process.setObjectName("menuPre_Process")
        self.menuExtract_pdf = QtWidgets.QMenu(self.menuPre_Process)
        self.menuExtract_pdf.setIcon(icon1)
        self.menuExtract_pdf.setObjectName("menuExtract_pdf")
        self.menuPrepare = QtWidgets.QMenu(self.menuPre_Process)
        self.menuPrepare.setObjectName("menuPrepare")
        self.menuGreekDR = QtWidgets.QMenu(self.menuPrepare)
        self.menuGreekDR.setObjectName("menuGreekDR")
        self.menuLatinDR = QtWidgets.QMenu(self.menuPrepare)
        self.menuLatinDR.setObjectName("menuLatinDR")
        self.menuTraining = QtWidgets.QMenu(self.menubar)
        self.menuTraining.setObjectName("menuTraining")
        self.menuGround_Truth = QtWidgets.QMenu(self.menuTraining)
        self.menuGround_Truth.setObjectName("menuGround_Truth")
        self.menuGreekGT = QtWidgets.QMenu(self.menuGround_Truth)
        self.menuGreekGT.setObjectName("menuGreekGT")
        self.menuGreek_Image_Lines = QtWidgets.QMenu(self.menuGreekGT)
        self.menuGreek_Image_Lines.setObjectName("menuGreek_Image_Lines")
        self.menuGreek_Text_Lines = QtWidgets.QMenu(self.menuGreekGT)
        self.menuGreek_Text_Lines.setObjectName("menuGreek_Text_Lines")
        self.menuLatinGT = QtWidgets.QMenu(self.menuGround_Truth)
        self.menuLatinGT.setObjectName("menuLatinGT")
        self.menuLatin_Image_Lines = QtWidgets.QMenu(self.menuLatinGT)
        self.menuLatin_Image_Lines.setObjectName("menuLatin_Image_Lines")
        self.menuLatin_Text_Lines = QtWidgets.QMenu(self.menuLatinGT)
        self.menuLatin_Text_Lines.setObjectName("menuLatin_Text_Lines")
        self.menuOCR = QtWidgets.QMenu(self.menubar)
        self.menuOCR.setObjectName("menuOCR")
        self.menuSelect_Language = QtWidgets.QMenu(self.menuOCR)
        self.menuSelect_Language.setObjectName("menuSelect_Language")
        self.menuPost_Process = QtWidgets.QMenu(self.menubar)
        self.menuPost_Process.setObjectName("menuPost_Process")
        self.menuModules = QtWidgets.QMenu(self.menuPost_Process)
        self.menuModules.setObjectName("menuModules")
        self.menuGreek = QtWidgets.QMenu(self.menuModules)
        self.menuGreek.setObjectName("menuGreek")
        self.menuType_Here = QtWidgets.QMenu(self.menuModules)
        self.menuType_Here.setObjectName("menuType_Here")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuGlyphs = QtWidgets.QMenu(self.menubar)
        self.menuGlyphs.setObjectName("menuGlyphs")
        self.menuIndex_Images = QtWidgets.QMenu(self.menuGlyphs)
        self.menuIndex_Images.setObjectName("menuIndex_Images")
        self.menuGround_Truth_2 = QtWidgets.QMenu(self.menubar)
        self.menuGround_Truth_2.setObjectName("menuGround_Truth_2")
        self.menuUpdate_Wordlists = QtWidgets.QMenu(self.menuGround_Truth_2)
        self.menuUpdate_Wordlists.setObjectName("menuUpdate_Wordlists")
        self.menuSetup_Training = QtWidgets.QMenu(self.menuGround_Truth_2)
        self.menuSetup_Training.setObjectName("menuSetup_Training")
        MainUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainUI)
        self.statusbar.setObjectName("statusbar")
        MainUI.setStatusBar(self.statusbar)
        self.ExtractPagesToolBar = QtWidgets.QToolBar(MainUI)
        self.ExtractPagesToolBar.setObjectName("ExtractPagesToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.ExtractPagesToolBar)
        self.ConvertPagesToolBar = QtWidgets.QToolBar(MainUI)
        self.ConvertPagesToolBar.setObjectName("ConvertPagesToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.ConvertPagesToolBar)
        self.GreekImagePagesToolBar = QtWidgets.QToolBar(MainUI)
        self.GreekImagePagesToolBar.setObjectName("GreekImagePagesToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.GreekImagePagesToolBar)
        self.LatinImagePagesToolBar = QtWidgets.QToolBar(MainUI)
        self.LatinImagePagesToolBar.setEnabled(True)
        self.LatinImagePagesToolBar.setObjectName("LatinImagePagesToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.LatinImagePagesToolBar)
        self.GreekImageLinesToolBar = QtWidgets.QToolBar(MainUI)
        self.GreekImageLinesToolBar.setObjectName("GreekImageLinesToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.GreekImageLinesToolBar)
        self.LatinImageLinesToolBar = QtWidgets.QToolBar(MainUI)
        self.LatinImageLinesToolBar.setEnabled(False)
        self.LatinImageLinesToolBar.setObjectName("LatinImageLinesToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.LatinImageLinesToolBar)
        self.ImageEditToolBar = QtWidgets.QToolBar(MainUI)
        self.ImageEditToolBar.setObjectName("ImageEditToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.ImageEditToolBar)
        self.FontForgeToolBar = QtWidgets.QToolBar(MainUI)
        self.FontForgeToolBar.setObjectName("FontForgeToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.FontForgeToolBar)
        self.GreekTextLinesToolBar = QtWidgets.QToolBar(MainUI)
        self.GreekTextLinesToolBar.setObjectName("GreekTextLinesToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.GreekTextLinesToolBar)
        self.LatinTextLinesToolBar = QtWidgets.QToolBar(MainUI)
        self.LatinTextLinesToolBar.setEnabled(False)
        self.LatinTextLinesToolBar.setObjectName("LatinTextLinesToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.LatinTextLinesToolBar)
        self.TesseractTrainingToolBar = QtWidgets.QToolBar(MainUI)
        self.TesseractTrainingToolBar.setObjectName("TesseractTrainingToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.TesseractTrainingToolBar)
        self.dockOutput = QtWidgets.QDockWidget(MainUI)
        self.dockOutput.setEnabled(True)
        self.dockOutput.setMinimumSize(QtCore.QSize(560, 200))
        self.dockOutput.setBaseSize(QtCore.QSize(520, 200))
        self.dockOutput.setAccessibleName("")
        self.dockOutput.setAccessibleDescription("")
        self.dockOutput.setFloating(False)
        self.dockOutput.setObjectName("dockOutput")
        self.dockOutputContents = QtWidgets.QWidget()
        self.dockOutputContents.setObjectName("dockOutputContents")
        self.OutputText = QtWidgets.QTextEdit(self.dockOutputContents)
        self.OutputText.setGeometry(QtCore.QRect(20, 0, 550, 200))
        self.OutputText.setMinimumSize(QtCore.QSize(520, 200))
        self.OutputText.setObjectName("OutputText")
        self.dockOutput.setWidget(self.dockOutputContents)
        MainUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockOutput)
        self.dockChrRef = QtWidgets.QDockWidget(MainUI)
        self.dockChrRef.setMinimumSize(QtCore.QSize(650, 220))
        self.dockChrRef.setBaseSize(QtCore.QSize(200, 200))
        self.dockChrRef.setObjectName("dockChrRef")
        self.dockChrRefContents = QtWidgets.QWidget()
        self.dockChrRefContents.setMinimumSize(QtCore.QSize(650, 200))
        self.dockChrRefContents.setObjectName("dockChrRefContents")
        self.ChrRefplainTextEdit = QtWidgets.QPlainTextEdit(self.dockChrRefContents)
        self.ChrRefplainTextEdit.setGeometry(QtCore.QRect(120, 0, 570, 200))
        self.ChrRefplainTextEdit.setMinimumSize(QtCore.QSize(570, 200))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(18)
        self.ChrRefplainTextEdit.setFont(font)
        self.ChrRefplainTextEdit.setObjectName("ChrRefplainTextEdit")
        self.dockChrRef.setWidget(self.dockChrRefContents)
        MainUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockChrRef)
        self.ModulesToolBar = QtWidgets.QToolBar(MainUI)
        self.ModulesToolBar.setObjectName("ModulesToolBar")
        MainUI.addToolBar(QtCore.Qt.TopToolBarArea, self.ModulesToolBar)
        self.actionpdf_to_tiff = QtWidgets.QAction(MainUI)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/Icons/Icons/ocr2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_to_tiff.setIcon(icon24)
        self.actionpdf_to_tiff.setObjectName("actionpdf_to_tiff")
        self.actionmove_pdf_for_tiff = QtWidgets.QAction(MainUI)
        self.actionmove_pdf_for_tiff.setObjectName("actionmove_pdf_for_tiff")
        self.actiontiff_to_mono = QtWidgets.QAction(MainUI)
        self.actiontiff_to_mono.setObjectName("actiontiff_to_mono")
        self.actionmono_to_png = QtWidgets.QAction(MainUI)
        self.actionmono_to_png.setObjectName("actionmono_to_png")
        self.actiontiff_to_png = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png.setObjectName("actiontiff_to_png")
        self.actionGreek = QtWidgets.QAction(MainUI)
        self.actionGreek.setObjectName("actionGreek")
        self.actiontiff_to_png_2 = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png_2.setObjectName("actiontiff_to_png_2")
        self.actionpdf_for_tiff = QtWidgets.QAction(MainUI)
        self.actionpdf_for_tiff.setObjectName("actionpdf_for_tiff")
        self.actionpdf_for_tiff_tb = QtWidgets.QAction(MainUI)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf4tiff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_for_tiff_tb.setIcon(icon25)
        self.actionpdf_for_tiff_tb.setObjectName("actionpdf_for_tiff_tb")
        self.actionpdf_to_tiff_tb = QtWidgets.QAction(MainUI)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf2tiff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_to_tiff_tb.setIcon(icon26)
        self.actionpdf_to_tiff_tb.setObjectName("actionpdf_to_tiff_tb")
        self.actiontiff_to_mono_tb = QtWidgets.QAction(MainUI)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiontiff_to_mono_tb.setIcon(icon27)
        self.actiontiff_to_mono_tb.setObjectName("actiontiff_to_mono_tb")
        self.actionmono_to_png_tb = QtWidgets.QAction(MainUI)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/Icons/Icons/png-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmono_to_png_tb.setIcon(icon28)
        self.actionmono_to_png_tb.setObjectName("actionmono_to_png_tb")
        self.actionLatin = QtWidgets.QAction(MainUI)
        self.actionLatin.setObjectName("actionLatin")
        self.actiontiff_to_png_3 = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png_3.setObjectName("actiontiff_to_png_3")
        self.actiontiff_to_png_4 = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png_4.setObjectName("actiontiff_to_png_4")
        self.actionDeskewGreek_tiff_tb = QtWidgets.QAction(MainUI)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeskewGreek_tiff_tb.setIcon(icon29)
        self.actionDeskewGreek_tiff_tb.setObjectName("actionDeskewGreek_tiff_tb")
        self.actiontiff_to_png_5 = QtWidgets.QAction(MainUI)
        self.actiontiff_to_png_5.setObjectName("actiontiff_to_png_5")
        self.actionDeskewLatin_tiff_tb = QtWidgets.QAction(MainUI)
        self.actionDeskewLatin_tiff_tb.setEnabled(False)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeskewLatin_tiff_tb.setIcon(icon30)
        self.actionDeskewLatin_tiff_tb.setVisible(False)
        self.actionDeskewLatin_tiff_tb.setIconVisibleInMenu(False)
        self.actionDeskewLatin_tiff_tb.setObjectName("actionDeskewLatin_tiff_tb")
        self.actionResizeGreek_png_tb = QtWidgets.QAction(MainUI)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/Icons/Icons/resize-png-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResizeGreek_png_tb.setIcon(icon31)
        self.actionResizeGreek_png_tb.setObjectName("actionResizeGreek_png_tb")
        self.actionResizeLatin_png_tb = QtWidgets.QAction(MainUI)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/Icons/Icons/resize-png-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResizeLatin_png_tb.setIcon(icon32)
        self.actionResizeLatin_png_tb.setVisible(False)
        self.actionResizeLatin_png_tb.setIconVisibleInMenu(False)
        self.actionResizeLatin_png_tb.setObjectName("actionResizeLatin_png_tb")
        self.actionCrop_Languages_tb = QtWidgets.QAction(MainUI)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-langs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrop_Languages_tb.setIcon(icon33)
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        self.actionCrop_Languages_tb.setFont(font)
        self.actionCrop_Languages_tb.setObjectName("actionCrop_Languages_tb")
        self.actionextract_pdf_tb = QtWidgets.QAction(MainUI)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf-extract1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionextract_pdf_tb.setIcon(icon34)
        self.actionextract_pdf_tb.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionextract_pdf_tb.setObjectName("actionextract_pdf_tb")
        self.actiontiff_for_Ground_Truth = QtWidgets.QAction(MainUI)
        self.actiontiff_for_Ground_Truth.setObjectName("actiontiff_for_Ground_Truth")
        self.actionCrop = QtWidgets.QAction(MainUI)
        self.actionCrop.setObjectName("actionCrop")
        self.actiontiff_for_Ground_Truth_2 = QtWidgets.QAction(MainUI)
        self.actiontiff_for_Ground_Truth_2.setObjectName("actiontiff_for_Ground_Truth_2")
        self.actionSplit = QtWidgets.QAction(MainUI)
        self.actionSplit.setObjectName("actionSplit")
        self.actionRename_tiff_lines = QtWidgets.QAction(MainUI)
        self.actionRename_tiff_lines.setObjectName("actionRename_tiff_lines")
        self.actionRename_text_lines = QtWidgets.QAction(MainUI)
        self.actionRename_text_lines.setObjectName("actionRename_text_lines")
        self.actionReview_Ground_Truth = QtWidgets.QAction(MainUI)
        self.actionReview_Ground_Truth.setObjectName("actionReview_Ground_Truth")
        self.actionGreek_Wordlist_2 = QtWidgets.QAction(MainUI)
        self.actionGreek_Wordlist_2.setObjectName("actionGreek_Wordlist_2")
        self.actionLatin_Wordlist = QtWidgets.QAction(MainUI)
        self.actionLatin_Wordlist.setObjectName("actionLatin_Wordlist")
        self.actionImage_Lines = QtWidgets.QAction(MainUI)
        self.actionImage_Lines.setObjectName("actionImage_Lines")
        self.actionText_Lines = QtWidgets.QAction(MainUI)
        self.actionText_Lines.setObjectName("actionText_Lines")
        self.actionReview_Ground_Truth_2 = QtWidgets.QAction(MainUI)
        self.actionReview_Ground_Truth_2.setObjectName("actionReview_Ground_Truth_2")
        self.actionUpdate_Wordlist = QtWidgets.QAction(MainUI)
        self.actionUpdate_Wordlist.setObjectName("actionUpdate_Wordlist")
        self.actionUpdate_Wordlist_2 = QtWidgets.QAction(MainUI)
        self.actionUpdate_Wordlist_2.setObjectName("actionUpdate_Wordlist_2")
        self.actionCorrect_OCR_tb = QtWidgets.QAction(MainUI)
        self.actionCorrect_OCR_tb.setIcon(icon18)
        self.actionCorrect_OCR_tb.setObjectName("actionCorrect_OCR_tb")
        self.actionVersify_Text = QtWidgets.QAction(MainUI)
        self.actionVersify_Text.setObjectName("actionVersify_Text")
        self.actionUpdate_Words = QtWidgets.QAction(MainUI)
        self.actionUpdate_Words.setObjectName("actionUpdate_Words")
        self.actionUpdate_Verses = QtWidgets.QAction(MainUI)
        self.actionUpdate_Verses.setObjectName("actionUpdate_Verses")
        self.actionUpdate_Words_Post = QtWidgets.QAction(MainUI)
        self.actionUpdate_Words_Post.setObjectName("actionUpdate_Words_Post")
        self.actionNormalize = QtWidgets.QAction(MainUI)
        self.actionNormalize.setObjectName("actionNormalize")
        self.actionLower_Case = QtWidgets.QAction(MainUI)
        self.actionLower_Case.setObjectName("actionLower_Case")
        self.actionRemove_Diacritics = QtWidgets.QAction(MainUI)
        self.actionRemove_Diacritics.setObjectName("actionRemove_Diacritics")
        self.actionAlign_Strongs = QtWidgets.QAction(MainUI)
        self.actionAlign_Strongs.setObjectName("actionAlign_Strongs")
        self.actionAlign_Lemmas = QtWidgets.QAction(MainUI)
        self.actionAlign_Lemmas.setObjectName("actionAlign_Lemmas")
        self.actionAlign_English = QtWidgets.QAction(MainUI)
        self.actionAlign_English.setObjectName("actionAlign_English")
        self.actionVariants = QtWidgets.QAction(MainUI)
        self.actionVariants.setObjectName("actionVariants")
        self.actionTrain_Tesseract_tb = QtWidgets.QAction(MainUI)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/Icons/Icons/trainOCR4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTrain_Tesseract_tb.setIcon(icon35)
        self.actionTrain_Tesseract_tb.setObjectName("actionTrain_Tesseract_tb")
        self.actionReview_Ground_Truth_tb = QtWidgets.QAction(MainUI)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/Icons/Icons/ground-truth1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReview_Ground_Truth_tb.setIcon(icon36)
        self.actionReview_Ground_Truth_tb.setObjectName("actionReview_Ground_Truth_tb")
        self.actionUpdate_Wordlist_tb = QtWidgets.QAction(MainUI)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/Icons/Icons/update-greek-wordlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdate_Wordlist_tb.setIcon(icon37)
        self.actionUpdate_Wordlist_tb.setObjectName("actionUpdate_Wordlist_tb")
        self.actionAutoCrop_Greek_to_tif_Lines_tb = QtWidgets.QAction(MainUI)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAutoCrop_Greek_to_tif_Lines_tb.setIcon(icon38)
        self.actionAutoCrop_Greek_to_tif_Lines_tb.setObjectName("actionAutoCrop_Greek_to_tif_Lines_tb")
        self.actionRename_Greek_tif_Lines_tb = QtWidgets.QAction(MainUI)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Greek_tif_Lines_tb.setIcon(icon39)
        self.actionRename_Greek_tif_Lines_tb.setObjectName("actionRename_Greek_tif_Lines_tb")
        self.actionMove_Greek_tif_Lines_tb = QtWidgets.QAction(MainUI)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/Icons/Icons/move-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_Greek_tif_Lines_tb.setIcon(icon40)
        self.actionMove_Greek_tif_Lines_tb.setObjectName("actionMove_Greek_tif_Lines_tb")
        self.actionSplitGreek_text_lines_tb = QtWidgets.QAction(MainUI)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-textlines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSplitGreek_text_lines_tb.setIcon(icon41)
        self.actionSplitGreek_text_lines_tb.setObjectName("actionSplitGreek_text_lines_tb")
        self.actionRenameGreek_text_lines_tb = QtWidgets.QAction(MainUI)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename_textlines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRenameGreek_text_lines_tb.setIcon(icon42)
        self.actionRenameGreek_text_lines_tb.setObjectName("actionRenameGreek_text_lines_tb")
        self.actionImage_Lines_3 = QtWidgets.QAction(MainUI)
        self.actionImage_Lines_3.setObjectName("actionImage_Lines_3")
        self.actionReview_Ground_Truth_menu = QtWidgets.QAction(MainUI)
        self.actionReview_Ground_Truth_menu.setObjectName("actionReview_Ground_Truth_menu")
        self.actionUpdate_Wordlist_menu = QtWidgets.QAction(MainUI)
        self.actionUpdate_Wordlist_menu.setObjectName("actionUpdate_Wordlist_menu")
        self.actionAutoCrop_Latin_To_tif_Lines_tb = QtWidgets.QAction(MainUI)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setIcon(icon43)
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setVisible(False)
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setIconVisibleInMenu(False)
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setObjectName("actionAutoCrop_Latin_To_tif_Lines_tb")
        self.actionRename_Latin_tif_Lines_tb = QtWidgets.QAction(MainUI)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Latin_tif_Lines_tb.setIcon(icon44)
        self.actionRename_Latin_tif_Lines_tb.setVisible(False)
        self.actionRename_Latin_tif_Lines_tb.setIconVisibleInMenu(False)
        self.actionRename_Latin_tif_Lines_tb.setObjectName("actionRename_Latin_tif_Lines_tb")
        self.actionMove_Latin_tif_Lines_tb = QtWidgets.QAction(MainUI)
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(":/Icons/Icons/move-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_Latin_tif_Lines_tb.setIcon(icon45)
        self.actionMove_Latin_tif_Lines_tb.setVisible(False)
        self.actionMove_Latin_tif_Lines_tb.setIconVisibleInMenu(False)
        self.actionMove_Latin_tif_Lines_tb.setObjectName("actionMove_Latin_tif_Lines_tb")
        self.actionSplit_Latin_Text_Lines_tb = QtWidgets.QAction(MainUI)
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-textlines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSplit_Latin_Text_Lines_tb.setIcon(icon46)
        self.actionSplit_Latin_Text_Lines_tb.setWhatsThis("")
        self.actionSplit_Latin_Text_Lines_tb.setVisible(False)
        self.actionSplit_Latin_Text_Lines_tb.setObjectName("actionSplit_Latin_Text_Lines_tb")
        self.actionRename_Latin_Text_Lines_tb = QtWidgets.QAction(MainUI)
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-textlines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Latin_Text_Lines_tb.setIcon(icon47)
        self.actionRename_Latin_Text_Lines_tb.setVisible(False)
        self.actionRename_Latin_Text_Lines_tb.setIconVisibleInMenu(False)
        self.actionRename_Latin_Text_Lines_tb.setObjectName("actionRename_Latin_Text_Lines_tb")
        self.actiondeskew_mono = QtWidgets.QAction(MainUI)
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-tiff-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondeskew_mono.setIcon(icon48)
        self.actiondeskew_mono.setObjectName("actiondeskew_mono")
        self.actionOpen_Image = QtWidgets.QAction(MainUI)
        self.actionOpen_Image.setIcon(icon1)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionVerse_Correction = QtWidgets.QAction(MainUI)
        icon49 = QtGui.QIcon()
        icon49.addPixmap(QtGui.QPixmap(":/Icons/Icons/versify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVerse_Correction.setIcon(icon49)
        self.actionVerse_Correction.setObjectName("actionVerse_Correction")
        self.actionConvert_Greek_tiff_To_png = QtWidgets.QAction(MainUI)
        icon50 = QtGui.QIcon()
        icon50.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff2png-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConvert_Greek_tiff_To_png.setIcon(icon50)
        self.actionConvert_Greek_tiff_To_png.setObjectName("actionConvert_Greek_tiff_To_png")
        self.actionConvert_Latin_tiff_To_png = QtWidgets.QAction(MainUI)
        self.actionConvert_Latin_tiff_To_png.setEnabled(False)
        icon51 = QtGui.QIcon()
        icon51.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff2png-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConvert_Latin_tiff_To_png.setIcon(icon51)
        self.actionConvert_Latin_tiff_To_png.setVisible(False)
        self.actionConvert_Latin_tiff_To_png.setIconVisibleInMenu(False)
        self.actionConvert_Latin_tiff_To_png.setObjectName("actionConvert_Latin_tiff_To_png")
        self.actionExtract_Glyphs = QtWidgets.QAction(MainUI)
        icon52 = QtGui.QIcon()
        icon52.addPixmap(QtGui.QPixmap(":/Icons/Icons/trace1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExtract_Glyphs.setIcon(icon52)
        self.actionExtract_Glyphs.setObjectName("actionExtract_Glyphs")
        self.actionLine_tif_to_bmp = QtWidgets.QAction(MainUI)
        icon53 = QtGui.QIcon()
        icon53.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff2bmp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLine_tif_to_bmp.setIcon(icon53)
        self.actionLine_tif_to_bmp.setObjectName("actionLine_tif_to_bmp")
        self.actionFontForge = QtWidgets.QAction(MainUI)
        icon54 = QtGui.QIcon()
        icon54.addPixmap(QtGui.QPixmap(":/Icons/Icons/FontForge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFontForge.setIcon(icon54)
        self.actionFontForge.setObjectName("actionFontForge")
        self.actionPrefernces = QtWidgets.QAction(MainUI)
        self.actionPrefernces.setObjectName("actionPrefernces")
        self.actionOpen_Text = QtWidgets.QAction(MainUI)
        self.actionOpen_Text.setIcon(icon2)
        self.actionOpen_Text.setObjectName("actionOpen_Text")
        self.actionSave_Image = QtWidgets.QAction(MainUI)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionSave_As_Image = QtWidgets.QAction(MainUI)
        self.actionSave_As_Image.setObjectName("actionSave_As_Image")
        self.actionSave_Text = QtWidgets.QAction(MainUI)
        self.actionSave_Text.setIcon(icon4)
        self.actionSave_Text.setObjectName("actionSave_Text")
        self.actionSave_As_Text = QtWidgets.QAction(MainUI)
        self.actionSave_As_Text.setIcon(icon3)
        self.actionSave_As_Text.setObjectName("actionSave_As_Text")
        self.actionConvert_Image_s = QtWidgets.QAction(MainUI)
        self.actionConvert_Image_s.setObjectName("actionConvert_Image_s")
        self.actionReview_Ground_Truth_3 = QtWidgets.QAction(MainUI)
        self.actionReview_Ground_Truth_3.setObjectName("actionReview_Ground_Truth_3")
        self.actionHebrew = QtWidgets.QAction(MainUI)
        self.actionHebrew.setObjectName("actionHebrew")
        self.actionHebrew_2 = QtWidgets.QAction(MainUI)
        self.actionHebrew_2.setObjectName("actionHebrew_2")
        self.actionUpdate_Hebrew_Wordlist = QtWidgets.QAction(MainUI)
        self.actionUpdate_Hebrew_Wordlist.setObjectName("actionUpdate_Hebrew_Wordlist")
        self.actionHebrew_3 = QtWidgets.QAction(MainUI)
        self.actionHebrew_3.setObjectName("actionHebrew_3")
        self.actionOCR_Image = QtWidgets.QAction(MainUI)
        self.actionOCR_Image.setObjectName("actionOCR_Image")
        self.actionSelect_Image = QtWidgets.QAction(MainUI)
        self.actionSelect_Image.setObjectName("actionSelect_Image")
        self.actionGreek_2 = QtWidgets.QAction(MainUI)
        self.actionGreek_2.setObjectName("actionGreek_2")
        self.actionHebrew_4 = QtWidgets.QAction(MainUI)
        self.actionHebrew_4.setObjectName("actionHebrew_4")
        self.actionLatin_2 = QtWidgets.QAction(MainUI)
        self.actionLatin_2.setObjectName("actionLatin_2")
        self.actionSelect_Language_Model = QtWidgets.QAction(MainUI)
        self.actionSelect_Language_Model.setObjectName("actionSelect_Language_Model")
        self.actionSelect_Fonts = QtWidgets.QAction(MainUI)
        self.actionSelect_Fonts.setObjectName("actionSelect_Fonts")
        self.actionany = QtWidgets.QAction(MainUI)
        self.actionany.setObjectName("actionany")
        self.actionAny = QtWidgets.QAction(MainUI)
        self.actionAny.setObjectName("actionAny")
        self.actionStage_Ground_Truth = QtWidgets.QAction(MainUI)
        self.actionStage_Ground_Truth.setObjectName("actionStage_Ground_Truth")
        self.actionCreate_e_Sword_Bible_Module = QtWidgets.QAction(MainUI)
        icon55 = QtGui.QIcon()
        icon55.addPixmap(QtGui.QPixmap(":/Icons/Icons/esword.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_e_Sword_Bible_Module.setIcon(icon55)
        self.actionCreate_e_Sword_Bible_Module.setObjectName("actionCreate_e_Sword_Bible_Module")
        self.actionCreate_theWord_Bible_Module = QtWidgets.QAction(MainUI)
        icon56 = QtGui.QIcon()
        icon56.addPixmap(QtGui.QPixmap(":/Icons/Icons/theword.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_theWord_Bible_Module.setIcon(icon56)
        self.actionCreate_theWord_Bible_Module.setObjectName("actionCreate_theWord_Bible_Module")
        self.actionEnglish = QtWidgets.QAction(MainUI)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionEnglishh = QtWidgets.QAction(MainUI)
        self.actionEnglishh.setObjectName("actionEnglishh")
        self.actionEnglish_2 = QtWidgets.QAction(MainUI)
        self.actionEnglish_2.setObjectName("actionEnglish_2")
        self.actionEnglish_3 = QtWidgets.QAction(MainUI)
        self.actionEnglish_3.setObjectName("actionEnglish_3")
        self.actionOnline = QtWidgets.QAction(MainUI)
        self.actionOnline.setObjectName("actionOnline")
        self.actionManual_Crop_Image_tb = QtWidgets.QAction(MainUI)
        icon57 = QtGui.QIcon()
        icon57.addPixmap(QtGui.QPixmap(":/Icons/Icons/image-crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionManual_Crop_Image_tb.setIcon(icon57)
        self.actionManual_Crop_Image_tb.setObjectName("actionManual_Crop_Image_tb")
        self.actionEdit_Image_tb = QtWidgets.QAction(MainUI)
        icon58 = QtGui.QIcon()
        icon58.addPixmap(QtGui.QPixmap(":/Icons/Icons/gimp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_Image_tb.setIcon(icon58)
        self.actionEdit_Image_tb.setObjectName("actionEdit_Image_tb")
        self.actionLibreOffice_Writer = QtWidgets.QAction(MainUI)
        self.actionLibreOffice_Writer.setIcon(icon5)
        self.actionLibreOffice_Writer.setObjectName("actionLibreOffice_Writer")
        self.actionLibreOffice_Calc = QtWidgets.QAction(MainUI)
        self.actionLibreOffice_Calc.setIcon(icon6)
        self.actionLibreOffice_Calc.setObjectName("actionLibreOffice_Calc")
        self.actionDB_Browser_for_SQLite = QtWidgets.QAction(MainUI)
        icon59 = QtGui.QIcon()
        icon59.addPixmap(QtGui.QPixmap(":/Icons/Icons/server.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDB_Browser_for_SQLite.setIcon(icon59)
        self.actionDB_Browser_for_SQLite.setObjectName("actionDB_Browser_for_SQLite")
        self.actionFind_and_Replace = QtWidgets.QAction(MainUI)
        self.actionFind_and_Replace.setIcon(icon23)
        self.actionFind_and_Replace.setObjectName("actionFind_and_Replace")
        self.actionInstall_Font = QtWidgets.QAction(MainUI)
        icon60 = QtGui.QIcon()
        icon60.addPixmap(QtGui.QPixmap(":/Icons/Icons/font.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInstall_Font.setIcon(icon60)
        self.actionInstall_Font.setObjectName("actionInstall_Font")
        self.actionToggle_Greek_Toolbars = QtWidgets.QAction(MainUI)
        self.actionToggle_Greek_Toolbars.setObjectName("actionToggle_Greek_Toolbars")
        self.actionToggle_Latin_Toolbars = QtWidgets.QAction(MainUI)
        self.actionToggle_Latin_Toolbars.setObjectName("actionToggle_Latin_Toolbars")
        self.actionPrepare_Text = QtWidgets.QAction(MainUI)
        self.actionPrepare_Text.setObjectName("actionPrepare_Text")
        self.actionEnglish_4 = QtWidgets.QAction(MainUI)
        self.actionEnglish_4.setObjectName("actionEnglish_4")
        self.actionLatin_3 = QtWidgets.QAction(MainUI)
        self.actionLatin_3.setObjectName("actionLatin_3")
        self.actionStart = QtWidgets.QAction(MainUI)
        self.actionStart.setObjectName("actionStart")
        self.actionHebrew_5 = QtWidgets.QAction(MainUI)
        self.actionHebrew_5.setObjectName("actionHebrew_5")
        self.actionGimp = QtWidgets.QAction(MainUI)
        self.actionGimp.setIcon(icon58)
        self.actionGimp.setObjectName("actionGimp")
        self.actionLibre_Office_Writer = QtWidgets.QAction(MainUI)
        self.actionLibre_Office_Writer.setIcon(icon5)
        self.actionLibre_Office_Writer.setObjectName("actionLibre_Office_Writer")
        self.actionLibre_Office_Calc = QtWidgets.QAction(MainUI)
        self.actionLibre_Office_Calc.setIcon(icon6)
        self.actionLibre_Office_Calc.setObjectName("actionLibre_Office_Calc")
        self.actionFont_Forge = QtWidgets.QAction(MainUI)
        self.actionFont_Forge.setIcon(icon54)
        self.actionFont_Forge.setObjectName("actionFont_Forge")
        self.actionDeveloper = QtWidgets.QAction(MainUI)
        self.actionDeveloper.setObjectName("actionDeveloper")
        self.actionAcademic = QtWidgets.QAction(MainUI)
        self.actionAcademic.setObjectName("actionAcademic")
        self.actionMistry = QtWidgets.QAction(MainUI)
        self.actionMistry.setObjectName("actionMistry")
        self.actionPixler_Image_Editor = QtWidgets.QAction(MainUI)
        self.actionPixler_Image_Editor.setIcon(icon9)
        self.actionPixler_Image_Editor.setObjectName("actionPixler_Image_Editor")
        self.menuExtract_pdf.addAction(self.actionextract_pdf_tb)
        self.menuExtract_pdf.addSeparator()
        self.menuExtract_pdf.addAction(self.actionpdf_for_tiff_tb)
        self.menuExtract_pdf.addAction(self.actionpdf_to_tiff_tb)
        self.menuExtract_pdf.addAction(self.actiontiff_to_mono_tb)
        self.menuExtract_pdf.addAction(self.actionmono_to_png_tb)
        self.menuExtract_pdf.addAction(self.actiondeskew_mono)
        self.menuGreekDR.addAction(self.actionConvert_Greek_tiff_To_png)
        self.menuGreekDR.addAction(self.actionDeskewGreek_tiff_tb)
        self.menuGreekDR.addAction(self.actionResizeGreek_png_tb)
        self.menuLatinDR.addAction(self.actionConvert_Latin_tiff_To_png)
        self.menuLatinDR.addAction(self.actionDeskewLatin_tiff_tb)
        self.menuLatinDR.addAction(self.actionResizeLatin_png_tb)
        self.menuPrepare.addSeparator()
        self.menuPrepare.addAction(self.actionCrop_Languages_tb)
        self.menuPrepare.addAction(self.actionManual_Crop_Image_tb)
        self.menuPrepare.addAction(self.actionHebrew)
        self.menuPrepare.addAction(self.menuGreekDR.menuAction())
        self.menuPrepare.addAction(self.menuLatinDR.menuAction())
        self.menuPrepare.addAction(self.actionEnglishh)
        self.menuPre_Process.addSeparator()
        self.menuPre_Process.addAction(self.menuExtract_pdf.menuAction())
        self.menuPre_Process.addSeparator()
        self.menuPre_Process.addSeparator()
        self.menuPre_Process.addAction(self.menuPrepare.menuAction())
        self.menuGreek_Image_Lines.addAction(self.actionAutoCrop_Greek_to_tif_Lines_tb)
        self.menuGreek_Image_Lines.addAction(self.actionRename_Greek_tif_Lines_tb)
        self.menuGreek_Image_Lines.addAction(self.actionMove_Greek_tif_Lines_tb)
        self.menuGreek_Text_Lines.addAction(self.actionSplitGreek_text_lines_tb)
        self.menuGreek_Text_Lines.addAction(self.actionRenameGreek_text_lines_tb)
        self.menuGreekGT.addAction(self.menuGreek_Image_Lines.menuAction())
        self.menuGreekGT.addAction(self.menuGreek_Text_Lines.menuAction())
        self.menuLatin_Image_Lines.addAction(self.actionAutoCrop_Latin_To_tif_Lines_tb)
        self.menuLatin_Image_Lines.addAction(self.actionRename_Latin_tif_Lines_tb)
        self.menuLatin_Image_Lines.addAction(self.actionMove_Latin_tif_Lines_tb)
        self.menuLatin_Text_Lines.addAction(self.actionSplit_Latin_Text_Lines_tb)
        self.menuLatin_Text_Lines.addAction(self.actionRename_Latin_Text_Lines_tb)
        self.menuLatinGT.addAction(self.menuLatin_Image_Lines.menuAction())
        self.menuLatinGT.addAction(self.menuLatin_Text_Lines.menuAction())
        self.menuGround_Truth.addAction(self.actionHebrew_2)
        self.menuGround_Truth.addAction(self.menuGreekGT.menuAction())
        self.menuGround_Truth.addAction(self.menuLatinGT.menuAction())
        self.menuGround_Truth.addAction(self.actionEnglish_3)
        self.menuTraining.addSeparator()
        self.menuTraining.addAction(self.menuGround_Truth.menuAction())
        self.menuTraining.addAction(self.actionReview_Ground_Truth_tb)
        self.menuTraining.addAction(self.actionStage_Ground_Truth)
        self.menuSelect_Language.addAction(self.actionGreek_2)
        self.menuSelect_Language.addAction(self.actionHebrew_4)
        self.menuSelect_Language.addAction(self.actionLatin_2)
        self.menuSelect_Language.addAction(self.actionEnglish_2)
        self.menuOCR.addAction(self.menuSelect_Language.menuAction())
        self.menuOCR.addAction(self.actionSelect_Image)
        self.menuOCR.addAction(self.actionCorrect_OCR_tb)
        self.menuGreek.addAction(self.actionUpdate_Verses)
        self.menuGreek.addAction(self.actionUpdate_Words_Post)
        self.menuGreek.addAction(self.actionNormalize)
        self.menuGreek.addAction(self.actionLower_Case)
        self.menuGreek.addAction(self.actionRemove_Diacritics)
        self.menuGreek.addAction(self.actionAlign_Strongs)
        self.menuGreek.addAction(self.actionAlign_English)
        self.menuGreek.addAction(self.actionVariants)
        self.menuModules.addAction(self.actionPrepare_Text)
        self.menuModules.addAction(self.actionHebrew_5)
        self.menuModules.addAction(self.menuGreek.menuAction())
        self.menuModules.addAction(self.actionLatin_3)
        self.menuModules.addAction(self.actionEnglish_4)
        self.menuModules.addAction(self.menuType_Here.menuAction())
        self.menuPost_Process.addAction(self.actionGimp)
        self.menuPost_Process.addAction(self.actionFont_Forge)
        self.menuPost_Process.addAction(self.actionLibre_Office_Writer)
        self.menuPost_Process.addAction(self.actionLibre_Office_Calc)
        self.menuPost_Process.addAction(self.actionVerse_Correction)
        self.menuPost_Process.addAction(self.actionDB_Browser_for_SQLite)
        self.menuPost_Process.addAction(self.actionCreate_e_Sword_Bible_Module)
        self.menuPost_Process.addAction(self.actionCreate_theWord_Bible_Module)
        self.menuPost_Process.addAction(self.menuModules.menuAction())
        self.menuPost_Process.addAction(self.actionMistry)
        self.menuPost_Process.addAction(self.actionAcademic)
        self.menuPost_Process.addAction(self.actionDeveloper)
        self.menuFile.addAction(self.actionOpen_Image)
        self.menuFile.addAction(self.actionOpen_Text)
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addAction(self.actionSave_As_Image)
        self.menuFile.addAction(self.actionSave_Text)
        self.menuFile.addAction(self.actionSave_As_Text)
        self.menuEdit.addAction(self.actionPixler_Image_Editor)
        self.menuEdit.addAction(self.actionEdit_Image_tb)
        self.menuEdit.addAction(self.actionPrefernces)
        self.menuEdit.addAction(self.actionFind_and_Replace)
        self.menuView.addAction(self.actionToggle_Greek_Toolbars)
        self.menuView.addAction(self.actionToggle_Latin_Toolbars)
        self.menuTools.addAction(self.actionConvert_Image_s)
        self.menuTools.addAction(self.actionOnline)
        self.menuTools.addAction(self.actionLibreOffice_Writer)
        self.menuTools.addAction(self.actionLibreOffice_Calc)
        self.menuIndex_Images.addAction(self.actionLine_tif_to_bmp)
        self.menuGlyphs.addAction(self.menuIndex_Images.menuAction())
        self.menuGlyphs.addAction(self.actionExtract_Glyphs)
        self.menuGlyphs.addAction(self.actionFontForge)
        self.menuGlyphs.addAction(self.actionInstall_Font)
        self.menuUpdate_Wordlists.addAction(self.actionUpdate_Hebrew_Wordlist)
        self.menuUpdate_Wordlists.addAction(self.actionUpdate_Wordlist_tb)
        self.menuUpdate_Wordlists.addAction(self.actionUpdate_Wordlist_menu)
        self.menuSetup_Training.addAction(self.actionSelect_Language_Model)
        self.menuSetup_Training.addAction(self.actionSelect_Fonts)
        self.menuGround_Truth_2.addAction(self.menuUpdate_Wordlists.menuAction())
        self.menuGround_Truth_2.addAction(self.menuSetup_Training.menuAction())
        self.menuGround_Truth_2.addAction(self.actionTrain_Tesseract_tb)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPre_Process.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuOCR.menuAction())
        self.menubar.addAction(self.menuTraining.menuAction())
        self.menubar.addAction(self.menuGlyphs.menuAction())
        self.menubar.addAction(self.menuGround_Truth_2.menuAction())
        self.menubar.addAction(self.menuPost_Process.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.ExtractPagesToolBar.addAction(self.actionextract_pdf_tb)
        self.ExtractPagesToolBar.addAction(self.actionpdf_for_tiff_tb)
        self.ExtractPagesToolBar.addAction(self.actionpdf_to_tiff_tb)
        self.ConvertPagesToolBar.addAction(self.actiontiff_to_mono_tb)
        self.ConvertPagesToolBar.addAction(self.actionmono_to_png_tb)
        self.ConvertPagesToolBar.addAction(self.actiondeskew_mono)
        self.ConvertPagesToolBar.addAction(self.actionCrop_Languages_tb)
        self.GreekImagePagesToolBar.addAction(self.actionConvert_Greek_tiff_To_png)
        self.GreekImagePagesToolBar.addAction(self.actionDeskewGreek_tiff_tb)
        self.GreekImagePagesToolBar.addAction(self.actionResizeGreek_png_tb)
        self.LatinImagePagesToolBar.addAction(self.actionDeskewLatin_tiff_tb)
        self.LatinImagePagesToolBar.addAction(self.actionConvert_Latin_tiff_To_png)
        self.LatinImagePagesToolBar.addAction(self.actionResizeLatin_png_tb)
        self.GreekImageLinesToolBar.addAction(self.actionAutoCrop_Greek_to_tif_Lines_tb)
        self.GreekImageLinesToolBar.addAction(self.actionRename_Greek_tif_Lines_tb)
        self.GreekImageLinesToolBar.addAction(self.actionMove_Greek_tif_Lines_tb)
        self.LatinImageLinesToolBar.addAction(self.actionAutoCrop_Latin_To_tif_Lines_tb)
        self.LatinImageLinesToolBar.addAction(self.actionRename_Latin_tif_Lines_tb)
        self.LatinImageLinesToolBar.addAction(self.actionMove_Latin_tif_Lines_tb)
        self.ImageEditToolBar.addAction(self.actionPixler_Image_Editor)
        self.ImageEditToolBar.addAction(self.actionEdit_Image_tb)
        self.ImageEditToolBar.addAction(self.actionCorrect_OCR_tb)
        self.FontForgeToolBar.addAction(self.actionLine_tif_to_bmp)
        self.FontForgeToolBar.addAction(self.actionExtract_Glyphs)
        self.FontForgeToolBar.addAction(self.actionFontForge)
        self.GreekTextLinesToolBar.addAction(self.actionSplitGreek_text_lines_tb)
        self.GreekTextLinesToolBar.addAction(self.actionRenameGreek_text_lines_tb)
        self.LatinTextLinesToolBar.addAction(self.actionSplit_Latin_Text_Lines_tb)
        self.LatinTextLinesToolBar.addAction(self.actionRename_Latin_Text_Lines_tb)
        self.TesseractTrainingToolBar.addAction(self.actionUpdate_Wordlist_tb)
        self.TesseractTrainingToolBar.addAction(self.actionReview_Ground_Truth_tb)
        self.TesseractTrainingToolBar.addAction(self.actionTrain_Tesseract_tb)
        self.ModulesToolBar.addAction(self.actionVerse_Correction)
        self.ModulesToolBar.addAction(self.actionDB_Browser_for_SQLite)
        self.ModulesToolBar.addAction(self.actionCreate_e_Sword_Bible_Module)
        self.ModulesToolBar.addAction(self.actionCreate_theWord_Bible_Module)

        self.retranslateUi(MainUI)
        QtCore.QMetaObject.connectSlotsByName(MainUI)

    def retranslateUi(self, MainUI):
        _translate = QtCore.QCoreApplication.translate
        MainUI.setWindowTitle(_translate("MainUI", "βϊϐλίον OCR"))
        self.OpenImageFilebutton.setToolTip(_translate("MainUI", "Open current image"))
        self.ImageLe.setToolTip(_translate("MainUI", "Current image name"))
        self.EditCorrectedTextbutton.setToolTip(_translate("MainUI", "Open current text(.txt,.csv) file"))
        self.SaveAsOCRCorrTextbutton.setToolTip(_translate("MainUI", "Save current text file as..."))
        self.SaveOCRCorrTextbutton.setToolTip(_translate("MainUI", "Overwrite current text file"))
        self.Writerbutton.setToolTip(_translate("MainUI", "Edit current text(.txt) file with OpenOffice Writer"))
        self.Calcbutton.setToolTip(_translate("MainUI", "Edit current text(.csv) file with OpenOffice Calc"))
        self.reloadTextbutton.setToolTip(_translate("MainUI", "Reload current text"))
        self.reloadImagebutton.setToolTip(_translate("MainUI", "Reload current image"))
        self.MyPixlerbutton.setToolTip(_translate("MainUI", "Edit images with Pixer"))
        self.Deskewbutton.setToolTip(_translate("MainUI", "Deskew current image"))
        self.PrevImgButton.setToolTip(_translate("MainUI", "Previous current image - !pair independent"))
        self.NextImgButton.setToolTip(_translate("MainUI", "Next current image - !pair independent"))
        self.PrevTxtButton.setToolTip(_translate("MainUI", "Previous current text - !pair independent"))
        self.NextTxtButton.setToolTip(_translate("MainUI", "Next current text - !pair independent"))
        self.BothNextButton.setToolTip(_translate("MainUI", "Next current image|text pair"))
        self.BothPrevButton.setToolTip(_translate("MainUI", "Previous current image|text pair"))
        self.BothLoadButton.setToolTip(_translate("MainUI", "Load current image|text pair"))
        self.OCRlangComboBox.setToolTip(_translate("MainUI", "Select OCR language"))
        self.OCRlangComboBox.setItemText(0, _translate("MainUI", "Ancient Greek"))
        self.OCRlangComboBox.setItemText(1, _translate("MainUI", "Middle Greek"))
        self.OCRlangComboBox.setItemText(2, _translate("MainUI", "Modern Greek"))
        self.OCRlangComboBox.setItemText(3, _translate("MainUI", "Hebrew"))
        self.OCRlangComboBox.setItemText(4, _translate("MainUI", "Latin"))
        self.OCRlanglabel.setText(_translate("MainUI", " OCR Language"))
        self.OCRModellabel.setToolTip(_translate("MainUI", "Select OCR LSTM model"))
        self.OCRModellabel.setText(_translate("MainUI", " OCR LSTM Model"))
        self.OCRModelComboBox.setToolTip(_translate("MainUI", "Select OCR language model"))
        self.OCRModelComboBox.setItemText(0, _translate("MainUI", "ell"))
        self.OCRModelComboBox.setItemText(1, _translate("MainUI", "grc"))
        self.OCRModelComboBox.setItemText(2, _translate("MainUI", "feg"))
        self.OCRModelComboBox.setItemText(3, _translate("MainUI", "heb"))
        self.OCRModelComboBox.setItemText(4, _translate("MainUI", "feh"))
        self.OCRModelComboBox.setItemText(5, _translate("MainUI", "lat"))
        self.OCRModelComboBox.setItemText(6, _translate("MainUI", "fel"))
        self.OCRbutton.setToolTip(_translate("MainUI", "OCR current image"))
        self.OCRbutton.setText(_translate("MainUI", "OCR Raw"))
        self.booklabel.setText(_translate("MainUI", "Book"))
        self.bookComboBox.setToolTip(_translate("MainUI", "Bible book current image|text directory"))
        self.bookComboBox.setItemText(0, _translate("MainUI", "Mat"))
        self.bookComboBox.setItemText(1, _translate("MainUI", "Mar"))
        self.bookComboBox.setItemText(2, _translate("MainUI", "Luk"))
        self.bookComboBox.setItemText(3, _translate("MainUI", "Joh"))
        self.bookComboBox.setItemText(4, _translate("MainUI", "Act"))
        self.bookComboBox.setItemText(5, _translate("MainUI", "Rom"))
        self.bookComboBox.setItemText(6, _translate("MainUI", "1Co"))
        self.bookComboBox.setItemText(7, _translate("MainUI", "2Co"))
        self.bookComboBox.setItemText(8, _translate("MainUI", "Gal"))
        self.bookComboBox.setItemText(9, _translate("MainUI", "Eph"))
        self.bookComboBox.setItemText(10, _translate("MainUI", "Php"))
        self.bookComboBox.setItemText(11, _translate("MainUI", "Col"))
        self.bookComboBox.setItemText(12, _translate("MainUI", "1Th"))
        self.bookComboBox.setItemText(13, _translate("MainUI", "2Th"))
        self.bookComboBox.setItemText(14, _translate("MainUI", "1Ti"))
        self.bookComboBox.setItemText(15, _translate("MainUI", "2Ti"))
        self.bookComboBox.setItemText(16, _translate("MainUI", "Tit"))
        self.bookComboBox.setItemText(17, _translate("MainUI", "Phm"))
        self.bookComboBox.setItemText(18, _translate("MainUI", "Heb"))
        self.bookComboBox.setItemText(19, _translate("MainUI", "Jas"))
        self.bookComboBox.setItemText(20, _translate("MainUI", "1Pe"))
        self.bookComboBox.setItemText(21, _translate("MainUI", "2Pe"))
        self.bookComboBox.setItemText(22, _translate("MainUI", "1Jn"))
        self.bookComboBox.setItemText(23, _translate("MainUI", "2Jn"))
        self.bookComboBox.setItemText(24, _translate("MainUI", "3Jn"))
        self.bookComboBox.setItemText(25, _translate("MainUI", "Jud"))
        self.bookComboBox.setItemText(26, _translate("MainUI", "Rev"))
        self.fontlabel.setText(_translate("MainUI", "Font"))
        self.fontSizelabel.setText(_translate("MainUI", "Font Size"))
        self.fontSizeBox.setToolTip(_translate("MainUI", "Select font size"))
        self.fontComboBox.setToolTip(_translate("MainUI", "Select font"))
        self.ZoomComboBox.setToolTip(_translate("MainUI", "Select current image zoom"))
        self.ZoomComboBox.setCurrentText(_translate("MainUI", "10 %"))
        self.ZoomComboBox.setItemText(0, _translate("MainUI", "10 %"))
        self.ZoomComboBox.setItemText(1, _translate("MainUI", "25 %"))
        self.ZoomComboBox.setItemText(2, _translate("MainUI", "50 %"))
        self.ZoomComboBox.setItemText(3, _translate("MainUI", "100 %"))
        self.ZoomComboBox.setItemText(4, _translate("MainUI", "200 %"))
        self.Zoombutton.setToolTip(_translate("MainUI", "Zoom decorator"))
        self.Cropbutton.setToolTip(_translate("MainUI", "Crop current image"))
        self.LHslider.setToolTip(_translate("MainUI", "Set current text line spacing"))
        self.LHlineEdit.setToolTip(_translate("MainUI", "Current text line spacing"))
        self.LHlineEdit.setText(_translate("MainUI", "150"))
        self.LHlineEdit.setPlaceholderText(_translate("MainUI", "150"))
        self.LHDialogtbutton.setToolTip(_translate("MainUI", "Enable line spacing slider"))
        self.Zoomslider.setToolTip(_translate("MainUI", "Set current text line spacing"))
        self.MyWriterbutton.setToolTip(_translate("MainUI", "Edit current text(.txt) file with OpenOffice Writer"))
        self.FindReplacebutton.setText(_translate("MainUI", "Find and Replace"))
        self.menuPre_Process.setTitle(_translate("MainUI", "Language"))
        self.menuExtract_pdf.setTitle(_translate("MainUI", "Source"))
        self.menuPrepare.setTitle(_translate("MainUI", "Languages"))
        self.menuGreekDR.setTitle(_translate("MainUI", "Greek"))
        self.menuLatinDR.setTitle(_translate("MainUI", "Latin"))
        self.menuTraining.setTitle(_translate("MainUI", "Ground-Truth"))
        self.menuGround_Truth.setTitle(_translate("MainUI", "Establish Truth"))
        self.menuGreekGT.setTitle(_translate("MainUI", "Greek"))
        self.menuGreek_Image_Lines.setTitle(_translate("MainUI", "Greek Image Lines"))
        self.menuGreek_Text_Lines.setTitle(_translate("MainUI", "Greek Text Lines"))
        self.menuLatinGT.setTitle(_translate("MainUI", "Latin"))
        self.menuLatin_Image_Lines.setTitle(_translate("MainUI", "Latin Image Lines"))
        self.menuLatin_Text_Lines.setTitle(_translate("MainUI", "Latin Text Lines"))
        self.menuOCR.setTitle(_translate("MainUI", "OCR"))
        self.menuSelect_Language.setTitle(_translate("MainUI", "Select Language"))
        self.menuPost_Process.setTitle(_translate("MainUI", "Extensions"))
        self.menuModules.setTitle(_translate("MainUI", "Modules"))
        self.menuGreek.setTitle(_translate("MainUI", "Greek"))
        self.menuType_Here.setTitle(_translate("MainUI", "Type Here"))
        self.menuFile.setTitle(_translate("MainUI", "File"))
        self.menuEdit.setTitle(_translate("MainUI", "Edit"))
        self.menuView.setTitle(_translate("MainUI", "View"))
        self.menuTools.setTitle(_translate("MainUI", "Tools"))
        self.menuHelp.setTitle(_translate("MainUI", "Help"))
        self.menuGlyphs.setTitle(_translate("MainUI", "FontForge"))
        self.menuIndex_Images.setTitle(_translate("MainUI", "Bitmap Images"))
        self.menuGround_Truth_2.setTitle(_translate("MainUI", "Training"))
        self.menuUpdate_Wordlists.setTitle(_translate("MainUI", "Update Wordlists"))
        self.menuSetup_Training.setTitle(_translate("MainUI", "Setup Training"))
        self.ExtractPagesToolBar.setWindowTitle(_translate("MainUI", "Extract Source Pages Tool Bar"))
        self.ExtractPagesToolBar.setToolTip(_translate("MainUI", "Extract Source Pages Tool Bar"))
        self.ConvertPagesToolBar.setWindowTitle(_translate("MainUI", "Convert Source Pages Tool Bar"))
        self.ConvertPagesToolBar.setToolTip(_translate("MainUI", "Convert Source Pages Tool Bar"))
        self.GreekImagePagesToolBar.setWindowTitle(_translate("MainUI", "Greek Image Pages Tool Bar"))
        self.GreekImagePagesToolBar.setToolTip(_translate("MainUI", "Greek Image Pages Tool Bar"))
        self.LatinImagePagesToolBar.setWindowTitle(_translate("MainUI", "Latin Image Pages Tool Bar"))
        self.LatinImagePagesToolBar.setToolTip(_translate("MainUI", "Latin Image Pages Tool Bar"))
        self.GreekImageLinesToolBar.setWindowTitle(_translate("MainUI", "Greek Image Lines Tool Bar"))
        self.GreekImageLinesToolBar.setToolTip(_translate("MainUI", "Greek Image Lines Tool Bar"))
        self.LatinImageLinesToolBar.setWindowTitle(_translate("MainUI", "Latin Image Lines Tool Bar"))
        self.LatinImageLinesToolBar.setToolTip(_translate("MainUI", "Latin Image Lines Tool Bar"))
        self.ImageEditToolBar.setWindowTitle(_translate("MainUI", "ImageEditToolBar"))
        self.ImageEditToolBar.setToolTip(_translate("MainUI", "ImageEditToolBar"))
        self.FontForgeToolBar.setWindowTitle(_translate("MainUI", "FontForge Tool Bar"))
        self.FontForgeToolBar.setToolTip(_translate("MainUI", "FontForge Tool Bar"))
        self.GreekTextLinesToolBar.setWindowTitle(_translate("MainUI", "Greek Text Lines Tool Bar"))
        self.GreekTextLinesToolBar.setToolTip(_translate("MainUI", "Greek Text Lines Tool Bar"))
        self.LatinTextLinesToolBar.setWindowTitle(_translate("MainUI", "Latin Text Lines Tool Bar"))
        self.LatinTextLinesToolBar.setToolTip(_translate("MainUI", "Latin Text Lines Tool Bar"))
        self.TesseractTrainingToolBar.setWindowTitle(_translate("MainUI", "Tesseract OCR Training Tool Bar"))
        self.TesseractTrainingToolBar.setToolTip(_translate("MainUI", "Tesseract OCR Training Tool Bar"))
        self.dockOutput.setWindowTitle(_translate("MainUI", " Output"))
        self.dockChrRef.setWindowTitle(_translate("MainUI", "                    Character Reference"))
        self.ChrRefplainTextEdit.setDocumentTitle(_translate("MainUI", "Character Reference"))
        self.ModulesToolBar.setWindowTitle(_translate("MainUI", "Versify Text Tool Bar"))
        self.ModulesToolBar.setToolTip(_translate("MainUI", "Versify Text Tool Bar"))
        self.actionpdf_to_tiff.setText(_translate("MainUI", "pdf for tiff"))
        self.actionmove_pdf_for_tiff.setText(_translate("MainUI", "pdf to tiff"))
        self.actiontiff_to_mono.setText(_translate("MainUI", "tiff to mono"))
        self.actionmono_to_png.setText(_translate("MainUI", "mono to png"))
        self.actiontiff_to_png.setText(_translate("MainUI", "tiff to png"))
        self.actionGreek.setText(_translate("MainUI", "Greek"))
        self.actiontiff_to_png_2.setText(_translate("MainUI", "tiff to png"))
        self.actionpdf_for_tiff.setText(_translate("MainUI", "pdf for tiff"))
        self.actionpdf_for_tiff_tb.setText(_translate("MainUI", "pdf For tiff"))
        self.actionpdf_for_tiff_tb.setToolTip(_translate("MainUI", "Stage extracted pdf pages FOR tif conversion"))
        self.actionpdf_for_tiff_tb.setStatusTip(_translate("MainUI", "Staging extracted pdf pages..."))
        self.actionpdf_to_tiff_tb.setText(_translate("MainUI", "pdf To tiff"))
        self.actionpdf_to_tiff_tb.setToolTip(_translate("MainUI", "Convert staged pdf pages TO tif pages"))
        self.actionpdf_to_tiff_tb.setStatusTip(_translate("MainUI", "Converting staged pdf pages..."))
        self.actiontiff_to_mono_tb.setText(_translate("MainUI", "tiff indexed"))
        self.actiontiff_to_mono_tb.setToolTip(_translate("MainUI", "Convert tif pages TO black&white indexed"))
        self.actiontiff_to_mono_tb.setStatusTip(_translate("MainUI", "Converting tif pages to black&white indexed..."))
        self.actionmono_to_png_tb.setText(_translate("MainUI", "png indexed"))
        self.actionmono_to_png_tb.setToolTip(_translate("MainUI", "Convert indexed tif pages TO png"))
        self.actionmono_to_png_tb.setStatusTip(_translate("MainUI", "Converting indexed tif pages to png pages..."))
        self.actionLatin.setText(_translate("MainUI", "Latin"))
        self.actiontiff_to_png_3.setText(_translate("MainUI", "tiff to png"))
        self.actiontiff_to_png_4.setText(_translate("MainUI", "tiff to png"))
        self.actionDeskewGreek_tiff_tb.setText(_translate("MainUI", "Deskew Greek tiff"))
        self.actionDeskewGreek_tiff_tb.setToolTip(_translate("MainUI", "Deskew Greek tif pages"))
        self.actionDeskewGreek_tiff_tb.setStatusTip(_translate("MainUI", "Deskewing Greek tif pages..."))
        self.actiontiff_to_png_5.setText(_translate("MainUI", "tiff to png"))
        self.actionDeskewLatin_tiff_tb.setText(_translate("MainUI", "Deskew Latin tif pages"))
        self.actionDeskewLatin_tiff_tb.setStatusTip(_translate("MainUI", "Deskewing Latin tif pages..."))
        self.actionResizeGreek_png_tb.setText(_translate("MainUI", "Resize Greek png pages"))
        self.actionResizeGreek_png_tb.setStatusTip(_translate("MainUI", "Resizing Greek png pages..."))
        self.actionResizeLatin_png_tb.setText(_translate("MainUI", "Resize Latin png pages"))
        self.actionResizeLatin_png_tb.setStatusTip(_translate("MainUI", "Resizing Latin png pages"))
        self.actionCrop_Languages_tb.setText(_translate("MainUI", "Auto Crop Languages"))
        self.actionCrop_Languages_tb.setToolTip(_translate("MainUI", "Auto crop language pages into separate tif files"))
        self.actionCrop_Languages_tb.setStatusTip(_translate("MainUI", "Auto cropping language pages..."))
        self.actionextract_pdf_tb.setText(_translate("MainUI", "Extract pdf"))
        self.actionextract_pdf_tb.setToolTip(_translate("MainUI", "Extract pdf pages from pdf source document"))
        self.actionextract_pdf_tb.setStatusTip(_translate("MainUI", "Extracting pdf pages..."))
        self.actiontiff_for_Ground_Truth.setText(_translate("MainUI", "tiff for Ground Truth"))
        self.actionCrop.setText(_translate("MainUI", "Crop to tiff lines"))
        self.actiontiff_for_Ground_Truth_2.setText(_translate("MainUI", "Move tiff lines"))
        self.actionSplit.setText(_translate("MainUI", "Split text lines"))
        self.actionRename_tiff_lines.setText(_translate("MainUI", "Rename tiff lines"))
        self.actionRename_text_lines.setText(_translate("MainUI", "Rename text lines"))
        self.actionReview_Ground_Truth.setText(_translate("MainUI", "Review Ground Truth"))
        self.actionGreek_Wordlist_2.setText(_translate("MainUI", "Greek Wordlist"))
        self.actionLatin_Wordlist.setText(_translate("MainUI", "Latin Wordlist"))
        self.actionImage_Lines.setText(_translate("MainUI", "Image Lines"))
        self.actionText_Lines.setText(_translate("MainUI", "Text Lines"))
        self.actionReview_Ground_Truth_2.setText(_translate("MainUI", "Review Ground Truth"))
        self.actionUpdate_Wordlist.setText(_translate("MainUI", "Update Wordlist"))
        self.actionUpdate_Wordlist_2.setText(_translate("MainUI", "Update Wordlist"))
        self.actionCorrect_OCR_tb.setText(_translate("MainUI", "OCR Image"))
        self.actionCorrect_OCR_tb.setToolTip(_translate("MainUI", "OCR current image"))
        self.actionCorrect_OCR_tb.setStatusTip(_translate("MainUI", "Performing OCR on current image..."))
        self.actionVersify_Text.setText(_translate("MainUI", "Versify Text"))
        self.actionUpdate_Words.setText(_translate("MainUI", "Latin"))
        self.actionUpdate_Verses.setText(_translate("MainUI", "Update Verses"))
        self.actionUpdate_Words_Post.setText(_translate("MainUI", "Update Words"))
        self.actionNormalize.setText(_translate("MainUI", "Normalize"))
        self.actionLower_Case.setText(_translate("MainUI", "Lower Case"))
        self.actionRemove_Diacritics.setText(_translate("MainUI", "Remove Diacritics"))
        self.actionAlign_Strongs.setText(_translate("MainUI", "Align Strongs+RMAC"))
        self.actionAlign_Lemmas.setText(_translate("MainUI", "Align Lemmas"))
        self.actionAlign_English.setText(_translate("MainUI", "Align English"))
        self.actionVariants.setText(_translate("MainUI", "Resolve Variants"))
        self.actionTrain_Tesseract_tb.setText(_translate("MainUI", "Train Tesseract"))
        self.actionTrain_Tesseract_tb.setToolTip(_translate("MainUI", "Train Tesseract OCR with current Ground Truth"))
        self.actionTrain_Tesseract_tb.setStatusTip(_translate("MainUI", "Training Tesseract OCR with current Ground Truth..."))
        self.actionReview_Ground_Truth_tb.setText(_translate("MainUI", "Validate Ground Truth"))
        self.actionReview_Ground_Truth_tb.setToolTip(_translate("MainUI", "Validate current Ground Truth image|text"))
        self.actionReview_Ground_Truth_tb.setStatusTip(_translate("MainUI", "Validating current Ground Truth image|text pairs..."))
        self.actionUpdate_Wordlist_tb.setText(_translate("MainUI", "Update Greek Wordlist"))
        self.actionUpdate_Wordlist_tb.setToolTip(_translate("MainUI", "Update Greek Wordlist for OCR Training"))
        self.actionUpdate_Wordlist_tb.setStatusTip(_translate("MainUI", "Upadting Greek wordlist..."))
        self.actionAutoCrop_Greek_to_tif_Lines_tb.setText(_translate("MainUI", "Crop Greek To tif Lines"))
        self.actionAutoCrop_Greek_to_tif_Lines_tb.setStatusTip(_translate("MainUI", "Auto cropping Greek tif lines...."))
        self.actionRename_Greek_tif_Lines_tb.setText(_translate("MainUI", "Rename Greek tif Lines"))
        self.actionRename_Greek_tif_Lines_tb.setStatusTip(_translate("MainUI", "Renaming Greek tif lines..."))
        self.actionMove_Greek_tif_Lines_tb.setText(_translate("MainUI", "Move Greek tif Lines"))
        self.actionMove_Greek_tif_Lines_tb.setStatusTip(_translate("MainUI", "Moving Greek tif lines..."))
        self.actionSplitGreek_text_lines_tb.setText(_translate("MainUI", "Split Greek Pages To Text Lines"))
        self.actionSplitGreek_text_lines_tb.setStatusTip(_translate("MainUI", "Splitting Greek pages to text lines..."))
        self.actionRenameGreek_text_lines_tb.setText(_translate("MainUI", "Rename Greek Text Lines"))
        self.actionRenameGreek_text_lines_tb.setStatusTip(_translate("MainUI", "Renaming Greek text lines..."))
        self.actionImage_Lines_3.setText(_translate("MainUI", "Image Lines"))
        self.actionReview_Ground_Truth_menu.setText(_translate("MainUI", "Review Ground Truth"))
        self.actionUpdate_Wordlist_menu.setText(_translate("MainUI", "Update Latin Wordlist"))
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setText(_translate("MainUI", "Crop Latin To tif Lines"))
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setIconText(_translate("MainUI", "Crop Latin To tif Lines"))
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setToolTip(_translate("MainUI", "Crop Latin To tif Lines"))
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setStatusTip(_translate("MainUI", "Auto croping Latin tif lines..."))
        self.actionRename_Latin_tif_Lines_tb.setText(_translate("MainUI", "Rename Latin tif Lines"))
        self.actionRename_Latin_tif_Lines_tb.setStatusTip(_translate("MainUI", "Renaming Latin tif lines..."))
        self.actionMove_Latin_tif_Lines_tb.setText(_translate("MainUI", "Move Latin tif Lines"))
        self.actionMove_Latin_tif_Lines_tb.setStatusTip(_translate("MainUI", "Moving Latin tif lines..."))
        self.actionSplit_Latin_Text_Lines_tb.setText(_translate("MainUI", "Split Latin Pages To Text Lines"))
        self.actionSplit_Latin_Text_Lines_tb.setStatusTip(_translate("MainUI", "Splitting Latin pages to text lines..."))
        self.actionRename_Latin_Text_Lines_tb.setText(_translate("MainUI", "Rename Latin Text Lines"))
        self.actionRename_Latin_Text_Lines_tb.setStatusTip(_translate("MainUI", "Renaming Latin text lines..."))
        self.actiondeskew_mono.setText(_translate("MainUI", "Deskew indexed"))
        self.actiondeskew_mono.setToolTip(_translate("MainUI", "Transform indexed tif pages To deskewed tif and png pages"))
        self.actiondeskew_mono.setStatusTip(_translate("MainUI", "Deskewing indexed tif pages..."))
        self.actionOpen_Image.setText(_translate("MainUI", "Open Image"))
        self.actionVerse_Correction.setText(_translate("MainUI", "Verse Correction"))
        self.actionVerse_Correction.setToolTip(_translate("MainUI", "Book Chapter:Verse Text Assignment"))
        self.actionVerse_Correction.setStatusTip(_translate("MainUI", "Assigning Book Chapter:Verse to text lines"))
        self.actionConvert_Greek_tiff_To_png.setText(_translate("MainUI", "Convert Greek tif To png"))
        self.actionConvert_Greek_tiff_To_png.setStatusTip(_translate("MainUI", "Converting Greek tif pages to png pages"))
        self.actionConvert_Latin_tiff_To_png.setText(_translate("MainUI", "Convert Latin tif To png"))
        self.actionConvert_Latin_tiff_To_png.setToolTip(_translate("MainUI", "Convert Latin tif pages To png pages"))
        self.actionConvert_Latin_tiff_To_png.setStatusTip(_translate("MainUI", "Converting Latin tif pages To png pages"))
        self.actionExtract_Glyphs.setText(_translate("MainUI", "GlyphTracer"))
        self.actionExtract_Glyphs.setToolTip(_translate("MainUI", "Extract and trace bitmap glyphs with GlyphTracer"))
        self.actionExtract_Glyphs.setStatusTip(_translate("MainUI", "Extracting and trace bitmap glyphs with GlyphTracer..."))
        self.actionLine_tif_to_bmp.setText(_translate("MainUI", "Convert tif To bmp"))
        self.actionLine_tif_to_bmp.setToolTip(_translate("MainUI", "Convert current tif image to bmp"))
        self.actionLine_tif_to_bmp.setStatusTip(_translate("MainUI", "Converting current tif image to bmp..."))
        self.actionFontForge.setText(_translate("MainUI", "FontForge"))
        self.actionFontForge.setToolTip(_translate("MainUI", "Edit current GlyphTracer sfd file in FontForge"))
        self.actionFontForge.setStatusTip(_translate("MainUI", "Editing current GlyphTracer sfd file in FontForge..."))
        self.actionPrefernces.setText(_translate("MainUI", "Preferences"))
        self.actionOpen_Text.setText(_translate("MainUI", "Open Text"))
        self.actionSave_Image.setText(_translate("MainUI", "Save Image"))
        self.actionSave_As_Image.setText(_translate("MainUI", "Save As Image"))
        self.actionSave_Text.setText(_translate("MainUI", "Save Text"))
        self.actionSave_As_Text.setText(_translate("MainUI", "Save As Text"))
        self.actionConvert_Image_s.setText(_translate("MainUI", "Convert Image(s)"))
        self.actionReview_Ground_Truth_3.setText(_translate("MainUI", "Review Ground Truth"))
        self.actionHebrew.setText(_translate("MainUI", "Hebrew"))
        self.actionHebrew_2.setText(_translate("MainUI", "Hebrew"))
        self.actionUpdate_Hebrew_Wordlist.setText(_translate("MainUI", "Update Hebrew Wordlist"))
        self.actionHebrew_3.setText(_translate("MainUI", "Hebrew"))
        self.actionOCR_Image.setText(_translate("MainUI", "OCR Image"))
        self.actionSelect_Image.setText(_translate("MainUI", "Select Image"))
        self.actionGreek_2.setText(_translate("MainUI", "Greek"))
        self.actionHebrew_4.setText(_translate("MainUI", "Hebrew"))
        self.actionLatin_2.setText(_translate("MainUI", "Latin"))
        self.actionSelect_Language_Model.setText(_translate("MainUI", "Select Language Model"))
        self.actionSelect_Fonts.setText(_translate("MainUI", "Select Fonts"))
        self.actionany.setText(_translate("MainUI", "any"))
        self.actionAny.setText(_translate("MainUI", "Any"))
        self.actionStage_Ground_Truth.setText(_translate("MainUI", "Stage Ground Truth"))
        self.actionCreate_e_Sword_Bible_Module.setText(_translate("MainUI", "e-Sword Bible Module"))
        self.actionCreate_theWord_Bible_Module.setText(_translate("MainUI", "theWord Bible Module"))
        self.actionEnglish.setText(_translate("MainUI", "English"))
        self.actionEnglishh.setText(_translate("MainUI", "English"))
        self.actionEnglish_2.setText(_translate("MainUI", "English"))
        self.actionEnglish_3.setText(_translate("MainUI", "English"))
        self.actionOnline.setText(_translate("MainUI", "Online"))
        self.actionManual_Crop_Image_tb.setText(_translate("MainUI", "Manual Crop"))
        self.actionManual_Crop_Image_tb.setToolTip(_translate("MainUI", "Manually crop current tif image"))
        self.actionManual_Crop_Image_tb.setStatusTip(_translate("MainUI", "Manually cropping current tif image..."))
        self.actionEdit_Image_tb.setText(_translate("MainUI", "Gimp Image Editor"))
        self.actionEdit_Image_tb.setStatusTip(_translate("MainUI", "Editing image in Gimp..."))
        self.actionLibreOffice_Writer.setText(_translate("MainUI", "LibreOffice Writer"))
        self.actionLibreOffice_Calc.setText(_translate("MainUI", "LibreOffice Calc"))
        self.actionDB_Browser_for_SQLite.setText(_translate("MainUI", "DB Browser for SQLite"))
        self.actionFind_and_Replace.setText(_translate("MainUI", "Find and Replace"))
        self.actionInstall_Font.setText(_translate("MainUI", "Install Font"))
        self.actionToggle_Greek_Toolbars.setText(_translate("MainUI", "Toggle Greek Toolbars"))
        self.actionToggle_Latin_Toolbars.setText(_translate("MainUI", "Toggle Latin Toolbars"))
        self.actionPrepare_Text.setText(_translate("MainUI", "Prepare Text"))
        self.actionEnglish_4.setText(_translate("MainUI", "English"))
        self.actionLatin_3.setText(_translate("MainUI", "Latin"))
        self.actionStart.setText(_translate("MainUI", "Start"))
        self.actionHebrew_5.setText(_translate("MainUI", "Hebrew"))
        self.actionGimp.setText(_translate("MainUI", "Gimp"))
        self.actionLibre_Office_Writer.setText(_translate("MainUI", "Libre Office Writer"))
        self.actionLibre_Office_Calc.setText(_translate("MainUI", "Libre Office Calc"))
        self.actionFont_Forge.setText(_translate("MainUI", "Font Forge"))
        self.actionDeveloper.setText(_translate("MainUI", "Developer"))
        self.actionAcademic.setText(_translate("MainUI", "Academic"))
        self.actionMistry.setText(_translate("MainUI", "Ministry"))
        self.actionPixler_Image_Editor.setText(_translate("MainUI", "Pixer Image Editor"))

import UI_Icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainUI = QtWidgets.QMainWindow()
    ui = Ui_MainUI()
    ui.setupUi(MainUI)
    MainUI.show()
    sys.exit(app.exec_())

