# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Developer/QtDesignerUI/ProjectCreationWizardDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectCreationWizardDialog(object):
    def setupUi(self, ProjectCreationWizardDialog):
        ProjectCreationWizardDialog.setObjectName("ProjectCreationWizardDialog")
        ProjectCreationWizardDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ProjectCreationWizardDialog.resize(760, 680)
        ProjectCreationWizardDialog.setMinimumSize(QtCore.QSize(640, 420))
        ProjectCreationWizardDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProjectCreationWizardDialog)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.intro_label = QtWidgets.QLabel(ProjectCreationWizardDialog)
        self.intro_label.setWordWrap(True)
        self.intro_label.setObjectName("intro_label")
        self.verticalLayout.addWidget(self.intro_label)
        self.page_title_label = QtWidgets.QLabel(ProjectCreationWizardDialog)
        self.page_title_label.setObjectName("page_title_label")
        self.verticalLayout.addWidget(self.page_title_label)
        self.page_stack = QtWidgets.QStackedWidget(ProjectCreationWizardDialog)
        self.page_stack.setObjectName("page_stack")
        self.verticalLayout.addWidget(self.page_stack)
        self.source_load_status_label = QtWidgets.QLabel(ProjectCreationWizardDialog)
        self.source_load_status_label.setVisible(False)
        self.source_load_status_label.setObjectName("source_load_status_label")
        self.verticalLayout.addWidget(self.source_load_status_label)
        self.source_load_progress_bar = QtWidgets.QProgressBar(ProjectCreationWizardDialog)
        self.source_load_progress_bar.setVisible(False)
        self.source_load_progress_bar.setProperty("value", 0)
        self.source_load_progress_bar.setTextVisible(True)
        self.source_load_progress_bar.setObjectName("source_load_progress_bar")
        self.verticalLayout.addWidget(self.source_load_progress_bar)
        self.navigation_layout = QtWidgets.QHBoxLayout()
        self.navigation_layout.setObjectName("navigation_layout")
        self.back_button = QtWidgets.QPushButton(ProjectCreationWizardDialog)
        self.back_button.setObjectName("back_button")
        self.navigation_layout.addWidget(self.back_button)
        self.next_button = QtWidgets.QPushButton(ProjectCreationWizardDialog)
        self.next_button.setObjectName("next_button")
        self.navigation_layout.addWidget(self.next_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.navigation_layout.addItem(spacerItem)
        self.cancel_button = QtWidgets.QPushButton(ProjectCreationWizardDialog)
        self.cancel_button.setObjectName("cancel_button")
        self.navigation_layout.addWidget(self.cancel_button)
        self.create_button = QtWidgets.QPushButton(ProjectCreationWizardDialog)
        self.create_button.setObjectName("create_button")
        self.navigation_layout.addWidget(self.create_button)
        self.verticalLayout.addLayout(self.navigation_layout)

        self.retranslateUi(ProjectCreationWizardDialog)
        QtCore.QMetaObject.connectSlotsByName(ProjectCreationWizardDialog)

    def retranslateUi(self, ProjectCreationWizardDialog):
        _translate = QtCore.QCoreApplication.translate
        ProjectCreationWizardDialog.setWindowTitle(_translate("ProjectCreationWizardDialog", "New Project"))
        self.intro_label.setText(_translate("ProjectCreationWizardDialog", "Create a new project from the current trimmed manifest. You can also load provenance from JSON, RIS, TXT, or CSV before creation starts."))
        self.page_title_label.setText(_translate("ProjectCreationWizardDialog", "Step 1 of 5: RIS import"))
        self.source_load_status_label.setText(_translate("ProjectCreationWizardDialog", "Preparing source document..."))
        self.back_button.setText(_translate("ProjectCreationWizardDialog", "Back"))
        self.next_button.setText(_translate("ProjectCreationWizardDialog", "Next"))
        self.cancel_button.setText(_translate("ProjectCreationWizardDialog", "Cancel"))
        self.create_button.setText(_translate("ProjectCreationWizardDialog", "Create Project"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectCreationWizardDialog = QtWidgets.QDialog()
    ui = Ui_ProjectCreationWizardDialog()
    ui.setupUi(ProjectCreationWizardDialog)
    ProjectCreationWizardDialog.show()
    sys.exit(app.exec_())
