# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jetson/Projects/BiblionOCR/ViewController/0-MainUI/QtDesignerUI/ChrReferenceDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CharRef(object):
    def setupUi(self, CharRef):
        CharRef.setObjectName("CharRef")
        CharRef.resize(591, 829)
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(9)
        CharRef.setFont(font)
        self.chrTableWidget = QtWidgets.QTableWidget(CharRef)
        self.chrTableWidget.setGeometry(QtCore.QRect(20, 260, 551, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chrTableWidget.sizePolicy().hasHeightForWidth())
        self.chrTableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(12)
        self.chrTableWidget.setFont(font)
        self.chrTableWidget.setAcceptDrops(False)
        self.chrTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.chrTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.chrTableWidget.setWordWrap(False)
        self.chrTableWidget.setCornerButtonEnabled(False)
        self.chrTableWidget.setObjectName("chrTableWidget")
        self.chrTableWidget.setColumnCount(0)
        self.chrTableWidget.setRowCount(0)
        self.fontlabel = QtWidgets.QLabel(CharRef)
        self.fontlabel.setGeometry(QtCore.QRect(290, 120, 50, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fontlabel.setFont(font)
        self.fontlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fontlabel.setObjectName("fontlabel")
        self.chrSelected = QtWidgets.QLineEdit(CharRef)
        self.chrSelected.setGeometry(QtCore.QRect(90, 50, 171, 131))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(9)
        self.chrSelected.setFont(font)
        self.chrSelected.setAlignment(QtCore.Qt.AlignCenter)
        self.chrSelected.setReadOnly(True)
        self.chrSelected.setObjectName("chrSelected")
        self.uCodeRangeComboBox = QtWidgets.QComboBox(CharRef)
        self.uCodeRangeComboBox.setGeometry(QtCore.QRect(350, 50, 181, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(9)
        self.uCodeRangeComboBox.setFont(font)
        self.uCodeRangeComboBox.setObjectName("uCodeRangeComboBox")
        self.fontSizeBox = QtWidgets.QSpinBox(CharRef)
        self.fontSizeBox.setGeometry(QtCore.QRect(520, 120, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(9)
        self.fontSizeBox.setFont(font)
        self.fontSizeBox.setAlignment(QtCore.Qt.AlignCenter)
        self.fontSizeBox.setMinimum(6)
        self.fontSizeBox.setMaximum(100)
        self.fontSizeBox.setProperty("value", 20)
        self.fontSizeBox.setObjectName("fontSizeBox")
        self.uCodeUTFLabel = QtWidgets.QLabel(CharRef)
        self.uCodeUTFLabel.setGeometry(QtCore.QRect(290, 90, 51, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.uCodeUTFLabel.setFont(font)
        self.uCodeUTFLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uCodeUTFLabel.setObjectName("uCodeUTFLabel")
        self.uCodeRangeLabel = QtWidgets.QLabel(CharRef)
        self.uCodeRangeLabel.setGeometry(QtCore.QRect(260, 50, 81, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.uCodeRangeLabel.setFont(font)
        self.uCodeRangeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uCodeRangeLabel.setObjectName("uCodeRangeLabel")
        self.uCodeEndRangeLabel = QtWidgets.QLabel(CharRef)
        self.uCodeEndRangeLabel.setGeometry(QtCore.QRect(460, 80, 16, 10))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(6)
        self.uCodeEndRangeLabel.setFont(font)
        self.uCodeEndRangeLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.uCodeEndRangeLabel.setObjectName("uCodeEndRangeLabel")
        self.uCodeStartRangeLabel = QtWidgets.QLabel(CharRef)
        self.uCodeStartRangeLabel.setGeometry(QtCore.QRect(350, 80, 21, 10))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(6)
        self.uCodeStartRangeLabel.setFont(font)
        self.uCodeStartRangeLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.uCodeStartRangeLabel.setObjectName("uCodeStartRangeLabel")
        self.GlyphNameLE = QtWidgets.QLineEdit(CharRef)
        self.GlyphNameLE.setEnabled(True)
        self.GlyphNameLE.setGeometry(QtCore.QRect(20, 20, 241, 21))
        self.GlyphNameLE.setObjectName("GlyphNameLE")
        self.fontComboBox = QtWidgets.QFontComboBox(CharRef)
        self.fontComboBox.setGeometry(QtCore.QRect(350, 120, 161, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fontComboBox.setFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.chrString = QtWidgets.QLineEdit(CharRef)
        self.chrString.setGeometry(QtCore.QRect(270, 190, 301, 61))
        self.chrString.setObjectName("chrString")
        self.Glyph = QtWidgets.QLabel(CharRef)
        self.Glyph.setGeometry(QtCore.QRect(20, 50, 61, 61))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(9)
        self.Glyph.setFont(font)
        self.Glyph.setFrameShape(QtWidgets.QFrame.Box)
        self.Glyph.setAlignment(QtCore.Qt.AlignCenter)
        self.Glyph.setObjectName("Glyph")
        self.nextButton = QtWidgets.QPushButton(CharRef)
        self.nextButton.setGeometry(QtCore.QRect(160, 230, 31, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(10)
        self.nextButton.setFont(font)
        self.nextButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/forward_alt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon)
        self.nextButton.setObjectName("nextButton")
        self.prevButton = QtWidgets.QPushButton(CharRef)
        self.prevButton.setGeometry(QtCore.QRect(90, 230, 31, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(10)
        self.prevButton.setFont(font)
        self.prevButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/back_alt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevButton.setIcon(icon1)
        self.prevButton.setObjectName("prevButton")
        self.chrSelectedFontSize = QtWidgets.QSpinBox(CharRef)
        self.chrSelectedFontSize.setGeometry(QtCore.QRect(20, 130, 61, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(9)
        self.chrSelectedFontSize.setFont(font)
        self.chrSelectedFontSize.setAlignment(QtCore.Qt.AlignCenter)
        self.chrSelectedFontSize.setMinimum(6)
        self.chrSelectedFontSize.setMaximum(80)
        self.chrSelectedFontSize.setProperty("value", 80)
        self.chrSelectedFontSize.setObjectName("chrSelectedFontSize")
        self.GSubLE = QtWidgets.QLineEdit(CharRef)
        self.GSubLE.setEnabled(False)
        self.GSubLE.setGeometry(QtCore.QRect(440, 160, 51, 21))
        self.GSubLE.setObjectName("GSubLE")
        self.gSubLabel = QtWidgets.QLabel(CharRef)
        self.gSubLabel.setGeometry(QtCore.QRect(440, 150, 21, 10))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(6)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.gSubLabel.setFont(font)
        self.gSubLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gSubLabel.setObjectName("gSubLabel")
        self.ligCheckBox = QtWidgets.QCheckBox(CharRef)
        self.ligCheckBox.setGeometry(QtCore.QRect(350, 150, 71, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.ligCheckBox.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/tick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ligCheckBox.setIcon(icon2)
        self.ligCheckBox.setIconSize(QtCore.QSize(10, 10))
        self.ligCheckBox.setObjectName("ligCheckBox")
        self.uCodeAddRangeButton = QtWidgets.QPushButton(CharRef)
        self.uCodeAddRangeButton.setGeometry(QtCore.QRect(530, 50, 16, 20))
        self.uCodeAddRangeButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/plus-small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uCodeAddRangeButton.setIcon(icon3)
        self.uCodeAddRangeButton.setIconSize(QtCore.QSize(16, 16))
        self.uCodeAddRangeButton.setObjectName("uCodeAddRangeButton")
        self.uCodeSelectionLabel = QtWidgets.QLabel(CharRef)
        self.uCodeSelectionLabel.setGeometry(QtCore.QRect(20, 0, 51, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.uCodeSelectionLabel.setFont(font)
        self.uCodeSelectionLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.uCodeSelectionLabel.setObjectName("uCodeSelectionLabel")
        self.uCodeSelectedLE = QtWidgets.QLineEdit(CharRef)
        self.uCodeSelectedLE.setEnabled(True)
        self.uCodeSelectedLE.setGeometry(QtCore.QRect(270, 20, 61, 20))
        self.uCodeSelectedLE.setText("")
        self.uCodeSelectedLE.setReadOnly(True)
        self.uCodeSelectedLE.setObjectName("uCodeSelectedLE")
        self.hexRadioButton = QtWidgets.QRadioButton(CharRef)
        self.hexRadioButton.setGeometry(QtCore.QRect(350, 20, 41, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.hexRadioButton.setFont(font)
        self.hexRadioButton.setChecked(True)
        self.hexRadioButton.setObjectName("hexRadioButton")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(CharRef)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.hexRadioButton)
        self.decRadioButton = QtWidgets.QRadioButton(CharRef)
        self.decRadioButton.setGeometry(QtCore.QRect(400, 20, 41, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.decRadioButton.setFont(font)
        self.decRadioButton.setObjectName("decRadioButton")
        self.buttonGroup_2.addButton(self.decRadioButton)
        self.uCodeRemoveRangeButton = QtWidgets.QPushButton(CharRef)
        self.uCodeRemoveRangeButton.setGeometry(QtCore.QRect(550, 50, 16, 20))
        self.uCodeRemoveRangeButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/minus-small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uCodeRemoveRangeButton.setIcon(icon4)
        self.uCodeRemoveRangeButton.setIconSize(QtCore.QSize(16, 16))
        self.uCodeRemoveRangeButton.setObjectName("uCodeRemoveRangeButton")
        self.uCodeStartRangeComboBox = QtWidgets.QComboBox(CharRef)
        self.uCodeStartRangeComboBox.setGeometry(QtCore.QRect(350, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.uCodeStartRangeComboBox.setFont(font)
        self.uCodeStartRangeComboBox.setObjectName("uCodeStartRangeComboBox")
        self.uCodeEndRangeComboBox = QtWidgets.QComboBox(CharRef)
        self.uCodeEndRangeComboBox.setGeometry(QtCore.QRect(460, 90, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.uCodeEndRangeComboBox.setFont(font)
        self.uCodeEndRangeComboBox.setObjectName("uCodeEndRangeComboBox")
        self.copyButton = QtWidgets.QPushButton(CharRef)
        self.copyButton.setGeometry(QtCore.QRect(550, 170, 20, 20))
        self.copyButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/document-copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyButton.setIcon(icon5)
        self.copyButton.setObjectName("copyButton")
        self.favoritesableView = QtWidgets.QTableView(CharRef)
        self.favoritesableView.setGeometry(QtCore.QRect(20, 190, 241, 31))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(10)
        self.favoritesableView.setFont(font)
        self.favoritesableView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.favoritesableView.setObjectName("favoritesableView")
        self.favoritesLabel = QtWidgets.QLabel(CharRef)
        self.favoritesLabel.setGeometry(QtCore.QRect(20, 180, 31, 10))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(6)
        self.favoritesLabel.setFont(font)
        self.favoritesLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.favoritesLabel.setObjectName("favoritesLabel")
        self.favoritesLabel_2 = QtWidgets.QLabel(CharRef)
        self.favoritesLabel_2.setGeometry(QtCore.QRect(20, 120, 61, 10))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(6)
        self.favoritesLabel_2.setFont(font)
        self.favoritesLabel_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.favoritesLabel_2.setObjectName("favoritesLabel_2")
        self.favoritesLabel_3 = QtWidgets.QLabel(CharRef)
        self.favoritesLabel_3.setGeometry(QtCore.QRect(270, 180, 41, 10))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(6)
        self.favoritesLabel_3.setFont(font)
        self.favoritesLabel_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.favoritesLabel_3.setObjectName("favoritesLabel_3")
        self.fontlabel.raise_()
        self.chrSelected.raise_()
        self.uCodeRangeComboBox.raise_()
        self.fontSizeBox.raise_()
        self.uCodeUTFLabel.raise_()
        self.uCodeRangeLabel.raise_()
        self.uCodeEndRangeLabel.raise_()
        self.uCodeStartRangeLabel.raise_()
        self.GlyphNameLE.raise_()
        self.fontComboBox.raise_()
        self.chrString.raise_()
        self.Glyph.raise_()
        self.nextButton.raise_()
        self.prevButton.raise_()
        self.chrSelectedFontSize.raise_()
        self.GSubLE.raise_()
        self.gSubLabel.raise_()
        self.ligCheckBox.raise_()
        self.uCodeAddRangeButton.raise_()
        self.uCodeSelectionLabel.raise_()
        self.uCodeSelectedLE.raise_()
        self.hexRadioButton.raise_()
        self.decRadioButton.raise_()
        self.uCodeRemoveRangeButton.raise_()
        self.uCodeStartRangeComboBox.raise_()
        self.uCodeEndRangeComboBox.raise_()
        self.copyButton.raise_()
        self.favoritesableView.raise_()
        self.favoritesLabel.raise_()
        self.favoritesLabel_2.raise_()
        self.favoritesLabel_3.raise_()
        self.chrTableWidget.raise_()

        self.retranslateUi(CharRef)
        QtCore.QMetaObject.connectSlotsByName(CharRef)

    def retranslateUi(self, CharRef):
        _translate = QtCore.QCoreApplication.translate
        CharRef.setWindowTitle(_translate("CharRef", "Character Reference"))
        self.fontlabel.setText(_translate("CharRef", "Font"))
        self.chrSelected.setToolTip(_translate("CharRef", "Selected Character"))
        self.chrSelected.setText(_translate("CharRef", "TEXT"))
        self.uCodeRangeComboBox.setToolTip(_translate("CharRef", "Select Unicode Point Range"))
        self.fontSizeBox.setToolTip(_translate("CharRef", "Select font size"))
        self.uCodeUTFLabel.setText(_translate("CharRef", "UTF-8"))
        self.uCodeRangeLabel.setText(_translate("CharRef", "Unicode Range"))
        self.uCodeEndRangeLabel.setText(_translate("CharRef", "End"))
        self.uCodeStartRangeLabel.setText(_translate("CharRef", "Start"))
        self.GlyphNameLE.setToolTip(_translate("CharRef", "Glyph Name"))
        self.fontComboBox.setToolTip(_translate("CharRef", "Select font"))
        self.fontComboBox.setCurrentText(_translate("CharRef", "FROMVS"))
        self.chrString.setToolTip(_translate("CharRef", "Selected Characters Text"))
        self.Glyph.setToolTip(_translate("CharRef", "Glyph"))
        self.Glyph.setText(_translate("CharRef", "Glyph"))
        self.nextButton.setToolTip(_translate("CharRef", "nextCharacter"))
        self.prevButton.setToolTip(_translate("CharRef", "prevCharacter"))
        self.chrSelectedFontSize.setToolTip(_translate("CharRef", "Select font size"))
        self.GSubLE.setToolTip(_translate("CharRef", "Ligature Substitution Characters"))
        self.gSubLabel.setText(_translate("CharRef", "GSUB"))
        self.ligCheckBox.setToolTip(_translate("CharRef", "Ligature"))
        self.ligCheckBox.setText(_translate("CharRef", "Ligature"))
        self.uCodeAddRangeButton.setToolTip(_translate("CharRef", "Add Unicode Point Range"))
        self.uCodeSelectionLabel.setText(_translate("CharRef", "Selection"))
        self.uCodeSelectedLE.setToolTip(_translate("CharRef", "Selected Unicode Point"))
        self.hexRadioButton.setToolTip(_translate("CharRef", "Show Hexadecimal Unicode Points"))
        self.hexRadioButton.setText(_translate("CharRef", "Hex"))
        self.decRadioButton.setToolTip(_translate("CharRef", "Show Decimal Unicode Points"))
        self.decRadioButton.setText(_translate("CharRef", "Dec"))
        self.uCodeRemoveRangeButton.setToolTip(_translate("CharRef", "Remove Unicode Point Range"))
        self.uCodeStartRangeComboBox.setToolTip(_translate("CharRef", "Start Unicode Point Range"))
        self.uCodeEndRangeComboBox.setToolTip(_translate("CharRef", "End Unicode Point Range"))
        self.favoritesableView.setToolTip(_translate("CharRef", "Favorites"))
        self.favoritesLabel.setText(_translate("CharRef", "Favorites"))
        self.favoritesLabel_2.setText(_translate("CharRef", "Glyph Size"))
        self.favoritesLabel_3.setText(_translate("CharRef", "Characters"))
import UI_Icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CharRef = QtWidgets.QDialog()
    ui = Ui_CharRef()
    ui.setupUi(CharRef)
    CharRef.show()
    sys.exit(app.exec_())
