# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jetson/Projects/BiblionOCR/ViewController/0-MainUI/QtDesignerUI/MyGrounderUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Grounder(object):
    def setupUi(self, Grounder):
        Grounder.setObjectName("Grounder")
        Grounder.resize(796, 982)
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        Grounder.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionGrounder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Grounder.setWindowIcon(icon)
        Grounder.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        Grounder.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Grounder)
        self.centralwidget.setObjectName("centralwidget")
        self.ImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.ImageButton.setGeometry(QtCore.QRect(50, 190, 81, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.ImageButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ImageButton.setIcon(icon1)
        self.ImageButton.setObjectName("ImageButton")
        self.TextButton = QtWidgets.QPushButton(self.centralwidget)
        self.TextButton.setGeometry(QtCore.QRect(50, 350, 81, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.TextButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-document-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TextButton.setIcon(icon2)
        self.TextButton.setObjectName("TextButton")
        self.SaveImgAsButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveImgAsButton.setGeometry(QtCore.QRect(220, 190, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveImgAsButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk-rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveImgAsButton.setIcon(icon3)
        self.SaveImgAsButton.setObjectName("SaveImgAsButton")
        self.BothPrevButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothPrevButton.setGeometry(QtCore.QRect(600, 30, 71, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.BothPrevButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/ui-button-navigation-back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothPrevButton.setIcon(icon4)
        self.BothPrevButton.setAutoRepeat(True)
        self.BothPrevButton.setObjectName("BothPrevButton")
        self.BothNextButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothNextButton.setGeometry(QtCore.QRect(680, 30, 71, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.BothNextButton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/ui-button-navigation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothNextButton.setIcon(icon5)
        self.BothNextButton.setAutoRepeat(True)
        self.BothNextButton.setObjectName("BothNextButton")
        self.Imagelabel = QtWidgets.QLabel(self.centralwidget)
        self.Imagelabel.setGeometry(QtCore.QRect(50, 90, 41, 17))
        self.Imagelabel.setObjectName("Imagelabel")
        self.ImageFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.ImageFileName.setGeometry(QtCore.QRect(100, 80, 461, 31))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.ImageFileName.setFont(font)
        self.ImageFileName.setObjectName("ImageFileName")
        self.PrevImgButton = QtWidgets.QPushButton(self.centralwidget)
        self.PrevImgButton.setGeometry(QtCore.QRect(600, 90, 71, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.PrevImgButton.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/back_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PrevImgButton.setIcon(icon6)
        self.PrevImgButton.setAutoRepeat(True)
        self.PrevImgButton.setObjectName("PrevImgButton")
        self.NextImgButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextImgButton.setGeometry(QtCore.QRect(680, 90, 71, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.NextImgButton.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/forward_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextImgButton.setIcon(icon7)
        self.NextImgButton.setAutoRepeat(True)
        self.NextImgButton.setObjectName("NextImgButton")
        self.ImageView = QtWidgets.QLabel(self.centralwidget)
        self.ImageView.setGeometry(QtCore.QRect(50, 120, 691, 51))
        self.ImageView.setMinimumSize(QtCore.QSize(691, 50))
        self.ImageView.setText("")
        self.ImageView.setObjectName("ImageView")
        self.TextFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.TextFileName.setGeometry(QtCore.QRect(100, 240, 461, 31))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.TextFileName.setFont(font)
        self.TextFileName.setObjectName("TextFileName")
        self.Textlabel = QtWidgets.QLabel(self.centralwidget)
        self.Textlabel.setGeometry(QtCore.QRect(50, 250, 41, 17))
        self.Textlabel.setObjectName("Textlabel")
        self.NextTxtButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextTxtButton.setGeometry(QtCore.QRect(680, 250, 71, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.NextTxtButton.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/forward_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextTxtButton.setIcon(icon8)
        self.NextTxtButton.setAutoRepeat(True)
        self.NextTxtButton.setObjectName("NextTxtButton")
        self.PrevTxtButton = QtWidgets.QPushButton(self.centralwidget)
        self.PrevTxtButton.setGeometry(QtCore.QRect(600, 250, 71, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.PrevTxtButton.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Icons/back_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PrevTxtButton.setIcon(icon9)
        self.PrevTxtButton.setAutoRepeat(True)
        self.PrevTxtButton.setObjectName("PrevTxtButton")
        self.SaveAsButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveAsButton.setGeometry(QtCore.QRect(220, 350, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveAsButton.setFont(font)
        self.SaveAsButton.setIcon(icon3)
        self.SaveAsButton.setObjectName("SaveAsButton")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(140, 350, 71, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveButton.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveButton.setIcon(icon10)
        self.SaveButton.setObjectName("SaveButton")
        self.OCRButton = QtWidgets.QPushButton(self.centralwidget)
        self.OCRButton.setGeometry(QtCore.QRect(50, 470, 91, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.OCRButton.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/Icons/ocr3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OCRButton.setIcon(icon11)
        self.OCRButton.setObjectName("OCRButton")
        self.SaveImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveImageButton.setGeometry(QtCore.QRect(140, 190, 71, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveImageButton.setFont(font)
        self.SaveImageButton.setIcon(icon10)
        self.SaveImageButton.setObjectName("SaveImageButton")
        self.AutoScancheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.AutoScancheckBox.setEnabled(True)
        self.AutoScancheckBox.setGeometry(QtCore.QRect(460, 470, 91, 23))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.AutoScancheckBox.setFont(font)
        self.AutoScancheckBox.setIcon(icon11)
        self.AutoScancheckBox.setChecked(True)
        self.AutoScancheckBox.setObjectName("AutoScancheckBox")
        self.DiscardImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.DiscardImageButton.setGeometry(QtCore.QRect(360, 190, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.DiscardImageButton.setFont(font)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icons/Icons/scissors.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DiscardImageButton.setIcon(icon12)
        self.DiscardImageButton.setObjectName("DiscardImageButton")
        self.DiscardTextButton = QtWidgets.QPushButton(self.centralwidget)
        self.DiscardTextButton.setGeometry(QtCore.QRect(360, 350, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.DiscardTextButton.setFont(font)
        self.DiscardTextButton.setIcon(icon12)
        self.DiscardTextButton.setObjectName("DiscardTextButton")
        self.BothDiscardButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothDiscardButton.setGeometry(QtCore.QRect(360, 30, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.BothDiscardButton.setFont(font)
        self.BothDiscardButton.setIcon(icon12)
        self.BothDiscardButton.setObjectName("BothDiscardButton")
        self.BothLoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothLoadButton.setGeometry(QtCore.QRect(50, 30, 81, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.BothLoadButton.setFont(font)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Icons/Icons/synchronize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothLoadButton.setIcon(icon13)
        self.BothLoadButton.setObjectName("BothLoadButton")
        self.VerseText = QtWidgets.QTextEdit(self.centralwidget)
        self.VerseText.setGeometry(QtCore.QRect(50, 680, 701, 91))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(24)
        self.VerseText.setFont(font)
        self.VerseText.setReadOnly(False)
        self.VerseText.setObjectName("VerseText")
        self.Startcolon = QtWidgets.QLabel(self.centralwidget)
        self.Startcolon.setGeometry(QtCore.QRect(306, 790, 20, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Startcolon.setFont(font)
        self.Startcolon.setAlignment(QtCore.Qt.AlignCenter)
        self.Startcolon.setObjectName("Startcolon")
        self.StartchapterComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.StartchapterComboBox.setGeometry(QtCore.QRect(270, 790, 41, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.StartchapterComboBox.setFont(font)
        self.StartchapterComboBox.setEditable(True)
        self.StartchapterComboBox.setObjectName("StartchapterComboBox")
        self.VerseFindButton = QtWidgets.QPushButton(self.centralwidget)
        self.VerseFindButton.setGeometry(QtCore.QRect(50, 790, 81, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.VerseFindButton.setFont(font)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Icons/Icons/Magnifying Glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.VerseFindButton.setIcon(icon14)
        self.VerseFindButton.setObjectName("VerseFindButton")
        self.StartbookComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.StartbookComboBox.setGeometry(QtCore.QRect(220, 790, 51, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.StartbookComboBox.setFont(font)
        self.StartbookComboBox.setEditable(True)
        self.StartbookComboBox.setObjectName("StartbookComboBox")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartverseComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.StartverseComboBox.setGeometry(QtCore.QRect(320, 790, 41, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.StartverseComboBox.setFont(font)
        self.StartverseComboBox.setEditable(True)
        self.StartverseComboBox.setObjectName("StartverseComboBox")
        self.bookComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.bookComboBox.setGeometry(QtCore.QRect(290, 30, 51, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.bookComboBox.setFont(font)
        self.bookComboBox.setEditable(True)
        self.bookComboBox.setObjectName("bookComboBox")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.OCRModelComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.OCRModelComboBox.setGeometry(QtCore.QRect(570, 470, 51, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(10)
        self.OCRModelComboBox.setFont(font)
        self.OCRModelComboBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OCRModelComboBox.setEditable(False)
        self.OCRModelComboBox.setObjectName("OCRModelComboBox")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModellabel = QtWidgets.QLabel(self.centralwidget)
        self.OCRModellabel.setGeometry(QtCore.QRect(550, 450, 91, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.OCRModellabel.setFont(font)
        self.OCRModellabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OCRModellabel.setObjectName("OCRModellabel")
        self.OCRlangComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.OCRlangComboBox.setGeometry(QtCore.QRect(640, 470, 111, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(10)
        self.OCRlangComboBox.setFont(font)
        self.OCRlangComboBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OCRlangComboBox.setEditable(False)
        self.OCRlangComboBox.setObjectName("OCRlangComboBox")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlanglabel = QtWidgets.QLabel(self.centralwidget)
        self.OCRlanglabel.setGeometry(QtCore.QRect(630, 450, 121, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.OCRlanglabel.setFont(font)
        self.OCRlanglabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OCRlanglabel.setObjectName("OCRlanglabel")
        self.fontSizelabel = QtWidgets.QLabel(self.centralwidget)
        self.fontSizelabel.setGeometry(QtCore.QRect(700, 330, 51, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.fontSizelabel.setFont(font)
        self.fontSizelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.fontSizelabel.setObjectName("fontSizelabel")
        self.fontSizeBox = QtWidgets.QSpinBox(self.centralwidget)
        self.fontSizeBox.setGeometry(QtCore.QRect(700, 350, 51, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(10)
        self.fontSizeBox.setFont(font)
        self.fontSizeBox.setAlignment(QtCore.Qt.AlignCenter)
        self.fontSizeBox.setMinimum(6)
        self.fontSizeBox.setMaximum(30)
        self.fontSizeBox.setProperty("value", 25)
        self.fontSizeBox.setObjectName("fontSizeBox")
        self.fontlabel = QtWidgets.QLabel(self.centralwidget)
        self.fontlabel.setGeometry(QtCore.QRect(610, 330, 41, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.fontlabel.setFont(font)
        self.fontlabel.setObjectName("fontlabel")
        self.fontComboBox = QtWidgets.QFontComboBox(self.centralwidget)
        self.fontComboBox.setGeometry(QtCore.QRect(570, 350, 131, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fontComboBox.setFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.OCRAccuracylabel = QtWidgets.QLabel(self.centralwidget)
        self.OCRAccuracylabel.setGeometry(QtCore.QRect(150, 450, 61, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.OCRAccuracylabel.setFont(font)
        self.OCRAccuracylabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OCRAccuracylabel.setObjectName("OCRAccuracylabel")
        self.OCRAccuracyLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.OCRAccuracyLineEdit.setGeometry(QtCore.QRect(150, 470, 61, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(10)
        self.OCRAccuracyLineEdit.setFont(font)
        self.OCRAccuracyLineEdit.setObjectName("OCRAccuracyLineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 470, 16, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.TextFileEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.TextFileEdit.setGeometry(QtCore.QRect(50, 280, 701, 51))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.TextFileEdit.setFont(font)
        self.TextFileEdit.setAcceptDrops(False)
        self.TextFileEdit.setObjectName("TextFileEdit")
        self.OCRTextEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.OCRTextEdit.setGeometry(QtCore.QRect(50, 400, 701, 51))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.OCRTextEdit.setFont(font)
        self.OCRTextEdit.setAcceptDrops(False)
        self.OCRTextEdit.setReadOnly(True)
        self.OCRTextEdit.setObjectName("OCRTextEdit")
        self.VersefontComboBox = QtWidgets.QFontComboBox(self.centralwidget)
        self.VersefontComboBox.setGeometry(QtCore.QRect(570, 790, 131, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.VersefontComboBox.setFont(font)
        self.VersefontComboBox.setObjectName("VersefontComboBox")
        self.Versefontlabel = QtWidgets.QLabel(self.centralwidget)
        self.Versefontlabel.setGeometry(QtCore.QRect(610, 770, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.Versefontlabel.setFont(font)
        self.Versefontlabel.setObjectName("Versefontlabel")
        self.VersefontSizeBox = QtWidgets.QSpinBox(self.centralwidget)
        self.VersefontSizeBox.setGeometry(QtCore.QRect(700, 790, 51, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(10)
        self.VersefontSizeBox.setFont(font)
        self.VersefontSizeBox.setAlignment(QtCore.Qt.AlignCenter)
        self.VersefontSizeBox.setMinimum(6)
        self.VersefontSizeBox.setMaximum(30)
        self.VersefontSizeBox.setProperty("value", 14)
        self.VersefontSizeBox.setObjectName("VersefontSizeBox")
        self.VersefontSizelabel = QtWidgets.QLabel(self.centralwidget)
        self.VersefontSizelabel.setGeometry(QtCore.QRect(700, 770, 51, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.VersefontSizelabel.setFont(font)
        self.VersefontSizelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VersefontSizelabel.setObjectName("VersefontSizelabel")
        self.SaveVerseTextButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveVerseTextButton.setGeometry(QtCore.QRect(140, 790, 71, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveVerseTextButton.setFont(font)
        self.SaveVerseTextButton.setIcon(icon10)
        self.SaveVerseTextButton.setObjectName("SaveVerseTextButton")
        self.PageText = QtWidgets.QTextEdit(self.centralwidget)
        self.PageText.setGeometry(QtCore.QRect(50, 520, 701, 91))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(24)
        self.PageText.setFont(font)
        self.PageText.setReadOnly(False)
        self.PageText.setObjectName("PageText")
        self.PageFindButton = QtWidgets.QPushButton(self.centralwidget)
        self.PageFindButton.setGeometry(QtCore.QRect(50, 630, 81, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.PageFindButton.setFont(font)
        self.PageFindButton.setIcon(icon14)
        self.PageFindButton.setObjectName("PageFindButton")
        self.SavePageTextButton = QtWidgets.QPushButton(self.centralwidget)
        self.SavePageTextButton.setGeometry(QtCore.QRect(140, 630, 71, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SavePageTextButton.setFont(font)
        self.SavePageTextButton.setIcon(icon10)
        self.SavePageTextButton.setObjectName("SavePageTextButton")
        self.PagefontSizeBox = QtWidgets.QSpinBox(self.centralwidget)
        self.PagefontSizeBox.setGeometry(QtCore.QRect(700, 630, 51, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(10)
        self.PagefontSizeBox.setFont(font)
        self.PagefontSizeBox.setAlignment(QtCore.Qt.AlignCenter)
        self.PagefontSizeBox.setMinimum(6)
        self.PagefontSizeBox.setMaximum(30)
        self.PagefontSizeBox.setProperty("value", 25)
        self.PagefontSizeBox.setObjectName("PagefontSizeBox")
        self.PagefontSizelabel = QtWidgets.QLabel(self.centralwidget)
        self.PagefontSizelabel.setGeometry(QtCore.QRect(700, 610, 51, 20))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.PagefontSizelabel.setFont(font)
        self.PagefontSizelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PagefontSizelabel.setObjectName("PagefontSizelabel")
        self.PagefontComboBox = QtWidgets.QFontComboBox(self.centralwidget)
        self.PagefontComboBox.setGeometry(QtCore.QRect(570, 630, 131, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PagefontComboBox.setFont(font)
        self.PagefontComboBox.setObjectName("PagefontComboBox")
        self.Pagefontlabel = QtWidgets.QLabel(self.centralwidget)
        self.Pagefontlabel.setGeometry(QtCore.QRect(610, 610, 41, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.Pagefontlabel.setFont(font)
        self.Pagefontlabel.setObjectName("Pagefontlabel")
        self.PagelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PagelineEdit.setGeometry(QtCore.QRect(140, 30, 31, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.PagelineEdit.setFont(font)
        self.PagelineEdit.setObjectName("PagelineEdit")
        self.Pagelabel = QtWidgets.QLabel(self.centralwidget)
        self.Pagelabel.setGeometry(QtCore.QRect(130, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.Pagelabel.setFont(font)
        self.Pagelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Pagelabel.setObjectName("Pagelabel")
        self.PageAutoSeekcheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.PageAutoSeekcheckBox.setGeometry(QtCore.QRect(460, 630, 91, 23))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.PageAutoSeekcheckBox.setFont(font)
        self.PageAutoSeekcheckBox.setIcon(icon11)
        self.PageAutoSeekcheckBox.setChecked(True)
        self.PageAutoSeekcheckBox.setObjectName("PageAutoSeekcheckBox")
        self.VerseAutoSeekcheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.VerseAutoSeekcheckBox.setGeometry(QtCore.QRect(460, 790, 91, 23))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.VerseAutoSeekcheckBox.setFont(font)
        self.VerseAutoSeekcheckBox.setIcon(icon11)
        self.VerseAutoSeekcheckBox.setChecked(True)
        self.VerseAutoSeekcheckBox.setObjectName("VerseAutoSeekcheckBox")
        self.VersefindPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.VersefindPushButton.setGeometry(QtCore.QRect(360, 790, 21, 25))
        self.VersefindPushButton.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Icons/Icons/binocular-small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.VersefindPushButton.setIcon(icon15)
        self.VersefindPushButton.setObjectName("VersefindPushButton")
        self.Booklabel = QtWidgets.QLabel(self.centralwidget)
        self.Booklabel.setGeometry(QtCore.QRect(290, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.Booklabel.setFont(font)
        self.Booklabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Booklabel.setObjectName("Booklabel")
        self.BothLoadlabel = QtWidgets.QLabel(self.centralwidget)
        self.BothLoadlabel.setGeometry(QtCore.QRect(60, 10, 61, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.BothLoadlabel.setFont(font)
        self.BothLoadlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.BothLoadlabel.setObjectName("BothLoadlabel")
        self.LinecomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.LinecomboBox.setGeometry(QtCore.QRect(210, 30, 51, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        self.LinecomboBox.setFont(font)
        self.LinecomboBox.setEditable(True)
        self.LinecomboBox.setObjectName("LinecomboBox")
        self.LineNumberlabel = QtWidgets.QLabel(self.centralwidget)
        self.LineNumberlabel.setGeometry(QtCore.QRect(220, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.LineNumberlabel.setFont(font)
        self.LineNumberlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LineNumberlabel.setObjectName("LineNumberlabel")
        self.Selectioncolon = QtWidgets.QLabel(self.centralwidget)
        self.Selectioncolon.setGeometry(QtCore.QRect(190, 30, 21, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Selectioncolon.setFont(font)
        self.Selectioncolon.setAlignment(QtCore.Qt.AlignCenter)
        self.Selectioncolon.setObjectName("Selectioncolon")
        self.LinefindPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.LinefindPushButton.setGeometry(QtCore.QRect(260, 30, 21, 25))
        self.LinefindPushButton.setText("")
        self.LinefindPushButton.setIcon(icon15)
        self.LinefindPushButton.setObjectName("LinefindPushButton")
        self.LinefindPushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.LinefindPushButton_2.setGeometry(QtCore.QRect(170, 30, 21, 25))
        self.LinefindPushButton_2.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-horizontal-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LinefindPushButton_2.setIcon(icon16)
        self.LinefindPushButton_2.setObjectName("LinefindPushButton_2")
        self.BothDiscardButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.BothDiscardButton_2.setGeometry(QtCore.QRect(470, 30, 89, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.BothDiscardButton_2.setFont(font)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Icons/Icons/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothDiscardButton_2.setIcon(icon17)
        self.BothDiscardButton_2.setObjectName("BothDiscardButton_2")
        Grounder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Grounder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 17))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuOCR = QtWidgets.QMenu(self.menubar)
        self.menuOCR.setObjectName("menuOCR")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Grounder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Grounder)
        self.statusbar.setObjectName("statusbar")
        Grounder.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(Grounder)
        self.toolBar.setObjectName("toolBar")
        Grounder.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionProject_Browser = QtWidgets.QAction(Grounder)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionExplorer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProject_Browser.setIcon(icon18)
        self.actionProject_Browser.setObjectName("actionProject_Browser")
        self.actionOpen_Line_Image = QtWidgets.QAction(Grounder)
        self.actionOpen_Line_Image.setIcon(icon1)
        self.actionOpen_Line_Image.setObjectName("actionOpen_Line_Image")
        self.actionOpen_Line_Text = QtWidgets.QAction(Grounder)
        self.actionOpen_Line_Text.setIcon(icon2)
        self.actionOpen_Line_Text.setObjectName("actionOpen_Line_Text")
        self.actionSave_Line_Image = QtWidgets.QAction(Grounder)
        self.actionSave_Line_Image.setIcon(icon10)
        self.actionSave_Line_Image.setObjectName("actionSave_Line_Image")
        self.actionSave_As_Line_Image = QtWidgets.QAction(Grounder)
        self.actionSave_As_Line_Image.setIcon(icon3)
        self.actionSave_As_Line_Image.setObjectName("actionSave_As_Line_Image")
        self.actionSave_Line_Text = QtWidgets.QAction(Grounder)
        self.actionSave_Line_Text.setIcon(icon10)
        self.actionSave_Line_Text.setObjectName("actionSave_Line_Text")
        self.actionSave_As_Line_Text = QtWidgets.QAction(Grounder)
        self.actionSave_As_Line_Text.setIcon(icon3)
        self.actionSave_As_Line_Text.setObjectName("actionSave_As_Line_Text")
        self.actionBoxer = QtWidgets.QAction(Grounder)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionBoxer2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBoxer.setIcon(icon19)
        self.actionBoxer.setObjectName("actionBoxer")
        self.actionVersifier = QtWidgets.QAction(Grounder)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionVersifier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVersifier.setIcon(icon20)
        self.actionVersifier.setObjectName("actionVersifier")
        self.actionScanner = QtWidgets.QAction(Grounder)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionScanner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScanner.setIcon(icon21)
        self.actionScanner.setObjectName("actionScanner")
        self.actionPage_Verse_Cross_Reference = QtWidgets.QAction(Grounder)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/Icons/Icons/Book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPage_Verse_Cross_Reference.setIcon(icon22)
        self.actionPage_Verse_Cross_Reference.setObjectName("actionPage_Verse_Cross_Reference")
        self.actionRenumber_Images = QtWidgets.QAction(Grounder)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/Icons/Icons/Image_renumber.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRenumber_Images.setIcon(icon23)
        self.actionRenumber_Images.setObjectName("actionRenumber_Images")
        self.actionRenumber_Text = QtWidgets.QAction(Grounder)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/Icons/Icons/text_renumber.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRenumber_Text.setIcon(icon24)
        self.actionRenumber_Text.setIconVisibleInMenu(True)
        self.actionRenumber_Text.setObjectName("actionRenumber_Text")
        self.actionStage_Ground_Truth = QtWidgets.QAction(Grounder)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionTrainer1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStage_Ground_Truth.setIcon(icon25)
        self.actionStage_Ground_Truth.setObjectName("actionStage_Ground_Truth")
        self.actionCharacter_Reference = QtWidgets.QAction(Grounder)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionGlypher.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCharacter_Reference.setIcon(icon26)
        self.actionCharacter_Reference.setObjectName("actionCharacter_Reference")
        self.menuFile.addAction(self.actionProject_Browser)
        self.menuFile.addAction(self.actionOpen_Line_Image)
        self.menuFile.addAction(self.actionSave_Line_Image)
        self.menuFile.addAction(self.actionSave_As_Line_Image)
        self.menuFile.addAction(self.actionOpen_Line_Text)
        self.menuFile.addAction(self.actionSave_Line_Text)
        self.menuFile.addAction(self.actionSave_As_Line_Text)
        self.menuTools.addAction(self.actionBoxer)
        self.menuTools.addAction(self.actionScanner)
        self.menuTools.addAction(self.actionVersifier)
        self.menuTools.addAction(self.actionStage_Ground_Truth)
        self.menuTools.addAction(self.actionCharacter_Reference)
        self.menuTools.addAction(self.actionPage_Verse_Cross_Reference)
        self.menuTools.addAction(self.actionRenumber_Images)
        self.menuTools.addAction(self.actionRenumber_Text)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuOCR.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionProject_Browser)
        self.toolBar.addAction(self.actionBoxer)
        self.toolBar.addAction(self.actionScanner)
        self.toolBar.addAction(self.actionVersifier)
        self.toolBar.addAction(self.actionStage_Ground_Truth)
        self.toolBar.addAction(self.actionCharacter_Reference)
        self.toolBar.addAction(self.actionPage_Verse_Cross_Reference)
        self.toolBar.addAction(self.actionRenumber_Images)
        self.toolBar.addAction(self.actionRenumber_Text)

        self.retranslateUi(Grounder)
        self.OCRModelComboBox.setCurrentIndex(2)
        self.OCRlangComboBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Grounder)

    def retranslateUi(self, Grounder):
        _translate = QtCore.QCoreApplication.translate
        Grounder.setWindowTitle(_translate("Grounder", "βϊϐλίον Grounder"))
        self.ImageButton.setText(_translate("Grounder", " Line Image"))
        self.TextButton.setText(_translate("Grounder", " Line Text"))
        self.SaveImgAsButton.setText(_translate("Grounder", "Save Image As"))
        self.BothPrevButton.setText(_translate("Grounder", " Both Prev"))
        self.BothNextButton.setText(_translate("Grounder", " Both Next"))
        self.Imagelabel.setText(_translate("Grounder", "Image:"))
        self.PrevImgButton.setText(_translate("Grounder", "  Prev"))
        self.NextImgButton.setText(_translate("Grounder", "  Next"))
        self.Textlabel.setText(_translate("Grounder", "Text:"))
        self.NextTxtButton.setText(_translate("Grounder", "  Next"))
        self.PrevTxtButton.setText(_translate("Grounder", "  Prev"))
        self.SaveAsButton.setText(_translate("Grounder", "Save Text As"))
        self.SaveButton.setText(_translate("Grounder", "Save Text"))
        self.OCRButton.setText(_translate("Grounder", "OCR Line Image"))
        self.SaveImageButton.setText(_translate("Grounder", "Save Image"))
        self.AutoScancheckBox.setText(_translate("Grounder", "Auto Scan"))
        self.DiscardImageButton.setToolTip(_translate("Grounder", "Discard Image & Remove Xref"))
        self.DiscardImageButton.setText(_translate("Grounder", " Discard Image"))
        self.DiscardTextButton.setToolTip(_translate("Grounder", "Discard Text & Remove Xref"))
        self.DiscardTextButton.setText(_translate("Grounder", " Discard Text"))
        self.BothDiscardButton.setToolTip(_translate("Grounder", "Discard Both & Remove Xref"))
        self.BothDiscardButton.setText(_translate("Grounder", " Discard Both"))
        self.BothLoadButton.setToolTip(_translate("Grounder", "Synchronize to selected verse"))
        self.BothLoadButton.setText(_translate("Grounder", "  Synch"))
        self.Startcolon.setText(_translate("Grounder", ":"))
        self.StartchapterComboBox.setToolTip(_translate("Grounder", "Select chapter"))
        self.VerseFindButton.setText(_translate("Grounder", "Find"))
        self.StartbookComboBox.setToolTip(_translate("Grounder", "Select book"))
        self.StartbookComboBox.setItemText(0, _translate("Grounder", "Mat"))
        self.StartbookComboBox.setItemText(1, _translate("Grounder", "Mar"))
        self.StartbookComboBox.setItemText(2, _translate("Grounder", "Luk"))
        self.StartbookComboBox.setItemText(3, _translate("Grounder", "Joh"))
        self.StartbookComboBox.setItemText(4, _translate("Grounder", "Act"))
        self.StartbookComboBox.setItemText(5, _translate("Grounder", "Rom"))
        self.StartbookComboBox.setItemText(6, _translate("Grounder", "1Co"))
        self.StartbookComboBox.setItemText(7, _translate("Grounder", "2Co"))
        self.StartbookComboBox.setItemText(8, _translate("Grounder", "Gal"))
        self.StartbookComboBox.setItemText(9, _translate("Grounder", "Eph"))
        self.StartbookComboBox.setItemText(10, _translate("Grounder", "Php"))
        self.StartbookComboBox.setItemText(11, _translate("Grounder", "Col"))
        self.StartbookComboBox.setItemText(12, _translate("Grounder", "1Th"))
        self.StartbookComboBox.setItemText(13, _translate("Grounder", "2Th"))
        self.StartbookComboBox.setItemText(14, _translate("Grounder", "1Ti"))
        self.StartbookComboBox.setItemText(15, _translate("Grounder", "2Ti"))
        self.StartbookComboBox.setItemText(16, _translate("Grounder", "Tit"))
        self.StartbookComboBox.setItemText(17, _translate("Grounder", "Phm"))
        self.StartbookComboBox.setItemText(18, _translate("Grounder", "Heb"))
        self.StartbookComboBox.setItemText(19, _translate("Grounder", "Jas"))
        self.StartbookComboBox.setItemText(20, _translate("Grounder", "1Pe"))
        self.StartbookComboBox.setItemText(21, _translate("Grounder", "2Pe"))
        self.StartbookComboBox.setItemText(22, _translate("Grounder", "1Jn"))
        self.StartbookComboBox.setItemText(23, _translate("Grounder", "2Jn"))
        self.StartbookComboBox.setItemText(24, _translate("Grounder", "3Jn"))
        self.StartbookComboBox.setItemText(25, _translate("Grounder", "Jud"))
        self.StartbookComboBox.setItemText(26, _translate("Grounder", "Rev"))
        self.StartverseComboBox.setToolTip(_translate("Grounder", "Select verse"))
        self.bookComboBox.setToolTip(_translate("Grounder", "Bible book current image|text directory"))
        self.bookComboBox.setItemText(0, _translate("Grounder", "Mat"))
        self.bookComboBox.setItemText(1, _translate("Grounder", "Mar"))
        self.bookComboBox.setItemText(2, _translate("Grounder", "Luk"))
        self.bookComboBox.setItemText(3, _translate("Grounder", "Joh"))
        self.bookComboBox.setItemText(4, _translate("Grounder", "Act"))
        self.bookComboBox.setItemText(5, _translate("Grounder", "Rom"))
        self.bookComboBox.setItemText(6, _translate("Grounder", "1Co"))
        self.bookComboBox.setItemText(7, _translate("Grounder", "2Co"))
        self.bookComboBox.setItemText(8, _translate("Grounder", "Gal"))
        self.bookComboBox.setItemText(9, _translate("Grounder", "Eph"))
        self.bookComboBox.setItemText(10, _translate("Grounder", "Php"))
        self.bookComboBox.setItemText(11, _translate("Grounder", "Col"))
        self.bookComboBox.setItemText(12, _translate("Grounder", "1Th"))
        self.bookComboBox.setItemText(13, _translate("Grounder", "2Th"))
        self.bookComboBox.setItemText(14, _translate("Grounder", "1Ti"))
        self.bookComboBox.setItemText(15, _translate("Grounder", "2Ti"))
        self.bookComboBox.setItemText(16, _translate("Grounder", "Tit"))
        self.bookComboBox.setItemText(17, _translate("Grounder", "Phm"))
        self.bookComboBox.setItemText(18, _translate("Grounder", "Heb"))
        self.bookComboBox.setItemText(19, _translate("Grounder", "Jas"))
        self.bookComboBox.setItemText(20, _translate("Grounder", "1Pe"))
        self.bookComboBox.setItemText(21, _translate("Grounder", "2Pe"))
        self.bookComboBox.setItemText(22, _translate("Grounder", "1Jn"))
        self.bookComboBox.setItemText(23, _translate("Grounder", "2Jn"))
        self.bookComboBox.setItemText(24, _translate("Grounder", "3Jn"))
        self.bookComboBox.setItemText(25, _translate("Grounder", "Jud"))
        self.bookComboBox.setItemText(26, _translate("Grounder", "Rev"))
        self.OCRModelComboBox.setToolTip(_translate("Grounder", "Select OCR language model"))
        self.OCRModelComboBox.setItemText(0, _translate("Grounder", "ell"))
        self.OCRModelComboBox.setItemText(1, _translate("Grounder", "grc"))
        self.OCRModelComboBox.setItemText(2, _translate("Grounder", "feg"))
        self.OCRModelComboBox.setItemText(3, _translate("Grounder", "heb"))
        self.OCRModelComboBox.setItemText(4, _translate("Grounder", "feh"))
        self.OCRModelComboBox.setItemText(5, _translate("Grounder", "lat"))
        self.OCRModelComboBox.setItemText(6, _translate("Grounder", "fel"))
        self.OCRModellabel.setToolTip(_translate("Grounder", "Select OCR LSTM model"))
        self.OCRModellabel.setText(_translate("Grounder", "OCR LSTM Model"))
        self.OCRlangComboBox.setToolTip(_translate("Grounder", "Select OCR language"))
        self.OCRlangComboBox.setItemText(0, _translate("Grounder", "Ancient Greek"))
        self.OCRlangComboBox.setItemText(1, _translate("Grounder", "Middle Greek"))
        self.OCRlangComboBox.setItemText(2, _translate("Grounder", "Modern Greek"))
        self.OCRlangComboBox.setItemText(3, _translate("Grounder", "Hebrew"))
        self.OCRlangComboBox.setItemText(4, _translate("Grounder", "Latin"))
        self.OCRlanglabel.setText(_translate("Grounder", " OCR Language"))
        self.fontSizelabel.setText(_translate("Grounder", "Size"))
        self.fontSizeBox.setToolTip(_translate("Grounder", "Select font size"))
        self.fontlabel.setText(_translate("Grounder", "Line Font"))
        self.fontComboBox.setToolTip(_translate("Grounder", "Select font"))
        self.OCRAccuracylabel.setText(_translate("Grounder", "OCR Accuracy"))
        self.label.setText(_translate("Grounder", " %"))
        self.VersefontComboBox.setToolTip(_translate("Grounder", "Select font"))
        self.Versefontlabel.setText(_translate("Grounder", "Verse Font"))
        self.VersefontSizeBox.setToolTip(_translate("Grounder", "Select font size"))
        self.VersefontSizelabel.setText(_translate("Grounder", "Size"))
        self.SaveVerseTextButton.setText(_translate("Grounder", "Save Verses"))
        self.PageFindButton.setText(_translate("Grounder", "Find"))
        self.SavePageTextButton.setText(_translate("Grounder", "Save Page"))
        self.PagefontSizeBox.setToolTip(_translate("Grounder", "Select font size"))
        self.PagefontSizelabel.setText(_translate("Grounder", "Size"))
        self.PagefontComboBox.setToolTip(_translate("Grounder", "Select font"))
        self.Pagefontlabel.setText(_translate("Grounder", "Page Font"))
        self.Pagelabel.setText(_translate("Grounder", "Page"))
        self.PageAutoSeekcheckBox.setText(_translate("Grounder", "Auto Seek"))
        self.VerseAutoSeekcheckBox.setText(_translate("Grounder", "Auto Seek"))
        self.VersefindPushButton.setToolTip(_translate("Grounder", "Select verse line"))
        self.Booklabel.setText(_translate("Grounder", "Book"))
        self.BothLoadlabel.setText(_translate("Grounder", "Load"))
        self.LineNumberlabel.setText(_translate("Grounder", "Line Number"))
        self.Selectioncolon.setText(_translate("Grounder", ":"))
        self.LinefindPushButton.setToolTip(_translate("Grounder", "Select verse line"))
        self.LinefindPushButton_2.setToolTip(_translate("Grounder", "Select verse line"))
        self.BothDiscardButton_2.setToolTip(_translate("Grounder", "Omit & Retain Xref"))
        self.BothDiscardButton_2.setText(_translate("Grounder", " Omit Both"))
        self.menuFile.setTitle(_translate("Grounder", "File"))
        self.menuEdit.setTitle(_translate("Grounder", "Edit"))
        self.menuView.setTitle(_translate("Grounder", "View"))
        self.menuTools.setTitle(_translate("Grounder", "Tools"))
        self.menuOCR.setTitle(_translate("Grounder", "OCR"))
        self.menuHelp.setTitle(_translate("Grounder", "Help"))
        self.toolBar.setWindowTitle(_translate("Grounder", "toolBar"))
        self.actionProject_Browser.setText(_translate("Grounder", "Project Browser"))
        self.actionOpen_Line_Image.setText(_translate("Grounder", "Open Line Image"))
        self.actionOpen_Line_Text.setText(_translate("Grounder", "Open Line Text"))
        self.actionSave_Line_Image.setText(_translate("Grounder", "Save Line Image"))
        self.actionSave_As_Line_Image.setText(_translate("Grounder", "Save As Line Image"))
        self.actionSave_Line_Text.setText(_translate("Grounder", "Save Line Text"))
        self.actionSave_As_Line_Text.setText(_translate("Grounder", "Save As Line Text"))
        self.actionBoxer.setText(_translate("Grounder", "Boxer"))
        self.actionVersifier.setText(_translate("Grounder", "Versifier"))
        self.actionScanner.setText(_translate("Grounder", "Scanner"))
        self.actionPage_Verse_Cross_Reference.setText(_translate("Grounder", "Page Verse Cross Reference"))
        self.actionRenumber_Images.setText(_translate("Grounder", "Renumber Images"))
        self.actionRenumber_Text.setText(_translate("Grounder", "Renumber Text"))
        self.actionStage_Ground_Truth.setText(_translate("Grounder", "Stage Ground Truth"))
        self.actionCharacter_Reference.setText(_translate("Grounder", "Character Reference"))
import UI_Icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Grounder = QtWidgets.QMainWindow()
    ui = Ui_Grounder()
    ui.setupUi(Grounder)
    Grounder.show()
    sys.exit(app.exec_())
