# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jetson/Projects/BiblionOCR/ViewController/0-MainUI/QtDesignerUI/MyScannerUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Scanner(object):
    def setupUi(self, Scanner):
        Scanner.setObjectName("Scanner")
        Scanner.setWindowModality(QtCore.Qt.NonModal)
        Scanner.setEnabled(True)
        Scanner.resize(1317, 820)
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        Scanner.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionScanner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Scanner.setWindowIcon(icon)
        Scanner.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Scanner)
        self.centralwidget.setObjectName("centralwidget")
        self.ImagescrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.ImagescrollArea.setGeometry(QtCore.QRect(20, 30, 551, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollArea.sizePolicy().hasHeightForWidth())
        self.ImagescrollArea.setSizePolicy(sizePolicy)
        self.ImagescrollArea.setMinimumSize(QtCore.QSize(501, 600))
        self.ImagescrollArea.setWidgetResizable(True)
        self.ImagescrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ImagescrollArea.setObjectName("ImagescrollArea")
        self.ImagescrollAreaWidgetContents = QtWidgets.QWidget()
        self.ImagescrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 3200, 4800))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.ImagescrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.ImagescrollAreaWidgetContents.setMinimumSize(QtCore.QSize(3200, 4800))
        self.ImagescrollAreaWidgetContents.setSizeIncrement(QtCore.QSize(0, 0))
        self.ImagescrollAreaWidgetContents.setBaseSize(QtCore.QSize(520, 700))
        self.ImagescrollAreaWidgetContents.setObjectName("ImagescrollAreaWidgetContents")
        self.Image = QtWidgets.QLabel(self.ImagescrollAreaWidgetContents)
        self.Image.setGeometry(QtCore.QRect(0, 2, 6800, 9600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Image.sizePolicy().hasHeightForWidth())
        self.Image.setSizePolicy(sizePolicy)
        self.Image.setMinimumSize(QtCore.QSize(3400, 4800))
        self.Image.setBaseSize(QtCore.QSize(520, 700))
        self.Image.setAcceptDrops(True)
        self.Image.setText("")
        self.Image.setScaledContents(False)
        self.Image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Image.setObjectName("Image")
        self.ImagescrollArea.setWidget(self.ImagescrollAreaWidgetContents)
        self.OpenImageFilebutton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenImageFilebutton.setGeometry(QtCore.QRect(20, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.OpenImageFilebutton.setFont(font)
        self.OpenImageFilebutton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenImageFilebutton.setIcon(icon1)
        self.OpenImageFilebutton.setObjectName("OpenImageFilebutton")
        self.ImageLe = QtWidgets.QLineEdit(self.centralwidget)
        self.ImageLe.setGeometry(QtCore.QRect(330, 0, 241, 25))
        self.ImageLe.setObjectName("ImageLe")
        self.EditCorrectedTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.EditCorrectedTextbutton.setGeometry(QtCore.QRect(980, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.EditCorrectedTextbutton.setFont(font)
        self.EditCorrectedTextbutton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-document-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EditCorrectedTextbutton.setIcon(icon2)
        self.EditCorrectedTextbutton.setObjectName("EditCorrectedTextbutton")
        self.SaveAsOCRCorrTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveAsOCRCorrTextbutton.setGeometry(QtCore.QRect(1250, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveAsOCRCorrTextbutton.setFont(font)
        self.SaveAsOCRCorrTextbutton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk-rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveAsOCRCorrTextbutton.setIcon(icon3)
        self.SaveAsOCRCorrTextbutton.setObjectName("SaveAsOCRCorrTextbutton")
        self.SaveOCRCorrTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveOCRCorrTextbutton.setGeometry(QtCore.QRect(1280, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.SaveOCRCorrTextbutton.setFont(font)
        self.SaveOCRCorrTextbutton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveOCRCorrTextbutton.setIcon(icon4)
        self.SaveOCRCorrTextbutton.setObjectName("SaveOCRCorrTextbutton")
        self.OCRText = QtWidgets.QTextEdit(self.centralwidget)
        self.OCRText.setGeometry(QtCore.QRect(730, 30, 570, 700))
        self.OCRText.setMinimumSize(QtCore.QSize(540, 600))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OCRText.setFont(font)
        self.OCRText.setAcceptDrops(False)
        self.OCRText.setObjectName("OCRText")
        self.Writerbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Writerbutton.setGeometry(QtCore.QRect(1180, 0, 21, 25))
        self.Writerbutton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/libreoffice-writer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Writerbutton.setIcon(icon5)
        self.Writerbutton.setObjectName("Writerbutton")
        self.reloadTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.reloadTextbutton.setGeometry(QtCore.QRect(710, 0, 21, 25))
        self.reloadTextbutton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/reload-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadTextbutton.setIcon(icon6)
        self.reloadTextbutton.setObjectName("reloadTextbutton")
        self.reloadImagebutton = QtWidgets.QPushButton(self.centralwidget)
        self.reloadImagebutton.setGeometry(QtCore.QRect(570, 0, 21, 25))
        self.reloadImagebutton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadImagebutton.setIcon(icon7)
        self.reloadImagebutton.setObjectName("reloadImagebutton")
        self.MyPixlerbutton = QtWidgets.QPushButton(self.centralwidget)
        self.MyPixlerbutton.setGeometry(QtCore.QRect(60, 0, 21, 25))
        self.MyPixlerbutton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionPixler1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MyPixlerbutton.setIcon(icon8)
        self.MyPixlerbutton.setObjectName("MyPixlerbutton")
        self.Deskewbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Deskewbutton.setGeometry(QtCore.QRect(100, 0, 21, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Deskewbutton.setFont(font)
        self.Deskewbutton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew_clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Deskewbutton.setIcon(icon9)
        self.Deskewbutton.setObjectName("Deskewbutton")
        self.PrevImgButton = QtWidgets.QPushButton(self.centralwidget)
        self.PrevImgButton.setGeometry(QtCore.QRect(270, 0, 21, 25))
        self.PrevImgButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/Icons/back_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PrevImgButton.setIcon(icon10)
        self.PrevImgButton.setObjectName("PrevImgButton")
        self.NextImgButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextImgButton.setGeometry(QtCore.QRect(300, 0, 21, 25))
        self.NextImgButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/Icons/forward_image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextImgButton.setIcon(icon11)
        self.NextImgButton.setObjectName("NextImgButton")
        self.PrevTxtButton = QtWidgets.QPushButton(self.centralwidget)
        self.PrevTxtButton.setGeometry(QtCore.QRect(1010, 0, 21, 25))
        self.PrevTxtButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icons/Icons/back_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PrevTxtButton.setIcon(icon12)
        self.PrevTxtButton.setObjectName("PrevTxtButton")
        self.NextTxtButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextTxtButton.setGeometry(QtCore.QRect(1040, 0, 21, 25))
        self.NextTxtButton.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Icons/Icons/forward_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextTxtButton.setIcon(icon13)
        self.NextTxtButton.setObjectName("NextTxtButton")
        self.BothNextButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothNextButton.setGeometry(QtCore.QRect(680, 0, 21, 25))
        self.BothNextButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Icons/Icons/ui-button-navigation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothNextButton.setIcon(icon14)
        self.BothNextButton.setObjectName("BothNextButton")
        self.BothPrevButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothPrevButton.setGeometry(QtCore.QRect(600, 0, 21, 25))
        self.BothPrevButton.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Icons/Icons/ui-button-navigation-back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothPrevButton.setIcon(icon15)
        self.BothPrevButton.setObjectName("BothPrevButton")
        self.BothLoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.BothLoadButton.setEnabled(True)
        self.BothLoadButton.setGeometry(QtCore.QRect(640, 0, 21, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.BothLoadButton.setFont(font)
        self.BothLoadButton.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Icons/Icons/synchronize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BothLoadButton.setIcon(icon16)
        self.BothLoadButton.setObjectName("BothLoadButton")
        self.OCRgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.OCRgroupBox.setGeometry(QtCore.QRect(570, 20, 161, 161))
        self.OCRgroupBox.setTitle("")
        self.OCRgroupBox.setObjectName("OCRgroupBox")
        self.OCRlangComboBox = QtWidgets.QComboBox(self.OCRgroupBox)
        self.OCRlangComboBox.setGeometry(QtCore.QRect(20, 70, 121, 25))
        self.OCRlangComboBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OCRlangComboBox.setEditable(False)
        self.OCRlangComboBox.setObjectName("OCRlangComboBox")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlangComboBox.addItem("")
        self.OCRlanglabel = QtWidgets.QLabel(self.OCRgroupBox)
        self.OCRlanglabel.setGeometry(QtCore.QRect(40, 50, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OCRlanglabel.setFont(font)
        self.OCRlanglabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OCRlanglabel.setObjectName("OCRlanglabel")
        self.OCRModellabel = QtWidgets.QLabel(self.OCRgroupBox)
        self.OCRModellabel.setGeometry(QtCore.QRect(30, 100, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OCRModellabel.setFont(font)
        self.OCRModellabel.setAlignment(QtCore.Qt.AlignCenter)
        self.OCRModellabel.setObjectName("OCRModellabel")
        self.OCRModelComboBox = QtWidgets.QComboBox(self.OCRgroupBox)
        self.OCRModelComboBox.setGeometry(QtCore.QRect(50, 120, 61, 25))
        self.OCRModelComboBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.OCRModelComboBox.setEditable(False)
        self.OCRModelComboBox.setObjectName("OCRModelComboBox")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRModelComboBox.addItem("")
        self.OCRbutton = QtWidgets.QPushButton(self.OCRgroupBox)
        self.OCRbutton.setGeometry(QtCore.QRect(50, 20, 61, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.OCRbutton.setFont(font)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Icons/Icons/ocr3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OCRbutton.setIcon(icon17)
        self.OCRbutton.setObjectName("OCRbutton")
        self.TextLE = QtWidgets.QLineEdit(self.centralwidget)
        self.TextLE.setGeometry(QtCore.QRect(730, 0, 241, 25))
        self.TextLE.setObjectName("TextLE")
        self.SessiongroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.SessiongroupBox.setGeometry(QtCore.QRect(570, 180, 161, 51))
        self.SessiongroupBox.setTitle("")
        self.SessiongroupBox.setObjectName("SessiongroupBox")
        self.booklabel = QtWidgets.QLabel(self.SessiongroupBox)
        self.booklabel.setGeometry(QtCore.QRect(50, 0, 61, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.booklabel.setFont(font)
        self.booklabel.setAlignment(QtCore.Qt.AlignCenter)
        self.booklabel.setObjectName("booklabel")
        self.bookComboBox = QtWidgets.QComboBox(self.SessiongroupBox)
        self.bookComboBox.setGeometry(QtCore.QRect(50, 20, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bookComboBox.setFont(font)
        self.bookComboBox.setEditable(True)
        self.bookComboBox.setObjectName("bookComboBox")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.bookComboBox.addItem("")
        self.TextgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.TextgroupBox.setGeometry(QtCore.QRect(570, 230, 161, 101))
        self.TextgroupBox.setTitle("")
        self.TextgroupBox.setObjectName("TextgroupBox")
        self.fontlabel = QtWidgets.QLabel(self.TextgroupBox)
        self.fontlabel.setGeometry(QtCore.QRect(70, 0, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fontlabel.setFont(font)
        self.fontlabel.setObjectName("fontlabel")
        self.fontSizelabel = QtWidgets.QLabel(self.TextgroupBox)
        self.fontSizelabel.setGeometry(QtCore.QRect(60, 50, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fontSizelabel.setFont(font)
        self.fontSizelabel.setObjectName("fontSizelabel")
        self.fontSizeBox = QtWidgets.QSpinBox(self.TextgroupBox)
        self.fontSizeBox.setGeometry(QtCore.QRect(57, 70, 51, 26))
        self.fontSizeBox.setAlignment(QtCore.Qt.AlignCenter)
        self.fontSizeBox.setMinimum(6)
        self.fontSizeBox.setMaximum(30)
        self.fontSizeBox.setProperty("value", 20)
        self.fontSizeBox.setObjectName("fontSizeBox")
        self.fontComboBox = QtWidgets.QFontComboBox(self.TextgroupBox)
        self.fontComboBox.setGeometry(QtCore.QRect(10, 20, 141, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fontComboBox.setFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.ZoomComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ZoomComboBox.setGeometry(QtCore.QRect(170, 0, 81, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZoomComboBox.sizePolicy().hasHeightForWidth())
        self.ZoomComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ZoomComboBox.setFont(font)
        self.ZoomComboBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ZoomComboBox.setEditable(True)
        self.ZoomComboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.ZoomComboBox.setObjectName("ZoomComboBox")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.ZoomComboBox.addItem("")
        self.Zoombutton = QtWidgets.QPushButton(self.centralwidget)
        self.Zoombutton.setEnabled(True)
        self.Zoombutton.setGeometry(QtCore.QRect(150, 0, 21, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Zoombutton.setFont(font)
        self.Zoombutton.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Icons/Icons/image-resize1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Zoombutton.setIcon(icon18)
        self.Zoombutton.setObjectName("Zoombutton")
        self.LHslider = QtWidgets.QSlider(self.centralwidget)
        self.LHslider.setEnabled(False)
        self.LHslider.setGeometry(QtCore.QRect(1090, 30, 21, 161))
        self.LHslider.setMinimum(100)
        self.LHslider.setMaximum(200)
        self.LHslider.setSingleStep(2)
        self.LHslider.setPageStep(10)
        self.LHslider.setProperty("value", 144)
        self.LHslider.setSliderPosition(144)
        self.LHslider.setOrientation(QtCore.Qt.Vertical)
        self.LHslider.setInvertedAppearance(True)
        self.LHslider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.LHslider.setObjectName("LHslider")
        self.LHlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.LHlineEdit.setGeometry(QtCore.QRect(1100, 0, 31, 25))
        self.LHlineEdit.setMaxLength(32767)
        self.LHlineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.LHlineEdit.setClearButtonEnabled(False)
        self.LHlineEdit.setObjectName("LHlineEdit")
        self.LHDialogtbutton = QtWidgets.QPushButton(self.centralwidget)
        self.LHDialogtbutton.setEnabled(True)
        self.LHDialogtbutton.setGeometry(QtCore.QRect(1070, 0, 31, 25))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.LHDialogtbutton.setFont(font)
        self.LHDialogtbutton.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-line-spacing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LHDialogtbutton.setIcon(icon19)
        self.LHDialogtbutton.setObjectName("LHDialogtbutton")
        self.Zoomslider = QtWidgets.QSlider(self.centralwidget)
        self.Zoomslider.setEnabled(False)
        self.Zoomslider.setGeometry(QtCore.QRect(190, 30, 21, 161))
        self.Zoomslider.setMinimum(10)
        self.Zoomslider.setMaximum(100)
        self.Zoomslider.setSingleStep(1)
        self.Zoomslider.setPageStep(20)
        self.Zoomslider.setProperty("value", 25)
        self.Zoomslider.setSliderPosition(25)
        self.Zoomslider.setOrientation(QtCore.Qt.Vertical)
        self.Zoomslider.setInvertedAppearance(True)
        self.Zoomslider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.Zoomslider.setObjectName("Zoomslider")
        self.MyWriterbutton = QtWidgets.QPushButton(self.centralwidget)
        self.MyWriterbutton.setGeometry(QtCore.QRect(1150, 0, 21, 25))
        self.MyWriterbutton.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionWriter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MyWriterbutton.setIcon(icon20)
        self.MyWriterbutton.setObjectName("MyWriterbutton")
        self.FindReplacebutton = QtWidgets.QPushButton(self.centralwidget)
        self.FindReplacebutton.setGeometry(QtCore.QRect(590, 340, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.FindReplacebutton.setFont(font)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/Icons/Icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FindReplacebutton.setIcon(icon21)
        self.FindReplacebutton.setObjectName("FindReplacebutton")
        Scanner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Scanner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1317, 20))
        self.menubar.setObjectName("menubar")
        self.menuOCR = QtWidgets.QMenu(self.menubar)
        self.menuOCR.setObjectName("menuOCR")
        self.menuSelect_Language = QtWidgets.QMenu(self.menuOCR)
        self.menuSelect_Language.setObjectName("menuSelect_Language")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(11)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.menuTools.setFont(font)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Scanner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Scanner)
        self.statusbar.setObjectName("statusbar")
        Scanner.setStatusBar(self.statusbar)
        self.ImageEditToolBar = QtWidgets.QToolBar(Scanner)
        self.ImageEditToolBar.setObjectName("ImageEditToolBar")
        Scanner.addToolBar(QtCore.Qt.TopToolBarArea, self.ImageEditToolBar)
        self.actionpdf_to_tiff = QtWidgets.QAction(Scanner)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/Icons/Icons/ocr2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_to_tiff.setIcon(icon22)
        self.actionpdf_to_tiff.setObjectName("actionpdf_to_tiff")
        self.actionmove_pdf_for_tiff = QtWidgets.QAction(Scanner)
        self.actionmove_pdf_for_tiff.setObjectName("actionmove_pdf_for_tiff")
        self.actiontiff_to_mono = QtWidgets.QAction(Scanner)
        self.actiontiff_to_mono.setObjectName("actiontiff_to_mono")
        self.actionmono_to_png = QtWidgets.QAction(Scanner)
        self.actionmono_to_png.setObjectName("actionmono_to_png")
        self.actiontiff_to_png = QtWidgets.QAction(Scanner)
        self.actiontiff_to_png.setObjectName("actiontiff_to_png")
        self.actionGreek = QtWidgets.QAction(Scanner)
        self.actionGreek.setObjectName("actionGreek")
        self.actiontiff_to_png_2 = QtWidgets.QAction(Scanner)
        self.actiontiff_to_png_2.setObjectName("actiontiff_to_png_2")
        self.actionpdf_for_tiff = QtWidgets.QAction(Scanner)
        self.actionpdf_for_tiff.setObjectName("actionpdf_for_tiff")
        self.actionpdf_for_tiff_tb = QtWidgets.QAction(Scanner)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf4tiff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_for_tiff_tb.setIcon(icon23)
        self.actionpdf_for_tiff_tb.setObjectName("actionpdf_for_tiff_tb")
        self.actionpdf_to_tiff_tb = QtWidgets.QAction(Scanner)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf2tiff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_to_tiff_tb.setIcon(icon24)
        self.actionpdf_to_tiff_tb.setObjectName("actionpdf_to_tiff_tb")
        self.actiontiff_to_mono_tb = QtWidgets.QAction(Scanner)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiontiff_to_mono_tb.setIcon(icon25)
        self.actiontiff_to_mono_tb.setObjectName("actiontiff_to_mono_tb")
        self.actionmono_to_png_tb = QtWidgets.QAction(Scanner)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/Icons/Icons/png-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmono_to_png_tb.setIcon(icon26)
        self.actionmono_to_png_tb.setObjectName("actionmono_to_png_tb")
        self.actionLatin = QtWidgets.QAction(Scanner)
        self.actionLatin.setObjectName("actionLatin")
        self.actiontiff_to_png_3 = QtWidgets.QAction(Scanner)
        self.actiontiff_to_png_3.setObjectName("actiontiff_to_png_3")
        self.actiontiff_to_png_4 = QtWidgets.QAction(Scanner)
        self.actiontiff_to_png_4.setObjectName("actiontiff_to_png_4")
        self.actionDeskewGreek_tiff_tb = QtWidgets.QAction(Scanner)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeskewGreek_tiff_tb.setIcon(icon27)
        self.actionDeskewGreek_tiff_tb.setObjectName("actionDeskewGreek_tiff_tb")
        self.actiontiff_to_png_5 = QtWidgets.QAction(Scanner)
        self.actiontiff_to_png_5.setObjectName("actiontiff_to_png_5")
        self.actionDeskewLatin_tiff_tb = QtWidgets.QAction(Scanner)
        self.actionDeskewLatin_tiff_tb.setEnabled(False)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeskewLatin_tiff_tb.setIcon(icon28)
        self.actionDeskewLatin_tiff_tb.setVisible(False)
        self.actionDeskewLatin_tiff_tb.setIconVisibleInMenu(False)
        self.actionDeskewLatin_tiff_tb.setObjectName("actionDeskewLatin_tiff_tb")
        self.actionResizeGreek_png_tb = QtWidgets.QAction(Scanner)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/Icons/Icons/resize-png-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResizeGreek_png_tb.setIcon(icon29)
        self.actionResizeGreek_png_tb.setObjectName("actionResizeGreek_png_tb")
        self.actionResizeLatin_png_tb = QtWidgets.QAction(Scanner)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/Icons/Icons/resize-png-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResizeLatin_png_tb.setIcon(icon30)
        self.actionResizeLatin_png_tb.setVisible(False)
        self.actionResizeLatin_png_tb.setIconVisibleInMenu(False)
        self.actionResizeLatin_png_tb.setObjectName("actionResizeLatin_png_tb")
        self.actionCrop_Languages_tb = QtWidgets.QAction(Scanner)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-langs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrop_Languages_tb.setIcon(icon31)
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        self.actionCrop_Languages_tb.setFont(font)
        self.actionCrop_Languages_tb.setObjectName("actionCrop_Languages_tb")
        self.actionextract_pdf_tb = QtWidgets.QAction(Scanner)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf-extract1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionextract_pdf_tb.setIcon(icon32)
        self.actionextract_pdf_tb.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionextract_pdf_tb.setObjectName("actionextract_pdf_tb")
        self.actiontiff_for_Ground_Truth = QtWidgets.QAction(Scanner)
        self.actiontiff_for_Ground_Truth.setObjectName("actiontiff_for_Ground_Truth")
        self.actionCrop = QtWidgets.QAction(Scanner)
        self.actionCrop.setObjectName("actionCrop")
        self.actiontiff_for_Ground_Truth_2 = QtWidgets.QAction(Scanner)
        self.actiontiff_for_Ground_Truth_2.setObjectName("actiontiff_for_Ground_Truth_2")
        self.actionSplit = QtWidgets.QAction(Scanner)
        self.actionSplit.setObjectName("actionSplit")
        self.actionRename_tiff_lines = QtWidgets.QAction(Scanner)
        self.actionRename_tiff_lines.setObjectName("actionRename_tiff_lines")
        self.actionRename_text_lines = QtWidgets.QAction(Scanner)
        self.actionRename_text_lines.setObjectName("actionRename_text_lines")
        self.actionReview_Ground_Truth = QtWidgets.QAction(Scanner)
        self.actionReview_Ground_Truth.setObjectName("actionReview_Ground_Truth")
        self.actionGreek_Wordlist_2 = QtWidgets.QAction(Scanner)
        self.actionGreek_Wordlist_2.setObjectName("actionGreek_Wordlist_2")
        self.actionLatin_Wordlist = QtWidgets.QAction(Scanner)
        self.actionLatin_Wordlist.setObjectName("actionLatin_Wordlist")
        self.actionImage_Lines = QtWidgets.QAction(Scanner)
        self.actionImage_Lines.setObjectName("actionImage_Lines")
        self.actionText_Lines = QtWidgets.QAction(Scanner)
        self.actionText_Lines.setObjectName("actionText_Lines")
        self.actionReview_Ground_Truth_2 = QtWidgets.QAction(Scanner)
        self.actionReview_Ground_Truth_2.setObjectName("actionReview_Ground_Truth_2")
        self.actionUpdate_Wordlist = QtWidgets.QAction(Scanner)
        self.actionUpdate_Wordlist.setObjectName("actionUpdate_Wordlist")
        self.actionUpdate_Wordlist_2 = QtWidgets.QAction(Scanner)
        self.actionUpdate_Wordlist_2.setObjectName("actionUpdate_Wordlist_2")
        self.actionCorrect_OCR_tb = QtWidgets.QAction(Scanner)
        self.actionCorrect_OCR_tb.setIcon(icon17)
        self.actionCorrect_OCR_tb.setObjectName("actionCorrect_OCR_tb")
        self.actionVersify_Text = QtWidgets.QAction(Scanner)
        self.actionVersify_Text.setObjectName("actionVersify_Text")
        self.actionUpdate_Words = QtWidgets.QAction(Scanner)
        self.actionUpdate_Words.setObjectName("actionUpdate_Words")
        self.actionUpdate_Verses = QtWidgets.QAction(Scanner)
        self.actionUpdate_Verses.setObjectName("actionUpdate_Verses")
        self.actionUpdate_Words_Post = QtWidgets.QAction(Scanner)
        self.actionUpdate_Words_Post.setObjectName("actionUpdate_Words_Post")
        self.actionNormalize = QtWidgets.QAction(Scanner)
        self.actionNormalize.setObjectName("actionNormalize")
        self.actionLower_Case = QtWidgets.QAction(Scanner)
        self.actionLower_Case.setObjectName("actionLower_Case")
        self.actionRemove_Diacritics = QtWidgets.QAction(Scanner)
        self.actionRemove_Diacritics.setObjectName("actionRemove_Diacritics")
        self.actionAlign_Strongs = QtWidgets.QAction(Scanner)
        self.actionAlign_Strongs.setObjectName("actionAlign_Strongs")
        self.actionAlign_Lemmas = QtWidgets.QAction(Scanner)
        self.actionAlign_Lemmas.setObjectName("actionAlign_Lemmas")
        self.actionAlign_English = QtWidgets.QAction(Scanner)
        self.actionAlign_English.setObjectName("actionAlign_English")
        self.actionVariants = QtWidgets.QAction(Scanner)
        self.actionVariants.setObjectName("actionVariants")
        self.actionTrain_Tesseract_tb = QtWidgets.QAction(Scanner)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/Icons/Icons/trainOCR4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTrain_Tesseract_tb.setIcon(icon33)
        self.actionTrain_Tesseract_tb.setObjectName("actionTrain_Tesseract_tb")
        self.actionReview_Ground_Truth_tb = QtWidgets.QAction(Scanner)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/Icons/Icons/ground-truth1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReview_Ground_Truth_tb.setIcon(icon34)
        self.actionReview_Ground_Truth_tb.setObjectName("actionReview_Ground_Truth_tb")
        self.actionUpdate_Wordlist_tb = QtWidgets.QAction(Scanner)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/Icons/Icons/update-greek-wordlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdate_Wordlist_tb.setIcon(icon35)
        self.actionUpdate_Wordlist_tb.setObjectName("actionUpdate_Wordlist_tb")
        self.actionAutoCrop_Greek_to_tif_Lines_tb = QtWidgets.QAction(Scanner)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAutoCrop_Greek_to_tif_Lines_tb.setIcon(icon36)
        self.actionAutoCrop_Greek_to_tif_Lines_tb.setObjectName("actionAutoCrop_Greek_to_tif_Lines_tb")
        self.actionRename_Greek_tif_Lines_tb = QtWidgets.QAction(Scanner)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Greek_tif_Lines_tb.setIcon(icon37)
        self.actionRename_Greek_tif_Lines_tb.setObjectName("actionRename_Greek_tif_Lines_tb")
        self.actionMove_Greek_tif_Lines_tb = QtWidgets.QAction(Scanner)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/Icons/Icons/move-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_Greek_tif_Lines_tb.setIcon(icon38)
        self.actionMove_Greek_tif_Lines_tb.setObjectName("actionMove_Greek_tif_Lines_tb")
        self.actionSplitGreek_text_lines_tb = QtWidgets.QAction(Scanner)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-textlines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSplitGreek_text_lines_tb.setIcon(icon39)
        self.actionSplitGreek_text_lines_tb.setObjectName("actionSplitGreek_text_lines_tb")
        self.actionRenameGreek_text_lines_tb = QtWidgets.QAction(Scanner)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename_textlines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRenameGreek_text_lines_tb.setIcon(icon40)
        self.actionRenameGreek_text_lines_tb.setObjectName("actionRenameGreek_text_lines_tb")
        self.actionImage_Lines_3 = QtWidgets.QAction(Scanner)
        self.actionImage_Lines_3.setObjectName("actionImage_Lines_3")
        self.actionReview_Ground_Truth_menu = QtWidgets.QAction(Scanner)
        self.actionReview_Ground_Truth_menu.setObjectName("actionReview_Ground_Truth_menu")
        self.actionUpdate_Wordlist_menu = QtWidgets.QAction(Scanner)
        self.actionUpdate_Wordlist_menu.setObjectName("actionUpdate_Wordlist_menu")
        self.actionAutoCrop_Latin_To_tif_Lines_tb = QtWidgets.QAction(Scanner)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setIcon(icon41)
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setVisible(False)
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setIconVisibleInMenu(False)
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setObjectName("actionAutoCrop_Latin_To_tif_Lines_tb")
        self.actionRename_Latin_tif_Lines_tb = QtWidgets.QAction(Scanner)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Latin_tif_Lines_tb.setIcon(icon42)
        self.actionRename_Latin_tif_Lines_tb.setVisible(False)
        self.actionRename_Latin_tif_Lines_tb.setIconVisibleInMenu(False)
        self.actionRename_Latin_tif_Lines_tb.setObjectName("actionRename_Latin_tif_Lines_tb")
        self.actionMove_Latin_tif_Lines_tb = QtWidgets.QAction(Scanner)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(":/Icons/Icons/move-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_Latin_tif_Lines_tb.setIcon(icon43)
        self.actionMove_Latin_tif_Lines_tb.setVisible(False)
        self.actionMove_Latin_tif_Lines_tb.setIconVisibleInMenu(False)
        self.actionMove_Latin_tif_Lines_tb.setObjectName("actionMove_Latin_tif_Lines_tb")
        self.actionSplit_Latin_Text_Lines_tb = QtWidgets.QAction(Scanner)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-textlines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSplit_Latin_Text_Lines_tb.setIcon(icon44)
        self.actionSplit_Latin_Text_Lines_tb.setWhatsThis("")
        self.actionSplit_Latin_Text_Lines_tb.setVisible(False)
        self.actionSplit_Latin_Text_Lines_tb.setObjectName("actionSplit_Latin_Text_Lines_tb")
        self.actionRename_Latin_Text_Lines_tb = QtWidgets.QAction(Scanner)
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-textlines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Latin_Text_Lines_tb.setIcon(icon45)
        self.actionRename_Latin_Text_Lines_tb.setVisible(False)
        self.actionRename_Latin_Text_Lines_tb.setIconVisibleInMenu(False)
        self.actionRename_Latin_Text_Lines_tb.setObjectName("actionRename_Latin_Text_Lines_tb")
        self.actiondeskew_mono = QtWidgets.QAction(Scanner)
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-tiff-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondeskew_mono.setIcon(icon46)
        self.actiondeskew_mono.setObjectName("actiondeskew_mono")
        self.actionOpen_Image = QtWidgets.QAction(Scanner)
        self.actionOpen_Image.setIcon(icon1)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionVersifier = QtWidgets.QAction(Scanner)
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionVersifier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVersifier.setIcon(icon47)
        self.actionVersifier.setObjectName("actionVersifier")
        self.actionConvert_Greek_tiff_To_png = QtWidgets.QAction(Scanner)
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff2png-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConvert_Greek_tiff_To_png.setIcon(icon48)
        self.actionConvert_Greek_tiff_To_png.setObjectName("actionConvert_Greek_tiff_To_png")
        self.actionConvert_Latin_tiff_To_png = QtWidgets.QAction(Scanner)
        self.actionConvert_Latin_tiff_To_png.setEnabled(False)
        icon49 = QtGui.QIcon()
        icon49.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff2png-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConvert_Latin_tiff_To_png.setIcon(icon49)
        self.actionConvert_Latin_tiff_To_png.setVisible(False)
        self.actionConvert_Latin_tiff_To_png.setIconVisibleInMenu(False)
        self.actionConvert_Latin_tiff_To_png.setObjectName("actionConvert_Latin_tiff_To_png")
        self.actionExtract_Glyphs = QtWidgets.QAction(Scanner)
        icon50 = QtGui.QIcon()
        icon50.addPixmap(QtGui.QPixmap(":/Icons/Icons/trace1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExtract_Glyphs.setIcon(icon50)
        self.actionExtract_Glyphs.setObjectName("actionExtract_Glyphs")
        self.actionLine_tif_to_bmp = QtWidgets.QAction(Scanner)
        icon51 = QtGui.QIcon()
        icon51.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff2bmp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLine_tif_to_bmp.setIcon(icon51)
        self.actionLine_tif_to_bmp.setObjectName("actionLine_tif_to_bmp")
        self.actionFontForge = QtWidgets.QAction(Scanner)
        icon52 = QtGui.QIcon()
        icon52.addPixmap(QtGui.QPixmap(":/Icons/Icons/FontForge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFontForge.setIcon(icon52)
        self.actionFontForge.setObjectName("actionFontForge")
        self.actionPrefernces = QtWidgets.QAction(Scanner)
        self.actionPrefernces.setObjectName("actionPrefernces")
        self.actionOpen_Text = QtWidgets.QAction(Scanner)
        self.actionOpen_Text.setIcon(icon2)
        self.actionOpen_Text.setObjectName("actionOpen_Text")
        self.actionSave_Image = QtWidgets.QAction(Scanner)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionSave_As_Image = QtWidgets.QAction(Scanner)
        self.actionSave_As_Image.setObjectName("actionSave_As_Image")
        self.actionSave_Text = QtWidgets.QAction(Scanner)
        self.actionSave_Text.setIcon(icon4)
        self.actionSave_Text.setObjectName("actionSave_Text")
        self.actionSave_As_Text = QtWidgets.QAction(Scanner)
        self.actionSave_As_Text.setIcon(icon3)
        self.actionSave_As_Text.setObjectName("actionSave_As_Text")
        self.actionConvert_Image_s = QtWidgets.QAction(Scanner)
        self.actionConvert_Image_s.setObjectName("actionConvert_Image_s")
        self.actionReview_Ground_Truth_3 = QtWidgets.QAction(Scanner)
        self.actionReview_Ground_Truth_3.setObjectName("actionReview_Ground_Truth_3")
        self.actionHebrew = QtWidgets.QAction(Scanner)
        self.actionHebrew.setObjectName("actionHebrew")
        self.actionHebrew_2 = QtWidgets.QAction(Scanner)
        self.actionHebrew_2.setObjectName("actionHebrew_2")
        self.actionUpdate_Hebrew_Wordlist = QtWidgets.QAction(Scanner)
        self.actionUpdate_Hebrew_Wordlist.setObjectName("actionUpdate_Hebrew_Wordlist")
        self.actionHebrew_3 = QtWidgets.QAction(Scanner)
        self.actionHebrew_3.setObjectName("actionHebrew_3")
        self.actionOCR_Image = QtWidgets.QAction(Scanner)
        self.actionOCR_Image.setObjectName("actionOCR_Image")
        self.actionSelect_Image = QtWidgets.QAction(Scanner)
        self.actionSelect_Image.setObjectName("actionSelect_Image")
        self.actionGreek_2 = QtWidgets.QAction(Scanner)
        self.actionGreek_2.setObjectName("actionGreek_2")
        self.actionHebrew_4 = QtWidgets.QAction(Scanner)
        self.actionHebrew_4.setObjectName("actionHebrew_4")
        self.actionLatin_2 = QtWidgets.QAction(Scanner)
        self.actionLatin_2.setObjectName("actionLatin_2")
        self.actionSelect_Language_Model = QtWidgets.QAction(Scanner)
        self.actionSelect_Language_Model.setObjectName("actionSelect_Language_Model")
        self.actionSelect_Fonts = QtWidgets.QAction(Scanner)
        self.actionSelect_Fonts.setObjectName("actionSelect_Fonts")
        self.actionany = QtWidgets.QAction(Scanner)
        self.actionany.setObjectName("actionany")
        self.actionAny = QtWidgets.QAction(Scanner)
        self.actionAny.setObjectName("actionAny")
        self.actionStage_Ground_Truth = QtWidgets.QAction(Scanner)
        self.actionStage_Ground_Truth.setObjectName("actionStage_Ground_Truth")
        self.actionCreate_e_Sword_Bible_Module = QtWidgets.QAction(Scanner)
        icon53 = QtGui.QIcon()
        icon53.addPixmap(QtGui.QPixmap(":/Icons/Icons/esword.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_e_Sword_Bible_Module.setIcon(icon53)
        self.actionCreate_e_Sword_Bible_Module.setObjectName("actionCreate_e_Sword_Bible_Module")
        self.actionCreate_theWord_Bible_Module = QtWidgets.QAction(Scanner)
        icon54 = QtGui.QIcon()
        icon54.addPixmap(QtGui.QPixmap(":/Icons/Icons/theword.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_theWord_Bible_Module.setIcon(icon54)
        self.actionCreate_theWord_Bible_Module.setObjectName("actionCreate_theWord_Bible_Module")
        self.actionEnglish = QtWidgets.QAction(Scanner)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionEnglishh = QtWidgets.QAction(Scanner)
        self.actionEnglishh.setObjectName("actionEnglishh")
        self.actionEnglish_2 = QtWidgets.QAction(Scanner)
        self.actionEnglish_2.setObjectName("actionEnglish_2")
        self.actionEnglish_3 = QtWidgets.QAction(Scanner)
        self.actionEnglish_3.setObjectName("actionEnglish_3")
        self.actionOnline = QtWidgets.QAction(Scanner)
        self.actionOnline.setObjectName("actionOnline")
        self.actionManual_Crop_Image_tb = QtWidgets.QAction(Scanner)
        icon55 = QtGui.QIcon()
        icon55.addPixmap(QtGui.QPixmap(":/Icons/Icons/image-crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionManual_Crop_Image_tb.setIcon(icon55)
        self.actionManual_Crop_Image_tb.setObjectName("actionManual_Crop_Image_tb")
        self.actionEdit_Image_tb = QtWidgets.QAction(Scanner)
        icon56 = QtGui.QIcon()
        icon56.addPixmap(QtGui.QPixmap(":/Icons/Icons/gimp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_Image_tb.setIcon(icon56)
        self.actionEdit_Image_tb.setObjectName("actionEdit_Image_tb")
        self.actionLibreOffice_Writer = QtWidgets.QAction(Scanner)
        self.actionLibreOffice_Writer.setIcon(icon5)
        self.actionLibreOffice_Writer.setObjectName("actionLibreOffice_Writer")
        self.actionLibreOffice_Calc = QtWidgets.QAction(Scanner)
        icon57 = QtGui.QIcon()
        icon57.addPixmap(QtGui.QPixmap(":/Icons/Icons/libreoffice-calc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLibreOffice_Calc.setIcon(icon57)
        self.actionLibreOffice_Calc.setObjectName("actionLibreOffice_Calc")
        self.actionDB_Browser_for_SQLite = QtWidgets.QAction(Scanner)
        icon58 = QtGui.QIcon()
        icon58.addPixmap(QtGui.QPixmap(":/Icons/Icons/server.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDB_Browser_for_SQLite.setIcon(icon58)
        self.actionDB_Browser_for_SQLite.setObjectName("actionDB_Browser_for_SQLite")
        self.actionFind_and_Replace = QtWidgets.QAction(Scanner)
        self.actionFind_and_Replace.setIcon(icon21)
        self.actionFind_and_Replace.setObjectName("actionFind_and_Replace")
        self.actionInstall_Font = QtWidgets.QAction(Scanner)
        icon59 = QtGui.QIcon()
        icon59.addPixmap(QtGui.QPixmap(":/Icons/Icons/font.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInstall_Font.setIcon(icon59)
        self.actionInstall_Font.setObjectName("actionInstall_Font")
        self.actionToggle_Greek_Toolbars = QtWidgets.QAction(Scanner)
        self.actionToggle_Greek_Toolbars.setObjectName("actionToggle_Greek_Toolbars")
        self.actionToggle_Latin_Toolbars = QtWidgets.QAction(Scanner)
        self.actionToggle_Latin_Toolbars.setObjectName("actionToggle_Latin_Toolbars")
        self.actionPrepare_Text = QtWidgets.QAction(Scanner)
        self.actionPrepare_Text.setObjectName("actionPrepare_Text")
        self.actionEnglish_4 = QtWidgets.QAction(Scanner)
        self.actionEnglish_4.setObjectName("actionEnglish_4")
        self.actionLatin_3 = QtWidgets.QAction(Scanner)
        self.actionLatin_3.setObjectName("actionLatin_3")
        self.actionStart = QtWidgets.QAction(Scanner)
        self.actionStart.setObjectName("actionStart")
        self.actionHebrew_5 = QtWidgets.QAction(Scanner)
        self.actionHebrew_5.setObjectName("actionHebrew_5")
        self.actionGimp = QtWidgets.QAction(Scanner)
        self.actionGimp.setIcon(icon56)
        self.actionGimp.setObjectName("actionGimp")
        self.actionLibre_Office_Writer = QtWidgets.QAction(Scanner)
        self.actionLibre_Office_Writer.setIcon(icon5)
        self.actionLibre_Office_Writer.setObjectName("actionLibre_Office_Writer")
        self.actionLibre_Office_Calc = QtWidgets.QAction(Scanner)
        self.actionLibre_Office_Calc.setIcon(icon57)
        self.actionLibre_Office_Calc.setObjectName("actionLibre_Office_Calc")
        self.actionFont_Forge = QtWidgets.QAction(Scanner)
        self.actionFont_Forge.setIcon(icon52)
        self.actionFont_Forge.setObjectName("actionFont_Forge")
        self.actionDeveloper = QtWidgets.QAction(Scanner)
        self.actionDeveloper.setObjectName("actionDeveloper")
        self.actionAcademic = QtWidgets.QAction(Scanner)
        self.actionAcademic.setObjectName("actionAcademic")
        self.actionMistry = QtWidgets.QAction(Scanner)
        self.actionMistry.setObjectName("actionMistry")
        self.actionPixler_Image_Editor = QtWidgets.QAction(Scanner)
        self.actionPixler_Image_Editor.setIcon(icon8)
        self.actionPixler_Image_Editor.setObjectName("actionPixler_Image_Editor")
        self.actionWriter = QtWidgets.QAction(Scanner)
        self.actionWriter.setIcon(icon20)
        self.actionWriter.setObjectName("actionWriter")
        self.actionBoxer = QtWidgets.QAction(Scanner)
        icon60 = QtGui.QIcon()
        icon60.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionBoxer2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBoxer.setIcon(icon60)
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        self.actionBoxer.setFont(font)
        self.actionBoxer.setObjectName("actionBoxer")
        self.actionProject_Browser = QtWidgets.QAction(Scanner)
        icon61 = QtGui.QIcon()
        icon61.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionExplorer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProject_Browser.setIcon(icon61)
        self.actionProject_Browser.setObjectName("actionProject_Browser")
        self.actionCharacter_Reference = QtWidgets.QAction(Scanner)
        icon62 = QtGui.QIcon()
        icon62.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionGlypher.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCharacter_Reference.setIcon(icon62)
        self.actionCharacter_Reference.setObjectName("actionCharacter_Reference")
        self.menuSelect_Language.addAction(self.actionGreek_2)
        self.menuSelect_Language.addAction(self.actionHebrew_4)
        self.menuSelect_Language.addAction(self.actionLatin_2)
        self.menuSelect_Language.addAction(self.actionEnglish_2)
        self.menuOCR.addAction(self.menuSelect_Language.menuAction())
        self.menuOCR.addAction(self.actionSelect_Image)
        self.menuOCR.addAction(self.actionCorrect_OCR_tb)
        self.menuFile.addAction(self.actionProject_Browser)
        self.menuFile.addAction(self.actionOpen_Image)
        self.menuFile.addAction(self.actionOpen_Text)
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addAction(self.actionSave_As_Image)
        self.menuFile.addAction(self.actionSave_Text)
        self.menuFile.addAction(self.actionSave_As_Text)
        self.menuEdit.addAction(self.actionPixler_Image_Editor)
        self.menuEdit.addAction(self.actionEdit_Image_tb)
        self.menuEdit.addAction(self.actionPrefernces)
        self.menuEdit.addAction(self.actionFind_and_Replace)
        self.menuView.addAction(self.actionToggle_Greek_Toolbars)
        self.menuView.addAction(self.actionToggle_Latin_Toolbars)
        self.menuTools.addAction(self.actionConvert_Image_s)
        self.menuTools.addAction(self.actionOnline)
        self.menuTools.addAction(self.actionVersifier)
        self.menuTools.addAction(self.actionLibreOffice_Writer)
        self.menuTools.addAction(self.actionLibreOffice_Calc)
        self.menuTools.addAction(self.actionGimp)
        self.menuTools.addAction(self.actionWriter)
        self.menuTools.addAction(self.actionBoxer)
        self.menuTools.addAction(self.actionCharacter_Reference)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuOCR.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.ImageEditToolBar.addAction(self.actionProject_Browser)
        self.ImageEditToolBar.addAction(self.actionCharacter_Reference)
        self.ImageEditToolBar.addAction(self.actionPixler_Image_Editor)
        self.ImageEditToolBar.addAction(self.actionEdit_Image_tb)
        self.ImageEditToolBar.addAction(self.actionCorrect_OCR_tb)
        self.ImageEditToolBar.addAction(self.actionVersifier)
        self.ImageEditToolBar.addAction(self.actionWriter)
        self.ImageEditToolBar.addAction(self.actionBoxer)

        self.retranslateUi(Scanner)
        QtCore.QMetaObject.connectSlotsByName(Scanner)

    def retranslateUi(self, Scanner):
        _translate = QtCore.QCoreApplication.translate
        Scanner.setWindowTitle(_translate("Scanner", "βϊϐλίον Scanner"))
        self.OpenImageFilebutton.setToolTip(_translate("Scanner", "Open current image"))
        self.ImageLe.setToolTip(_translate("Scanner", "Current image name"))
        self.EditCorrectedTextbutton.setToolTip(_translate("Scanner", "Open current text(.txt,.csv) file"))
        self.SaveAsOCRCorrTextbutton.setToolTip(_translate("Scanner", "Save current text file as..."))
        self.SaveOCRCorrTextbutton.setToolTip(_translate("Scanner", "Overwrite current text file"))
        self.Writerbutton.setToolTip(_translate("Scanner", "Edit current text(.txt) file with OpenOffice Writer"))
        self.reloadTextbutton.setToolTip(_translate("Scanner", "Reload current text"))
        self.reloadImagebutton.setToolTip(_translate("Scanner", "Reload current image"))
        self.MyPixlerbutton.setToolTip(_translate("Scanner", "Edit images with Pixer"))
        self.Deskewbutton.setToolTip(_translate("Scanner", "Deskew current image"))
        self.PrevImgButton.setToolTip(_translate("Scanner", "Previous current image - !pair independent"))
        self.NextImgButton.setToolTip(_translate("Scanner", "Next current image - !pair independent"))
        self.PrevTxtButton.setToolTip(_translate("Scanner", "Previous current text - !pair independent"))
        self.NextTxtButton.setToolTip(_translate("Scanner", "Next current text - !pair independent"))
        self.BothNextButton.setToolTip(_translate("Scanner", "Next current image|text pair"))
        self.BothPrevButton.setToolTip(_translate("Scanner", "Previous current image|text pair"))
        self.BothLoadButton.setToolTip(_translate("Scanner", "Load current image|text pair"))
        self.OCRlangComboBox.setToolTip(_translate("Scanner", "Select OCR language"))
        self.OCRlangComboBox.setItemText(0, _translate("Scanner", "Ancient Greek"))
        self.OCRlangComboBox.setItemText(1, _translate("Scanner", "Middle Greek"))
        self.OCRlangComboBox.setItemText(2, _translate("Scanner", "Modern Greek"))
        self.OCRlangComboBox.setItemText(3, _translate("Scanner", "Hebrew"))
        self.OCRlangComboBox.setItemText(4, _translate("Scanner", "Latin"))
        self.OCRlanglabel.setText(_translate("Scanner", " OCR Language"))
        self.OCRModellabel.setToolTip(_translate("Scanner", "Select OCR LSTM model"))
        self.OCRModellabel.setText(_translate("Scanner", " OCR LSTM Model"))
        self.OCRModelComboBox.setToolTip(_translate("Scanner", "Select OCR language model"))
        self.OCRModelComboBox.setItemText(0, _translate("Scanner", "ell"))
        self.OCRModelComboBox.setItemText(1, _translate("Scanner", "grc"))
        self.OCRModelComboBox.setItemText(2, _translate("Scanner", "feg"))
        self.OCRModelComboBox.setItemText(3, _translate("Scanner", "heb"))
        self.OCRModelComboBox.setItemText(4, _translate("Scanner", "feh"))
        self.OCRModelComboBox.setItemText(5, _translate("Scanner", "lat"))
        self.OCRModelComboBox.setItemText(6, _translate("Scanner", "fel"))
        self.OCRbutton.setToolTip(_translate("Scanner", "OCR current image"))
        self.OCRbutton.setText(_translate("Scanner", "OCR Raw"))
        self.booklabel.setText(_translate("Scanner", "Book"))
        self.bookComboBox.setToolTip(_translate("Scanner", "Bible book current image|text directory"))
        self.bookComboBox.setItemText(0, _translate("Scanner", "Mat"))
        self.bookComboBox.setItemText(1, _translate("Scanner", "Mar"))
        self.bookComboBox.setItemText(2, _translate("Scanner", "Luk"))
        self.bookComboBox.setItemText(3, _translate("Scanner", "Joh"))
        self.bookComboBox.setItemText(4, _translate("Scanner", "Act"))
        self.bookComboBox.setItemText(5, _translate("Scanner", "Rom"))
        self.bookComboBox.setItemText(6, _translate("Scanner", "1Co"))
        self.bookComboBox.setItemText(7, _translate("Scanner", "2Co"))
        self.bookComboBox.setItemText(8, _translate("Scanner", "Gal"))
        self.bookComboBox.setItemText(9, _translate("Scanner", "Eph"))
        self.bookComboBox.setItemText(10, _translate("Scanner", "Php"))
        self.bookComboBox.setItemText(11, _translate("Scanner", "Col"))
        self.bookComboBox.setItemText(12, _translate("Scanner", "1Th"))
        self.bookComboBox.setItemText(13, _translate("Scanner", "2Th"))
        self.bookComboBox.setItemText(14, _translate("Scanner", "1Ti"))
        self.bookComboBox.setItemText(15, _translate("Scanner", "2Ti"))
        self.bookComboBox.setItemText(16, _translate("Scanner", "Tit"))
        self.bookComboBox.setItemText(17, _translate("Scanner", "Phm"))
        self.bookComboBox.setItemText(18, _translate("Scanner", "Heb"))
        self.bookComboBox.setItemText(19, _translate("Scanner", "Jas"))
        self.bookComboBox.setItemText(20, _translate("Scanner", "1Pe"))
        self.bookComboBox.setItemText(21, _translate("Scanner", "2Pe"))
        self.bookComboBox.setItemText(22, _translate("Scanner", "1Jn"))
        self.bookComboBox.setItemText(23, _translate("Scanner", "2Jn"))
        self.bookComboBox.setItemText(24, _translate("Scanner", "3Jn"))
        self.bookComboBox.setItemText(25, _translate("Scanner", "Jud"))
        self.bookComboBox.setItemText(26, _translate("Scanner", "Rev"))
        self.fontlabel.setText(_translate("Scanner", "Font"))
        self.fontSizelabel.setText(_translate("Scanner", "Font Size"))
        self.fontSizeBox.setToolTip(_translate("Scanner", "Select font size"))
        self.fontComboBox.setToolTip(_translate("Scanner", "Select font"))
        self.ZoomComboBox.setToolTip(_translate("Scanner", "Select current image zoom"))
        self.ZoomComboBox.setCurrentText(_translate("Scanner", "10 %"))
        self.ZoomComboBox.setItemText(0, _translate("Scanner", "10 %"))
        self.ZoomComboBox.setItemText(1, _translate("Scanner", "25 %"))
        self.ZoomComboBox.setItemText(2, _translate("Scanner", "50 %"))
        self.ZoomComboBox.setItemText(3, _translate("Scanner", "100 %"))
        self.ZoomComboBox.setItemText(4, _translate("Scanner", "200 %"))
        self.Zoombutton.setToolTip(_translate("Scanner", "Zoom decorator"))
        self.LHslider.setToolTip(_translate("Scanner", "Set current text line spacing"))
        self.LHlineEdit.setToolTip(_translate("Scanner", "Current text line spacing"))
        self.LHlineEdit.setText(_translate("Scanner", "150"))
        self.LHlineEdit.setPlaceholderText(_translate("Scanner", "150"))
        self.LHDialogtbutton.setToolTip(_translate("Scanner", "Enable line spacing slider"))
        self.Zoomslider.setToolTip(_translate("Scanner", "Set current text line spacing"))
        self.MyWriterbutton.setToolTip(_translate("Scanner", "Edit current text(.txt) file with OpenOffice Writer"))
        self.FindReplacebutton.setText(_translate("Scanner", "Find and Replace"))
        self.menuOCR.setTitle(_translate("Scanner", "OCR"))
        self.menuSelect_Language.setTitle(_translate("Scanner", "Select Language"))
        self.menuFile.setTitle(_translate("Scanner", "File"))
        self.menuEdit.setTitle(_translate("Scanner", "Edit"))
        self.menuView.setTitle(_translate("Scanner", "View"))
        self.menuTools.setTitle(_translate("Scanner", "Tools"))
        self.menuHelp.setTitle(_translate("Scanner", "Help"))
        self.ImageEditToolBar.setWindowTitle(_translate("Scanner", "ImageEditToolBar"))
        self.ImageEditToolBar.setToolTip(_translate("Scanner", "ImageEditToolBar"))
        self.actionpdf_to_tiff.setText(_translate("Scanner", "pdf for tiff"))
        self.actionmove_pdf_for_tiff.setText(_translate("Scanner", "pdf to tiff"))
        self.actiontiff_to_mono.setText(_translate("Scanner", "tiff to mono"))
        self.actionmono_to_png.setText(_translate("Scanner", "mono to png"))
        self.actiontiff_to_png.setText(_translate("Scanner", "tiff to png"))
        self.actionGreek.setText(_translate("Scanner", "Greek"))
        self.actiontiff_to_png_2.setText(_translate("Scanner", "tiff to png"))
        self.actionpdf_for_tiff.setText(_translate("Scanner", "pdf for tiff"))
        self.actionpdf_for_tiff_tb.setText(_translate("Scanner", "pdf For tiff"))
        self.actionpdf_for_tiff_tb.setToolTip(_translate("Scanner", "Stage extracted pdf pages FOR tif conversion"))
        self.actionpdf_for_tiff_tb.setStatusTip(_translate("Scanner", "Staging extracted pdf pages..."))
        self.actionpdf_to_tiff_tb.setText(_translate("Scanner", "pdf To tiff"))
        self.actionpdf_to_tiff_tb.setToolTip(_translate("Scanner", "Convert staged pdf pages TO tif pages"))
        self.actionpdf_to_tiff_tb.setStatusTip(_translate("Scanner", "Converting staged pdf pages..."))
        self.actiontiff_to_mono_tb.setText(_translate("Scanner", "tiff indexed"))
        self.actiontiff_to_mono_tb.setToolTip(_translate("Scanner", "Convert tif pages TO black&white indexed"))
        self.actiontiff_to_mono_tb.setStatusTip(_translate("Scanner", "Converting tif pages to black&white indexed..."))
        self.actionmono_to_png_tb.setText(_translate("Scanner", "png indexed"))
        self.actionmono_to_png_tb.setToolTip(_translate("Scanner", "Convert indexed tif pages TO png"))
        self.actionmono_to_png_tb.setStatusTip(_translate("Scanner", "Converting indexed tif pages to png pages..."))
        self.actionLatin.setText(_translate("Scanner", "Latin"))
        self.actiontiff_to_png_3.setText(_translate("Scanner", "tiff to png"))
        self.actiontiff_to_png_4.setText(_translate("Scanner", "tiff to png"))
        self.actionDeskewGreek_tiff_tb.setText(_translate("Scanner", "Deskew Greek tiff"))
        self.actionDeskewGreek_tiff_tb.setToolTip(_translate("Scanner", "Deskew Greek tif pages"))
        self.actionDeskewGreek_tiff_tb.setStatusTip(_translate("Scanner", "Deskewing Greek tif pages..."))
        self.actiontiff_to_png_5.setText(_translate("Scanner", "tiff to png"))
        self.actionDeskewLatin_tiff_tb.setText(_translate("Scanner", "Deskew Latin tif pages"))
        self.actionDeskewLatin_tiff_tb.setStatusTip(_translate("Scanner", "Deskewing Latin tif pages..."))
        self.actionResizeGreek_png_tb.setText(_translate("Scanner", "Resize Greek png pages"))
        self.actionResizeGreek_png_tb.setStatusTip(_translate("Scanner", "Resizing Greek png pages..."))
        self.actionResizeLatin_png_tb.setText(_translate("Scanner", "Resize Latin png pages"))
        self.actionResizeLatin_png_tb.setStatusTip(_translate("Scanner", "Resizing Latin png pages"))
        self.actionCrop_Languages_tb.setText(_translate("Scanner", "Auto Crop Languages"))
        self.actionCrop_Languages_tb.setToolTip(_translate("Scanner", "Auto crop language pages into separate tif files"))
        self.actionCrop_Languages_tb.setStatusTip(_translate("Scanner", "Auto cropping language pages..."))
        self.actionextract_pdf_tb.setText(_translate("Scanner", "Extract pdf"))
        self.actionextract_pdf_tb.setToolTip(_translate("Scanner", "Extract pdf pages from pdf source document"))
        self.actionextract_pdf_tb.setStatusTip(_translate("Scanner", "Extracting pdf pages..."))
        self.actiontiff_for_Ground_Truth.setText(_translate("Scanner", "tiff for Ground Truth"))
        self.actionCrop.setText(_translate("Scanner", "Crop to tiff lines"))
        self.actiontiff_for_Ground_Truth_2.setText(_translate("Scanner", "Move tiff lines"))
        self.actionSplit.setText(_translate("Scanner", "Split text lines"))
        self.actionRename_tiff_lines.setText(_translate("Scanner", "Rename tiff lines"))
        self.actionRename_text_lines.setText(_translate("Scanner", "Rename text lines"))
        self.actionReview_Ground_Truth.setText(_translate("Scanner", "Review Ground Truth"))
        self.actionGreek_Wordlist_2.setText(_translate("Scanner", "Greek Wordlist"))
        self.actionLatin_Wordlist.setText(_translate("Scanner", "Latin Wordlist"))
        self.actionImage_Lines.setText(_translate("Scanner", "Image Lines"))
        self.actionText_Lines.setText(_translate("Scanner", "Text Lines"))
        self.actionReview_Ground_Truth_2.setText(_translate("Scanner", "Review Ground Truth"))
        self.actionUpdate_Wordlist.setText(_translate("Scanner", "Update Wordlist"))
        self.actionUpdate_Wordlist_2.setText(_translate("Scanner", "Update Wordlist"))
        self.actionCorrect_OCR_tb.setText(_translate("Scanner", "OCR Image"))
        self.actionCorrect_OCR_tb.setToolTip(_translate("Scanner", "OCR current image"))
        self.actionCorrect_OCR_tb.setStatusTip(_translate("Scanner", "Performing OCR on current image..."))
        self.actionVersify_Text.setText(_translate("Scanner", "Versify Text"))
        self.actionUpdate_Words.setText(_translate("Scanner", "Latin"))
        self.actionUpdate_Verses.setText(_translate("Scanner", "Update Verses"))
        self.actionUpdate_Words_Post.setText(_translate("Scanner", "Update Words"))
        self.actionNormalize.setText(_translate("Scanner", "Normalize"))
        self.actionLower_Case.setText(_translate("Scanner", "Lower Case"))
        self.actionRemove_Diacritics.setText(_translate("Scanner", "Remove Diacritics"))
        self.actionAlign_Strongs.setText(_translate("Scanner", "Align Strongs+RMAC"))
        self.actionAlign_Lemmas.setText(_translate("Scanner", "Align Lemmas"))
        self.actionAlign_English.setText(_translate("Scanner", "Align English"))
        self.actionVariants.setText(_translate("Scanner", "Resolve Variants"))
        self.actionTrain_Tesseract_tb.setText(_translate("Scanner", "Train Tesseract"))
        self.actionTrain_Tesseract_tb.setToolTip(_translate("Scanner", "Train Tesseract OCR with current Ground Truth"))
        self.actionTrain_Tesseract_tb.setStatusTip(_translate("Scanner", "Training Tesseract OCR with current Ground Truth..."))
        self.actionReview_Ground_Truth_tb.setText(_translate("Scanner", "Validate Ground Truth"))
        self.actionReview_Ground_Truth_tb.setToolTip(_translate("Scanner", "Validate current Ground Truth image|text"))
        self.actionReview_Ground_Truth_tb.setStatusTip(_translate("Scanner", "Validating current Ground Truth image|text pairs..."))
        self.actionUpdate_Wordlist_tb.setText(_translate("Scanner", "Update Greek Wordlist"))
        self.actionUpdate_Wordlist_tb.setToolTip(_translate("Scanner", "Update Greek Wordlist for OCR Training"))
        self.actionUpdate_Wordlist_tb.setStatusTip(_translate("Scanner", "Upadting Greek wordlist..."))
        self.actionAutoCrop_Greek_to_tif_Lines_tb.setText(_translate("Scanner", "Crop Greek To tif Lines"))
        self.actionAutoCrop_Greek_to_tif_Lines_tb.setStatusTip(_translate("Scanner", "Auto cropping Greek tif lines...."))
        self.actionRename_Greek_tif_Lines_tb.setText(_translate("Scanner", "Rename Greek tif Lines"))
        self.actionRename_Greek_tif_Lines_tb.setStatusTip(_translate("Scanner", "Renaming Greek tif lines..."))
        self.actionMove_Greek_tif_Lines_tb.setText(_translate("Scanner", "Move Greek tif Lines"))
        self.actionMove_Greek_tif_Lines_tb.setStatusTip(_translate("Scanner", "Moving Greek tif lines..."))
        self.actionSplitGreek_text_lines_tb.setText(_translate("Scanner", "Split Greek Pages To Text Lines"))
        self.actionSplitGreek_text_lines_tb.setStatusTip(_translate("Scanner", "Splitting Greek pages to text lines..."))
        self.actionRenameGreek_text_lines_tb.setText(_translate("Scanner", "Rename Greek Text Lines"))
        self.actionRenameGreek_text_lines_tb.setStatusTip(_translate("Scanner", "Renaming Greek text lines..."))
        self.actionImage_Lines_3.setText(_translate("Scanner", "Image Lines"))
        self.actionReview_Ground_Truth_menu.setText(_translate("Scanner", "Review Ground Truth"))
        self.actionUpdate_Wordlist_menu.setText(_translate("Scanner", "Update Latin Wordlist"))
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setText(_translate("Scanner", "Crop Latin To tif Lines"))
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setIconText(_translate("Scanner", "Crop Latin To tif Lines"))
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setToolTip(_translate("Scanner", "Crop Latin To tif Lines"))
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setStatusTip(_translate("Scanner", "Auto croping Latin tif lines..."))
        self.actionRename_Latin_tif_Lines_tb.setText(_translate("Scanner", "Rename Latin tif Lines"))
        self.actionRename_Latin_tif_Lines_tb.setStatusTip(_translate("Scanner", "Renaming Latin tif lines..."))
        self.actionMove_Latin_tif_Lines_tb.setText(_translate("Scanner", "Move Latin tif Lines"))
        self.actionMove_Latin_tif_Lines_tb.setStatusTip(_translate("Scanner", "Moving Latin tif lines..."))
        self.actionSplit_Latin_Text_Lines_tb.setText(_translate("Scanner", "Split Latin Pages To Text Lines"))
        self.actionSplit_Latin_Text_Lines_tb.setStatusTip(_translate("Scanner", "Splitting Latin pages to text lines..."))
        self.actionRename_Latin_Text_Lines_tb.setText(_translate("Scanner", "Rename Latin Text Lines"))
        self.actionRename_Latin_Text_Lines_tb.setStatusTip(_translate("Scanner", "Renaming Latin text lines..."))
        self.actiondeskew_mono.setText(_translate("Scanner", "Deskew indexed"))
        self.actiondeskew_mono.setToolTip(_translate("Scanner", "Transform indexed tif pages To deskewed tif and png pages"))
        self.actiondeskew_mono.setStatusTip(_translate("Scanner", "Deskewing indexed tif pages..."))
        self.actionOpen_Image.setText(_translate("Scanner", "Open Image"))
        self.actionVersifier.setText(_translate("Scanner", "Verse Correction"))
        self.actionVersifier.setToolTip(_translate("Scanner", "Book Chapter:Verse Text Assignment"))
        self.actionVersifier.setStatusTip(_translate("Scanner", "Assigning Book Chapter:Verse to text lines"))
        self.actionConvert_Greek_tiff_To_png.setText(_translate("Scanner", "Convert Greek tif To png"))
        self.actionConvert_Greek_tiff_To_png.setStatusTip(_translate("Scanner", "Converting Greek tif pages to png pages"))
        self.actionConvert_Latin_tiff_To_png.setText(_translate("Scanner", "Convert Latin tif To png"))
        self.actionConvert_Latin_tiff_To_png.setToolTip(_translate("Scanner", "Convert Latin tif pages To png pages"))
        self.actionConvert_Latin_tiff_To_png.setStatusTip(_translate("Scanner", "Converting Latin tif pages To png pages"))
        self.actionExtract_Glyphs.setText(_translate("Scanner", "GlyphTracer"))
        self.actionExtract_Glyphs.setToolTip(_translate("Scanner", "Extract and trace bitmap glyphs with GlyphTracer"))
        self.actionExtract_Glyphs.setStatusTip(_translate("Scanner", "Extracting and trace bitmap glyphs with GlyphTracer..."))
        self.actionLine_tif_to_bmp.setText(_translate("Scanner", "Convert tif To bmp"))
        self.actionLine_tif_to_bmp.setToolTip(_translate("Scanner", "Convert current tif image to bmp"))
        self.actionLine_tif_to_bmp.setStatusTip(_translate("Scanner", "Converting current tif image to bmp..."))
        self.actionFontForge.setText(_translate("Scanner", "FontForge"))
        self.actionFontForge.setToolTip(_translate("Scanner", "Edit current GlyphTracer sfd file in FontForge"))
        self.actionFontForge.setStatusTip(_translate("Scanner", "Editing current GlyphTracer sfd file in FontForge..."))
        self.actionPrefernces.setText(_translate("Scanner", "Preferences"))
        self.actionOpen_Text.setText(_translate("Scanner", "Open Text"))
        self.actionSave_Image.setText(_translate("Scanner", "Save Image"))
        self.actionSave_As_Image.setText(_translate("Scanner", "Save As Image"))
        self.actionSave_Text.setText(_translate("Scanner", "Save Text"))
        self.actionSave_As_Text.setText(_translate("Scanner", "Save As Text"))
        self.actionConvert_Image_s.setText(_translate("Scanner", "Convert Image(s)"))
        self.actionReview_Ground_Truth_3.setText(_translate("Scanner", "Review Ground Truth"))
        self.actionHebrew.setText(_translate("Scanner", "Hebrew"))
        self.actionHebrew_2.setText(_translate("Scanner", "Hebrew"))
        self.actionUpdate_Hebrew_Wordlist.setText(_translate("Scanner", "Update Hebrew Wordlist"))
        self.actionHebrew_3.setText(_translate("Scanner", "Hebrew"))
        self.actionOCR_Image.setText(_translate("Scanner", "OCR Image"))
        self.actionSelect_Image.setText(_translate("Scanner", "Select Image"))
        self.actionGreek_2.setText(_translate("Scanner", "Greek"))
        self.actionHebrew_4.setText(_translate("Scanner", "Hebrew"))
        self.actionLatin_2.setText(_translate("Scanner", "Latin"))
        self.actionSelect_Language_Model.setText(_translate("Scanner", "Select Language Model"))
        self.actionSelect_Fonts.setText(_translate("Scanner", "Select Fonts"))
        self.actionany.setText(_translate("Scanner", "any"))
        self.actionAny.setText(_translate("Scanner", "Any"))
        self.actionStage_Ground_Truth.setText(_translate("Scanner", "Stage Ground Truth"))
        self.actionCreate_e_Sword_Bible_Module.setText(_translate("Scanner", "e-Sword Bible Module"))
        self.actionCreate_theWord_Bible_Module.setText(_translate("Scanner", "theWord Bible Module"))
        self.actionEnglish.setText(_translate("Scanner", "English"))
        self.actionEnglishh.setText(_translate("Scanner", "English"))
        self.actionEnglish_2.setText(_translate("Scanner", "English"))
        self.actionEnglish_3.setText(_translate("Scanner", "English"))
        self.actionOnline.setText(_translate("Scanner", "Online"))
        self.actionManual_Crop_Image_tb.setText(_translate("Scanner", "Manual Crop"))
        self.actionManual_Crop_Image_tb.setToolTip(_translate("Scanner", "Manually crop current tif image"))
        self.actionManual_Crop_Image_tb.setStatusTip(_translate("Scanner", "Manually cropping current tif image..."))
        self.actionEdit_Image_tb.setText(_translate("Scanner", "Gimp Image Editor"))
        self.actionEdit_Image_tb.setStatusTip(_translate("Scanner", "Editing image in Gimp..."))
        self.actionLibreOffice_Writer.setText(_translate("Scanner", "LibreOffice Writer"))
        self.actionLibreOffice_Calc.setText(_translate("Scanner", "LibreOffice Calc"))
        self.actionDB_Browser_for_SQLite.setText(_translate("Scanner", "DB Browser for SQLite"))
        self.actionFind_and_Replace.setText(_translate("Scanner", "Find and Replace"))
        self.actionInstall_Font.setText(_translate("Scanner", "Install Font"))
        self.actionToggle_Greek_Toolbars.setText(_translate("Scanner", "Toggle Greek Toolbars"))
        self.actionToggle_Latin_Toolbars.setText(_translate("Scanner", "Toggle Latin Toolbars"))
        self.actionPrepare_Text.setText(_translate("Scanner", "Prepare Text"))
        self.actionEnglish_4.setText(_translate("Scanner", "English"))
        self.actionLatin_3.setText(_translate("Scanner", "Latin"))
        self.actionStart.setText(_translate("Scanner", "Start"))
        self.actionHebrew_5.setText(_translate("Scanner", "Hebrew"))
        self.actionGimp.setText(_translate("Scanner", "Gimp"))
        self.actionLibre_Office_Writer.setText(_translate("Scanner", "Libre Office Writer"))
        self.actionLibre_Office_Calc.setText(_translate("Scanner", "Libre Office Calc"))
        self.actionFont_Forge.setText(_translate("Scanner", "Font Forge"))
        self.actionDeveloper.setText(_translate("Scanner", "Developer"))
        self.actionAcademic.setText(_translate("Scanner", "Academic"))
        self.actionMistry.setText(_translate("Scanner", "Ministry"))
        self.actionPixler_Image_Editor.setText(_translate("Scanner", "Pixer Image Editor"))
        self.actionWriter.setText(_translate("Scanner", "Writer"))
        self.actionBoxer.setText(_translate("Scanner", "Boxer"))
        self.actionProject_Browser.setText(_translate("Scanner", "Project Browser"))
        self.actionCharacter_Reference.setText(_translate("Scanner", "Character Reference"))
import UI_Icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Scanner = QtWidgets.QMainWindow()
    ui = Ui_Scanner()
    ui.setupUi(Scanner)
    Scanner.show()
    sys.exit(app.exec_())
