# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerUI/MyTrainerUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Trainer(object):
    def setupUi(self, Trainer):
        Trainer.setObjectName("Trainer")
        Trainer.setEnabled(True)
        Trainer.resize(1363, 928)
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        Trainer.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionTrainer1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Trainer.setWindowIcon(icon)
        Trainer.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(Trainer)
        self.centralwidget.setObjectName("centralwidget")
        self.VerseText = QtWidgets.QTextEdit(self.centralwidget)
        self.VerseText.setGeometry(QtCore.QRect(750, 60, 581, 671))
        self.VerseText.setMinimumSize(QtCore.QSize(540, 600))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.VerseText.setFont(font)
        self.VerseText.setObjectName("VerseText")
        self.RefText = QtWidgets.QTextEdit(self.centralwidget)
        self.RefText.setGeometry(QtCore.QRect(10, 60, 581, 671))
        self.RefText.setMinimumSize(QtCore.QSize(540, 600))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.RefText.setFont(font)
        self.RefText.setReadOnly(True)
        self.RefText.setObjectName("RefText")
        Trainer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Trainer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1363, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Trainer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Trainer)
        self.statusbar.setObjectName("statusbar")
        Trainer.setStatusBar(self.statusbar)
        self.dockOutput = QtWidgets.QDockWidget(Trainer)
        self.dockOutput.setEnabled(True)
        self.dockOutput.setMinimumSize(QtCore.QSize(100, 100))
        self.dockOutput.setBaseSize(QtCore.QSize(520, 200))
        self.dockOutput.setAccessibleName("")
        self.dockOutput.setAccessibleDescription("")
        self.dockOutput.setFloating(False)
        self.dockOutput.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.LeftDockWidgetArea)
        self.dockOutput.setObjectName("dockOutput")
        self.dockOutputContents = QtWidgets.QWidget()
        self.dockOutputContents.setMinimumSize(QtCore.QSize(0, 0))
        self.dockOutputContents.setObjectName("dockOutputContents")
        self.OutputText = QtWidgets.QTextEdit(self.dockOutputContents)
        self.OutputText.setGeometry(QtCore.QRect(10, -1, 1281, 101))
        self.OutputText.setMinimumSize(QtCore.QSize(100, 100))
        self.OutputText.setObjectName("OutputText")
        self.dockOutput.setWidget(self.dockOutputContents)
        Trainer.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockOutput)
        self.dockChrRef = QtWidgets.QDockWidget(Trainer)
        self.dockChrRef.setMinimumSize(QtCore.QSize(400, 619))
        self.dockChrRef.setBaseSize(QtCore.QSize(200, 200))
        self.dockChrRef.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockChrRef.setObjectName("dockChrRef")
        self.dockChrRefContents = QtWidgets.QWidget()
        self.dockChrRefContents.setMinimumSize(QtCore.QSize(400, 600))
        self.dockChrRefContents.setObjectName("dockChrRefContents")
        self.ChrRefplainTextEdit = QtWidgets.QPlainTextEdit(self.dockChrRefContents)
        self.ChrRefplainTextEdit.setGeometry(QtCore.QRect(0, 10, 380, 671))
        self.ChrRefplainTextEdit.setMinimumSize(QtCore.QSize(360, 500))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(18)
        self.ChrRefplainTextEdit.setFont(font)
        self.ChrRefplainTextEdit.setObjectName("ChrRefplainTextEdit")
        self.dockChrRef.setWidget(self.dockChrRefContents)
        Trainer.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockChrRef)
        self.ModulesToolBar = QtWidgets.QToolBar(Trainer)
        self.ModulesToolBar.setObjectName("ModulesToolBar")
        Trainer.addToolBar(QtCore.Qt.TopToolBarArea, self.ModulesToolBar)
        self.toolBar = QtWidgets.QToolBar(Trainer)
        self.toolBar.setObjectName("toolBar")
        Trainer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionpdf_to_tiff = QtWidgets.QAction(Trainer)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/ocr2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_to_tiff.setIcon(icon1)
        self.actionpdf_to_tiff.setObjectName("actionpdf_to_tiff")
        self.actionmove_pdf_for_tiff = QtWidgets.QAction(Trainer)
        self.actionmove_pdf_for_tiff.setObjectName("actionmove_pdf_for_tiff")
        self.actiontiff_to_mono = QtWidgets.QAction(Trainer)
        self.actiontiff_to_mono.setObjectName("actiontiff_to_mono")
        self.actionmono_to_png = QtWidgets.QAction(Trainer)
        self.actionmono_to_png.setObjectName("actionmono_to_png")
        self.actiontiff_to_png = QtWidgets.QAction(Trainer)
        self.actiontiff_to_png.setObjectName("actiontiff_to_png")
        self.actionGreek = QtWidgets.QAction(Trainer)
        self.actionGreek.setObjectName("actionGreek")
        self.actiontiff_to_png_2 = QtWidgets.QAction(Trainer)
        self.actiontiff_to_png_2.setObjectName("actiontiff_to_png_2")
        self.actionpdf_for_tiff = QtWidgets.QAction(Trainer)
        self.actionpdf_for_tiff.setObjectName("actionpdf_for_tiff")
        self.actionpdf_for_tiff_tb = QtWidgets.QAction(Trainer)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf4tiff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_for_tiff_tb.setIcon(icon2)
        self.actionpdf_for_tiff_tb.setObjectName("actionpdf_for_tiff_tb")
        self.actionpdf_to_tiff_tb = QtWidgets.QAction(Trainer)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf2tiff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdf_to_tiff_tb.setIcon(icon3)
        self.actionpdf_to_tiff_tb.setObjectName("actionpdf_to_tiff_tb")
        self.actiontiff_to_mono_tb = QtWidgets.QAction(Trainer)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiontiff_to_mono_tb.setIcon(icon4)
        self.actiontiff_to_mono_tb.setObjectName("actiontiff_to_mono_tb")
        self.actionmono_to_png_tb = QtWidgets.QAction(Trainer)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/png-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmono_to_png_tb.setIcon(icon5)
        self.actionmono_to_png_tb.setObjectName("actionmono_to_png_tb")
        self.actionLatin = QtWidgets.QAction(Trainer)
        self.actionLatin.setObjectName("actionLatin")
        self.actiontiff_to_png_3 = QtWidgets.QAction(Trainer)
        self.actiontiff_to_png_3.setObjectName("actiontiff_to_png_3")
        self.actiontiff_to_png_4 = QtWidgets.QAction(Trainer)
        self.actiontiff_to_png_4.setObjectName("actiontiff_to_png_4")
        self.actionDeskewGreek_tiff_tb = QtWidgets.QAction(Trainer)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeskewGreek_tiff_tb.setIcon(icon6)
        self.actionDeskewGreek_tiff_tb.setObjectName("actionDeskewGreek_tiff_tb")
        self.actiontiff_to_png_5 = QtWidgets.QAction(Trainer)
        self.actiontiff_to_png_5.setObjectName("actiontiff_to_png_5")
        self.actionDeskewLatin_tiff_tb = QtWidgets.QAction(Trainer)
        self.actionDeskewLatin_tiff_tb.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeskewLatin_tiff_tb.setIcon(icon7)
        self.actionDeskewLatin_tiff_tb.setVisible(False)
        self.actionDeskewLatin_tiff_tb.setIconVisibleInMenu(False)
        self.actionDeskewLatin_tiff_tb.setObjectName("actionDeskewLatin_tiff_tb")
        self.actionResizeGreek_png_tb = QtWidgets.QAction(Trainer)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/resize-png-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResizeGreek_png_tb.setIcon(icon8)
        self.actionResizeGreek_png_tb.setObjectName("actionResizeGreek_png_tb")
        self.actionResizeLatin_png_tb = QtWidgets.QAction(Trainer)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Icons/resize-png-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResizeLatin_png_tb.setIcon(icon9)
        self.actionResizeLatin_png_tb.setVisible(False)
        self.actionResizeLatin_png_tb.setIconVisibleInMenu(False)
        self.actionResizeLatin_png_tb.setObjectName("actionResizeLatin_png_tb")
        self.actionCrop_Languages_tb = QtWidgets.QAction(Trainer)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-langs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCrop_Languages_tb.setIcon(icon10)
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        self.actionCrop_Languages_tb.setFont(font)
        self.actionCrop_Languages_tb.setObjectName("actionCrop_Languages_tb")
        self.actionextract_pdf_tb = QtWidgets.QAction(Trainer)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/Icons/pdf-extract1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionextract_pdf_tb.setIcon(icon11)
        self.actionextract_pdf_tb.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionextract_pdf_tb.setObjectName("actionextract_pdf_tb")
        self.actiontiff_for_Ground_Truth = QtWidgets.QAction(Trainer)
        self.actiontiff_for_Ground_Truth.setObjectName("actiontiff_for_Ground_Truth")
        self.actionCrop = QtWidgets.QAction(Trainer)
        self.actionCrop.setObjectName("actionCrop")
        self.actiontiff_for_Ground_Truth_2 = QtWidgets.QAction(Trainer)
        self.actiontiff_for_Ground_Truth_2.setObjectName("actiontiff_for_Ground_Truth_2")
        self.actionSplit = QtWidgets.QAction(Trainer)
        self.actionSplit.setObjectName("actionSplit")
        self.actionRename_tiff_lines = QtWidgets.QAction(Trainer)
        self.actionRename_tiff_lines.setObjectName("actionRename_tiff_lines")
        self.actionRename_text_lines = QtWidgets.QAction(Trainer)
        self.actionRename_text_lines.setObjectName("actionRename_text_lines")
        self.actionReview_Ground_Truth = QtWidgets.QAction(Trainer)
        self.actionReview_Ground_Truth.setObjectName("actionReview_Ground_Truth")
        self.actionGreek_Wordlist_2 = QtWidgets.QAction(Trainer)
        self.actionGreek_Wordlist_2.setObjectName("actionGreek_Wordlist_2")
        self.actionLatin_Wordlist = QtWidgets.QAction(Trainer)
        self.actionLatin_Wordlist.setObjectName("actionLatin_Wordlist")
        self.actionImage_Lines = QtWidgets.QAction(Trainer)
        self.actionImage_Lines.setObjectName("actionImage_Lines")
        self.actionText_Lines = QtWidgets.QAction(Trainer)
        self.actionText_Lines.setObjectName("actionText_Lines")
        self.actionReview_Ground_Truth_2 = QtWidgets.QAction(Trainer)
        self.actionReview_Ground_Truth_2.setObjectName("actionReview_Ground_Truth_2")
        self.actionUpdate_Wordlist = QtWidgets.QAction(Trainer)
        self.actionUpdate_Wordlist.setObjectName("actionUpdate_Wordlist")
        self.actionUpdate_Wordlist_2 = QtWidgets.QAction(Trainer)
        self.actionUpdate_Wordlist_2.setObjectName("actionUpdate_Wordlist_2")
        self.actionCorrect_OCR_tb = QtWidgets.QAction(Trainer)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icons/Icons/ocr3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCorrect_OCR_tb.setIcon(icon12)
        self.actionCorrect_OCR_tb.setObjectName("actionCorrect_OCR_tb")
        self.actionVersify_Text = QtWidgets.QAction(Trainer)
        self.actionVersify_Text.setObjectName("actionVersify_Text")
        self.actionUpdate_Words = QtWidgets.QAction(Trainer)
        self.actionUpdate_Words.setObjectName("actionUpdate_Words")
        self.actionUpdate_Verses = QtWidgets.QAction(Trainer)
        self.actionUpdate_Verses.setObjectName("actionUpdate_Verses")
        self.actionUpdate_Words_Post = QtWidgets.QAction(Trainer)
        self.actionUpdate_Words_Post.setObjectName("actionUpdate_Words_Post")
        self.actionNormalize = QtWidgets.QAction(Trainer)
        self.actionNormalize.setObjectName("actionNormalize")
        self.actionLower_Case = QtWidgets.QAction(Trainer)
        self.actionLower_Case.setObjectName("actionLower_Case")
        self.actionRemove_Diacritics = QtWidgets.QAction(Trainer)
        self.actionRemove_Diacritics.setObjectName("actionRemove_Diacritics")
        self.actionAlign_Strongs = QtWidgets.QAction(Trainer)
        self.actionAlign_Strongs.setObjectName("actionAlign_Strongs")
        self.actionAlign_Lemmas = QtWidgets.QAction(Trainer)
        self.actionAlign_Lemmas.setObjectName("actionAlign_Lemmas")
        self.actionAlign_English = QtWidgets.QAction(Trainer)
        self.actionAlign_English.setObjectName("actionAlign_English")
        self.actionVariants = QtWidgets.QAction(Trainer)
        self.actionVariants.setObjectName("actionVariants")
        self.actionTrain_Tesseract_tb = QtWidgets.QAction(Trainer)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Icons/Icons/trainOCR4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTrain_Tesseract_tb.setIcon(icon13)
        self.actionTrain_Tesseract_tb.setObjectName("actionTrain_Tesseract_tb")
        self.actionReview_Ground_Truth_tb = QtWidgets.QAction(Trainer)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Icons/Icons/ground-truth1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReview_Ground_Truth_tb.setIcon(icon14)
        self.actionReview_Ground_Truth_tb.setObjectName("actionReview_Ground_Truth_tb")
        self.actionUpdate_Greek_Wordlist = QtWidgets.QAction(Trainer)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Icons/Icons/update-greek-wordlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdate_Greek_Wordlist.setIcon(icon15)
        self.actionUpdate_Greek_Wordlist.setObjectName("actionUpdate_Greek_Wordlist")
        self.actionAutoCrop_Greek_to_tif_Lines_tb = QtWidgets.QAction(Trainer)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAutoCrop_Greek_to_tif_Lines_tb.setIcon(icon16)
        self.actionAutoCrop_Greek_to_tif_Lines_tb.setObjectName("actionAutoCrop_Greek_to_tif_Lines_tb")
        self.actionRename_Greek_tif_Lines_tb = QtWidgets.QAction(Trainer)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Greek_tif_Lines_tb.setIcon(icon17)
        self.actionRename_Greek_tif_Lines_tb.setObjectName("actionRename_Greek_tif_Lines_tb")
        self.actionMove_Greek_tif_Lines_tb = QtWidgets.QAction(Trainer)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Icons/Icons/move-lines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_Greek_tif_Lines_tb.setIcon(icon18)
        self.actionMove_Greek_tif_Lines_tb.setObjectName("actionMove_Greek_tif_Lines_tb")
        self.actionSplitGreek_text_lines_tb = QtWidgets.QAction(Trainer)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-textlines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSplitGreek_text_lines_tb.setIcon(icon19)
        self.actionSplitGreek_text_lines_tb.setObjectName("actionSplitGreek_text_lines_tb")
        self.actionRenameGreek_text_lines_tb = QtWidgets.QAction(Trainer)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename_textlines-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRenameGreek_text_lines_tb.setIcon(icon20)
        self.actionRenameGreek_text_lines_tb.setObjectName("actionRenameGreek_text_lines_tb")
        self.actionImage_Lines_3 = QtWidgets.QAction(Trainer)
        self.actionImage_Lines_3.setObjectName("actionImage_Lines_3")
        self.actionReview_Ground_Truth_menu = QtWidgets.QAction(Trainer)
        self.actionReview_Ground_Truth_menu.setObjectName("actionReview_Ground_Truth_menu")
        self.actionUpdate_Latin_Wordlist = QtWidgets.QAction(Trainer)
        self.actionUpdate_Latin_Wordlist.setObjectName("actionUpdate_Latin_Wordlist")
        self.actionAutoCrop_Latin_To_tif_Lines_tb = QtWidgets.QAction(Trainer)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setIcon(icon21)
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setVisible(False)
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setIconVisibleInMenu(False)
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setObjectName("actionAutoCrop_Latin_To_tif_Lines_tb")
        self.actionRename_Latin_tif_Lines_tb = QtWidgets.QAction(Trainer)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Latin_tif_Lines_tb.setIcon(icon22)
        self.actionRename_Latin_tif_Lines_tb.setVisible(False)
        self.actionRename_Latin_tif_Lines_tb.setIconVisibleInMenu(False)
        self.actionRename_Latin_tif_Lines_tb.setObjectName("actionRename_Latin_tif_Lines_tb")
        self.actionMove_Latin_tif_Lines_tb = QtWidgets.QAction(Trainer)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/Icons/Icons/move-lines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_Latin_tif_Lines_tb.setIcon(icon23)
        self.actionMove_Latin_tif_Lines_tb.setVisible(False)
        self.actionMove_Latin_tif_Lines_tb.setIconVisibleInMenu(False)
        self.actionMove_Latin_tif_Lines_tb.setObjectName("actionMove_Latin_tif_Lines_tb")
        self.actionSplit_Latin_Text_Lines_tb = QtWidgets.QAction(Trainer)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/Icons/Icons/split-textlines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSplit_Latin_Text_Lines_tb.setIcon(icon24)
        self.actionSplit_Latin_Text_Lines_tb.setWhatsThis("")
        self.actionSplit_Latin_Text_Lines_tb.setVisible(False)
        self.actionSplit_Latin_Text_Lines_tb.setObjectName("actionSplit_Latin_Text_Lines_tb")
        self.actionRename_Latin_Text_Lines_tb = QtWidgets.QAction(Trainer)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/Icons/Icons/rename-textlines-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename_Latin_Text_Lines_tb.setIcon(icon25)
        self.actionRename_Latin_Text_Lines_tb.setVisible(False)
        self.actionRename_Latin_Text_Lines_tb.setIconVisibleInMenu(False)
        self.actionRename_Latin_Text_Lines_tb.setObjectName("actionRename_Latin_Text_Lines_tb")
        self.actiondeskew_mono = QtWidgets.QAction(Trainer)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/Icons/Icons/deskew-tiff-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondeskew_mono.setIcon(icon26)
        self.actiondeskew_mono.setObjectName("actiondeskew_mono")
        self.actionOpen_Image = QtWidgets.QAction(Trainer)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Image.setIcon(icon27)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionVerse_Correction = QtWidgets.QAction(Trainer)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/Icons/Icons/versify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVerse_Correction.setIcon(icon28)
        self.actionVerse_Correction.setObjectName("actionVerse_Correction")
        self.actionConvert_Greek_tiff_To_png = QtWidgets.QAction(Trainer)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff2png-greek.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConvert_Greek_tiff_To_png.setIcon(icon29)
        self.actionConvert_Greek_tiff_To_png.setObjectName("actionConvert_Greek_tiff_To_png")
        self.actionConvert_Latin_tiff_To_png = QtWidgets.QAction(Trainer)
        self.actionConvert_Latin_tiff_To_png.setEnabled(False)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff2png-latin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConvert_Latin_tiff_To_png.setIcon(icon30)
        self.actionConvert_Latin_tiff_To_png.setVisible(False)
        self.actionConvert_Latin_tiff_To_png.setIconVisibleInMenu(False)
        self.actionConvert_Latin_tiff_To_png.setObjectName("actionConvert_Latin_tiff_To_png")
        self.actionExtract_Glyphs = QtWidgets.QAction(Trainer)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/Icons/Icons/trace1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExtract_Glyphs.setIcon(icon31)
        self.actionExtract_Glyphs.setObjectName("actionExtract_Glyphs")
        self.actionLine_tif_to_bmp = QtWidgets.QAction(Trainer)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/Icons/Icons/tiff2bmp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLine_tif_to_bmp.setIcon(icon32)
        self.actionLine_tif_to_bmp.setObjectName("actionLine_tif_to_bmp")
        self.actionFontForge = QtWidgets.QAction(Trainer)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/Icons/Icons/FontForge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFontForge.setIcon(icon33)
        self.actionFontForge.setObjectName("actionFontForge")
        self.actionPreferences = QtWidgets.QAction(Trainer)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionOpen_Text = QtWidgets.QAction(Trainer)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-document-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Text.setIcon(icon34)
        self.actionOpen_Text.setObjectName("actionOpen_Text")
        self.actionSave_Image = QtWidgets.QAction(Trainer)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionSave_As_Image = QtWidgets.QAction(Trainer)
        self.actionSave_As_Image.setObjectName("actionSave_As_Image")
        self.actionSave_Text = QtWidgets.QAction(Trainer)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Text.setIcon(icon35)
        self.actionSave_Text.setObjectName("actionSave_Text")
        self.actionSave_As_Text = QtWidgets.QAction(Trainer)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk-rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As_Text.setIcon(icon36)
        self.actionSave_As_Text.setObjectName("actionSave_As_Text")
        self.actionConvert_Image_s = QtWidgets.QAction(Trainer)
        self.actionConvert_Image_s.setObjectName("actionConvert_Image_s")
        self.actionReview_Ground_Truth_3 = QtWidgets.QAction(Trainer)
        self.actionReview_Ground_Truth_3.setObjectName("actionReview_Ground_Truth_3")
        self.actionHebrew = QtWidgets.QAction(Trainer)
        self.actionHebrew.setObjectName("actionHebrew")
        self.actionHebrew_2 = QtWidgets.QAction(Trainer)
        self.actionHebrew_2.setObjectName("actionHebrew_2")
        self.actionUpdate_Hebrew_Wordlist = QtWidgets.QAction(Trainer)
        self.actionUpdate_Hebrew_Wordlist.setObjectName("actionUpdate_Hebrew_Wordlist")
        self.actionHebrew_3 = QtWidgets.QAction(Trainer)
        self.actionHebrew_3.setObjectName("actionHebrew_3")
        self.actionOCR_Image = QtWidgets.QAction(Trainer)
        self.actionOCR_Image.setObjectName("actionOCR_Image")
        self.actionSelect_Image = QtWidgets.QAction(Trainer)
        self.actionSelect_Image.setObjectName("actionSelect_Image")
        self.actionGreek_2 = QtWidgets.QAction(Trainer)
        self.actionGreek_2.setObjectName("actionGreek_2")
        self.actionHebrew_4 = QtWidgets.QAction(Trainer)
        self.actionHebrew_4.setObjectName("actionHebrew_4")
        self.actionLatin_2 = QtWidgets.QAction(Trainer)
        self.actionLatin_2.setObjectName("actionLatin_2")
        self.actionSelect_Language_Model = QtWidgets.QAction(Trainer)
        self.actionSelect_Language_Model.setObjectName("actionSelect_Language_Model")
        self.actionSelect_Fonts = QtWidgets.QAction(Trainer)
        self.actionSelect_Fonts.setObjectName("actionSelect_Fonts")
        self.actionany = QtWidgets.QAction(Trainer)
        self.actionany.setObjectName("actionany")
        self.actionAny = QtWidgets.QAction(Trainer)
        self.actionAny.setObjectName("actionAny")
        self.actionStage_Ground_Truth = QtWidgets.QAction(Trainer)
        self.actionStage_Ground_Truth.setObjectName("actionStage_Ground_Truth")
        self.actionCreate_e_Sword_Bible_Module = QtWidgets.QAction(Trainer)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/Icons/Icons/esword.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_e_Sword_Bible_Module.setIcon(icon37)
        self.actionCreate_e_Sword_Bible_Module.setObjectName("actionCreate_e_Sword_Bible_Module")
        self.actionCreate_theWord_Bible_Module = QtWidgets.QAction(Trainer)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/Icons/Icons/theword.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_theWord_Bible_Module.setIcon(icon38)
        self.actionCreate_theWord_Bible_Module.setObjectName("actionCreate_theWord_Bible_Module")
        self.actionEnglish = QtWidgets.QAction(Trainer)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionEnglishh = QtWidgets.QAction(Trainer)
        self.actionEnglishh.setObjectName("actionEnglishh")
        self.actionEnglish_2 = QtWidgets.QAction(Trainer)
        self.actionEnglish_2.setObjectName("actionEnglish_2")
        self.actionEnglish_3 = QtWidgets.QAction(Trainer)
        self.actionEnglish_3.setObjectName("actionEnglish_3")
        self.actionOnline = QtWidgets.QAction(Trainer)
        self.actionOnline.setObjectName("actionOnline")
        self.actionManual_Crop_Image_tb = QtWidgets.QAction(Trainer)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/Icons/Icons/image-crop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionManual_Crop_Image_tb.setIcon(icon39)
        self.actionManual_Crop_Image_tb.setObjectName("actionManual_Crop_Image_tb")
        self.actionEdit_Image_tb = QtWidgets.QAction(Trainer)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/Icons/Icons/gimp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit_Image_tb.setIcon(icon40)
        self.actionEdit_Image_tb.setObjectName("actionEdit_Image_tb")
        self.actionLibreOffice_Writer = QtWidgets.QAction(Trainer)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/Icons/Icons/libreoffice-writer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLibreOffice_Writer.setIcon(icon41)
        self.actionLibreOffice_Writer.setObjectName("actionLibreOffice_Writer")
        self.actionLibreOffice_Calc = QtWidgets.QAction(Trainer)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/Icons/Icons/libreoffice-calc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLibreOffice_Calc.setIcon(icon42)
        self.actionLibreOffice_Calc.setObjectName("actionLibreOffice_Calc")
        self.actionDB_Browser_for_SQLite = QtWidgets.QAction(Trainer)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(":/Icons/Icons/server.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDB_Browser_for_SQLite.setIcon(icon43)
        self.actionDB_Browser_for_SQLite.setObjectName("actionDB_Browser_for_SQLite")
        self.actionOpen_Reference_Text = QtWidgets.QAction(Trainer)
        self.actionOpen_Reference_Text.setIcon(icon34)
        self.actionOpen_Reference_Text.setObjectName("actionOpen_Reference_Text")
        self.action_Writer = QtWidgets.QAction(Trainer)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionWriter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Writer.setIcon(icon44)
        self.action_Writer.setObjectName("action_Writer")
        self.actionWordcount = QtWidgets.QAction(Trainer)
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(":/Icons/Icons/countblue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWordcount.setIcon(icon45)
        self.actionWordcount.setObjectName("actionWordcount")
        self.menuFile.addAction(self.actionOpen_Reference_Text)
        self.menuFile.addAction(self.actionOpen_Text)
        self.menuFile.addAction(self.actionSave_Text)
        self.menuFile.addAction(self.actionSave_As_Text)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuTools.addAction(self.action_Writer)
        self.menuTools.addAction(self.actionUpdate_Greek_Wordlist)
        self.menuTools.addAction(self.actionUpdate_Hebrew_Wordlist)
        self.menuTools.addAction(self.actionUpdate_Latin_Wordlist)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.ModulesToolBar.addAction(self.action_Writer)
        self.ModulesToolBar.addAction(self.actionUpdate_Greek_Wordlist)

        self.retranslateUi(Trainer)
        QtCore.QMetaObject.connectSlotsByName(Trainer)

    def retranslateUi(self, Trainer):
        _translate = QtCore.QCoreApplication.translate
        Trainer.setWindowTitle(_translate("Trainer", "βϊϐλίον Trainer"))
        self.menuFile.setTitle(_translate("Trainer", "File"))
        self.menuEdit.setTitle(_translate("Trainer", "Edit"))
        self.menuView.setTitle(_translate("Trainer", "View"))
        self.menuTools.setTitle(_translate("Trainer", "Tools"))
        self.menuHelp.setTitle(_translate("Trainer", "Help"))
        self.dockOutput.setWindowTitle(_translate("Trainer", " Output"))
        self.dockChrRef.setWindowTitle(_translate("Trainer", "Character Reference"))
        self.ChrRefplainTextEdit.setDocumentTitle(_translate("Trainer", "Character Reference"))
        self.ModulesToolBar.setWindowTitle(_translate("Trainer", "Versify Text Tool Bar"))
        self.ModulesToolBar.setToolTip(_translate("Trainer", "Versify Text Tool Bar"))
        self.toolBar.setWindowTitle(_translate("Trainer", "toolBar"))
        self.actionpdf_to_tiff.setText(_translate("Trainer", "pdf for tiff"))
        self.actionmove_pdf_for_tiff.setText(_translate("Trainer", "pdf to tiff"))
        self.actiontiff_to_mono.setText(_translate("Trainer", "tiff to mono"))
        self.actionmono_to_png.setText(_translate("Trainer", "mono to png"))
        self.actiontiff_to_png.setText(_translate("Trainer", "tiff to png"))
        self.actionGreek.setText(_translate("Trainer", "Greek"))
        self.actiontiff_to_png_2.setText(_translate("Trainer", "tiff to png"))
        self.actionpdf_for_tiff.setText(_translate("Trainer", "pdf for tiff"))
        self.actionpdf_for_tiff_tb.setText(_translate("Trainer", "pdf For tiff"))
        self.actionpdf_for_tiff_tb.setToolTip(_translate("Trainer", "Stage extracted pdf pages FOR tif conversion"))
        self.actionpdf_for_tiff_tb.setStatusTip(_translate("Trainer", "Staging extracted pdf pages..."))
        self.actionpdf_to_tiff_tb.setText(_translate("Trainer", "pdf To tiff"))
        self.actionpdf_to_tiff_tb.setToolTip(_translate("Trainer", "Convert staged pdf pages TO tif pages"))
        self.actionpdf_to_tiff_tb.setStatusTip(_translate("Trainer", "Converting staged pdf pages..."))
        self.actiontiff_to_mono_tb.setText(_translate("Trainer", "tiff indexed"))
        self.actiontiff_to_mono_tb.setToolTip(_translate("Trainer", "Convert tif pages TO black&white indexed"))
        self.actiontiff_to_mono_tb.setStatusTip(_translate("Trainer", "Converting tif pages to black&white indexed..."))
        self.actionmono_to_png_tb.setText(_translate("Trainer", "png indexed"))
        self.actionmono_to_png_tb.setToolTip(_translate("Trainer", "Convert indexed tif pages TO png"))
        self.actionmono_to_png_tb.setStatusTip(_translate("Trainer", "Converting indexed tif pages to png pages..."))
        self.actionLatin.setText(_translate("Trainer", "Latin"))
        self.actiontiff_to_png_3.setText(_translate("Trainer", "tiff to png"))
        self.actiontiff_to_png_4.setText(_translate("Trainer", "tiff to png"))
        self.actionDeskewGreek_tiff_tb.setText(_translate("Trainer", "Deskew Greek tiff"))
        self.actionDeskewGreek_tiff_tb.setToolTip(_translate("Trainer", "Deskew Greek tif pages"))
        self.actionDeskewGreek_tiff_tb.setStatusTip(_translate("Trainer", "Deskewing Greek tif pages..."))
        self.actiontiff_to_png_5.setText(_translate("Trainer", "tiff to png"))
        self.actionDeskewLatin_tiff_tb.setText(_translate("Trainer", "Deskew Latin tif pages"))
        self.actionDeskewLatin_tiff_tb.setStatusTip(_translate("Trainer", "Deskewing Latin tif pages..."))
        self.actionResizeGreek_png_tb.setText(_translate("Trainer", "Resize Greek png pages"))
        self.actionResizeGreek_png_tb.setStatusTip(_translate("Trainer", "Resizing Greek png pages..."))
        self.actionResizeLatin_png_tb.setText(_translate("Trainer", "Resize Latin png pages"))
        self.actionResizeLatin_png_tb.setStatusTip(_translate("Trainer", "Resizing Latin png pages"))
        self.actionCrop_Languages_tb.setText(_translate("Trainer", "Auto Crop Languages"))
        self.actionCrop_Languages_tb.setToolTip(_translate("Trainer", "Auto crop language pages into separate tif files"))
        self.actionCrop_Languages_tb.setStatusTip(_translate("Trainer", "Auto cropping language pages..."))
        self.actionextract_pdf_tb.setText(_translate("Trainer", "Extract pdf"))
        self.actionextract_pdf_tb.setToolTip(_translate("Trainer", "Extract pdf pages from pdf source document"))
        self.actionextract_pdf_tb.setStatusTip(_translate("Trainer", "Extracting pdf pages..."))
        self.actiontiff_for_Ground_Truth.setText(_translate("Trainer", "tiff for Ground Truth"))
        self.actionCrop.setText(_translate("Trainer", "Crop to tiff lines"))
        self.actiontiff_for_Ground_Truth_2.setText(_translate("Trainer", "Move tiff lines"))
        self.actionSplit.setText(_translate("Trainer", "Split text lines"))
        self.actionRename_tiff_lines.setText(_translate("Trainer", "Rename tiff lines"))
        self.actionRename_text_lines.setText(_translate("Trainer", "Rename text lines"))
        self.actionReview_Ground_Truth.setText(_translate("Trainer", "Review Ground Truth"))
        self.actionGreek_Wordlist_2.setText(_translate("Trainer", "Greek Wordlist"))
        self.actionLatin_Wordlist.setText(_translate("Trainer", "Latin Wordlist"))
        self.actionImage_Lines.setText(_translate("Trainer", "Image Lines"))
        self.actionText_Lines.setText(_translate("Trainer", "Text Lines"))
        self.actionReview_Ground_Truth_2.setText(_translate("Trainer", "Review Ground Truth"))
        self.actionUpdate_Wordlist.setText(_translate("Trainer", "Update Wordlist"))
        self.actionUpdate_Wordlist_2.setText(_translate("Trainer", "Update Wordlist"))
        self.actionCorrect_OCR_tb.setText(_translate("Trainer", "OCR Image"))
        self.actionCorrect_OCR_tb.setToolTip(_translate("Trainer", "OCR current image"))
        self.actionCorrect_OCR_tb.setStatusTip(_translate("Trainer", "Performing OCR on current image..."))
        self.actionVersify_Text.setText(_translate("Trainer", "Versify Text"))
        self.actionUpdate_Words.setText(_translate("Trainer", "Latin"))
        self.actionUpdate_Verses.setText(_translate("Trainer", "Update Verses"))
        self.actionUpdate_Words_Post.setText(_translate("Trainer", "Update Words"))
        self.actionNormalize.setText(_translate("Trainer", "Normalize"))
        self.actionLower_Case.setText(_translate("Trainer", "Lower Case"))
        self.actionRemove_Diacritics.setText(_translate("Trainer", "Remove Diacritics"))
        self.actionAlign_Strongs.setText(_translate("Trainer", "Align Strongs+RMAC"))
        self.actionAlign_Lemmas.setText(_translate("Trainer", "Align Lemmas"))
        self.actionAlign_English.setText(_translate("Trainer", "Align English"))
        self.actionVariants.setText(_translate("Trainer", "Variants"))
        self.actionTrain_Tesseract_tb.setText(_translate("Trainer", "Train Tesseract"))
        self.actionTrain_Tesseract_tb.setToolTip(_translate("Trainer", "Train Tesseract OCR with current Ground Truth"))
        self.actionTrain_Tesseract_tb.setStatusTip(_translate("Trainer", "Training Tesseract OCR with current Ground Truth..."))
        self.actionReview_Ground_Truth_tb.setText(_translate("Trainer", "Validate Ground Truth"))
        self.actionReview_Ground_Truth_tb.setToolTip(_translate("Trainer", "Validate current Ground Truth image|text"))
        self.actionReview_Ground_Truth_tb.setStatusTip(_translate("Trainer", "Validating current Ground Truth image|text pairs..."))
        self.actionUpdate_Greek_Wordlist.setText(_translate("Trainer", "Update Greek Wordlist"))
        self.actionUpdate_Greek_Wordlist.setToolTip(_translate("Trainer", "Update Greek Wordlist for OCR Training"))
        self.actionUpdate_Greek_Wordlist.setStatusTip(_translate("Trainer", "Upadting Greek wordlist..."))
        self.actionAutoCrop_Greek_to_tif_Lines_tb.setText(_translate("Trainer", "Crop Greek To tif Lines"))
        self.actionAutoCrop_Greek_to_tif_Lines_tb.setStatusTip(_translate("Trainer", "Auto cropping Greek tif lines...."))
        self.actionRename_Greek_tif_Lines_tb.setText(_translate("Trainer", "Rename Greek tif Lines"))
        self.actionRename_Greek_tif_Lines_tb.setStatusTip(_translate("Trainer", "Renaming Greek tif lines..."))
        self.actionMove_Greek_tif_Lines_tb.setText(_translate("Trainer", "Move Greek tif Lines"))
        self.actionMove_Greek_tif_Lines_tb.setStatusTip(_translate("Trainer", "Moving Greek tif lines..."))
        self.actionSplitGreek_text_lines_tb.setText(_translate("Trainer", "Split Greek Pages To Text Lines"))
        self.actionSplitGreek_text_lines_tb.setStatusTip(_translate("Trainer", "Splitting Greek pages to text lines..."))
        self.actionRenameGreek_text_lines_tb.setText(_translate("Trainer", "Rename Greek Text Lines"))
        self.actionRenameGreek_text_lines_tb.setStatusTip(_translate("Trainer", "Renaming Greek text lines..."))
        self.actionImage_Lines_3.setText(_translate("Trainer", "Image Lines"))
        self.actionReview_Ground_Truth_menu.setText(_translate("Trainer", "Review Ground Truth"))
        self.actionUpdate_Latin_Wordlist.setText(_translate("Trainer", "Update Latin Wordlist"))
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setText(_translate("Trainer", "Crop Latin To tif Lines"))
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setIconText(_translate("Trainer", "Crop Latin To tif Lines"))
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setToolTip(_translate("Trainer", "Crop Latin To tif Lines"))
        self.actionAutoCrop_Latin_To_tif_Lines_tb.setStatusTip(_translate("Trainer", "Auto croping Latin tif lines..."))
        self.actionRename_Latin_tif_Lines_tb.setText(_translate("Trainer", "Rename Latin tif Lines"))
        self.actionRename_Latin_tif_Lines_tb.setStatusTip(_translate("Trainer", "Renaming Latin tif lines..."))
        self.actionMove_Latin_tif_Lines_tb.setText(_translate("Trainer", "Move Latin tif Lines"))
        self.actionMove_Latin_tif_Lines_tb.setStatusTip(_translate("Trainer", "Moving Latin tif lines..."))
        self.actionSplit_Latin_Text_Lines_tb.setText(_translate("Trainer", "Split Latin Pages To Text Lines"))
        self.actionSplit_Latin_Text_Lines_tb.setStatusTip(_translate("Trainer", "Splitting Latin pages to text lines..."))
        self.actionRename_Latin_Text_Lines_tb.setText(_translate("Trainer", "Rename Latin Text Lines"))
        self.actionRename_Latin_Text_Lines_tb.setStatusTip(_translate("Trainer", "Renaming Latin text lines..."))
        self.actiondeskew_mono.setText(_translate("Trainer", "Deskew indexed"))
        self.actiondeskew_mono.setToolTip(_translate("Trainer", "Transform indexed tif pages To deskewed tif and png pages"))
        self.actiondeskew_mono.setStatusTip(_translate("Trainer", "Deskewing indexed tif pages..."))
        self.actionOpen_Image.setText(_translate("Trainer", "Open Image"))
        self.actionVerse_Correction.setText(_translate("Trainer", "Verse Correction"))
        self.actionVerse_Correction.setToolTip(_translate("Trainer", "Book Chapter:Verse Text Assignment"))
        self.actionVerse_Correction.setStatusTip(_translate("Trainer", "Assigning Book Chapter:Verse to text lines"))
        self.actionConvert_Greek_tiff_To_png.setText(_translate("Trainer", "Convert Greek tif To png"))
        self.actionConvert_Greek_tiff_To_png.setStatusTip(_translate("Trainer", "Converting Greek tif pages to png pages"))
        self.actionConvert_Latin_tiff_To_png.setText(_translate("Trainer", "Convert Latin tif To png"))
        self.actionConvert_Latin_tiff_To_png.setToolTip(_translate("Trainer", "Convert Latin tif pages To png pages"))
        self.actionConvert_Latin_tiff_To_png.setStatusTip(_translate("Trainer", "Converting Latin tif pages To png pages"))
        self.actionExtract_Glyphs.setText(_translate("Trainer", "GlyphTracer"))
        self.actionExtract_Glyphs.setToolTip(_translate("Trainer", "Extract and trace bitmap glyphs with GlyphTracer"))
        self.actionExtract_Glyphs.setStatusTip(_translate("Trainer", "Extracting and trace bitmap glyphs with GlyphTracer..."))
        self.actionLine_tif_to_bmp.setText(_translate("Trainer", "Convert tif To bmp"))
        self.actionLine_tif_to_bmp.setToolTip(_translate("Trainer", "Convert current tif image to bmp"))
        self.actionLine_tif_to_bmp.setStatusTip(_translate("Trainer", "Converting current tif image to bmp..."))
        self.actionFontForge.setText(_translate("Trainer", "FontForge"))
        self.actionFontForge.setToolTip(_translate("Trainer", "Edit current GlyphTracer sfd file in FontForge"))
        self.actionFontForge.setStatusTip(_translate("Trainer", "Editing current GlyphTracer sfd file in FontForge..."))
        self.actionPreferences.setText(_translate("Trainer", "Preferences"))
        self.actionOpen_Text.setText(_translate("Trainer", "Open Text"))
        self.actionSave_Image.setText(_translate("Trainer", "Save Image"))
        self.actionSave_As_Image.setText(_translate("Trainer", "Save As Image"))
        self.actionSave_Text.setText(_translate("Trainer", "Save Text"))
        self.actionSave_As_Text.setText(_translate("Trainer", "Save As Text"))
        self.actionConvert_Image_s.setText(_translate("Trainer", "Convert Image(s)"))
        self.actionReview_Ground_Truth_3.setText(_translate("Trainer", "Review Ground Truth"))
        self.actionHebrew.setText(_translate("Trainer", "Hebrew"))
        self.actionHebrew_2.setText(_translate("Trainer", "Hebrew"))
        self.actionUpdate_Hebrew_Wordlist.setText(_translate("Trainer", "Update Hebrew Wordlist"))
        self.actionHebrew_3.setText(_translate("Trainer", "Hebrew"))
        self.actionOCR_Image.setText(_translate("Trainer", "OCR Image"))
        self.actionSelect_Image.setText(_translate("Trainer", "Select Image"))
        self.actionGreek_2.setText(_translate("Trainer", "Greek"))
        self.actionHebrew_4.setText(_translate("Trainer", "Hebrew"))
        self.actionLatin_2.setText(_translate("Trainer", "Latin"))
        self.actionSelect_Language_Model.setText(_translate("Trainer", "Select Language Model"))
        self.actionSelect_Fonts.setText(_translate("Trainer", "Select Fonts"))
        self.actionany.setText(_translate("Trainer", "any"))
        self.actionAny.setText(_translate("Trainer", "Any"))
        self.actionStage_Ground_Truth.setText(_translate("Trainer", "Stage Ground Truth"))
        self.actionCreate_e_Sword_Bible_Module.setText(_translate("Trainer", "e-Sword Bible Module"))
        self.actionCreate_theWord_Bible_Module.setText(_translate("Trainer", "theWord Bible Module"))
        self.actionEnglish.setText(_translate("Trainer", "English"))
        self.actionEnglishh.setText(_translate("Trainer", "English"))
        self.actionEnglish_2.setText(_translate("Trainer", "English"))
        self.actionEnglish_3.setText(_translate("Trainer", "English"))
        self.actionOnline.setText(_translate("Trainer", "Online"))
        self.actionManual_Crop_Image_tb.setText(_translate("Trainer", "Manual Crop"))
        self.actionManual_Crop_Image_tb.setToolTip(_translate("Trainer", "Manually crop current tif image"))
        self.actionManual_Crop_Image_tb.setStatusTip(_translate("Trainer", "Manually cropping current tif image..."))
        self.actionEdit_Image_tb.setText(_translate("Trainer", "Gimp Image Editor"))
        self.actionEdit_Image_tb.setStatusTip(_translate("Trainer", "Editing image in Gimp..."))
        self.actionLibreOffice_Writer.setText(_translate("Trainer", "LibreOffice Writer"))
        self.actionLibreOffice_Calc.setText(_translate("Trainer", "LibreOffice Calc"))
        self.actionDB_Browser_for_SQLite.setText(_translate("Trainer", "DB Browser for SQLite"))
        self.actionOpen_Reference_Text.setText(_translate("Trainer", "Open Reference Text"))
        self.action_Writer.setText(_translate("Trainer", "βϊϐλίον Writer"))
        self.actionWordcount.setText(_translate("Trainer", "Reference Word Count"))

import UI_Icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Trainer = QtWidgets.QMainWindow()
    ui = Ui_Trainer()
    ui.setupUi(Trainer)
    Trainer.show()
    sys.exit(app.exec_())

