# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerUI/MyWriterUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MyWriterUI(object):
    def setupUi(self, MyWriterUI):
        MyWriterUI.setObjectName("MyWriterUI")
        MyWriterUI.setWindowModality(QtCore.Qt.ApplicationModal)
        MyWriterUI.resize(901, 900)
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        MyWriterUI.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/BiblionWriter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MyWriterUI.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MyWriterUI)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 0, 881, 741))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(20)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.LHslider = QtWidgets.QSlider(self.centralwidget)
        self.LHslider.setEnabled(False)
        self.LHslider.setGeometry(QtCore.QRect(260, 0, 21, 161))
        self.LHslider.setMinimum(100)
        self.LHslider.setMaximum(200)
        self.LHslider.setSingleStep(2)
        self.LHslider.setPageStep(10)
        self.LHslider.setProperty("value", 110)
        self.LHslider.setSliderPosition(110)
        self.LHslider.setOrientation(QtCore.Qt.Vertical)
        self.LHslider.setInvertedAppearance(True)
        self.LHslider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.LHslider.setObjectName("LHslider")
        MyWriterUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MyWriterUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MyWriterUI.setMenuBar(self.menubar)
        self.toolbar = QtWidgets.QToolBar(MyWriterUI)
        self.toolbar.setObjectName("toolbar")
        MyWriterUI.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.formatbar = QtWidgets.QToolBar(MyWriterUI)
        self.formatbar.setObjectName("formatbar")
        MyWriterUI.addToolBar(QtCore.Qt.TopToolBarArea, self.formatbar)
        MyWriterUI.insertToolBarBreak(self.formatbar)
        self.statusbar = QtWidgets.QStatusBar(MyWriterUI)
        self.statusbar.setObjectName("statusbar")
        MyWriterUI.setStatusBar(self.statusbar)
        self.fontbar = QtWidgets.QToolBar(MyWriterUI)
        self.fontbar.setObjectName("fontbar")
        MyWriterUI.addToolBar(QtCore.Qt.TopToolBarArea, self.fontbar)
        self.markupbar = QtWidgets.QToolBar(MyWriterUI)
        self.markupbar.setObjectName("markupbar")
        MyWriterUI.addToolBar(QtCore.Qt.TopToolBarArea, self.markupbar)
        self.actionNew = QtWidgets.QAction(MyWriterUI)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/document--plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setObjectName("actionNew")
        self.actionOpenFile = QtWidgets.QAction(MyWriterUI)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/folder-open-document-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenFile.setIcon(icon2)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionSave = QtWidgets.QAction(MyWriterUI)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionPrint_Document = QtWidgets.QAction(MyWriterUI)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/printer-monochrome.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint_Document.setIcon(icon4)
        self.actionPrint_Document.setObjectName("actionPrint_Document")
        self.actionPage_View = QtWidgets.QAction(MyWriterUI)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/printer--arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPage_View.setIcon(icon5)
        self.actionPage_View.setObjectName("actionPage_View")
        self.actionUndo = QtWidgets.QAction(MyWriterUI)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/Undo-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon6)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MyWriterUI)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/Icons/Redo-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon7)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MyWriterUI)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/Icons/scissors.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon8)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MyWriterUI)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/Icons/documents1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon9)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MyWriterUI)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Icons/Icons/clipboard-paste-document-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon10)
        self.actionPaste.setObjectName("actionPaste")
        self.actionFind_Replace = QtWidgets.QAction(MyWriterUI)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Icons/Icons/findreplace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFind_Replace.setIcon(icon11)
        self.actionFind_Replace.setObjectName("actionFind_Replace")
        self.actionToggle_Toolbar = QtWidgets.QAction(MyWriterUI)
        self.actionToggle_Toolbar.setObjectName("actionToggle_Toolbar")
        self.actionToggle_Formatbar = QtWidgets.QAction(MyWriterUI)
        self.actionToggle_Formatbar.setObjectName("actionToggle_Formatbar")
        self.actionToggle_Statusbar = QtWidgets.QAction(MyWriterUI)
        self.actionToggle_Statusbar.setObjectName("actionToggle_Statusbar")
        self.actionSave_As = QtWidgets.QAction(MyWriterUI)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Icons/Icons/disk-rename.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon12)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionDateTime = QtWidgets.QAction(MyWriterUI)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Icons/Icons/calendar-day.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDateTime.setIcon(icon13)
        self.actionDateTime.setObjectName("actionDateTime")
        self.actionWordcount = QtWidgets.QAction(MyWriterUI)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Icons/Icons/countblue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWordcount.setIcon(icon14)
        self.actionWordcount.setText("")
        self.actionWordcount.setObjectName("actionWordcount")
        self.actionInsertTable = QtWidgets.QAction(MyWriterUI)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Icons/Icons/document-table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertTable.setIcon(icon15)
        self.actionInsertTable.setObjectName("actionInsertTable")
        self.actionInsertImage = QtWidgets.QAction(MyWriterUI)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Icons/Icons/image copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertImage.setIcon(icon16)
        self.actionInsertImage.setObjectName("actionInsertImage")
        self.actionBulletList = QtWidgets.QAction(MyWriterUI)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBulletList.setIcon(icon17)
        self.actionBulletList.setObjectName("actionBulletList")
        self.actionNumberedList = QtWidgets.QAction(MyWriterUI)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-list-order.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNumberedList.setIcon(icon18)
        self.actionNumberedList.setObjectName("actionNumberedList")
        self.actionFontColor = QtWidgets.QAction(MyWriterUI)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFontColor.setIcon(icon19)
        self.actionFontColor.setObjectName("actionFontColor")
        self.actionHighlightText = QtWidgets.QAction(MyWriterUI)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/Icons/Icons/highlighter-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHighlightText.setIcon(icon20)
        self.actionHighlightText.setObjectName("actionHighlightText")
        self.actionBold = QtWidgets.QAction(MyWriterUI)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBold.setIcon(icon21)
        self.actionBold.setObjectName("actionBold")
        self.actionItalic = QtWidgets.QAction(MyWriterUI)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionItalic.setIcon(icon22)
        self.actionItalic.setObjectName("actionItalic")
        self.actionUnderline = QtWidgets.QAction(MyWriterUI)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnderline.setIcon(icon23)
        self.actionUnderline.setObjectName("actionUnderline")
        self.actionStrikeThrough = QtWidgets.QAction(MyWriterUI)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-strike.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStrikeThrough.setIcon(icon24)
        self.actionStrikeThrough.setObjectName("actionStrikeThrough")
        self.actionSuperscript = QtWidgets.QAction(MyWriterUI)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-superscript.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSuperscript.setIcon(icon25)
        self.actionSuperscript.setObjectName("actionSuperscript")
        self.actionSubscript = QtWidgets.QAction(MyWriterUI)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-subscript.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSubscript.setIcon(icon26)
        self.actionSubscript.setObjectName("actionSubscript")
        self.actionLeftJustify = QtWidgets.QAction(MyWriterUI)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-alignment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLeftJustify.setIcon(icon27)
        self.actionLeftJustify.setObjectName("actionLeftJustify")
        self.actionCenterAlign = QtWidgets.QAction(MyWriterUI)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-alignment-center.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCenterAlign.setIcon(icon28)
        self.actionCenterAlign.setObjectName("actionCenterAlign")
        self.actionRightJustify = QtWidgets.QAction(MyWriterUI)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-alignment-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRightJustify.setIcon(icon29)
        self.actionRightJustify.setObjectName("actionRightJustify")
        self.actionJustify = QtWidgets.QAction(MyWriterUI)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-alignment-justify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJustify.setIcon(icon30)
        self.actionJustify.setObjectName("actionJustify")
        self.actionIndent = QtWidgets.QAction(MyWriterUI)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-indent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIndent.setIcon(icon31)
        self.actionIndent.setObjectName("actionIndent")
        self.actionOutdent = QtWidgets.QAction(MyWriterUI)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-outdent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOutdent.setIcon(icon32)
        self.actionOutdent.setObjectName("actionOutdent")
        self.actionLineSpacing = QtWidgets.QAction(MyWriterUI)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/Icons/Icons/edit-line-spacing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLineSpacing.setIcon(icon33)
        self.actionLineSpacing.setObjectName("actionLineSpacing")
        self.actionImport = QtWidgets.QAction(MyWriterUI)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/Icons/Icons/document-import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport.setIcon(icon34)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MyWriterUI)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/Icons/Icons/document--arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon35)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionFind_Replace)
        self.menuView.addAction(self.actionToggle_Toolbar)
        self.menuView.addAction(self.actionToggle_Formatbar)
        self.menuView.addAction(self.actionToggle_Statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.toolbar.addAction(self.actionImport)
        self.toolbar.addAction(self.actionNew)
        self.toolbar.addAction(self.actionOpenFile)
        self.toolbar.addAction(self.actionSave_As)
        self.toolbar.addAction(self.actionSave)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.actionUndo)
        self.toolbar.addAction(self.actionRedo)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.actionCut)
        self.toolbar.addAction(self.actionCopy)
        self.toolbar.addAction(self.actionPaste)
        self.toolbar.addAction(self.actionFind_Replace)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.actionDateTime)
        self.toolbar.addAction(self.actionWordcount)
        self.toolbar.addAction(self.actionInsertTable)
        self.toolbar.addAction(self.actionNumberedList)
        self.toolbar.addAction(self.actionBulletList)
        self.formatbar.addAction(self.actionHighlightText)
        self.formatbar.addAction(self.actionLeftJustify)
        self.formatbar.addAction(self.actionCenterAlign)
        self.formatbar.addAction(self.actionRightJustify)
        self.formatbar.addAction(self.actionJustify)
        self.formatbar.addSeparator()
        self.formatbar.addAction(self.actionIndent)
        self.formatbar.addAction(self.actionOutdent)
        self.formatbar.addAction(self.actionLineSpacing)
        self.markupbar.addAction(self.actionFontColor)
        self.markupbar.addAction(self.actionBold)
        self.markupbar.addAction(self.actionItalic)
        self.markupbar.addAction(self.actionUnderline)
        self.markupbar.addAction(self.actionStrikeThrough)
        self.markupbar.addAction(self.actionSuperscript)
        self.markupbar.addAction(self.actionSubscript)

        self.retranslateUi(MyWriterUI)
        QtCore.QMetaObject.connectSlotsByName(MyWriterUI)

    def retranslateUi(self, MyWriterUI):
        _translate = QtCore.QCoreApplication.translate
        MyWriterUI.setWindowTitle(_translate("MyWriterUI", "βϊϐλίον Writer"))
        self.LHslider.setToolTip(_translate("MyWriterUI", "Set current text line spacing"))
        self.menuFile.setTitle(_translate("MyWriterUI", "File"))
        self.menuEdit.setTitle(_translate("MyWriterUI", "Edit"))
        self.menuView.setTitle(_translate("MyWriterUI", "View"))
        self.toolbar.setWindowTitle(_translate("MyWriterUI", "toolBar"))
        self.formatbar.setWindowTitle(_translate("MyWriterUI", "Format Bar"))
        self.fontbar.setWindowTitle(_translate("MyWriterUI", "toolBar"))
        self.markupbar.setWindowTitle(_translate("MyWriterUI", "toolBar_2"))
        self.actionNew.setText(_translate("MyWriterUI", "New"))
        self.actionNew.setShortcut(_translate("MyWriterUI", "Ctrl+N"))
        self.actionOpenFile.setText(_translate("MyWriterUI", "Open File"))
        self.actionOpenFile.setShortcut(_translate("MyWriterUI", "Ctrl+O"))
        self.actionSave.setText(_translate("MyWriterUI", "Save"))
        self.actionSave.setShortcut(_translate("MyWriterUI", "Ctrl+S"))
        self.actionPrint_Document.setText(_translate("MyWriterUI", "Print Document"))
        self.actionPrint_Document.setShortcut(_translate("MyWriterUI", "Ctrl+P"))
        self.actionPage_View.setText(_translate("MyWriterUI", "Page View"))
        self.actionPage_View.setShortcut(_translate("MyWriterUI", "Ctrl+Shift+P"))
        self.actionUndo.setText(_translate("MyWriterUI", "Undo"))
        self.actionUndo.setShortcut(_translate("MyWriterUI", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MyWriterUI", "Redo"))
        self.actionRedo.setShortcut(_translate("MyWriterUI", "Ctrl+Y"))
        self.actionCut.setText(_translate("MyWriterUI", "Cut"))
        self.actionCut.setShortcut(_translate("MyWriterUI", "Ctrl+X"))
        self.actionCopy.setText(_translate("MyWriterUI", "Copy"))
        self.actionCopy.setShortcut(_translate("MyWriterUI", "Ctrl+C"))
        self.actionPaste.setText(_translate("MyWriterUI", "Paste"))
        self.actionPaste.setShortcut(_translate("MyWriterUI", "Ctrl+V"))
        self.actionFind_Replace.setText(_translate("MyWriterUI", "Find and Replace"))
        self.actionFind_Replace.setShortcut(_translate("MyWriterUI", "Ctrl+F"))
        self.actionToggle_Toolbar.setText(_translate("MyWriterUI", "Toggle Toolbar"))
        self.actionToggle_Formatbar.setText(_translate("MyWriterUI", "Toggle Formatbar"))
        self.actionToggle_Statusbar.setText(_translate("MyWriterUI", "Toggle Statusbar"))
        self.actionSave_As.setText(_translate("MyWriterUI", "Save As"))
        self.actionSave_As.setShortcut(_translate("MyWriterUI", "Ctrl+Shift+S"))
        self.actionDateTime.setText(_translate("MyWriterUI", "DateTime"))
        self.actionInsertTable.setText(_translate("MyWriterUI", "InsertTable"))
        self.actionInsertImage.setText(_translate("MyWriterUI", "InsertImage"))
        self.actionBulletList.setText(_translate("MyWriterUI", "BulletList"))
        self.actionNumberedList.setText(_translate("MyWriterUI", "NumberedList"))
        self.actionFontColor.setText(_translate("MyWriterUI", "FontColor"))
        self.actionHighlightText.setText(_translate("MyWriterUI", "HighlighText"))
        self.actionBold.setText(_translate("MyWriterUI", "Bold"))
        self.actionItalic.setText(_translate("MyWriterUI", "Italic"))
        self.actionUnderline.setText(_translate("MyWriterUI", "Underline"))
        self.actionStrikeThrough.setText(_translate("MyWriterUI", "StrikeThrough"))
        self.actionSuperscript.setText(_translate("MyWriterUI", "Superscript"))
        self.actionSubscript.setText(_translate("MyWriterUI", "Subscript"))
        self.actionLeftJustify.setText(_translate("MyWriterUI", "LeftJustify"))
        self.actionCenterAlign.setText(_translate("MyWriterUI", "CenterAlign"))
        self.actionRightJustify.setText(_translate("MyWriterUI", "RightJustify"))
        self.actionJustify.setText(_translate("MyWriterUI", "Justified"))
        self.actionIndent.setText(_translate("MyWriterUI", "Indent"))
        self.actionIndent.setShortcut(_translate("MyWriterUI", "Ctrl+Tab"))
        self.actionOutdent.setText(_translate("MyWriterUI", "Outdent"))
        self.actionOutdent.setShortcut(_translate("MyWriterUI", "Ctrl+Shift+Tab"))
        self.actionLineSpacing.setText(_translate("MyWriterUI", "LineSpacing"))
        self.actionImport.setText(_translate("MyWriterUI", "Import"))
        self.actionExport.setText(_translate("MyWriterUI", "Export"))

import UI_Icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MyWriterUI = QtWidgets.QMainWindow()
    ui = Ui_MyWriterUI()
    ui.setupUi(MyWriterUI)
    MyWriterUI.show()
    sys.exit(app.exec_())

