# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerUI/PageVerseCrossReferenceUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PageVerseCrossReference(object):
    def setupUi(self, PageVerseCrossReference):
        PageVerseCrossReference.setObjectName("PageVerseCrossReference")
        PageVerseCrossReference.resize(800, 960)
        self.centralwidget = QtWidgets.QWidget(PageVerseCrossReference)
        self.centralwidget.setObjectName("centralwidget")
        self.StartbookComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.StartbookComboBox.setGeometry(QtCore.QRect(500, 50, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StartbookComboBox.setFont(font)
        self.StartbookComboBox.setEditable(True)
        self.StartbookComboBox.setObjectName("StartbookComboBox")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.LinefindPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.LinefindPushButton.setGeometry(QtCore.QRect(200, 50, 21, 25))
        self.LinefindPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/binocular-small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LinefindPushButton.setIcon(icon)
        self.LinefindPushButton.setObjectName("LinefindPushButton")
        self.Startlabel = QtWidgets.QLabel(self.centralwidget)
        self.Startlabel.setGeometry(QtCore.QRect(440, 50, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(10)
        self.Startlabel.setFont(font)
        self.Startlabel.setObjectName("Startlabel")
        self.Startcolon = QtWidgets.QLabel(self.centralwidget)
        self.Startcolon.setGeometry(QtCore.QRect(610, 50, 20, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Startcolon.setFont(font)
        self.Startcolon.setAlignment(QtCore.Qt.AlignCenter)
        self.Startcolon.setObjectName("Startcolon")
        self.PageTextFilelabel = QtWidgets.QLabel(self.centralwidget)
        self.PageTextFilelabel.setGeometry(QtCore.QRect(440, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.PageTextFilelabel.setFont(font)
        self.PageTextFilelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PageTextFilelabel.setObjectName("PageTextFilelabel")
        self.LineImageFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.LineImageFileName.setGeometry(QtCore.QRect(20, 170, 341, 31))
        self.LineImageFileName.setObjectName("LineImageFileName")
        self.LineTextFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.LineTextFileName.setGeometry(QtCore.QRect(440, 170, 341, 31))
        self.LineTextFileName.setObjectName("LineTextFileName")
        self.StartverseComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.StartverseComboBox.setGeometry(QtCore.QRect(630, 50, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StartverseComboBox.setFont(font)
        self.StartverseComboBox.setEditable(True)
        self.StartverseComboBox.setObjectName("StartverseComboBox")
        self.LineTextFilelabel = QtWidgets.QLabel(self.centralwidget)
        self.LineTextFilelabel.setGeometry(QtCore.QRect(440, 150, 91, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.LineTextFilelabel.setFont(font)
        self.LineTextFilelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LineTextFilelabel.setObjectName("LineTextFilelabel")
        self.PageTextFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.PageTextFileName.setGeometry(QtCore.QRect(440, 110, 341, 31))
        self.PageTextFileName.setObjectName("PageTextFileName")
        self.LineImageFilelabel = QtWidgets.QLabel(self.centralwidget)
        self.LineImageFilelabel.setGeometry(QtCore.QRect(20, 150, 91, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.LineImageFilelabel.setFont(font)
        self.LineImageFilelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LineImageFilelabel.setObjectName("LineImageFilelabel")
        self.PageNumberlabel = QtWidgets.QLabel(self.centralwidget)
        self.PageNumberlabel.setGeometry(QtCore.QRect(80, 30, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.PageNumberlabel.setFont(font)
        self.PageNumberlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PageNumberlabel.setObjectName("PageNumberlabel")
        self.Verselabel = QtWidgets.QLabel(self.centralwidget)
        self.Verselabel.setGeometry(QtCore.QRect(620, 30, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.Verselabel.setFont(font)
        self.Verselabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Verselabel.setObjectName("Verselabel")
        self.LineNumberlabel = QtWidgets.QLabel(self.centralwidget)
        self.LineNumberlabel.setGeometry(QtCore.QRect(150, 30, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.LineNumberlabel.setFont(font)
        self.LineNumberlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LineNumberlabel.setObjectName("LineNumberlabel")
        self.Booklabel = QtWidgets.QLabel(self.centralwidget)
        self.Booklabel.setGeometry(QtCore.QRect(500, 30, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.Booklabel.setFont(font)
        self.Booklabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Booklabel.setObjectName("Booklabel")
        self.Chapterlabel = QtWidgets.QLabel(self.centralwidget)
        self.Chapterlabel.setGeometry(QtCore.QRect(560, 30, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.Chapterlabel.setFont(font)
        self.Chapterlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Chapterlabel.setObjectName("Chapterlabel")
        self.VersefindPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.VersefindPushButton.setGeometry(QtCore.QRect(680, 50, 21, 25))
        self.VersefindPushButton.setText("")
        self.VersefindPushButton.setIcon(icon)
        self.VersefindPushButton.setObjectName("VersefindPushButton")
        self.StartchapterComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.StartchapterComboBox.setGeometry(QtCore.QRect(560, 50, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StartchapterComboBox.setFont(font)
        self.StartchapterComboBox.setEditable(True)
        self.StartchapterComboBox.setObjectName("StartchapterComboBox")
        self.PagecomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.PagecomboBox.setGeometry(QtCore.QRect(80, 50, 51, 25))
        self.PagecomboBox.setObjectName("PagecomboBox")
        self.LinecomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.LinecomboBox.setGeometry(QtCore.QRect(150, 50, 51, 25))
        self.LinecomboBox.setObjectName("LinecomboBox")
        self.XrefTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.XrefTableWidget.setGeometry(QtCore.QRect(20, 230, 761, 671))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(8)
        self.XrefTableWidget.setFont(font)
        self.XrefTableWidget.setObjectName("XrefTableWidget")
        self.XrefTableWidget.setColumnCount(7)
        self.XrefTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.XrefTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.XrefTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.XrefTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.XrefTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.XrefTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.XrefTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.XrefTableWidget.setHorizontalHeaderItem(6, item)
        self.Selectioncolon = QtWidgets.QLabel(self.centralwidget)
        self.Selectioncolon.setGeometry(QtCore.QRect(130, 50, 20, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Selectioncolon.setFont(font)
        self.Selectioncolon.setAlignment(QtCore.Qt.AlignCenter)
        self.Selectioncolon.setObjectName("Selectioncolon")
        self.PageImageFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.PageImageFileName.setGeometry(QtCore.QRect(20, 110, 341, 31))
        self.PageImageFileName.setObjectName("PageImageFileName")
        self.PageImageFilelabel = QtWidgets.QLabel(self.centralwidget)
        self.PageImageFilelabel.setGeometry(QtCore.QRect(20, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.PageImageFilelabel.setFont(font)
        self.PageImageFilelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PageImageFilelabel.setObjectName("PageImageFilelabel")
        self.Selectionlabel = QtWidgets.QLabel(self.centralwidget)
        self.Selectionlabel.setGeometry(QtCore.QRect(20, 50, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(10)
        self.Selectionlabel.setFont(font)
        self.Selectionlabel.setObjectName("Selectionlabel")
        self.Xreflabel = QtWidgets.QLabel(self.centralwidget)
        self.Xreflabel.setGeometry(QtCore.QRect(20, 210, 131, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.Xreflabel.setFont(font)
        self.Xreflabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Xreflabel.setObjectName("Xreflabel")
        PageVerseCrossReference.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PageVerseCrossReference)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        PageVerseCrossReference.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PageVerseCrossReference)
        self.statusbar.setObjectName("statusbar")
        PageVerseCrossReference.setStatusBar(self.statusbar)

        self.retranslateUi(PageVerseCrossReference)
        QtCore.QMetaObject.connectSlotsByName(PageVerseCrossReference)

    def retranslateUi(self, PageVerseCrossReference):
        _translate = QtCore.QCoreApplication.translate
        PageVerseCrossReference.setWindowTitle(_translate("PageVerseCrossReference", "Page Verse Cross Reference"))
        self.StartbookComboBox.setToolTip(_translate("PageVerseCrossReference", "Select book"))
        self.StartbookComboBox.setItemText(0, _translate("PageVerseCrossReference", "Mat"))
        self.StartbookComboBox.setItemText(1, _translate("PageVerseCrossReference", "Mar"))
        self.StartbookComboBox.setItemText(2, _translate("PageVerseCrossReference", "Luk"))
        self.StartbookComboBox.setItemText(3, _translate("PageVerseCrossReference", "Joh"))
        self.StartbookComboBox.setItemText(4, _translate("PageVerseCrossReference", "Act"))
        self.StartbookComboBox.setItemText(5, _translate("PageVerseCrossReference", "Rom"))
        self.StartbookComboBox.setItemText(6, _translate("PageVerseCrossReference", "1Co"))
        self.StartbookComboBox.setItemText(7, _translate("PageVerseCrossReference", "2Co"))
        self.StartbookComboBox.setItemText(8, _translate("PageVerseCrossReference", "Gal"))
        self.StartbookComboBox.setItemText(9, _translate("PageVerseCrossReference", "Eph"))
        self.StartbookComboBox.setItemText(10, _translate("PageVerseCrossReference", "Php"))
        self.StartbookComboBox.setItemText(11, _translate("PageVerseCrossReference", "Col"))
        self.StartbookComboBox.setItemText(12, _translate("PageVerseCrossReference", "1Th"))
        self.StartbookComboBox.setItemText(13, _translate("PageVerseCrossReference", "2Th"))
        self.StartbookComboBox.setItemText(14, _translate("PageVerseCrossReference", "1Ti"))
        self.StartbookComboBox.setItemText(15, _translate("PageVerseCrossReference", "2Ti"))
        self.StartbookComboBox.setItemText(16, _translate("PageVerseCrossReference", "Tit"))
        self.StartbookComboBox.setItemText(17, _translate("PageVerseCrossReference", "Phm"))
        self.StartbookComboBox.setItemText(18, _translate("PageVerseCrossReference", "Heb"))
        self.StartbookComboBox.setItemText(19, _translate("PageVerseCrossReference", "Jas"))
        self.StartbookComboBox.setItemText(20, _translate("PageVerseCrossReference", "1Pe"))
        self.StartbookComboBox.setItemText(21, _translate("PageVerseCrossReference", "2Pe"))
        self.StartbookComboBox.setItemText(22, _translate("PageVerseCrossReference", "1Jn"))
        self.StartbookComboBox.setItemText(23, _translate("PageVerseCrossReference", "2Jn"))
        self.StartbookComboBox.setItemText(24, _translate("PageVerseCrossReference", "3Jn"))
        self.StartbookComboBox.setItemText(25, _translate("PageVerseCrossReference", "Jud"))
        self.StartbookComboBox.setItemText(26, _translate("PageVerseCrossReference", "Rev"))
        self.LinefindPushButton.setToolTip(_translate("PageVerseCrossReference", "Select verse line"))
        self.Startlabel.setText(_translate("PageVerseCrossReference", "Starts In:"))
        self.Startcolon.setText(_translate("PageVerseCrossReference", ":"))
        self.PageTextFilelabel.setText(_translate("PageVerseCrossReference", "Page Text File"))
        self.StartverseComboBox.setToolTip(_translate("PageVerseCrossReference", "Select verse"))
        self.LineTextFilelabel.setText(_translate("PageVerseCrossReference", "Line Text File"))
        self.LineImageFilelabel.setText(_translate("PageVerseCrossReference", "Line Image File"))
        self.PageNumberlabel.setText(_translate("PageVerseCrossReference", "Page Number"))
        self.Verselabel.setText(_translate("PageVerseCrossReference", "Verse"))
        self.LineNumberlabel.setText(_translate("PageVerseCrossReference", "Line Number"))
        self.Booklabel.setText(_translate("PageVerseCrossReference", "Book"))
        self.Chapterlabel.setText(_translate("PageVerseCrossReference", "Chapter"))
        self.VersefindPushButton.setToolTip(_translate("PageVerseCrossReference", "Select verse line"))
        self.StartchapterComboBox.setToolTip(_translate("PageVerseCrossReference", "Select chapter"))
        item = self.XrefTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("PageVerseCrossReference", "Page"))
        item = self.XrefTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("PageVerseCrossReference", "Line"))
        item = self.XrefTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("PageVerseCrossReference", "Line Image File"))
        item = self.XrefTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("PageVerseCrossReference", "Line Text File"))
        item = self.XrefTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("PageVerseCrossReference", "Start Book"))
        item = self.XrefTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("PageVerseCrossReference", "Start Chapter"))
        item = self.XrefTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("PageVerseCrossReference", "Start Verse"))
        self.Selectioncolon.setText(_translate("PageVerseCrossReference", ":"))
        self.PageImageFilelabel.setText(_translate("PageVerseCrossReference", "Page Image File"))
        self.Selectionlabel.setText(_translate("PageVerseCrossReference", "Selection:"))
        self.Xreflabel.setText(_translate("PageVerseCrossReference", "Page-Verse Cross Reference Table"))

import UI_Icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PageVerseCrossReference = QtWidgets.QMainWindow()
    ui = Ui_PageVerseCrossReference()
    ui.setupUi(PageVerseCrossReference)
    PageVerseCrossReference.show()
    sys.exit(app.exec_())

