# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OCRCorrection.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OCRbutton = QtWidgets.QPushButton(self.centralwidget)
        self.OCRbutton.setEnabled(True)
        self.OCRbutton.setGeometry(QtCore.QRect(540, 60, 201, 25))
        self.OCRbutton.setObjectName("OCRbutton")
        self.SaveOCRTextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveOCRTextbutton.setEnabled(True)
        self.SaveOCRTextbutton.setGeometry(QtCore.QRect(540, 190, 201, 25))
        self.SaveOCRTextbutton.setObjectName("SaveOCRTextbutton")
        self.ImageAreaTitlelabel = QtWidgets.QLabel(self.centralwidget)
        self.ImageAreaTitlelabel.setGeometry(QtCore.QRect(10, 0, 171, 20))
        self.ImageAreaTitlelabel.setObjectName("ImageAreaTitlelabel")
        self.OCRTextAreaTitlelabel = QtWidgets.QLabel(self.centralwidget)
        self.OCRTextAreaTitlelabel.setGeometry(QtCore.QRect(960, 0, 141, 20))
        self.OCRTextAreaTitlelabel.setObjectName("OCRTextAreaTitlelabel")
        self.ChrRefTitlelabel = QtWidgets.QLabel(self.centralwidget)
        self.ChrRefTitlelabel.setGeometry(QtCore.QRect(560, 230, 141, 20))
        self.ChrRefTitlelabel.setObjectName("ChrRefTitlelabel")
        self.ImagescrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.ImagescrollArea.setGeometry(QtCore.QRect(0, 20, 520, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollArea.sizePolicy().hasHeightForWidth())
        self.ImagescrollArea.setSizePolicy(sizePolicy)
        self.ImagescrollArea.setMinimumSize(QtCore.QSize(501, 700))
        self.ImagescrollArea.setWidgetResizable(True)
        self.ImagescrollArea.setObjectName("ImagescrollArea")
        self.ImagescrollAreaWidgetContents = QtWidgets.QWidget()
        self.ImagescrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 501, 1800))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImagescrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.ImagescrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.ImagescrollAreaWidgetContents.setMinimumSize(QtCore.QSize(501, 1800))
        self.ImagescrollAreaWidgetContents.setSizeIncrement(QtCore.QSize(0, 0))
        self.ImagescrollAreaWidgetContents.setBaseSize(QtCore.QSize(520, 700))
        self.ImagescrollAreaWidgetContents.setObjectName("ImagescrollAreaWidgetContents")
        self.Image = QtWidgets.QLabel(self.ImagescrollAreaWidgetContents)
        self.Image.setGeometry(QtCore.QRect(0, 0, 521, 1680))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Image.sizePolicy().hasHeightForWidth())
        self.Image.setSizePolicy(sizePolicy)
        self.Image.setMinimumSize(QtCore.QSize(500, 1680))
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("../../Images/Greek/jpg_desk_greek/greek_book_40_Matthew/greek1516_Page_012.jpg"))
        self.Image.setObjectName("Image")
        self.ImagescrollArea.setWidget(self.ImagescrollAreaWidgetContents)
        self.ChrRefscrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.ChrRefscrollArea.setGeometry(QtCore.QRect(530, 250, 220, 400))
        self.ChrRefscrollArea.setWidgetResizable(True)
        self.ChrRefscrollArea.setObjectName("ChrRefscrollArea")
        self.ChrRefcrollAreaWidgetContents = QtWidgets.QWidget()
        self.ChrRefcrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 200, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChrRefcrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.ChrRefcrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.ChrRefcrollAreaWidgetContents.setMinimumSize(QtCore.QSize(200, 500))
        self.ChrRefcrollAreaWidgetContents.setObjectName("ChrRefcrollAreaWidgetContents")
        self.ChrRefplainTextEdit = QtWidgets.QPlainTextEdit(self.ChrRefcrollAreaWidgetContents)
        self.ChrRefplainTextEdit.setGeometry(QtCore.QRect(0, 0, 201, 401))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(18)
        self.ChrRefplainTextEdit.setFont(font)
        self.ChrRefplainTextEdit.setObjectName("ChrRefplainTextEdit")
        self.ChrRefscrollArea.setWidget(self.ChrRefcrollAreaWidgetContents)
        
        self.OCRTextscrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.OCRTextscrollArea.setGeometry(QtCore.QRect(760, 20, 540, 700))
        self.OCRTextscrollArea.setAcceptDrops(False)
        self.OCRTextscrollArea.setWidgetResizable(True)
        self.OCRTextscrollArea.setObjectName("OCRTextscrollArea")
        self.OCRTextscrollAreaWidgetContents = QtWidgets.QWidget()
        self.OCRTextscrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 540, 1700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OCRTextscrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.OCRTextscrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.OCRTextscrollAreaWidgetContents.setMinimumSize(QtCore.QSize(540, 1700))
        self.OCRTextscrollAreaWidgetContents.setObjectName("OCRTextscrollAreaWidgetContents")
        self.OCRText = QtWidgets.QTextEdit(self.OCRTextscrollAreaWidgetContents)
        self.OCRText.setGeometry(QtCore.QRect(0, 0, 540, 1702))
        self.OCRText.setMinimumSize(QtCore.QSize(540, 1702))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(20)
        self.OCRText.setFont(font)
        self.OCRText.setAutoFillBackground(False)
        self.OCRText.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.OCRText.setObjectName("OCRText")
        self.OCRTextscrollArea.setWidget(self.OCRTextscrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(540, 150, 201, 25))
        self.pushButton.setObjectName("pushButton")
        self.SaveOCRTextbutton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.SaveOCRTextbutton_2.setEnabled(True)
        self.SaveOCRTextbutton_2.setGeometry(QtCore.QRect(540, 100, 201, 25))
        self.SaveOCRTextbutton_2.setObjectName("SaveOCRTextbutton_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(542, 20, 201, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OCR Correction"))
        self.OCRbutton.setText(_translate("MainWindow", "Generate OCR Raw Text"))
        self.SaveOCRTextbutton.setText(_translate("MainWindow", "Save Corrected Text File"))
        self.ImageAreaTitlelabel.setText(_translate("MainWindow", "Image to Recognize OCR"))
        self.OCRTextAreaTitlelabel.setText(_translate("MainWindow", "OCR Text File to Edit"))
        self.ChrRefTitlelabel.setText(_translate("MainWindow", "Character Reference"))
        self.pushButton.setText(_translate("MainWindow", "Edit Corrected Text"))
        self.SaveOCRTextbutton_2.setText(_translate("MainWindow", "Save Raw Text File"))
        self.pushButton_2.setText(_translate("MainWindow", "Open Image File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

