# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerUI/PageVerseXrefDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PageVerseXrefDialog(object):
    def setupUi(self, PageVerseXrefDialog):
        PageVerseXrefDialog.setObjectName("PageVerseXrefDialog")
        PageVerseXrefDialog.resize(800, 693)
        self.buttonBox = QtWidgets.QDialogButtonBox(PageVerseXrefDialog)
        self.buttonBox.setGeometry(QtCore.QRect(370, 650, 411, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.PageNumberlabel = QtWidgets.QLabel(PageVerseXrefDialog)
        self.PageNumberlabel.setGeometry(QtCore.QRect(80, 20, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.PageNumberlabel.setFont(font)
        self.PageNumberlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PageNumberlabel.setObjectName("PageNumberlabel")
        self.LineNumberlabel = QtWidgets.QLabel(PageVerseXrefDialog)
        self.LineNumberlabel.setGeometry(QtCore.QRect(150, 20, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.LineNumberlabel.setFont(font)
        self.LineNumberlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LineNumberlabel.setObjectName("LineNumberlabel")
        self.Startcolon = QtWidgets.QLabel(PageVerseXrefDialog)
        self.Startcolon.setGeometry(QtCore.QRect(610, 40, 20, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Startcolon.setFont(font)
        self.Startcolon.setAlignment(QtCore.Qt.AlignCenter)
        self.Startcolon.setObjectName("Startcolon")
        self.StartverseComboBox = QtWidgets.QComboBox(PageVerseXrefDialog)
        self.StartverseComboBox.setGeometry(QtCore.QRect(630, 40, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StartverseComboBox.setFont(font)
        self.StartverseComboBox.setEditable(True)
        self.StartverseComboBox.setObjectName("StartverseComboBox")
        self.VersefindPushButton = QtWidgets.QPushButton(PageVerseXrefDialog)
        self.VersefindPushButton.setGeometry(QtCore.QRect(680, 40, 21, 25))
        self.VersefindPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/binocular-small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.VersefindPushButton.setIcon(icon)
        self.VersefindPushButton.setObjectName("VersefindPushButton")
        self.StartchapterComboBox = QtWidgets.QComboBox(PageVerseXrefDialog)
        self.StartchapterComboBox.setGeometry(QtCore.QRect(560, 40, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StartchapterComboBox.setFont(font)
        self.StartchapterComboBox.setEditable(True)
        self.StartchapterComboBox.setObjectName("StartchapterComboBox")
        self.StartbookComboBox = QtWidgets.QComboBox(PageVerseXrefDialog)
        self.StartbookComboBox.setGeometry(QtCore.QRect(500, 40, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StartbookComboBox.setFont(font)
        self.StartbookComboBox.setEditable(True)
        self.StartbookComboBox.setObjectName("StartbookComboBox")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.StartbookComboBox.addItem("")
        self.Booklabel = QtWidgets.QLabel(PageVerseXrefDialog)
        self.Booklabel.setGeometry(QtCore.QRect(500, 20, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.Booklabel.setFont(font)
        self.Booklabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Booklabel.setObjectName("Booklabel")
        self.Chapterlabel = QtWidgets.QLabel(PageVerseXrefDialog)
        self.Chapterlabel.setGeometry(QtCore.QRect(560, 20, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.Chapterlabel.setFont(font)
        self.Chapterlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Chapterlabel.setObjectName("Chapterlabel")
        self.Verselabel = QtWidgets.QLabel(PageVerseXrefDialog)
        self.Verselabel.setGeometry(QtCore.QRect(630, 20, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.Verselabel.setFont(font)
        self.Verselabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Verselabel.setObjectName("Verselabel")
        self.PagecomboBox = QtWidgets.QComboBox(PageVerseXrefDialog)
        self.PagecomboBox.setGeometry(QtCore.QRect(80, 40, 51, 25))
        self.PagecomboBox.setEditable(True)
        self.PagecomboBox.setObjectName("PagecomboBox")
        self.LinecomboBox = QtWidgets.QComboBox(PageVerseXrefDialog)
        self.LinecomboBox.setGeometry(QtCore.QRect(150, 40, 51, 25))
        self.LinecomboBox.setEditable(True)
        self.LinecomboBox.setObjectName("LinecomboBox")
        self.PageImageFileName = QtWidgets.QLineEdit(PageVerseXrefDialog)
        self.PageImageFileName.setGeometry(QtCore.QRect(20, 100, 341, 31))
        self.PageImageFileName.setObjectName("PageImageFileName")
        self.LineTextFileName = QtWidgets.QLineEdit(PageVerseXrefDialog)
        self.LineTextFileName.setGeometry(QtCore.QRect(440, 160, 341, 31))
        self.LineTextFileName.setObjectName("LineTextFileName")
        self.LineImageFileName = QtWidgets.QLineEdit(PageVerseXrefDialog)
        self.LineImageFileName.setGeometry(QtCore.QRect(20, 160, 341, 31))
        self.LineImageFileName.setObjectName("LineImageFileName")
        self.LineImageFilelabel = QtWidgets.QLabel(PageVerseXrefDialog)
        self.LineImageFilelabel.setGeometry(QtCore.QRect(20, 140, 91, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.LineImageFilelabel.setFont(font)
        self.LineImageFilelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LineImageFilelabel.setObjectName("LineImageFilelabel")
        self.LineTextFilelabel = QtWidgets.QLabel(PageVerseXrefDialog)
        self.LineTextFilelabel.setGeometry(QtCore.QRect(440, 140, 91, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.LineTextFilelabel.setFont(font)
        self.LineTextFilelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LineTextFilelabel.setObjectName("LineTextFilelabel")
        self.LinefindPushButton = QtWidgets.QPushButton(PageVerseXrefDialog)
        self.LinefindPushButton.setGeometry(QtCore.QRect(200, 40, 21, 25))
        self.LinefindPushButton.setText("")
        self.LinefindPushButton.setIcon(icon)
        self.LinefindPushButton.setObjectName("LinefindPushButton")
        self.Startlabel = QtWidgets.QLabel(PageVerseXrefDialog)
        self.Startlabel.setGeometry(QtCore.QRect(440, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(10)
        self.Startlabel.setFont(font)
        self.Startlabel.setObjectName("Startlabel")
        self.XrefTableView = QtWidgets.QTableView(PageVerseXrefDialog)
        self.XrefTableView.setGeometry(QtCore.QRect(20, 220, 760, 400))
        self.XrefTableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.XrefTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.XrefTableView.setSortingEnabled(True)
        self.XrefTableView.setObjectName("XrefTableView")
        self.XrefTableView.verticalHeader().setSortIndicatorShown(True)
        self.PageTextFileName = QtWidgets.QLineEdit(PageVerseXrefDialog)
        self.PageTextFileName.setGeometry(QtCore.QRect(440, 100, 341, 31))
        self.PageTextFileName.setObjectName("PageTextFileName")
        self.PageTextFilelabel = QtWidgets.QLabel(PageVerseXrefDialog)
        self.PageTextFilelabel.setGeometry(QtCore.QRect(440, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.PageTextFilelabel.setFont(font)
        self.PageTextFilelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PageTextFilelabel.setObjectName("PageTextFilelabel")
        self.PageImageFilelabel = QtWidgets.QLabel(PageVerseXrefDialog)
        self.PageImageFilelabel.setGeometry(QtCore.QRect(20, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(7)
        self.PageImageFilelabel.setFont(font)
        self.PageImageFilelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PageImageFilelabel.setObjectName("PageImageFilelabel")
        self.Selectionlabel = QtWidgets.QLabel(PageVerseXrefDialog)
        self.Selectionlabel.setGeometry(QtCore.QRect(20, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS [MAXR]")
        font.setPointSize(10)
        self.Selectionlabel.setFont(font)
        self.Selectionlabel.setObjectName("Selectionlabel")
        self.Selectioncolon = QtWidgets.QLabel(PageVerseXrefDialog)
        self.Selectioncolon.setGeometry(QtCore.QRect(130, 40, 20, 21))
        font = QtGui.QFont()
        font.setFamily("FROMVS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Selectioncolon.setFont(font)
        self.Selectioncolon.setAlignment(QtCore.Qt.AlignCenter)
        self.Selectioncolon.setObjectName("Selectioncolon")

        self.retranslateUi(PageVerseXrefDialog)
        self.buttonBox.accepted.connect(PageVerseXrefDialog.accept)
        self.buttonBox.rejected.connect(PageVerseXrefDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PageVerseXrefDialog)

    def retranslateUi(self, PageVerseXrefDialog):
        _translate = QtCore.QCoreApplication.translate
        PageVerseXrefDialog.setWindowTitle(_translate("PageVerseXrefDialog", "Dialog"))
        self.PageNumberlabel.setText(_translate("PageVerseXrefDialog", "Page Number"))
        self.LineNumberlabel.setText(_translate("PageVerseXrefDialog", "Line Number"))
        self.Startcolon.setText(_translate("PageVerseXrefDialog", ":"))
        self.StartverseComboBox.setToolTip(_translate("PageVerseXrefDialog", "Select verse"))
        self.VersefindPushButton.setToolTip(_translate("PageVerseXrefDialog", "Select verse line"))
        self.StartchapterComboBox.setToolTip(_translate("PageVerseXrefDialog", "Select chapter"))
        self.StartbookComboBox.setToolTip(_translate("PageVerseXrefDialog", "Select book"))
        self.StartbookComboBox.setItemText(0, _translate("PageVerseXrefDialog", "Mat"))
        self.StartbookComboBox.setItemText(1, _translate("PageVerseXrefDialog", "Mar"))
        self.StartbookComboBox.setItemText(2, _translate("PageVerseXrefDialog", "Luk"))
        self.StartbookComboBox.setItemText(3, _translate("PageVerseXrefDialog", "Joh"))
        self.StartbookComboBox.setItemText(4, _translate("PageVerseXrefDialog", "Act"))
        self.StartbookComboBox.setItemText(5, _translate("PageVerseXrefDialog", "Rom"))
        self.StartbookComboBox.setItemText(6, _translate("PageVerseXrefDialog", "1Co"))
        self.StartbookComboBox.setItemText(7, _translate("PageVerseXrefDialog", "2Co"))
        self.StartbookComboBox.setItemText(8, _translate("PageVerseXrefDialog", "Gal"))
        self.StartbookComboBox.setItemText(9, _translate("PageVerseXrefDialog", "Eph"))
        self.StartbookComboBox.setItemText(10, _translate("PageVerseXrefDialog", "Php"))
        self.StartbookComboBox.setItemText(11, _translate("PageVerseXrefDialog", "Col"))
        self.StartbookComboBox.setItemText(12, _translate("PageVerseXrefDialog", "1Th"))
        self.StartbookComboBox.setItemText(13, _translate("PageVerseXrefDialog", "2Th"))
        self.StartbookComboBox.setItemText(14, _translate("PageVerseXrefDialog", "1Ti"))
        self.StartbookComboBox.setItemText(15, _translate("PageVerseXrefDialog", "2Ti"))
        self.StartbookComboBox.setItemText(16, _translate("PageVerseXrefDialog", "Tit"))
        self.StartbookComboBox.setItemText(17, _translate("PageVerseXrefDialog", "Phm"))
        self.StartbookComboBox.setItemText(18, _translate("PageVerseXrefDialog", "Heb"))
        self.StartbookComboBox.setItemText(19, _translate("PageVerseXrefDialog", "Jas"))
        self.StartbookComboBox.setItemText(20, _translate("PageVerseXrefDialog", "1Pe"))
        self.StartbookComboBox.setItemText(21, _translate("PageVerseXrefDialog", "2Pe"))
        self.StartbookComboBox.setItemText(22, _translate("PageVerseXrefDialog", "1Jn"))
        self.StartbookComboBox.setItemText(23, _translate("PageVerseXrefDialog", "2Jn"))
        self.StartbookComboBox.setItemText(24, _translate("PageVerseXrefDialog", "3Jn"))
        self.StartbookComboBox.setItemText(25, _translate("PageVerseXrefDialog", "Jud"))
        self.StartbookComboBox.setItemText(26, _translate("PageVerseXrefDialog", "Rev"))
        self.Booklabel.setText(_translate("PageVerseXrefDialog", "Book"))
        self.Chapterlabel.setText(_translate("PageVerseXrefDialog", "Chapter"))
        self.Verselabel.setText(_translate("PageVerseXrefDialog", "Verse"))
        self.LineImageFilelabel.setText(_translate("PageVerseXrefDialog", "Line Image File"))
        self.LineTextFilelabel.setText(_translate("PageVerseXrefDialog", "Line Text File"))
        self.LinefindPushButton.setToolTip(_translate("PageVerseXrefDialog", "Select verse line"))
        self.Startlabel.setText(_translate("PageVerseXrefDialog", "Starts In:"))
        self.PageTextFilelabel.setText(_translate("PageVerseXrefDialog", "Page Text File"))
        self.PageImageFilelabel.setText(_translate("PageVerseXrefDialog", "Page Image File"))
        self.Selectionlabel.setText(_translate("PageVerseXrefDialog", "Selection:"))
        self.Selectioncolon.setText(_translate("PageVerseXrefDialog", ":"))

import UI_Icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PageVerseXrefDialog = QtWidgets.QDialog()
    ui = Ui_PageVerseXrefDialog()
    ui.setupUi(PageVerseXrefDialog)
    PageVerseXrefDialog.show()
    sys.exit(app.exec_())

