# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Developer/QtDesignerUI/StageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StageDialog(object):
    def setupUi(self, StageDialog):
        StageDialog.setObjectName("StageDialog")
        StageDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        StageDialog.resize(620, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(StageDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.defaultsrcBox = QtWidgets.QCheckBox(StageDialog)
        self.defaultsrcBox.setChecked(True)
        self.defaultsrcBox.setObjectName("defaultsrcBox")
        self.verticalLayout.addWidget(self.defaultsrcBox)
        self.SourceLabel = QtWidgets.QLabel(StageDialog)
        self.SourceLabel.setObjectName("SourceLabel")
        self.verticalLayout.addWidget(self.SourceLabel)
        self.sourceLayout = QtWidgets.QHBoxLayout()
        self.sourceLayout.setObjectName("sourceLayout")
        self.SourceLineEdit = QtWidgets.QLineEdit(StageDialog)
        self.SourceLineEdit.setObjectName("SourceLineEdit")
        self.sourceLayout.addWidget(self.SourceLineEdit)
        self.SourceButton = QtWidgets.QPushButton(StageDialog)
        self.SourceButton.setEnabled(False)
        self.SourceButton.setObjectName("SourceButton")
        self.sourceLayout.addWidget(self.SourceButton)
        self.verticalLayout.addLayout(self.sourceLayout)
        self.DestinationLabel = QtWidgets.QLabel(StageDialog)
        self.DestinationLabel.setObjectName("DestinationLabel")
        self.verticalLayout.addWidget(self.DestinationLabel)
        self.destinationLayout = QtWidgets.QHBoxLayout()
        self.destinationLayout.setObjectName("destinationLayout")
        self.DestinationLineEdit = QtWidgets.QLineEdit(StageDialog)
        self.DestinationLineEdit.setObjectName("DestinationLineEdit")
        self.destinationLayout.addWidget(self.DestinationLineEdit)
        self.DestinationButton = QtWidgets.QPushButton(StageDialog)
        self.DestinationButton.setEnabled(False)
        self.DestinationButton.setObjectName("DestinationButton")
        self.destinationLayout.addWidget(self.DestinationButton)
        self.verticalLayout.addLayout(self.destinationLayout)
        self.OverrideCheckBox = QtWidgets.QCheckBox(StageDialog)
        self.OverrideCheckBox.setChecked(True)
        self.OverrideCheckBox.setObjectName("OverrideCheckBox")
        self.verticalLayout.addWidget(self.OverrideCheckBox)
        self.StatusLabel = QtWidgets.QLabel(StageDialog)
        self.StatusLabel.setWordWrap(True)
        self.StatusLabel.setObjectName("StatusLabel")
        self.verticalLayout.addWidget(self.StatusLabel)
        self.ProgressBar = QtWidgets.QProgressBar(StageDialog)
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setObjectName("ProgressBar")
        self.verticalLayout.addWidget(self.ProgressBar)
        self.buttonBox = QtWidgets.QDialogButtonBox(StageDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(StageDialog)
        self.buttonBox.accepted.connect(StageDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(StageDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(StageDialog)

    def retranslateUi(self, StageDialog):
        _translate = QtCore.QCoreApplication.translate
        StageDialog.setWindowTitle(_translate("StageDialog", "Stage source PDF"))
        self.defaultsrcBox.setText(_translate("StageDialog", "Use workflow defaults"))
        self.SourceLabel.setText(_translate("StageDialog", "Source folder"))
        self.SourceButton.setText(_translate("StageDialog", "Select source"))
        self.DestinationLabel.setText(_translate("StageDialog", "Destination folder"))
        self.DestinationButton.setText(_translate("StageDialog", "Select destination"))
        self.OverrideCheckBox.setText(_translate("StageDialog", "Overwrite an existing staged PDF"))
        self.StatusLabel.setText(_translate("StageDialog", "Ready to stage source PDF"))
        self.ProgressBar.setFormat(_translate("StageDialog", "%p%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StageDialog = QtWidgets.QDialog()
    ui = Ui_StageDialog()
    ui.setupUi(StageDialog)
    StageDialog.show()
    sys.exit(app.exec_())
